### ISSUE TITLE
Add support for MS430

### ISSUE THREAD

**Issue by morenod** [esphome/feature-requests#1017]
**Describe the problem you have/What new integration you would like**

There is a new (at least new for me) sensor which includes temperature, humidity, air quality and light

https://www.metriful.com/?fbclid=IwAR2emP6bDKc0mp6q3EUEAZpB94zAQ_1ObrDdx9D1eezMenZ3paq3WcInhDw

Seems to be compatible with ESP, so it would be nice if we could use on esphome

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by SimoneGianni** [comment]
https://github.com/SimoneGianni/metriful-esphome 

While Metriful added some ESP Home support, it requires you to setup a dev environment; I instead repackaged it as an external component, so now it can simply be used as follows:

```yaml
# Reference my repository so that ESPHome can use the code there
external_components:
  - source: 
      type: git
      url: https://github.com/SimoneGianni/metriful-esphome

# Configure I2C on the proper pins (may already be set up for other peripherals)
i2c:
  sda: 19
  scl: 22

# Metriful sensor setup, specifying the ready_pin, which is required
metriful:
  ready_pin: 23
```

You can also specify the the cycle_time and reconfigure each of the sensors by declaring them, otherwise they are all setup with default values. 

It is working properly on my ESP Home with Home Assistant on a LOLIN32 board, however please note that:
1. it is 0.0.0.0.1 alpha level code :D, and I'm not an ESP home expert
2. I have not tested it on any other board
3. There are a few things yet untested or not completely implemented (see issues on the repo)

Totally open to suggestions, PRs etc..  

Also happy to contribute it to ESP Home project itself if requested and licenses are compatible.
