### ISSUE TITLE
Get current id with lambdas

### ISSUE THREAD

**Issue by xalexslx** [esphome/feature-requests#102]
**Describe the problem you have/What new integration you would like**
I would like to be possible to retrive the current id from a lambda call. Below I attached an example of the automation I would like to do with lambda.

**Please describe your use case for this integration and alternatives you've tried:**
```yaml
binary_sensor:
  # Button 00
  - platform: gpio
    id: button_00
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.1s
        then:
          - text_sensor.template.publish:
              id: buttons
              # evaluate to button_00_click
              state: !lambda "return current_id() + '_click';"
```

**Additional context**
None
