### ISSUE TITLE
Abstraction for packet-based UART/RS485/Modbus communication

### ISSUE THREAD

**Issue by loongyh** [esphome/feature-requests#1051]
**Describe the problem you have/What new integration you would like**

Devices with a serial interface such as UART, RS485 from different manufacturers usually have frame structures defined by start_code, device_address, identifier, payload, checksum:

![114905l75px50rbalh7puy](https://user-images.githubusercontent.com/20846761/103016703-70c32d80-457d-11eb-92aa-273e32b17dab.jpg)

![Capture](https://user-images.githubusercontent.com/20846761/103016893-c4ce1200-457d-11eb-8033-21c29fe0564e.PNG)

Instead of creating yet another integration for a specific manufacturer, why not have a generic abstraction such that the user can define in .yaml the start_code, device_address, payload (byte representation for the state of a trait), etc., this will enable users to easily integrate numerous RS485 devices into ESPHome potentially without having to dive into C++.

**Please describe your use case for this integration and alternatives you've tried:**

This integration should span the core abstractions (light, cover, fan, switch, etc.). For any UART-interfacable device that follows the frame structure, and uses the same UART settings (baud rate, start bits, parity, etc.) the user can define in .yaml the start_code, device_address, identifier, payload, checksum type for each device and can then string them together in a RS485 bus to be controlled using one ESPHome master device.

**Additional context**

Upon receiving a valid command packet, RS485 devices usually transmit a response packet with the result (and payload if any) for the command, usually with the same frame structure.
The user defines in .yaml the response bytes representing the state of each core abstraction trait (such as `0x01` for `COVER_OPEN`).

```
# Example config.yaml
uart:
  tx_pin: D0
  rx_pin: D1
  baud_rate: 9600

cover:
  generic_uart:
    name: Bedroom Window
    header: 0x55
    address: 0xFEFE
    checksum_type: CRC16
    command:
      open: 0x01   #command code for COVER_OPEN
      stop: 0x00   #command code for COVER_STOP
      close: 0x02  #command code for COVER_CLOSE
    response:
      octet: 5            #vector index of the byte in a frame representing the position of the window
      position_min: 0x00  #byte representation of fully closed
      position_max: 0x64  #byte representation of fully open
```

Considerations:
Although the frame structure may appear to be consistent across manufacturers, there are still other variables to account for such as differences in:
- No. of bytes for each field type (start_code, address, etc.)
- Some are fixed length frames, some are variable with an additional length field type, some are variable depending on the identifier.
- Variances in integer-percentage state value mappings; many ways to represent state values (e.g. 0-255 for 0-100%).

This is more of a RFC as I have just done my first integration (the Grow fingerprint reader currently still in PR) and am just started on writing another integration for Dooya RS485 blinds, so if there's any other issues/considerations with this approach do let me know! This feature request will be revised accordingly as I get familiar with the intricacies in due time.
