### ISSUE TITLE
Implement the ability to send data to thingspeak

### ISSUE THREAD

**Issue by gigios** [esphome/feature-requests#1072]
**Describe the problem you have/What new integration you would like**
Implement the ability to send data to thingspeak

**Please describe your use case for this integration and alternatives you've tried:**
I'm migrating a my arduino sketch to esphome. I'm able to port all my sensors,  even an MQ-135 gas sensor which is not available 'natively'.
The problem is that I have also the send all the data (fields) to a thingspeak channel. This is not possible now in ESPHome.
I have checked also Home Assistant, but it's possible to send only one field to a channel and not multiple fields.
My idea is to use ESPHome to implement my sensors and use Home Assistant as a supervisor, but I want that my sensors is able to works, and store data, also without the Home Assistant.
Do you think that this is possible or is it a wrong usage of ESPHome?

**Additional context**
Do you think that, eventually, it might be possible to use a 'fake' sensor ('[Generic Custom Component](https://esphome.io/custom/custom_component.html)'), to try to manage the sending of thingspeak data?

**Comment by jbrepogmailcom** [comment]
Hello sir, I am not experienced with ESPHome, but I think it has HTTP GET component, so you can use that to post values to thingspeak, right? I use thingspeak a lot. Jan

**Comment by gigios** [comment]
Thank you for your suggestion. Also i am not an expert, this is the first time i use ESPHome.
I will check the HTTP component.

**Comment by frspp** [comment]
You can also use MQTT to send values to Thingspeak
https://esphome.io/components/mqtt.html
https://blogs.mathworks.com/iot/2017/01/20/use-mqtt-to-send-iot-data-to-thingspeak/
https://se.mathworks.com/help/thingspeak/mqtt-api.html

**Comment by gigios** [comment]
Thanks for the answer, this for me it's a great news.
Thanks again, I will try immediately.

**Comment by frspp** [comment]
@gigios please let me know if you get Thingspeak working.

I have tried setting mqtt publish to Thingspeak, no luck so far.

https://se.mathworks.com/help/thingspeak/mqtt-basics.html reads "MQTT publish does not require the API key." so i tried
`
mqtt:
  broker: mqtt.thingspeak.com

interval:
  - interval: 15sec
    then:
    - mqtt.publish:
        topic: channels/CHANNELID/publish/CHANNELWRITEAPIKEY 
        payload: field1=id
`
result: "MQTT Disconnected: Not Authorized."

I also looked https://se.mathworks.com/help/thingspeak/use-arduino-client-to-publish-to-a-channel.html for help but no luck. In this example they username (random), password (user write api key) and client id (random). 
`
mqtt:
  broker: mqtt.thingspeak.com
  username: usernamedoesnotmatter
  password: USERWRITEAPIKEY
  client_id: 202104132256
  discovery: false

interval:
  - interval: 15sec
    then:
    - mqtt.publish:
        topic: channels/CHANNELID/publish/CHANNELWRITEAPIKEY
        payload: field1=id
`
result: "MQTT Disconnected: Not Authorized."

**Comment by jbrepogmailcom** [comment]
Hello I think it should be pretty easy to use current functionality and call thingspeak with http get. Have you tried it?

I personally would define global string variable and then update it in lambda with complete URL and field parameters. Then you can use http get in esphome to call thingspeak.

**Comment by jbrepogmailcom** [comment]
You definitely need authorization to mqtt publish. From their web:
"MQTT Publish
The figure describes the topic structure. The Write API Key is required to publish. The broker acknowledges a correct CONNECT request with CONNACK"

**Comment by ESPmonster** [comment]
@frspp  I have previously figured out the ESPhome -> thingspeak via MQTT problem. Have a look at my working code [here](https://github.com/ESPmonster/Esphome-boat-battery-and-waterlevel-monitor/blob/main/ESPhome-YAML)

It's essential to add 
`discovery_retain: 'false'`
and
`   discovery: False
    retain: false`

**Comment by jbrepogmailcom** [comment]
Is it possible to connect to two mqtt brokers? If not then you can use thingspeak but you cannot send mqtt message to Home Assistant and have to use api. Or?

**Comment by zierbeek** [comment]
Hi @ESPmonster , I'm also trying to get it published! but I have some trouble of selecting what I want to get published.

```
mqtt:
  broker: mqtt.thingspeak.com
  username: !
  password: !
  client_id: !
  discovery: false
  discovery_retain: 'false'
  discovery: False retain: false
  
interval:
  - interval: 3 sec
    then:
    - mqtt.publish:
        topic: channels/set/publish/set
        payload: field1="pH measurement"

sensor:
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 6.144
    name: "pH measurement"
    unit_of_measurement: "pH"
    accuracy_decimals: 1
    state_class: "measurement"
    update_interval: 1s
    filters:
      - calibrate_linear:
        - 0.00 -> 0.0
        - 2.363 -> 7.0
        - 4.92 -> 14.0
```
