### ISSUE TITLE
1-wire IButton reader integration

### ISSUE THREAD

**Issue by strbackatomas** [esphome/feature-requests#1074]
**Describe the problem you have/What new integration you would like**

The esphome device will report the iButton address attached to 1wire connected reader as value to home assitant sensor.

**Please describe your use case for this integration and alternatives you've tried:**

if I attach the iButton chip to the reader, the address of the chip will be displayed in the text sensor of the home assistant.
It can also be used as a trigger

**Additional context**

Possible sources:
https://github.com/pezinek/ibutton_reader
https://home.1vp.ru/en/1-wire-controller/
https://shop.loxone.com/cscz/ctecka-elektronickeho-klice.html

**Comment by Misiu** [comment]
@strbackatomas great idea. I have a reader based on Arduino, but I'd like to move my project and integrate everything with Home Assistant.

**Comment by Misiu** [comment]
This should be build based on https://github.com/esphome/esphome/tree/dev/esphome/components/dallas or should be added to this component, but not sure about the second option because 1-wire doesn't have a resolution and 1-wire isn't a temperature sensor.
@strbackatomas do you think the sensor should return value only when 1-wire ID is on the list of allowed sensors (like here: https://esphome.io/components/sensor/dallas.html) or all ID's and Home Assistant should decide if a specific value is allowed or not (like this: https://esphome.io/components/binary_sensor/pn532.html)?

So the config could look like this:

```
# Example configuration entry
onewire:
  - pin: 23

#individual sensors
sensor:
  - platform: onewire
    address: 0x1c0000031edd2a30
    name: "Dad keychain"
  - platform: onewire
    address: 0x2c0004431edd2a10
    name: "Mom keychain"
```


If you only add the first part then all IDs should get reported, if you add the second part then individual sensors should get created (as binary sensors?)
Not sure if this is possible, but that would allow the most flexible approach.
