### ISSUE TITLE
Pass list as value in call_homeassistant_service

### ISSUE THREAD

**Issue by KTibow** [esphome/feature-requests#1080]
**Describe the problem you have/What new integration you would like**
Right now, you can pass numbers and strings to `call_homeassistant_service`. However, you can't pass lists, which is needed to set colors without using `color_name`.

**Please describe your use case for this integration and alternatives you've tried:**
So that I can set colors, or anything else needing passing a list, without making some kind of proxy script.

**Additional context**
I asked for support, and posted my proxy script here: https://community.home-assistant.io/t/passing-list-to-service-call/266214

**Comment by kwirk** [comment]
As a work around, you can use `data_template` for example with *rgbww* bulb color:
```yaml
- homeassistant.service:
    service: light.toggle
    data:
      entity_id: light.my_bulb
    data_template:
      rgbww_color: '[0, 0, 0, 255, 0]'
```
