### ISSUE TITLE
Replacement for TX20/TX23 Wind Speed/Direction Sensor

### ISSUE THREAD

**Issue by IkaSGC** [esphome/feature-requests#1103]
**Describe the problem you have/What new integration you would like**
I would like to add a wind and direction sensor to my weather station. Unfortunately, the TX20 / TX23 sensor is no longer manufactured and sold. There are several ways to replace the device. That is why I do not mention any specific ones.

**Please describe your use case for this integration and alternatives you've tried:**
weather stations

**Additional context**
I couldn't find any other used weather station anywhere.

**Comment by nagyrobi** [comment]
Seems like WS2300-15 is something similar.
Also looks close to TX20 as: https://tasmota.github.io/docs/TX2x/

**Comment by nagyrobi** [comment]
There's a wind speed meter on Aliexpress (black plastic), type **pr-3000-fsjt-n01** works with this config, using an RS485/TTL adapter (connected alone):
```yaml
uart:
  rx_pin: GPIOXX
  tx_pin: GPIOXX
  baud_rate: 4800

modbus:
  id: modbus1

modbus_controller:
- id: wind_speed_meter
  address: 1
  modbus_id: modbus1
  setup_priority: -10
  command_throttle: 200ms
  update_interval: 30s #or whatever you need

sensor:
- platform: modbus_controller
  modbus_controller_id: wind_speed_meter
  name: "Wind speed"
  device_class: wind_speed
  id: wind_speed
  register_type: read
  address: 1
  unit_of_measurement: "m/s"
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
    - multiply: 0.1
```

They also sell a direction sensor, type **pr-3000-fxjt-n01** this config, using an RS485/TTL adapter (connected alone):

```yaml
uart:
  rx_pin: GPIOXX
  tx_pin: GPIOXX
  baud_rate: 4800

modbus:
  id: modbus1

modbus_controller:
- id: wind_direction_meter
  address: 1
  modbus_id: modbus1
  setup_priority: -10
  command_throttle: 200ms
  update_interval: 30s #or whatever you need

sensor:
- platform: modbus_controller
  modbus_controller_id: wind_direction_meter
  name: "Wind direction gear"
  icon: mdi:compass-rose
  register_type: read
  address: 1
  value_type: U_WORD
  accuracy_decimals: 0

- platform: modbus_controller
  modbus_controller_id: wind_direction_meter
  name: "Wind direction degree"
  icon: mdi:compass-rose
  register_type: read
  address: 2
  value_type: U_WORD
  accuracy_decimals: 0
  unit_of_measurement: "°"
```

Note that both **pr-3000-fsjt-n0**1 and **pr-3000-fxjt-n01** are by default set to modbus address `1`, so out of the box it's not possible to connect to the same modbus adapter.

**Comment by nagyrobi** [comment]
The seller offers a helper application for Windows, called `485 Parameter Configuration Tool V5.0.7.1.exe`. The sensor can be connected to the PC with a USB-to-RS485 adapter, and the configuration tool makes it easily possible to change the modbus address to something else, eg. `2` (just type it in the _Addr_ box and press _Setup_ button).

After that it becomes possible to simply connect the sensors in parrallel on the same cable, to a single RS485-TTL adapter attached to a single UART on the ESP:

```yaml
uart:
  rx_pin: GPIOXX
  tx_pin: GPIOXX
  baud_rate: 4800

modbus:
  id: modbus1

modbus_controller:
- id: wind_speed_meter
  address: 1
  modbus_id: modbus1
  setup_priority: -10
  command_throttle: 200ms
  update_interval: 30s #or whatever you need

- id: wind_direction_meter
  address: 2
  modbus_id: modbus1
  setup_priority: -10
  command_throttle: 200ms
  update_interval: 30s #or whatever you need

sensor:
- platform: modbus_controller
  modbus_controller_id: wind_speed_meter
  name: Szélsebesség
  device_class: wind_speed
  id: wind_speed
  register_type: read
  address: 1
  unit_of_measurement: "m/s"
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
    - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: wind_direction_meter
  name: "Wind direction gear"
  icon: mdi:compass-rose
  register_type: read
  address: 1
  value_type: U_WORD
  accuracy_decimals: 0

- platform: modbus_controller
  modbus_controller_id: wind_direction_meter
  name: "Wind direction degree"
  icon: mdi:compass-rose
  register_type: read
  address: 2
  value_type: U_WORD
  accuracy_decimals: 0
  unit_of_measurement: "°"
```
