### ISSUE TITLE
Serial to MQTT

### ISSUE THREAD

**Issue by AquaMCU** [esphome/feature-requests#1105]
**Describe the problem you have/What new integration you would like**

 try to set up a simple serial to mqtt gateway. Basically ESPhome should read a topic like serial/send and send everything that it receives there to the UART and it should pubish everything that comes back from the UART to serial/receive. Should be simple, right? I have seen, that some people want to do something similar, but since they are immediately have to deal with lambdas and custom components, it is out of their ( and my ) league.

I think it would be nice to have something like this as an example on the homepage for other people to solve their serial issues.

The code below, is how far I have come. Unfortunately, I can not find anywhere, how to read from serial (on_receive does not exist). So I do not know if this is a feature or a bug, but it is a pain for all projects, that just want to work with serial.
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

```yaml
mqtt:
  broker: MyBriker
  username: livingroom
  password: MyMQTTPassword
  birth_message:
    topic: inverter/status
    payload: online
  will_message:
    topic: inverter/status
    payload: offline
  on_message:
    topic: inverter/send
    then:
      - uart.write: !lambda "return x['message'];"
uart:
  tx_pin: D0
  rx_pin: D1
  baud_rate: 9600
```
