### ISSUE TITLE
Loop current song for Rtttl Buzzer?

### ISSUE THREAD

**Issue by whc2001** [esphome/feature-requests#1118]
**Describe the problem you have/What new integration you would like**
I am trying to hack a siren, so I would like to play the song sent through MQTT repeatedly until `rtttl.stop` is invoked.

**Please describe your use case for this integration and alternatives you've tried:**
Not aware there are any other options for now.

**Additional context**

**Comment by glmnet** [comment]
You can do that with node automations 

If not sure how to ask in discord they will get you going very quickly

**Comment by whc2001** [comment]
> You can do that with node automations
> 
> If not sure how to, ask in discord they will get you going very quickly

Thanks, do you mean using NodeRED to achieve this? But I wanted it to be self enclosed without relying on other softwares. I have found a solution with `script` though:

```
globals:
  - id: score
    type: std::string

# play_song() { while(1) { rtttl.play(score); while(rtttl.is_playing); } }
script:
  - id: play_song
    then:
      - while:
          condition:
            - lambda: 'return true;'
          then:
            - rtttl.play:
                rtttl: !lambda 'return id(score);'
            - wait_until:
                - not:
                    rtttl.is_playing

mqtt:
  on_message:
    - topic: play
      then:
        - lambda: id(score) = x;
        - script.execute: play_song

    - topic: stop
      then:
        - script.stop: play_song
        - rtttl.stop
        - lambda: id(score) = "";
```
