### ISSUE TITLE
Allow multiple ranges for the sensor.on_value_range trigger

### ISSUE THREAD

**Issue by Nosen92** [esphome/feature-requests#1130]
**Describe the problem you have/What new integration you would like**

Allow multiple ranges for the on_range_value automation trigger.

As it stands, on_range_value can only be included once per sensor. This is because the sensor value is only compared to one range of values. If the value crosses into the range of values, the trigger fires. But since some sensor ranges call for different actions along its range of possible values, this diminishes the on_range_value trigger's usefulness.

**Please describe your use case for this integration and alternatives you've tried:**

For instance, the humidity in a bathroom. If it's 0-33%, turn fan off, if it's 33-67% turn fan to low, if it's 67-100% turn fan to high.

It's currently probably easiest to accomplish this using templates, but templates are not user friendly.

Something like this is far more parseable and easier for the user to maintain:

```
on_value_range:
  below: 33%
  then:
    - homeassistant.service:
        service: fan.turn_off
        data:
          entity_id: fan.bathroom
  above: 33%
  below: 67%
  then:
    - homeassistant.service:
        service: fan.set_speed
        data:
          entity_id: fan.bathroom
          speed: low
  above: 67%
  then:
    - homeassistant.service:
        service: fan.set_speed
        data:
          entity_id: fan.bathroom
          speed: high
```

**Additional context**
