### ISSUE TITLE
turn_on/off_action for switch.gpio 

### ISSUE THREAD

**Issue by WagnerBeccard** [esphome/feature-requests#116]
I try for the last days to sync the state of an relais with an led on a tuya plug 
```
switch:

- platform: gpio
  name: "${plug_name}_Relay"
  id: "${plug_name}_Relay"
  pin: GPIO14
  restore_mode: RESTORE_DEFAULT_OFF
  turn_on_action:
  - switch.turn_on: "${plug_name}_LED_Blue"
  turn_off_action:
  - switch.turn_off:"${plug_name}_LED_Blue"

- platform: gpio
  name: "${plug_name}_LED_Blue"
  id: "${plug_name}_LED_Blue"
  pin: GPIO1
  inverted: True
  restore_mode: RESTORE_DEFAULT_OFF
``` 
like its possible with the template switches already.
