### ISSUE TITLE
Cookbooks for Sonoff Slampher and Sonoff S31

### ISSUE THREAD

**Issue by NearlCrews** [esphome/feature-requests#118]
I'd like to preface this by saying I'm horrible at git and do not know how to create a PR to update the [ESPHome Cookbooks](https://esphome.io/cookbook/index.html), and was hoping someone could get these added. I've got around 13 total deployed total between the Slampher and S31.

[Sonoff Slampher](https://www.itead.cc/slampher.html):
```
esphome:
  name: device_name
  platform: ESP8266
  board: esp01_1m
  esphome_core_version: dev
  arduino_version: dev

wifi:
  ssid: 'Your_SSID'
  password: 'Your_Passwd'
  domain: '.your.domain'

api:

# Enable logging
logger:

ota:

sensor:
  - platform: wifi_signal
    name: "device_name WiFi"

binary_sensor:
  - platform: status
    name: "device_name Status"
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "device_name Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    pin: GPIO12
    name: "device_name Relay"
    id: relay
  - platform: restart
    name: "device_name Restart"

status_led:
  pin:
    inverted: True
    number: GPIO13

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org
```

[Sonoff S31](https://www.itead.cc/sonoff-s31.html):
```
esphome:
  name: your_device
  platform: ESP8266
  board: esp01_1m
  esphome_core_version: dev
  arduino_version: dev
  on_boot:
    then:
      - switch.turn_on: relay

wifi:
  ssid: 'Your_SSID'
  password: 'Your_Passwd'
  domain: '.your.domain'

api:

# Enable logging
logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

ota:

sensor:
  - platform: wifi_signal
    name: "your_device WiFi"
  - platform: cse7766
    current:
      name: "your_device Current"
    voltage:
      name: "your_device Voltage"
    power:
      name: "your_device Power"
      filters:
      - lambda: |-
          if (x > 1000) return {};
          return x;
    update_interval: 15s

binary_sensor:
  - platform: status
    name: "your_device Status"
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "your_device Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    pin: GPIO12
    name: "your_device Relay"
    id: relay
  - platform: restart
    name: "your_device Restart"

status_led:
  pin:
    inverted: True
    number: GPIO13

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org
