### ISSUE TITLE
More clear error messages related to esphome: name

### ISSUE THREAD

**Issue by akasma74** [esphome/feature-requests#119]
**Describe the problem you have/What new integration you would like**
If I try to compile this sample config
````
esphome:
  name: bad name
  platform: ESP8266
  board: d1_mini

switch:
  - platform: restart
    name: device restart
````

I only get

> INFO Reading configuration...
> ERROR Error while reading config: ' ' is an invalid character for names. Valid characters are: abcdefghijklmnopqrstuvwxyz0123456789_ (lowercase, no spaces)
> 

It's very vague as there may be hundreds of `name:` variables, but apparently only `esphome: name` cannot contain spaces etc. 
Error message is a bit exhaustive, too
Line number is exactly what's required here I think.
