### ISSUE TITLE
Please support m5stack-coreink board

### ISSUE THREAD

**Issue by ax42** [esphome/feature-requests#1196]
**Describe the problem you have/What new integration you would like**

Support for https://docs.m5stack.com/#/en/core/coreink

**Please describe your use case for this integration and alternatives you've tried:**

As per the platformio documentation, the board is supported: https://docs.platformio.org/en/latest/boards/espressif32/m5stack-coreink.html#board-espressif32-m5stack-coreink

When I put `m5stack-coreink` as the board type in the esphome config, I get an 'could not find board' error.

**Additional context**

Currently using esphome 1.16.2 (Home Assistant addon)

**Comment by ax42** [comment]
![image](https://user-images.githubusercontent.com/1254869/115368665-97117680-a1c7-11eb-8bec-a54c18e78b0d.png)

**Comment by koenvervloesem** [comment]
What if you try the following:

```
esphome:
  name: "$[devicename}"
  platform: esp32
  board: m5stack-core-esp32
  platformio_options:
    platform: espressif32
    board: m5stack-coreink
    board_build.mcu: esp32
    board_build.f_cpu: 240000000L
```
