### ISSUE TITLE
Add transition_length in servo.write

### ISSUE THREAD

**Issue by Coninox** [esphome/feature-requests#1246]
**Describe the problem you have/What new integration you would like**

It would be nice if we could set the transition_length parameter in the servo.write action.
We could have the ability to have different rotation speed in different cases.

**Please describe your use case for this integration and alternatives you've tried:**

For example: 
```
api:
  services:
    - service: control
      variables:
        level: float
	transition_lenght: string
      then:
        - servo.write:
            id: my_servo1
            level: !lambda 'return (-2*(level/255))+1;'
	    transition_lenght: !lambda 'return transition_lenght;'

switch:
  - platform: template
    name: boule_ch2
    restore_state: true
    optimistic: true
    
    turn_on_action:
      - servo.write:
          id: my_servo1
          level: -1
          transition_length: "00:00:10"

    turn_off_action:
      - servo.write:
          id: my_servo1
          level: 1
          transition_length: "00:00:40"
```
**Additional context**
