### ISSUE TITLE
Extend Neopixelbus to support SK6812 'White Chip' and WWA.

### ISSUE THREAD

**Issue by slimcdk** [esphome/feature-requests#1249]
**Describe the problem you have/What new integration you would like**

Add support for SK6812 White chip and WWA as seen at the bottom on their [product listing](https://www.btf-lighting.com/pages/led-chips-contrast)

**Please describe your use case for this integration and alternatives you've tried:**

A solution could possible be having two new variants `SK6812_WHITE` and `SK6812_WWA` for these chips. 
```yaml
light:
  - platform: neopixelbus
    name: "NeoPixel Light"
    pin: GPIO23
    num_leds: 60
    variant: SK6812_WHITE or SK6812_WWA
```

**Additional context**

Limited testing shows that both chips are reacting to data from this configuration.
```yaml
light:
    - platform: neopixelbus
      name: "NeoPixel Light"
      pin: GPIO23
      num_leds: 60
      variant: SK6812
      type: BRGW
```
[https://www.btf-lighting.com/pages/led-chips-contrast](https://www.btf-lighting.com/pages/led-chips-contrast)
