### ISSUE TITLE
Hidden SSIDs and connection based on signal strength

### ISSUE THREAD

**Issue by ArturFormella** [esphome/feature-requests#1256]
Hello! I have multiple devices with ESP8266 (nodemcu) and 8 WIFI networks with hidden SSID on 10000m^2 area. I would like to use the option to set all the access points so that ESP will choose the one with the best signal strength. 
Today "fast_connect" is required to connect to hidden network. ESPHome prohibits the use of this option with a connection based on signal strength.

**Describe the problem you have/What new integration you would like**

I've made an example of this idea: "allow_hidden_ssid" option which allows to connect to hidden network without disabling signal-strength-based negotiation (fast_connect: false). The string "allow_hidden_ssid" is of course an example only.
```
wifi:
  fast_connect: false
  networks:
  - ssid: "new_york"
    password: "password"
    allow_hidden_ssid: true

  - ssid: "london"
    password: "password"
    allow_hidden_ssid: true

  - ssid: "moscow"
    password: "password"
    allow_hidden_ssid: true

  - ssid: "berlin"
    password: "password"
    allow_hidden_ssid: true

  - ssid: "sydney"
    password: "password"
    allow_hidden_ssid: true

  - ssid: "Wien"
    password: "password"
    allow_hidden_ssid: true
```

**Please describe your use case for this integration and alternatives you've tried:**

I've tried to set the nearest network for every device but it was painful. Buildings and other obstacles change wifi signal. The best solution is to choose WIFI dynamically.

**Additional context**

I have no option do "un-hide" SSIDs.
