### ISSUE TITLE
several xpt2046, please implement "touch:" like "display:" to have more than one xpt2046

### ISSUE THREAD

**Issue by Electronlibre2012** [esphome/feature-requests#1272]
**Describe the problem you have/What new integration you would like**

Hello,

like the "display:" then you can add many display, can you please implement "touch:" to have more than only one xpt2046?

i just want to make a big remote and use 2 TFT ILI9341 screen with xpt2046, but with the "xpt2046:" i can put more than one touchscreen...

Thanks for your reply,

Olivier
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by Electronlibre2012** [comment]
EDIT : perhaps nobody will respond or make something to make it work...so 👍 

- i copy the xpt2046 folder of Esphome in "esphome/custom_component/"
- i rename the xpt2046 folder to xpt2046_2
- i rename the xpt2046.h to xpt2046_2.h and xpt2046.cpp to xpt2046_2.cpp
- in the Esphome config of my node i add : 
````
xpt2046:
  id: touchscreen_up
  cs_pin: 17
  irq_pin: 16
  update_interval: 50ms
  report_interval: 1s
  threshold: 400
  dimension_x: 320
  dimension_y: 240
  calibration_x_min: 240
  calibration_x_max: 3860
  calibration_y_min: 240
  calibration_y_max: 3860
  swap_x_y: true

xpt2046_2:
  id: touchscreen_down
  cs_pin: 19
  irq_pin: 18
  update_interval: 50ms
  report_interval: 1s
  threshold: 400
  dimension_x: 320
  dimension_y: 240
  calibration_x_min: 240
  calibration_x_max: 3860
  calibration_y_min: 240
  calibration_y_max: 3860
  swap_x_y: true
```
no more error, i can validate, now i try to compile...
