### ISSUE TITLE
Support for nodemcu(v2+) in neopixelbus

### ISSUE THREAD

**Issue by magenbrot** [esphome/feature-requests#1274]
**Describe the problem you have/What new integration you would like**

It seems that neopixelbus is not supported on nodemcu(v2+) boards. The IDE tells me to use GPIO pins which aren't available on nodemcu.

**Please describe your use case for this integration and alternatives you've tried:**

Here's the code I'm using:
```
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: D0
    num_leds: 8
    name: "NeoPixel Stick"
```

The IDE gives me the following hint:
![Screenshot_20210623_104421](https://user-images.githubusercontent.com/4865153/123092262-99dc5200-d42a-11eb-874e-a117a35a7ab2.png)

Using the UART method shows the same message.

**Additional context**
