### ISSUE TITLE
Allow Secrets to Create configuration

### ISSUE THREAD

**Issue by 3ative** [esphome/feature-requests#1279]
**Describe the problem you have/What new integration you would like**

Would it be possible to add a check to the "Create configuration" backend to allow for **Secrets** to be used?

For Example:
![01 start](https://user-images.githubusercontent.com/51385971/123531325-80bdf480-d6fb-11eb-8b90-62e6f91c9f79.JPG)

Currently, it results in plain text being added to the config:
```yaml
wifi:
  ssid: "!secret ssid"
  password: "!secret wifi_password"
```
- Note the included quotation marks.

Obviously, it needs to be:
```yaml
wifi:
  ssid: !secret ssid
  password: !secret wifi_password
```

**Please describe your use case for this integration and alternatives you've tried:**

It's obviously an advantage to use secrets in ESPHome and I think this feature could make the user experience smother. 

**Additional context**

Thanks. 👍
