### ISSUE TITLE
name_add_mac_suffix  for hotspot name

### ISSUE THREAD

**Issue by vzagorovskiy** [esphome/feature-requests#1294]
**Describe the problem you have/What new integration you would like**
Add name_add_mac_suffix  option for ssid for “Access Point Mode”

```yaml
wifi:
  ap:
    ssid: "Fallback Hotspot"
    password: "W1PBGyrokfLz"
    name_add_mac_suffix: true
```

**Please describe your use case for this integration and alternatives you've tried:**
Configuring multiple devices at the same time that use single config with name_add_mac_suffix option 

**Additional context**

This option will greatly improve usability when using a single config for many devices.
