### ISSUE TITLE
SPI Support for BMP280

### ISSUE THREAD

**Issue by psbankar** [esphome/feature-requests#1321]
**Describe the problem you have/What new integration you would like**

BMP280 sensor supports I2C as well as SPI but ESPHome currently supports only I2C for it. It would be great if SPI support was added for this sensor as well.

**Please describe your use case for this integration and alternatives you've tried:**

Same as above

**Additional context**

Same as above

**Comment by njbuch** [comment]
I will support this feature request! Thanks

The case is that I have a need for greater distance and the sensor supports this, in the I2C case shorter distance is required.

**Comment by DamianBroj** [comment]
any progress?

**Comment by Stef33fr** [comment]
Did something done for this ?

**Comment by IGitYou** [comment]
I vote for this for sensor distance. It was not clear to me it did not support it until I read this and I was attempting to research how to do exactly what is requested.

**Comment by apbodrov** [comment]
I will try to make a version of bme280 for SPI within a couple of weeks

**Comment by rossens** [comment]
I also look forward to this. 
Another advantage for SPI over I2C - more sensors can be connected.
My understanding is Pi Pico can only support 2 x I2C BME280 (unless including a multiplexer).
But with SPI can support many more sensors.

**Comment by bartoszwalicki** [comment]
Is there any work in progress on this issue?

**Comment by apbodrov** [comment]
> Is there any work in progress on this issue?
Hello! I don’t have a BMP280, I can try to write a pull request blindly, but it’s not very convenient

**Comment by grahen** [comment]
Ja det verkar faktiskt så,

🎉

Vad är det som har åtgärdats?

Då kommer jag cancellera utbytet av min mätare =).

Med vänliga hälsningar
Henrik

Den sön 9 juni 2024 kl 15:26 skrev Andrey Bodrov ***@***.***>:

**Comment by IGitYou** [comment]
I happen to have one I could spare but am in the domestic US, and would not even begin to know how to get something like that to Moscow. Sorry.

**Comment by ademuri** [comment]
I have a [draft pull request](https://github.com/esphome/esphome/pull/7053) which adds support for BMP280 via SPI. You can test it out by adding the following to your yaml file: 

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/ademuri/esphome
      ref: bmp280-spi
    components: [ bmp280_spi, bmp280_base ]

sensor:
  - platform: bmp280_spi
    temperature:
      name: "Board Temperature"
      oversampling: 16x
    pressure:
      name: "Board Pressure"
      oversampling: 16x
    update_interval: 5s
    cs_pin: GPIO16

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15
  miso_pin: GPIO14
  interface: hardware
```

If you do, feedback on whether it worked or not would be helpful.
