### ISSUE TITLE
Improve HA device registry and support multiple devices in one config

### ISSUE THREAD

**Issue by iMicknl** [esphome/feature-requests#1335]
**Describe the problem you have/What new integration you would like**

I recently got started with ESPHome and I like it very much! Most of my cases for ESPHome are in situations where I try to build a 'digital twin' for multiple physical devices. Think of a physical standing desk or Xiaomi MiFlora devices.

However, currently when you configure this, it will add all entities to a single espressif device in Home Assistant. It would be great if you could use the ESPHome YAML to create devices and decide which sensors are linked to which devices.

Use cases:
- ESP32 with Xaomi MiFlora devices
- ESP32 with multiple Switchbot Curtains
- ESP32 with multiple Oral B toothbrushes
(or even a combination of the ones above)

Eventually, this would allow us to show the `model`, `manufacturer` and `firmware` of the device we mimic, instead of our ESPHome device. I was looking to port https://github.com/devWaves/SwitchBot-MQTT-BLE-ESP32, however the features regarding device registry and information are not possible (yet) with ESPHome. 

**Screenshots**
Current situation
![image](https://user-images.githubusercontent.com/1424596/127865508-b6a10618-1d5f-49da-9dcf-84438e0f948e.png)

Proposed situation:
![image](https://user-images.githubusercontent.com/1424596/127865459-7e692d24-5201-432f-8417-6b1e6d8cfb53.png)

(and with multiple devices, there would be multiple entries)

**Please describe your use case for this integration and alternatives you've tried:**

Prefixing all entities with the digital twin device name, however this will be messy at some point and doesn't show up nice in the Home Assistant device registry.

**Additional context**

This would mainly be a cosmetic change, so I can understand that this is not something which has any priority over the other issues. However, perhaps there is someone that would like to tackle this, or work with me to see how we can add this. 
(unfortunately my C++ is really limited, however I can do Python :-)).

**Example YAML**
```yaml
# If not added to a device, it will be added to the main device
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

# If added to a device, it will create a new device in the Device Registry
device:
  desk:
    name: Desk Mick
    model: EK5
    manufacturer: Flexispot

  - platform: uart
    name: "Preset 1"
    id: switch_preset1
    icon: mdi:numeric-1-box
    data: [0x9b, 0x06, 0x02, 0x04, 0x00, 0xac, 0xa3, 0x9d]
    uart_id: desk_uart
```

**Comment by cliffordwhansen** [comment]
I would also like to see this, I have an ESP32 reading Xiaomi ble temp sensors, and it would be nice if they were different devices.

Might be possible to get the platform to register as sub device of the integration?
The Plex, SynologyDSM, and Unifi integrations do something like that.

or something like this in yaml
eg.
```yaml
esp32_ble_tracker:

device:
  bedroom:
    name: Bedroom
    model: lywsdcgq
    manufacturer: Xiaomi
    sensor:
      - platform: xiaomi_lywsdcgq
        mac_address: xx:xx:xx:xx:xx:xx
        temperature:
          name: ${name} Temperature
          state_class: measurement
        humidity:
          name: ${name} Humidity
          state_class: measurement
        battery_level:
          name: ${name} Battery Level
          state_class: measurement
```

I also think this will require work on the HomeAssistant integration as well to add device support.

**Comment by jesserockz** [comment]
This is certainly possible from the HA side, and is also on our list TODO at some point. But will probably require quite a bit of work.

**Comment by nagyrobi** [comment]
May be related to https://github.com/esphome/feature-requests/issues/1714

**Comment by kpfleming** [comment]
I've also been wanting to do this, and I've got the time to work on the implementation as well (it will definitely be a significant amount of work). This is the same request as in #1714 (which was closed) and in #2275.

As a first step, I've written a proposal document describing why this would be useful, and how I'd go about implementing it. The doc is [here](https://docs.google.com/document/d/1eWG4a2TuxdSo7Mj8D_0cFBMFoumGwI-faVCmNq2rbmI/edit?usp=sharing) and comments are most welcome. For those who don't want to use Google Docs, I've attached V1 of the proposal doc to this comment, and I'll attach future versions as well as we make progress towards a decision.

[V1 - Proposal Connected Devices in ESPHome.pdf](https://github.com/esphome/feature-requests/files/12373244/V1.-.Proposal.Connected.Devices.in.ESPHome.pdf)

@nagyrobi If you want to close #2275 in favor of this one, so the discussion can live in one issue, that might be good.

**Comment by dougiteixeira** [comment]
### I leave here the suggestion I made in #2275 to contribute to the discussion:

We often use the same ESP device to connect sensors that are not always related but are physically close, taking better advantage of the ESP's GPIO.

In these cases, things can get pretty confusing on the Home Assistant, as the device will have a lot of unrelated entities.

With that in mind, I would like to suggest a resource so that it is possible to configure in ESPHome which device each entity will be linked to when exposed by the API or MQTT.

It would look something like the code below (omitting `device_id` in the component would keep the current behavior).

```
esphome:
  friendly_name: Device Default
[…]

devices:
  - id: device_1
    friendly_name: Device 1
  - id: device_2
    friendly_name: Device 2

[…]

sensor: 
  - platform: xxxxx
    device_id: device_1
    name: Sensor device 1

  - platform: xxxxx
    name: Sensor device default

switch:
  - platform: xxxxx
    device_id: device_2
    name: Switch device 2
```

These secondary devices would be linked to  the main (default) device by Home Assistant's `via_device` property, making it easier to navigate between them in Home Assistant.

I don't have the knowledge to implement such features, so if anyone is willing to evaluate this possibility I would be very grateful!

This configuration would only have an effect on exposing the entities to the Home Assistant API or via MQTT (maybe including the webserver's dashbord?).

**Comment by kpfleming** [comment]
If you take a look at the last example in the proposal document, it provides the functionality you are looking for (combining unrelated `switch` and `cover` devices into single "device" on the HA side).

**Comment by dougiteixeira** [comment]
I read the proposal and I also think it is good.

Greatly improves the user experience when the ESP board has multiple unrelated components.

Thank you @kpfleming for your willingness to make this a reality.

**Comment by zhaqianyuan** [comment]
this is which I need

**Comment by dougiteixeira** [comment]
> I've also been wanting to do this, and I've got the time to work on the implementation as well (it will definitely be a significant amount of work). This is the same request as in #1714 (which was closed) and in #2275.
> 
> As a first step, I've written a proposal document describing why this would be useful, and how I'd go about implementing it. The doc is [here](https://docs.google.com/document/d/1eWG4a2TuxdSo7Mj8D_0cFBMFoumGwI-faVCmNq2rbmI/edit?usp=sharing) and comments are most welcome. For those who don't want to use Google Docs, I've attached V1 of the proposal doc to this comment, and I'll attach future versions as well as we make progress towards a decision.
> 
> [V1 - Proposal Connected Devices in ESPHome.pdf](https://github.com/esphome/feature-requests/files/12373244/V1.-.Proposal.Connected.Devices.in.ESPHome.pdf)
> 
> @nagyrobi If you want to close #2275 in favor of this one, so the discussion can live in one issue, that might be good.

Hi @kpfleming, please let us know if you proceeded with the implementation based on your proposal. This feature would be really nice! Thanks.

**Comment by kpfleming** [comment]
I've got some non-work time coming up over the next two weeks so I plan to start working on this soon. Hopefully @jesserockz will get a few moments to give this idea a sanity check before I get too far into it!

**Comment by jesserockz** [comment]
I have nothing against the idea, as long as it doesnt complicate the codebase too much.

I would think something like this in config:
```yaml
esphome:
  ...
  
sub_devices:
  - id: that_ble_thermometer
    name: ...
    manufacturer: ...
    mac: ...

sensor:
  - platform: some_ble_sensor_platform
    name: Temperature
    device_id: that_ble_thermometer
    ...
```

In terms of c++, maybe `EntityBase` just needs an optional pointer to a `SubDevice` and then the api and mqtt code can send an id of that alonf with the `EntityInfo` message, and also send the sub_devices by themselves before the entities so Ha can link them up
