### ISSUE TITLE
Check ID exists

### ISSUE THREAD

**Issue by joshuaspence** [esphome/feature-requests#1351]
**Describe the problem you have/What new integration you would like**
I have created a package that I am using for all of my Shelly 2.5 devices. This package includes power/temperature limiting for both outputs, although on some of my Shelly devices I am only using one of the two device outputs.

**Please describe your use case for this integration and alternatives you've tried:**
Originally I was using the following configuration:

```
  - platform: 'ade7953'
    irq_pin: 'GPIO16'
    voltage:
      name: '${device_name} Voltage'
      internal: true
    current_a:
      name: '${device_name} Output2 Current'
      internal: true
    current_b:
      name: '${device_name} Output1 Current'
      internal: true
    active_power_a:
      name: '${device_name} Output2 Power'
      filters:
        multiply: -1
      on_value_range:
        above: '${max_power}'
        then:
          - output.turnoff: 'relay2'
```

I then tried this:

```
  - platform: 'ade7953'
    irq_pin: 'GPIO16'
    voltage:
      name: '${device_name} Voltage'
      internal: true
    current_a:
      name: '${device_name} Output2 Current'
      internal: true
    current_b:
      name: '${device_name} Output1 Current'
      internal: true
    active_power_a:
      name: '${device_name} Output2 Power'
      filters:
        multiply: -1
      on_value_range:
        above: '${max_power}'
        then:
          - lambda: |-
              output::BinaryOutput *output = id(relay2);

              if (output != NULL) {
                output->turn_off();
              }
```

Both of these fail with the following error:

```
Couldn't find ID 'relay2'. Please check you have defined an ID with that name in your configuration. These IDs look similar: "relay1".
```

**Additional context**
