### ISSUE TITLE
Convert substitution to mDNS friendly name

### ISSUE THREAD

**Issue by ElVit** [esphome/feature-requests#1367]
**Describe the problem you have/What new integration you would like**

It would be nice if there would be a function to convert a substitution to a mDNS friendly name.

**Please describe your use case for this integration and alternatives you've tried:**

I have a substitution for my device name which I use for my sensor names. 
To keep the code clean I want to use this substitution also for the device name.
This is not possible because it contains spaces and/or underscores which is not permitted for a mDNS name.
It would be nice if all illegal characters would be automatically replaced with "-" for the mDNS name.

An alternative may be to use the file name and replace all mDNS illegal characters with "-".

**Additional context**

```
substitutions:
  device_name: "Wemos D1 mini 1"

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini

...

binary_sensor:
  - platform: status
    name: "${device_name} Status"
```
