### ISSUE TITLE
Add possibility to read fan speed in lambdas e.g. id(fan.my_fan).speed

### ISSUE THREAD

**Issue by dgtal1** [esphome/feature-requests#1380]
**Describe the problem you have/What new integration you would like**

I need to be able to react on fan speed changes set by either home assistant or locally by a micro switch and automation. Currently this is impossible as there is no way to read a fan speed (PWM level).

**Please describe your use case for this integration and alternatives you've tried:**

I can't find any solution to this currently

**Additional context**

**Comment by nuttytree** [comment]
While this is not documented you actually can access the speed, state, oscillating, and direction properties of a fan.  One thing to note is that the id function takes only the id of the fan and does not expect the "fan." in front of the id. Here is an example:
```yaml
output:
  - platform: gpio
    id: fan_out
    pin: GPIO10

fan:
  - platform: binary
    id: my_fan
    output: fan_out

interval:
  - interval: 1min
    then:
      - lambda: >-
          int speed = id(my_fan).speed;
          bool state = id(my_fan).state;
          bool oscillating = id(my_fan).oscillating;
          FanDirection direction = id(my_fan).direction;
```
