### ISSUE TITLE
use if/else conditions with on_multi_click

### ISSUE THREAD

**Issue by Ramblurr** [esphome/feature-requests#1383]
**Describe the problem you have/What new integration you would like**

I would like to be able to use the`on_multi_click` combined with if/else conditions.

**Please describe your use case for this integration and alternatives you've tried:**

I have a Shelly device flashed with ESPHome. The relay controls a light fixture that has Zigbee bulbs. My esphome configuration keeps the relay turned on (so the zigbee bulbs have power), and then uses `on_multi_click` to trigger automations in home assistant (which control the bulbs via zigbee).

This works great, until the esphome device loses connection to HA, then the switch does nothing. So I use the `api.connected` condition to only control the zigbee when the device is connected to HA, otherwise the switches control the relay like a normal light switch.

The on_multi_click automation doesn't support conditionals, which makes it more difficult to use.

**Additional context**

**Comment by nuttytree** [comment]
Are you saying you can't compile the device with conditionals on the on_multi_click trigger or that you can compile but it doesn't actually work?  I was able to successfully compile the code for a device (but didn't actually test that it worked on a physical device) that had this configuration:
```yaml
binary_sensor:
  - platform: gpio
    id: my_button
    pin:
      number: 12
      mode: INPUT_PULLUP
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for 0.5s to 1s
        - OFF for at least 0.2s
      then:
        - if:
            condition:
              api.connected:
            then:
              - logger.log: "Multi-clicked while API was connected"
            else:
              - logger.log: "Multi-clicked while API was disconnected"
```
