### ISSUE TITLE
DHT20 temperature and humidity sensor

### ISSUE THREAD

**Issue by mcristina422** [esphome/feature-requests#1398]
**Describe the problem you have/What new integration you would like**
Support for the DHT20 temperature and humidity sensor that communicates over I2C.

The sensor is sold here https://www.adafruit.com/product/5183

**Please describe your use case for this integration and alternatives you've tried:**
I'll try implementing a [custom component](https://esphome.io/custom/i2c.html) but I'd be nice to see this in core

**Additional context**

**Comment by mcristina422** [comment]
Using some examples I have a basic setup working with a d1_mini
```yaml
esphome:
  name: dht20
  platform: ESP8266
  board: d1_mini
  includes:
  - ahtx0.h
  libraries:
  - "https://github.com/adafruit/Adafruit_AHTX0"

# wifi, ota, api etc

# not needed for some reason? idk
# i2c:
#   - id: bus_a
#     sda: D2
#     scl: D1
#     scan: True
    
sensor:
  - platform: custom
    lambda: |-
      auto aht20 = new AHTX0Sensor();
      App.register_component(aht20);
      return {aht20->temperature_sensor, aht20->humidity_sensor};
    sensors:
    - name: "Temperature"
      unit_of_measurement: °C
      accuracy_decimals: 2
    - name: "Humidity"
      unit_of_measurement: "%"
      accuracy_decimals: 2
```
where the `ahtx0.h` file is 
```cpp
#include "esphome.h"
#include <Wire.h>
#include "Adafruit_AHTX0.h"

#define TAG "ahtx0"

class AHTX0Sensor : public PollingComponent {

  public:
    Adafruit_AHTX0 aht;
    Sensor *temperature_sensor = new Sensor();
    Sensor *humidity_sensor = new Sensor();

    AHTX0Sensor() : PollingComponent(15000) { }

    void setup() override {
      ESP_LOGCONFIG(TAG, "Setting up AHTX0Sensor...");
      if (!aht.begin()) {
        ESP_LOGCONFIG(TAG, "Failed to start AHTX0Sensor...");
      }
      LOG_SENSOR("  ", "Temperature", this->temperature_sensor);
      LOG_SENSOR("  ", "Humidity", this->humidity_sensor);
    }

    void update() override {
      sensors_event_t humidity, temp;
      aht.getEvent(&humidity, &temp);
      temperature_sensor->publish_state(temp.temperature);
      humidity_sensor->publish_state(humidity.relative_humidity);
    }
};
```
