### ISSUE TITLE
Support Austrian Dsmr encryption with 2 keys for the Slimmelezer

### ISSUE THREAD

**Issue by wieluk** [esphome/feature-requests#1404]
**Describe the problem you have/What new integration you would like**

I would like to use the slimmelezer in Austria with the Sagecom T210-D-r and the Sagecom S210 energy meter.
All information I could gather so far are these:
Safetylayer COSEM Security Suite 0, additional Datatransfer encryption, two keys needed 
GAK > Global authentification Key and
GUEK > Global unicast encryption Key

The best documentation I found for Austria was this document for a austrian P1 concept:
https://oesterreichsenergie.at/fileadmin/user_upload/Smart_Meter-Plattform/20200201_Konzept_Kundenschnittstelle_SM.pdf 

**Please describe your use case for this integration and alternatives you've tried:**

I tried setting up the slimmelezer with setting both keys as Dsmr key individually. 
But my log only returns:
`[W][dsmr:126]: Timeout while waiting for encrypted data or invalid data received.`
and sometimes inbetween it sends Wifi-Signal strength or uptime.

**Additional context**

I contacted the seller of the slimmelezer and he was very nice but told me to ask here because he didn't write the code.
He said that they also use two keys in Luxemburg. Maybe the data is similar? I will try to get more information in the next days. Unfortunately it seems really hard to get information on this.

**Comment by wieluk** [comment]
On the Sagecom S210 I am getting this error message in the log: 
```
Invalid unit
[E][dsmr:138]: 1-0:1.8.0(000439385*Wh)
                    ^
```
so the decryption seem to work. 

for the T210-D-r 99% of the time i get the log posted in my first post. 
But once I got this: 

```
[E][dsmr:138]: �P[�%A_��V�7�o'�k����÷]�YN�����e
^
Data should start with /
```
so decryption does not seem to work for this device.

**Comment by mmakaay** [comment]
For the "Invalid unit" error, I have worked out a solution. The decryption indeed seems to work there, but the meter reports a value in Wh instead of kWh, which can be considered a violation of the standard. I wrote a fix for the DSMR parser library, which allows meters to report both Wh and kWh, which fixes this specific error. 
The fix was tested against my own and against @wieluk 's meter. Both are working with this change.

PR can be found at: https://github.com/glmnet/arduino-dsmr/pull/7

**Comment by mprokop** [comment]
Hello,
is there an update to the unit problem?

Is there any way I can integrate / test this fix?

I tried to use the library from Github but I still get the "Invalid unit" errors.

**Comment by mmakaay** [comment]
If you are using the code from the PR that I mentioned, then possibly you are running into a different issue.
Can you share the exact error message that you are getting, so this can be asserted?

**Comment by mprokop** [comment]
Thanks, I just used the library but not the PR for the component.
After I changed the configuration it works, but I'm not able to the `receive_timeout` anymore.


Here is my configuration for reference.

```
esphome:
  name: $devicename
  platform: ESP32
  board: nodemcu-32s

  libraries:
    - https://github.com/glmnet/arduino-dsmr.git#master

external_components:
  - source: github://pr#2841
    components: [ dsmr ]

uart:
  id: uart_smart_meter
  rx_pin:
    number: GPIO16
    inverted: true
  baud_rate: 115200
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 3000

dsmr:
  uart_id: uart_smart_meter
  decryption_key: !secret smart_meter_GUEK
  max_telegram_length: 3000

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      id: energy_delivered_tariff1
      name: "${devicename}_energy_delivered_tariff1"
    power_delivered :
      id: power_delivered
      name: "${devicename}_power_delivered"

```

**Comment by nagyrobi** [comment]
Corresponding PR https://github.com/esphome/esphome/pull/2841 closed due to inactivity.

**Comment by mmakaay** [comment]
Reopened the issue. My change for the external Dsmr library was never incorporated, but the "Invalid unit" issue still stands.
That's something that I want to fix through another route, dropping the external library.

**Comment by maxodoble** [comment]
any news on the status here?

@wieluk: do you have a working slimmelezer configuration for the  Austrian T210 smartmeter you can share, or have infos on how to make it work for a esphome newbie?

thanks,
Max

**Comment by wieluk** [comment]
Yea for me it is working right now. I don't know if the external Dsmr library from mmakaay is imported.  I never updated to the most recent esphome version because for me it worked with adding his library manually.

My yaml looks like this right now.
```
substitutions:
  device_name: slimmelezerday
  device_description: "DIY P1 module to read your smart meter"

esphome:
  name: ${device_name}
  comment: "${device_description}"
  platform: ESP8266
  esp8266_restore_from_flash: true
  board: d1_mini
  name_add_mac_suffix: false

wifi:
  networks:
    - ssid: 'wifi'
      password: 'password'

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: 'password'
    ap_timeout: 15s

captive_portal:

logger:

api:

ota:

web_server:
  port: 80

uart:
  baud_rate: 115200
  rx_pin: D7

dsmr:
  decryption_key: #GUEK KEY

sensor:
  - platform: dsmr
    energy_delivered_lux:
      name: "Energy Consumed total_increasing"
      state_class: total_increasing
    energy_delivered_tariff1:
      name: "Energy Consumed total_increasing Tariff 1"
      state_class: total_increasing
    energy_delivered_tariff2:
      name: "Energy Consumed total_increasing Tariff 2"
      state_class: total_increasing
    power_delivered:
      name: "Power Consumed"
      #accuracy_decimals: 0
```
