### ISSUE TITLE
Support for Light sleep mode

### ISSUE THREAD

**Issue by ghvader** [esphome/feature-requests#141]
**Describe the problem you have/What new integration you would like**

Support for ESP32 light sleep mode

**Please describe your use case for this integration and alternatives you've tried:**

ESPhome only supports deep sleep mode. i'm building battery powered sensors that are awoke by the use of PIR, waking from deep sleep activate the reset function and the whole board reboots upon motion detection.
support for light sleep or alternative sleep modes that permit this behavior is requested.

**Additional context**

https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/sleep_modes.html

**Comment by OttoWinter** [comment]
The highest contributor to power usage is by far the WiFi interface, AFAIK light sleep current is dwarfed by wifi. Have you looked into the wifi power save mode?

As light sleep would also require many core changes, I don't think this will be supported. However, esp-idf might support an automatic version of it at some point - so that might be an option once it ships. https://github.com/espressif/arduino-esp32/pull/1165#issuecomment-376717287

**Comment by ghvader** [comment]
@OttoWinter forgive me as i'm not a C programmer, so i may be misunderstanding, 
but if esp_deep_sleep_start() calls the deep sleep function and esp_light_sleep_start() enables light sleep, would that not be trivial to implement?
"esp_light_sleep_start() function can be used to enter light sleep once wake-up sources are configured."

according to that 1st link, wifi power saving mode still use 3 - 20 mA while light sleep mode uses 0.8 mA
in light sleep mode, i don't believe an entire board reset would be required upon receiving a signal from a configured wake up pin.
appreciate you taking the time to look at my request either way.

**Comment by OttoWinter** [comment]
AFAIK, light sleep is not designed for what you want it to do: extended sleeps, it's designed for short sleeps of a few milliseconds.

I also don't understand why deep sleep wouldn't work for you. Have you tried setting static IP + fast_connect mode already? Connection time is pretty darn fast then.

**Comment by ghvader** [comment]
@OttoWinter unless i have something misconfigured. device goes into deep sleep mode and then when motion is detected, it wakes it up. the problem is, it doesn't wake it up. it does a full reset/reboot, even connecting fast is sufficient, because you miss the initial motion.
so you walk into a room, motion is detected, then the light turns on (is what is supposed to happen) instead the esp32 is rebooting from deep sleep mode, re-connecting and you have to stand in the dark moving around again, until it picks up your motion a 2nd time to then turn on the light.

```

19:27:57.320 -> [0;35m[C][deep_sleep:034]:   Wakeup Pin: GPIO15 (Mode: INPUT)[0m
19:27:58.984 -> [0;36m[D][api:546]: Client 'Home Assistant 0.90.1 (192.168.2.70)' connected successfully![0m
19:28:05.284 -> [0;32m[I][deep_sleep:072]: Beginning Deep Sleep[0m
19:28:10.618 -> ets Jun  8 2016 00:22:57
19:28:10.618 -> 
19:28:10.618 -> rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
19:28:10.618 -> configsip: 0, SPIWP:0xee
19:28:10.618 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
19:28:10.651 -> mode:DOUT, clock div:2
19:28:10.651 -> load:0x3fff0018,len:4
19:28:10.651 -> load:0x3fff001c,len:928
19:28:10.651 -> ho 0 tail 12 room 4
19:28:10.651 -> load:0x40078000,len:9280
19:28:10.651 -> load:0x40080400,len:5860
19:28:10.651 -> entry 0x40080698
19:28:11.054 -> [0;32m[I][logger:119]: Log initialized[0m
```

**Comment by ghvader** [comment]
here is my yaml file
```
esphome:
  name: test
  platform: ESP32
  board: lolin_d32

text_sensor:
  - platform: version
    name: "ESPhome version 1.0"

wifi:
  ssid: removed
  password: removed
  fast_connect: on 
  manual_ip:
    static_ip: 192.168.x.x
    gateway: 192.168.x.x
    subnet: 255.255.255.0

web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin: GPIO15
    name: "PIR Sensor"
    device_class: motion

sensor:
  - platform: adc
    pin: GPIO32
    name: "TEMT6000 Illuminance"
    unit_of_measurement: lx
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;

  - platform: dht
    pin: GPIO17
    model: DHT22
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
   # update_interval: 60s
deep_sleep:
  run_duration: 10s
  sleep_duration: 5min
  wakeup_pin: GPIO15
  wakeup_pin_mode: IGNORE
```
