### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by andker87** [esphome/feature-requests#1411]
**Describe the problem you have/What new integration you would like**

Implementation of monthly consumption meter, as is already done for daily.

**Please describe your use case for this integration and alternatives you've tried:**

Home Assistant foresees the possibility to implement a monthly counter, however due to connectivity problems or a high update rate of the base sensor, the counter -especially the monthly one- could undergo a considerable deviation from the real consumption.
It would therefore be useful to introduce a monthly meter, which would be more reliable than the one calculated by external software (e.g. Home Assistant).

**Additional context**

**Comment by snakuzzo** [comment]
it might be useful to have only one `total_energy` platform and manage the cycle with a specific parameter

e.g.

```yaml
sensor:
  - platform: total_energy
    name: "Total Energy"
    cycle: <daily | weekly | monthly | yearly> 
    power_id: my_power
```
