### ISSUE TITLE
SDM meter support for modus flow_control_pin

### ISSUE THREAD

**Issue by depuits** [esphome/feature-requests#1415]
**Describe the problem you have/What new integration you would like**

The current sdm meter component does not support the flow_control_pin like the Modbus Component. The use case for this is stated in the modbus component documentation.

**Please describe your use case for this integration and alternatives you've tried:**

I've tried using the `flow_control_pin` option in the configuration but it states that this is an invalid option.

**Additional context**

**Comment by martgras** [comment]
You have to add 'flow_control_pin' to the  modbus component not to sdm

```
modbus:
  id: modbus_heidelberg_wallbox
  flow_control_pin: 4
  send_wait_time: 200ms
```
