### ISSUE TITLE
Support for Homey in ESPHome 

### ISSUE THREAD

**Issue by Radiotechniman** [esphome/feature-requests#1418]
**Describe the problem you have/What new integration you would like**

I would love to see Homey (https://homey.app/en-us/) support in ESP home, 
they already have an arduino compatible library :
https://www.arduino.cc/reference/en/libraries/homeyduino/
 

**Please describe your use case for this integration and alternatives you've tried:**

I love home automation and i'm frequently tinkering with all sorts of sensors, ESPHome is my go-to platform, but the lack of homey support is a shame, otherwise I could use one sensor for multiple hubs (win-win) 

Athom (the company) will be releasing Homey globally soon, this will only increase the userbase.

**Additional context**

How I would see this being implemented (as a noob) 
In esphome one would add the hardware-sensors like normal, including an ID and lastly a "homey:" keyword
here you would be able to create your homey sensor by specifying the capabilities and the corresponding ID

```
homey:
  livingroom_sensor:
    name: Livingroom environment
    icon: alarm_motion
    capabilities:
      measure_temperature: livingroom_temperature
      measure_humidity: livingroom_humidity
      measure_luminance: livingroom_luminance
      alarm_motion: livingroom_motion
      alarm_contact: toilet_door
      button: test234
      onoff: vent_1
      dim: test_slider
```

The Homey sensors (can) consist of multiple sensors, someone already tried to make a custom_component for Home Assistant, but it doesn't seem to be working anymore : https://github.com/dutchdevil83/io.homeassistant
The above comes from there, maybe some of the python code can be (re)used?
