### ISSUE TITLE
MPDMv7.5 DAC support (MPC4726)

### ISSUE THREAD

**Issue by daenny** [esphome/feature-requests#145]
**Describe the problem you have/What new integration you would like**

I created a MPC4726 DAC output component tailored to the MPDMv7.5. I already had done something similar for Tasmota (https://github.com/arendst/Sonoff-Tasmota/pull/3015).
Maybe that is useful for some other people as well.

```cpp
#include "esphome.h"
using namespace esphome;

class DacOut : public Component, public output::FloatOutput {
 public:
  void setup() override {
    // This will be called by App.setup()
    Wire.begin();
    pinMode(16, OUTPUT);

  }

  void write_state(float state) override {
    //first check if the general output should be enables
    if (state == 0.0) {
        digitalWrite(16, 0);
    }
    else {
        digitalWrite(16, 1);
    }
    // state is the amount this output should be on, from 0.0 to 1.0
    // we need to convert it to an integer first
    int value = state * 1024;
    //Map to 2100-3350, values by trial and error, may depend on used light. I am using LEDs. 
    uint16_t output = (uint16_t) map((1024-value), 0, 1024, 2100, 3350);
  
    Wire.beginTransmission(0x60); //address of DAC
    Wire.write(0x40); //write data to DAC
    Wire.write(output >> 4);                   // Upper data bits          (D11.D10.D9.D8.D7.D6.D5.D4)
    Wire.write((output & 15) << 4);            // Lower data bits          (D3.D2.D1.D0.x.x.x.x)
    Wire.endTransmission();

  }
};
```

yaml config:
```yaml
substitutions:
  devicename: ikea_stand
  upper_devicename: Ikea Stand
  ip_end: "207"

esphome:
  name: ${devicename}_light
  platform: ESP8266
  board: esp01_1m
  includes:
    - dac_out.h

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: True
  frequency: 400kHz

wifi:
  ssid: 'xxx'
  password: 'xxx'
  manual_ip:
    static_ip: "192.168.2.${ip_end}"
    gateway: 192.168.2.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'xxx'

ota:
  password: 'xxx'

output:
- platform: custom
  type: float
  lambda: |-
    auto my_custom_float_output = new DacOut();
    App.register_component(my_custom_float_output);
    return {my_custom_float_output};
  outputs:
    id: dac_out

# Example configuration entry
light:
  - platform: monochromatic
    name: "${upper_devicename} Light"
    output: dac_out
    default_transition_length: 0.1s

switch:
  - platform: restart
    name: "${upper_devicename} Light Restart"

# Example configuration entry
web_server:
  port: 80
```

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**
