### ISSUE TITLE
Display Pages for character-based displays

### ISSUE THREAD

**Issue by JanPeter1** [esphome/feature-requests#1480]
**Describe the problem you have/What new integration you would like**

Allow the Display Pages concept also for character-based (eg. LCD-) displays.

**Please describe your use case for this integration and alternatives you've tried:**

I really like the concept of "pages" that can be used to show different texts on a display. Unfortunately, this concept is only coupled with the DisplayBuffer class that is used for pixel-based displays. I'd like to use it as well for character-based displays (I have a UART-based M18ST05B display from an old computer).

**Additional context**

The most easy way would be to declare the following functions as _virtual_:
```
void DisplayBuffer::print(int x, int y, Font *font, Color color, TextAlign align, const char *text);
void DisplayBuffer::clear();
```
With that, a character-based display class can inherit from _display_buffer::DisplayBuffer_ and the pages mechanism can be used right-away (ignoring all pixel-based content).
A more "sophisticated" solution would be a common base class for all displays that can handle display pages and common aspects (eg. strftime, printf, columns/rows/text alignment) and inherit DisplayBuffer and LcdDisplay from that class.

Currently I'm developing a M18ST05B display class that can be used like this:

```
m18st05b:
  id: my_display
  name: $upper_devicename
  pages:
    - id: page_time
      lambda: |-
        m18st05b::M18ST05B& mit = (m18st05b::M18ST05B&)it;
        mit.strftime(0, 0, TextAlign::CENTER, "%H:%M:%S", id(homeassistant_time).now());
        mit.strftime(0, 1, TextAlign::CENTER, "%d.%m.%Y", id(homeassistant_time).now());
        mit.image("time");
    - id: page_temp
      lambda: |-
        m18st05b::M18ST05B& mit = (m18st05b::M18ST05B&)it;
        mit.printf(0, 0, "In:  %4.1fC %2.0f%%", id(temp1_temperature).state, id(temp1_humidity).state); 
        mit.printf(0, 1, "Out: %4.1fC %2.0f%%", id(aussen_temperature).state, id(aussen_humidity).state); 
        mit.image("temp");
```
But I have to re-write all the _print/printf/strftime_ functions and also the cast-command doesn't look right (and using _id(my_display)_ instead of _mit_ also feels wrong).

**Comment by bachya** [comment]
I wholeheartedly support this. I have several LCDs with PCF8574s and would love to display multiple "pages" of content. Right now, I'm having to do wild things like hold onto multiple `text_sensors` and attempt to redraw them based on the time; very unwieldy.

**Comment by LewisSpring** [comment]
This looks like my request of #1300. Glad to see there's some other people who want this feature too.

**Comment by nagyrobi** [comment]
I added a `select` with page numbers and:

```yaml
  lambda: |-
        if (id(lcd_page).state == "1") {
          it.print(0, 1, "Page1");
        }
        if (id(lcd_page).state == "2") {
          it.print(0, 1, "Page2");
        }
        if (id(lcd_page).state == "3") {
          it.print(0, 1, "Page3");
        }
```

I change the values of the `select` with a rotary encoder, but one could step it automatically with some timer routine.

**Comment by LewisSpring** [comment]
> Until pages will be supported, I added a `select` with page numbers and:
> 
> ```yaml
>   lambda: |-
>         if (id(lcd_page).state == "1") {
>           it.print(0, 1, "Page1");
>         }
>         if (id(lcd_page).state == "2") {
>           it.print(0, 1, "Page2");
>         }
>         if (id(lcd_page).state == "3") {
>           it.print(0, 1, "Page3");
>         }
> ```
> 
> I change the values of the `select` with a rotary encoder, but one could step it automatically with some timer routine.

This seems like a decent workaround - I haven't had chance to try it yet, but I'll let you know how it works for me.

**Comment by nagyrobi** [comment]
Or, another approach:


```yaml
display:
  - platform: lcd_pcf8574
    dimensions: 20x4
    address: 0x27
    id: lcd
    lambda: |-
            switch (id(page)){
              case 1:
                it.print(0, 1, "Page1");
                break;
              case 2: 
                it.print(0, 1, "Page2");
                break;
              case 3: 
                it.print(0, 1, "Page3");
                break;
            }

globals:
- id: page
  type: int
  initial_value: "1"

interval:
- interval: 5s
  then:
    - lambda: |-
        id(page) = (id(page) + 1);
        if (id(page) > 3) {
          id(page) = 0;
        }
```
