### ISSUE TITLE
Request to add a popular photovoltaic controller mc24xx series

### ISSUE THREAD

**Issue by phpphph** [esphome/feature-requests#1485]
I can't write code, but I obtained the communication protocol file from the manufacturer. The controller is based on Modbus protocol. The instructions and instructions are in the attachment. Please check it. Thank you!
[MC2420 MODBUS.docX](https://github.com/esphome/feature-requests/files/7441032/MC2420.MODBUS.docX)

**Comment by martgras** [comment]
(I had to use an online translator since I can't read Chinese - an English PDF would have been a lot better) 

You can use the [mod_controller](https://esphome.io/components/modbus_controller.html) component. 
There is no programming required but you have to define the registers yourself .    

The sample for  [EPEVER](https://esphome.io/cookbook/tracer-an.html) might also help how to use the various register types

Based on the docs I implemented a few registers to get you started. 

```yaml
substitutions:
  updates: 60s
  unique_id: solarstation

esphome:
  name: ${unique_id}
  platform: ESP32
  board: esp32dev

# Enable logging
logger:
  level: DEBUG


uart:
  id: mod_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  stop_bits: 1

modbus:
  #flow_control_pin: 23
  send_wait_time: 200ms
  id: mod_bus_mcp2420

modbus_controller:
  - id: mcp2420
    ## the Modbus device addr
    address: 0x1
    modbus_id: mod_bus_mcp2420
    command_throttle: 200ms
    setup_priority: -10
    update_interval: ${updates}

sensor:  
  - platform: modbus_controller
    modbus_controller_id: mcp2420
    id: array_rated_voltage
    name: "array_rated_voltage"
    address: 0xA
    unit_of_measurement: "V"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 0


  - platform: modbus_controller
    modbus_controller_id: mcp2420
    id: array_rated_current
    name: "array_rated_current"
    address: 0xB
    unit_of_measurement: "A"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: mcp2420
    name: "Battery Power SOC"
    address: 0x100
    unit_of_measurement: "%"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 0


  - platform: modbus_controller
    modbus_controller_id: mcp2420
    name: "Battery Voltage"
    address: 0x101
    unit_of_measurement: "V"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: mcp2420
    name: "recharging current"
    address: 0x102
    unit_of_measurement: "A"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: mcp2420
    name: "Controller Temp"
    address: 0x103
    bitmask: 0xFF00
    unit_of_measurement: "°C"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1

  - platform: modbus_controller
    modbus_controller_id: mcp2420
    name: "Surface Temp"
    address: 0x103
    bitmask: 0x00FF
    unit_of_measurement: "°C"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1

  - platform: modbus_controller
    modbus_controller_id: mcp2420
    name: "Load Voltage"
    address: 0x104
    unit_of_measurement: "V"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: mcp2420
    name: "Load Current"
    address: 0x105
    unit_of_measurement: "A"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: mcp2420
    name: "Load Power"
    address: 0x106
    unit_of_measurement: "W"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: mcp2420
    name: "Solar Voltage"
    address: 0x107
    unit_of_measurement: "V"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: mcp2420
    name: "Solar Current"
    address: 0x108
    unit_of_measurement: "A"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: mcp2420
    name: "Solar Power"
    address: 0x109
    unit_of_measurement: "W"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 0

```

 
Do that work for you?
