### ISSUE TITLE
Shared addressable effects

### ISSUE THREAD

**Issue by muxa** [esphome/feature-requests#1495]
**Describe the problem you have/What new integration you would like**
I want to be able to create custom addressable effects so that they can be:

- shared between different lights
- packaged up and published as external components to share them between different projects

**Please describe your use case for this integration and alternatives you've tried:**
I'm working on a [MIDI integration](https://github.com/esphome/feature-requests/issues/1501) which detects MIDI notes, and the next phase of the project is to control addressable LED lights by MIDI. I want to have the logic of mapping MIDI events to LEDs in an effect module, so that a single addressable light can have multiples effects, including multiple MIDI effects.
  
**Additional context**
An idea to made this work:

```yaml
addressable_effects:
  - platform: midi # I want to create this component
     midi_in_id: midi1
     id: random_midi_fx
     name: "MIDI Random"
     start_note: "0x15"
     note_on_fade: 500ms
     note_off_fade: 5s
     palette: random # rainbow, white, ...
  - platform: midi # I want to create this component
     midi_in_id: midi1
     id: rainbow_midi_fx
     name: "MIDI Rainbow"
     start_note: "0x15"
     note_on_fade: 500ms
     note_off_fade: 5s
     palette: rainbow.

light:
  - platform: fastled_clockless
    ...
    effects:
      - addressable_rainbow: # this exists
      - addressable_component: # this does not exist
        name: "MIDI Random Custom Name"
        id: random_midi_fx
      - addressable_component: # this does not exist
        id: rainbow_midi_fx
```

**Comment by oxan** [comment]
I'm working on custom effects, but life has been busy lately... If you're feeling adventurous, the [light/transitions](https://github.com/oxan/esphome/tree/light/transitions) branch in my repository should be somewhat usable.

**Comment by tungmeister** [comment]
@oxan will this offer the ability to create, say, a twinking random color effect on a single light?

**Comment by oxan** [comment]
Wait, I misread, this is about effects and not transitions. For effects it's already possible to do this.

**Comment by tungmeister** [comment]
@oxan, are you saying it's already possible to create a twinkle effect that changes color at random on a single rgb light? If so I couldn't see any way to achieve this via the effects within the light component.

**Comment by oxan** [comment]
Yes. You can do it either with an [addressable lambda](https://esphome.io/components/light/index.html#addressable-lambda-effect) from YAML, or from a component by using one of the `register_*_effect` decorators (from `esphome.components.light.effects`, see e.g. the `adalight` component for an example).

**Comment by tungmeister** [comment]
Thanks, I'll take a look 👍

**Comment by muxa** [comment]
Cool, ESPHome already supports what I want to do, looking at example here: https://github.com/esphome/esphome/tree/dev/esphome/components/adalight 

So my custom effects are going to look something like this:

```yaml
midi_in: # MIDI In support is being added here: https://github.com/esphome/esphome/pull/2698
   - id: midi1

light:
  - platform: fastled_clockless
    ...
    effects:
      - addressable_rainbow: # this exists
      - midi_effect: # this is what I want to build
        name: "MIDI Random"
        midi_in_id: midi1
        start_note: "0x15"
        keys: 88
        note_on_fade: 500ms
        note_off_fade: 5s
        palette: random
```
