### ISSUE TITLE
MIDI In support

### ISSUE THREAD

**Issue by muxa** [esphome/feature-requests#1501]
**Describe the problem you have/What new integration you would like**
I want to be able to detect MIDI events in ESPHome from external MIDI devices, such as MIDI Keyboards

**Please describe your use case for this integration and alternatives you've tried:**
Such integration would allow be to do the follow:
* Keep track of how much time per day I spend practicing playing piano
* Add addressable LED lighting to my MIDI keyboard and have more fun while playing

**Additional context**
Here's a config example:

```yaml
uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 31250

midi_in:
  - uart_id: uart_bus
    on_channel_message:
      - logger.log:
          format: "%i: %#04x (%#04x %#04x)"
          args: [ 'x.channel', 'x.type', 'x.data1', 'x.data2' ]
      - lambda: |-
          if (x.type == midi::MidiType::ProgramChange) {
            ESP_LOGD("midi_in", "PROGRAM CHANGE: %#02x (channel %i)", x.data1, x.channel);
          }
    on_system_message:
      - lambda: |-
          if (x.type == midi::MidiType::SystemReset) {
            ESP_LOGD("midi_in", "RESET");
          }
    connected: # optional binary_sensor
      name: "MIDI Keyboard Connected"
      device_class: connectivity
      filters:
        - delayed_off: 5s
    playback: # optional binary_sensor
      name: "MIDI Keyboard Playback"
      device_class: occupancy
      icon: mdi:piano
      filters:
        - delayed_off: 60s
```

I have this more or less working in a custom (external) component. Will tidy things up and create a PR.

Once this is done I want implement addressable MIDI effects, and in order to implement this I've proposed [Shared addressable effects](https://github.com/esphome/feature-requests/issues/1495)
