### ISSUE TITLE
Add support for internal pullup and debouncing for Rotary Encoders

### ISSUE THREAD

**Issue by feeling001** [esphome/feature-requests#1530]
**Describe the problem you have/What new integration you would like**

Rotary encoders can't be connected without pull up resistors without "unpredictable behavior". Pullup + debouncing is needed.
https://esphome.io/components/sensor/rotary_encoder.html

As most esp support internal pull up resistors, it would be nice:

- to be able to configure these internal pull up into the rotary encoder yaml declaration.
- to be able to set a debounce timer value into the rotary encoder yaml declaration.
 
This could result in something like :

> pin_a:
>   pin : D1
>   pullup : true
>   debounce: 5ms
>pin_b: 
>   pin : D2
>   pullup : true
>   debounce: 5ms

This behavior allow to connect directly the encoder to the esp without dedicated hardware components (resistor, condensator).

**Please describe your use case for this integration and alternatives you've tried:**

My actual workaround is to use GPIO binary_sensor (which allow debounce/pullup), and implement by myself the rotary compute trough lambda's.

**Additional context**

Tried on ESP32 (nodemcu 32s)

**Comment by martgras** [comment]
did you already try using the explicit pin definition . It doesn't allow debouncing but enables the pullup mode. 

```yaml
sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    pin_a:
      number: 18
      mode:
        input: true
        pullup: true
    pin_b: 
      number: 25
      mode:
        input: true
        pullup: true

    
binary_sensor:
  - platform: gpio
    name: "Rotary Button"
    pin: 
      number: 19
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 50ms
      - delayed_on: 50ms
```

**Comment by balk77** [comment]
I am successfully using debounce on a rotary encoder in combination with the internal pullups. Values are "collected" for 250ms before being sent out.
```
sensor:
  - platform: rotary_encoder
    name: "dimmer knob"
    id: my_rotary_encoder
    resolution: 4
    min_value: 0
    max_value: 255
    pin_a:
      number: GPIO26
      mode:
        input: true
        pullup: true
    pin_b:
      number: GPIO27
      mode:
        input: true
        pullup: true
    filters:
      debounce: 0.25s
```
