### ISSUE TITLE
Support lambdas for on_value_range above and below

### ISSUE THREAD

**Issue by vooon** [esphome/feature-requests#1532]
**Describe the problem you have/What new integration you would like**

Now it's not possible to write something like that because above/below wants float:
```
number:
  - platform: template
    name: Low threshold
    id: low
    ...
    restore_value: true
    initial_value: 50.0
    
sensor:
  - platform: template
    name: Some sensor
    on_value_range:
      - below: !lambda return id(low).state
        then:
          - light.turn_on: alarm
```

With that support it'll be much easier (less reflash) to find good limit levels and let them just live in preferences.
For example in that air compressor controller:

https://github.com/vooon/smart-door-lock/blob/c5343cf334c4ce40818b402702fb3b2d4b19fcf2/entrance-lock.yaml#L346-L352

**Please describe your use case for this integration and alternatives you've tried:**

Now i had to run OTA again and again to find best values.

**Additional context**

No.
