### ISSUE TITLE
Friendly name in Home Assistant

### ISSUE THREAD

**Issue by the-cyberspace** [esphome/feature-requests#1539]
**Describe the problem you have/What new integration you would like**

Using a friendly name in Home Assistant

**Please describe your use case for this integration and alternatives you've tried:**

In every esphome config i`m using this to give different sensors a name.

```
# substitutions #
substitutions:
  device_name: mi_flora
  friendly_name: Mi flora
```

And i have made a sensor in ESPHome:
```
# binary sensor #
binary_sensor:
  # status #
  - platform: status
    name: "${device_name}_device_status"
```
 
And getting this in Home Assistant:

![afbeelding](https://user-images.githubusercontent.com/46862733/145106016-23691098-0ccc-48a1-93a4-fb895207d6f3.png)

Is it possible to use the friendly_name so a get a (friendly) name in "Naam" in the screenshot?
