### ISSUE TITLE
Modbus Sensor Datatypes

### ISSUE THREAD

**Issue by geelenbert** [esphome/feature-requests#1553]
**Describe the problem you have/What new integration you would like**
The current datatypes for the modbus sensor are:

> Value_type: (Required): datatype of the mod_bus register data. The default data type for modbus is a 16 bit integer in big endian format (MSB first)
> U_WORD (unsigned 16 bit integer from 1 register = 16bit)
> S_WORD (signed 16 bit integer from 1 register = 16bit)
> U_DWORD (unsigned 32 bit integer from 2 registers = 32bit)
> S_DWORD (signed 32 bit integer from 2 registers = 32bit)
> U_DWORD_R (unsigned 32 bit integer from 2 registers low word first)
> S_DWORD_R (signed 32 bit integer from 2 registers low word first)
> U_QWORD (unsigned 64 bit integer from 4 registers = 64bit)
> S_QWORD (unsigned 64 bit integer from 4 registers = 64bit)
> U_QWORD_R (unsigned 64 bit integer from 4 registers low word first)
> U_QWORD_R signed 64 bit integer from 4 registers low word first)
> FP32 (32 bit IEEE 754 floating point from 2 registers)
> FP32_R (32 bit IEEE 754 floating point - same as FP32 but low word first)s

The modbus meters I have installed use a different 3 word data format:
![image](https://user-images.githubusercontent.com/91923/146563100-a69f42ce-245b-47ba-9fff-d56d28093376.png)

Currently i use a nodered flow to read modbus values:
![image](https://user-images.githubusercontent.com/91923/146563344-0721e903-12d5-4d48-b846-06e9c0dc48fc.png)

First i read 65 registers
![image](https://user-images.githubusercontent.com/91923/146563425-5a12b095-8414-4913-b161-e8bf997e03a0.png)

Next step is to do some bit shifting to get the values:
![image](https://user-images.githubusercontent.com/91923/146563615-807bd646-b7d0-48e9-afcd-4807c7d35025.png)

For me to use this integration, i would need a datatype of 3 registers of 16 bit (signed and unsigned)

**Please describe your use case for this integration and alternatives you've tried:**
This would expand its current functionlality

**Additional context**

**Comment by martgras** [comment]
Well 3 words is quite uncommon. 

From the screenshot it seems that you can get the value as an integer from address 0x100 or the same as floating point from address 0x1100.  Since esphome uses float internally anyways using address 0x1100 is the easiest approach
```YAML
  - platform: modbus_controller
    modbus_controller_id: epever
    name: "testraw"
    id: testfp32
    register_type: holding
    value_type: FP32
    address: 0x1100
```

However you can also handle the response yourself  
```YAML
  - platform: modbus_controller
    modbus_controller_id: epever
    name: "testraw"
    id: testraw
    register_type: holding
    value_type: RAW
    address: 0x9013
    register_count: 3
    response_size: 6
    lambda: |-
      // Apply your conversation and return a float
      // data is an uint8_t array containing the raw modbus bytes
      return static_cast<float>( ((uint64_t)data[0] << 8 | data[1] ) << 32 | (data[2] << 8 | data[3]) << 16 | ( data[4] << 8 | data[5]) );
```
