### ISSUE TITLE
Supporting subfolders in external_components

### ISSUE THREAD

**Issue by hencou** [esphome/feature-requests#1566]
**Describe the problem you have/What new integration you would like**

I want to create an external_component with help of some additional sub libraries. I want to include this sub libraries in a subfolder lib/  of the project folder. On the moment (2021.12.1) additional subfolders are not copied to the build folders when compiling the project.

**Please describe your use case for this integration and alternatives you've tried:**

This is my integration:
https://github.com/hencou/esphome_components/tree/main/components/mi

Here is the subfolder which I want as a subfolder to the folder above:
https://github.com/hencou/esphome_components/tree/main/milight

**Additional context**

On the moment I include this folder as "include" in my projects yaml and copy the "milight" folder manually to the root of ESPHome. But this a manual action, I want to achieve a automatic behaviour.

**Comment by hencou** [comment]
Question solved with help of @shbatm, by move the addional libraries to an own Github repo.
Then in ESP Home yaml configuration:

```
esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini
  libraries:
    - milight=https://github.com/hencou/esphome-milight#main
```
