### ISSUE TITLE
PCF8574 LCD backlight control.

### ISSUE THREAD

**Issue by hmmhhh** [esphome/feature-requests#160]
**Describe the problem you have/What new integration you would like**

PCF8574 LCD display backlight control. ON/OFF and brightness.

**Please describe your use case for this integration and alternatives you've tried:**

Sonoff-tasmota has ON/OFF function for this display.

**Additional context**

Goal is to automate display backlight to save energy. Éxample use in sauna where temperature goes above 50C turn backlight ON.

**Comment by rradar** [comment]
actually I did this with a hardware hack. There is this little jumper on the i2c controller board. I took one of them and wired to my esp8266 (pin D5). I also wired a pir sensor on D7 - when motion is detected the lcd background light is automatically turned on (and turns of after a delay)

This is my code:
```

output:
  - platform: gpio
    pin: D5
    id: lcdbacklight

switch:
  - platform: output
    name: "LCD LED"
    output: lcdbacklight
    id: switch_lcdbacklight

binary_sensor:
  - platform: gpio
    pin: D7
    name: "PIR"
    device_class: motion
    filters:
      - delayed_off: 3000ms
    on_press:
      then:
        - switch.turn_on: switch_lcdbacklight
    on_release:
      then:
        - switch.turn_off: switch_lcdbacklight
```
