### ISSUE TITLE
Add midea_ir.follow_me action

### ISSUE THREAD

**Issue by rmounce** [esphome/feature-requests#1627]
**Describe the problem you have/What new integration you would like**
There is no `midea_ir.follow_me` action equivalent to `midea_ac.follow_me`. The latter works with `midea_ir` devices, however it is only available after configuring the wired `midea` component.

**Please describe your use case for this integration and alternatives you've tried:**

My AC indoor unit's return air temp sensor is influenced by the ambient temperature in the roof, basically the outside temperature. Without adjusting the setpoint the actual indoor temperature becomes too cool during the day & too warm overnight. The wall controller supports "follow me" however this room is unoccupied overnight. The solution of course is IR "follow me" which thankfully is supported by this ducted system, so a more accurate temperature reading can be provided (and in my case, combines data from multiple sensors based on which zones are enabled).

As a workaround I have configured `midea` with a dummy UART and it is functioning, however this results in logspam as it cannot detect any physically attached AC.

Workaround config:
```
remote_transmitter:
  pin: 14
  carrier_duty_percent: 50%
  id: ir_tx

# dummy
uart:
  baud_rate: 9600
  rx_pin: 16 # unpopulated
  tx_pin: 17 # unpopulated

climate:
  - platform: midea
    id: midea_uart_dummy
    transmitter_id: ir_tx
  - platform: midea_ir
    id: midea_ac
    name: "AC"
    sensor: frontend_temp

sensor:
  - platform: homeassistant
    id: frontend_temp
    entity_id: sensor.ble_weighted_avg_temp   # Sensor from HASS
    internal: true
    filters:
      - throttle: 10s
      - heartbeat: 2min             # Maximum interval between updates.
      - debounce: 1s
    on_value:
      midea_ac.follow_me:
        temperature: !lambda "return x;"
        beeper: false               # Optional. Beep on update.
```

**Additional context**

Some extra background as I have not found anyone else attempting DIY control of Midea ducted systems, and hope they find this mostly successful report. I have an ActronAir UltraSlim ducted AC with LRE-100AS indoor unit. This is a rebranded Midea system, Carrier and Rinnai also appear to sell closely related systems. In addition to the WC-02 wall controller inside the house (connected to CN40), there is a basic control panel (connected to CN10) mounted to the indoor unit in the roof with an IR window. 

I am using the new `midea_ir` component to control the system via an ESP32 placed next to the indoor unit in the roof. This works great, I am able to change the mode, temperature setpoint and fan speed via ESPHome & Home Assistant. Thanks @dudanov! This unit does not appear to have an IR Tx LED to report back its status if changes are made from the wall controller.
