### ISSUE TITLE
Add "optionmap" to modbus controller text sensor (as seen at modbus select)

### ISSUE THREAD

**Issue by Bascht74** [esphome/feature-requests#1642]
**Describe the problem you have/What new integration you would like**
If you want to "translate" modbus numbers to a readable text, you have to use lambda. 
In the following pull request an `option map` is implemented by @stegm to do the same thing for select entities:
https://github.com/esphome/esphome/pull/3032

**Please describe your use case for this integration and alternatives you've tried:**
It would be nice if the option map is added to the modbus controller text sensor as on optional way to translate the modbus numbers to text (instead of the need to use lamdba for that). This way you can use option maps for reading addresses.

**Additional context**
Instead of 
```
text_sensor:
  - platform: modbus_controller
    name: "${upper_devicename} Control mode"
    id: nilan_control_state
    register_type: read
    address: 1002
    lambda: !lambda |-
      uint16_t int_mode = (data[item->offset] << 8) + data[item->offset+1];
      ESP_LOGD("main","Parsed operation mode int : %d", int_mode);
      std::string mode_str;
      switch (int_mode) {
        case 0:  mode_str = "Off"; break;
        case 1:  mode_str = "Shift"; break;
        case 2:  mode_str = "Stop"; break;
        case 3:  mode_str = "Start"; break;
        case 4:  mode_str = "Standby"; break;
...
        default: mode_str = "Unknown"; break;
  
      }
      return mode_str;
```

you could use: 
```
text_sensor:
  - platform: modbus_controller
    name: "${upper_devicename} Control mode"
    id: nilan_control_state
    register_type: read
    address: 1002
    optionsmap:
      "Off": 0
      "Shift": 1
      "Stop": 2
      "Start": 3
      "Standby" : 4
```
