### ISSUE TITLE
Add support for fan preset modes

### ISSUE THREAD

**Issue by finity69x2** [esphome/feature-requests#1661]
**Describe the problem you have/What new integration you would like**

add a configuration option to allow the use of defined preset modes for fans that support them.

**Please describe your use case for this integration and alternatives you've tried:**

adding preset modes to ESP based fans would allow more flexibility than just supporting percentage speeds.

**Additional context**

**Comment by nagyrobi** [comment]
I think this is deprecated from HA side... originally they supported speeds as presets, but it was changed to percentage.

**Comment by scotty1395** [comment]
From what I understand, `speed_list:` is deprecated but `preset_modes:` isn't?
ESPHome populates `speed_list: off, low, medium, high` but leaves `preset_modes: null`.

**Comment by voed** [comment]
Any progress on this?

**Comment by millerm1993** [comment]
I'm also interested in this!

**Comment by ChristianNewton** [comment]
> I'm also interested in this!

Me aswell, I would love if this could get some more attention.

**Comment by Robbe-B** [comment]
Same, is there already any alternative in the mean time ?

**Comment by mill1000** [comment]
> I think this is deprecated from HA side... originally they supported speeds as presets, but it was changed to percentage.

Here's what the HA dev docs say about fan entities and preset modes.
https://developers.home-assistant.io/docs/core/entity/fan#preset-modes

I may take a swing at this if I find enough time.

**Comment by mill1000** [comment]
I've taken some steps to start implementing this.

- How does everyone plan to use this function?
- What fan components are you using? (e.g. speed fan, h-bridge, etc)

**Comment by nagyrobi** [comment]
I use speed and binary fan.

**Comment by ChristianNewton** [comment]
> I've taken some steps to start implementing this.
> 
> - How does everyone plan to use this function?
> - What fan components are you using? (e.g. speed fan, h-bridge, etc)

Hey, thanks for helping work on this! I'm using the Tuya fan component. It works very well, I just wish that there would be an easier way to control it other than 0-100, since it is only 4 speeds.

**Comment by mill1000** [comment]
> Hey, thanks for helping work on this! I'm using the Tuya fan component. It works very well, I just wish that there would be an easier way to control it other than 0-100, since it is only 4 speeds.

Does setting [speed_count](https://esphome.io/components/fan/tuya#configuration-variables) not achieve that already?

**Comment by flyize** [comment]
> I've taken some steps to start implementing this.
> 
> * How does everyone plan to use this function?
> * What fan components are you using? (e.g. speed fan, h-bridge, etc)

Would this allow me to go back to using low, medium, and high - even though I have a 4 speed fan? That's really what I'm hoping for. Using percentages *only* is unnecessarily confusing to anyone else in my house. Everyone understands low, medium, and high.

**Comment by mill1000** [comment]
Yes, although that is considered to be an [improper use of the function](https://github.com/esphome/esphome/pull/5694#issuecomment-1807224011) and is better handled [via other means](https://github.com/esphome/esphome/pull/5694#issuecomment-1811364019) (in Home Assistant).

**Comment by flyize** [comment]
While I totally get that I can work my way around this developer-imposed HA limitation, it seems insane. People intuitively understand low, medium, and high (especially for voice assistants!). For more advanced use-cases, use the percentages.

So in short, thank you for possibly bringing this back!

**Comment by filmkorn** [comment]
I use a speed fan component in an esphome replacement of the broken brains of a smart air purifier - see https://github.com/filmkorn/air_purifier

> How does everyone plan to use this function?

I'd like to reimplement the preset modes provided by the original integretion (VeSync):
- auto: based on the current air pollution)
- sleep: basically lowest speed setting)
- manual: Which the VeSync integration no longer explicitly supports, but it switches to manual mode when you select one of the three speeds of the air purifier. Unsure where this automation is implemented but I'm thinking this could be done through esphome automations.

![image](https://github.com/esphome/feature-requests/assets/8842084/96b04cd7-80e9-40ed-9804-56830523c102)

All I want is to have this component to support preset modes as enum on the same entity so I don't have to navigate through 'related' entities to find the mode I have currently implemented as separate entity (select component in esphome).

> What fan components are you using? (e.g. speed fan, h-bridge, etc)

`speed` fan like this

```yaml
output:
  - platform: esp8266_pwm
    pin: D1
    frequency: 1000 Hz
    id: pwm_output

fan:
  - platform: speed
    output: pwm_output
    name: "Air Purifier"
    id: air_purifier   
    speed_count: 10
```

**Comment by mill1000** [comment]
FYI this feature was released in ESPHome 2023.12.5, and HomeAssistant just added support in 2024.1.0

**Comment by flyize** [comment]
@mill1000 I'm a little confused. Where do I define these presets? I see in the ESPHome docs where they are referenced, but not where they are defined.

**Comment by mill1000** [comment]
For a speed_fan or hbridge_fan it would looks something like this
```yaml
fan:
  - platform: speed
    name: "Test Fan"
    id: test_fan
    # ...snip...
    # Define desired preset modes here
    preset_modes: 
      - Auto
      - Sleep
    # Write automations for preset modes here
    on_preset_set:
      then:
        lambda: |-
          if (id(test_fan).preset_mode == "Auto") {
            // Auto preset enabled
          }
          else if (id(test_fan).preset_mode == "Sleep") {
            // Sleep preset enabled
            // Maybe set the speed to super low here
          }
          else {
            // No preset enabled
          }
```

Or if you wanted an auto mode that sets fan speed based on a sensor...
```yaml
sensor:
  - platform: adc
    name: Test Sensor
    # ...snip...
    on_value:
      then:
        lambda: |-
          if (id(test_fan).preset_mode == "Auto") {
            // Set fan speed based on sensor value
            auto call = id(test_fan).make_call();
            call.set_speed(x/10);
            call.perform();
          }
```

**Comment by nagyrobi** [comment]
> Or if you wanted an auto mode that sets fan speed based on a sensor...

Unfortunately this doesn't work because as soon as you change the speed from the sensor it automatically exits the `Auto` preset.

Actually this preset thing is pretty useless this way...

**Comment by mill1000** [comment]
> > Or if you wanted an auto mode that sets fan speed based on a sensor...
> 
> This is exactly what I need!
> 
> But unfortunately it doesn't work because as soon as you change the speed from the sensor it automatically exits the `Auto` preset. 

You're right, it won't as is. Probably need to revisit.

> Actually this preset thing is pretty useless this way... It exits any preset if you change the speed.
That is actually desired behavior, **if** the change comes from a front end (i.e. Home Assistant changes the speed).

> Additionally it would be nice to have a way to select a default preset (to use when node boots). Currently it starts wit no preset selected, but if you choose a preset you can't go back to "no preset"...

You could add a "None" preset to the list. (Or maybe even an empty string ""?)

**Comment by filmkorn** [comment]
> But unfortunately it doesn't work because as soon as you change the speed from the sensor it automatically exits the Auto preset.

I can confirm, the `preset_mode` value is lost when I set the fan speed through `fan.turn_on`.

I'm wondering if the mode could also be shown on the web UI (more of a nice to have)?

**Comment by mill1000** [comment]
It's a hack but you might be able to work around the issue by setting preset mode in the call.
e.g.
```yaml
sensor:
  - platform: adc
    name: Test Sensor
    # ...snip...
    on_value:
      then:
        lambda: |-
          if (id(test_fan).preset_mode == "Auto") {
            // Set fan speed based on sensor value
            auto call = id(test_fan).make_call();
            call.set_preset_mode(id(test_fan).preset_mode); // Copy preset mode into call so it won't get cleared
            call.set_speed(x/10);
            call.perform();
          }
```
