### ISSUE TITLE
Add Ethernet support to `esp-idf`

### ISSUE THREAD

**Issue by nagyrobi** [esphome/feature-requests#1683]
**Describe the problem you have/What new integration you would like**
More and more Ethernet supporting boards are available these days.
- WT32-ETH01
- Olimex ESP32-POE/ISO, ESP32-EVB, ESP32-GATEWAY
- PRODINo ESP32 Ethernet
- TTGO T-Internet-POE ESP32
- wESP32 
- OpenHacks LAN8720
- ESP32-Ethernet-Kit

Currently ESPHome only supports Ethernet under `arduino` platform (config example below for WT32-ETH01):

```yaml
esphome:
  name: "Test"

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  manual_ip:
    static_ip: 192.168.2.10
    gateway: 192.168.2.1
    subnet: 255.255.255.0
  use_address: 192.168.2.10
```
Results in error:

```yaml
ethernet: [source /config/esphome/test.yaml:38]
  
  This feature is only available with frameworks ['arduino'].
```

**Please describe your use case for this integration and alternatives you've tried:**
Please add Ethernet support to `esp-idf`. Less memory consumption.

**Additional context**
N/A
