### ISSUE TITLE
Expiry/Timeout for `esp32_ble_tracker` sensors

### ISSUE THREAD

**Issue by nagyrobi** [esphome/feature-requests#1687]
**Describe the problem you have/What new integration you would like**

Sensors provided through `esp32_ble_tracker` stay on their last known value infinitely, if no advertising packet is received.
Applies to `ble_rssi` or `pvvx_mithermometer` and many others.

It would be more correct if we could have a configuration option like `expire_after` where, if no BLE advertisment came within that time period, set the sensor value to NaN.

Kind of like presence sensor works I guess, if the device doesn't send advertisments anymore, it considers it away - here it would set it as NaN but the expiration time should be configurable (and if unconfigured, keep the current behavior).

**Please describe your use case for this integration and alternatives you've tried:**

Need to detect when BLE sensors don't transmit advertisments anymore. Like when battery dies, or some RF interference causes signal loss or whatever. 

Don't know if it would be better to configure this in `esp32_ble_tracker` component, or each sensor component separately.

Should it be:

```
api:
  expire_after: 600s
```
or
```
esp32_ble_tracker:
  scan_parameters:
    interval: 1s
    window: 1s
    active: false
  expire_after: 600s
```
or
```
sensor:
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:B1:CD:7F"
    expire_after: 600s
    temperature:
      name: "PVVX Temperature"
    humidity:
      name: "PVVX Humidity"
    battery_level:
      name: "PVVX Battery-Level"
    battery_voltage:
      name: "PVVX Battery-Voltage"
```
or

```
sensor:
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:B1:CD:7F"
    temperature:
      name: "PVVX Temperature"
      expire_after: 600s
    humidity:
      name: "PVVX Humidity"
      expire_after: 600s
    battery_level: #battery levels don't expire... maybe useful?
      name: "PVVX Battery-Level"
    battery_voltage:
      name: "PVVX Battery-Voltage"
```
?

**Additional context**

To avoid situations like this:
![kép](https://user-images.githubusercontent.com/1550668/160350269-008c0663-3021-45e7-872a-1659c98f22ee.png)

**Comment by nagyrobi** [comment]
As a workaround it's possible to use the _value publish method from elsewhere_ provided by [template sensor](https://esphome.io/components/sensor/template.html#sensor-template-publish-action).

The only requirement is to also have a real template sensor added to the config. A useful such could be measurement of free heap memory.

Once you have this, you can use the `sensor.template.publish` action against any other sensor type, in our case `pvvx_mithermometer`. So all we have to do is to add the `ble_presence` sensor and automate it when it goes off, set the temperature sensor to _Unavailable_ (`nan`):

```
binary_sensor:
- platform: ble_presence
  mac_address: "A4:C1:38:B1:CD:7F"
  id: avail_nappali
  on_release:
    then:
      - sensor.template.publish:
          id: pvvx_temp
          state: nan

sensor:
- platform: pvvx_mithermometer
  mac_address: "A4:C1:38:B1:CD:7F"
  temperature:
    name: "PVVX Temperature"
    id: pvvx_temp
  humidity:
    name: "PVVX Humidity"
  battery_level:
    name: "PVVX Battery-Level"
  battery_voltage:
    name: "PVVX Battery-Voltage"

- platform: template
  name: ESP32 free memory
  lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
  icon: "mdi:memory"
  entity_category: diagnostic
  state_class: measurement
  unit_of_measurement: "b"
  update_interval: 60s
```
Ref: https://discord.com/channels/429907082951524364/429907082955718657/957906168498487306
