### ISSUE TITLE
Make a Total energy sensor that is restored after reboot

### ISSUE THREAD

**Issue by niklerus** [esphome/feature-requests#1693]
**Describe the problem you have/What new integration you would like**
There's a "Total Daily Energy" sensor that persists through reboots but it would be even more usable if there was a "Total energy" sensor that was persistant as well.

**Please describe your use case for this integration and alternatives you've tried:**
There's a Power Consumption application (https://github.com/klaasnicolaas/home-assistant-glow ) that works great but if you reboot the ESP32 the total energy number is lost but the daily is preserved. Would make sense to be able to preserve the total as well. (probably more useful than saving the daily consumption)

**Additional context**

**Comment by dz0ny** [comment]
This can be done via https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/memory-types.html#noinit-dram

```yaml

  on_boot:
    priority: 800.0
    then:
    - lambda: |-
        __NOINIT_ATTR uint32_t my_data;
        id(some_value_sensor).publish_state(my_data);
sensor:
    ...
    id: some_value_sensor
    on_value:
        then:
        - lambda: |-
            __NOINIT_ATTR uint32_t my_data;
           my_data = x;
```
