### ISSUE TITLE
Growatt SFP-5000US/ES Support?

### ISSUE THREAD

**Issue by JohnGalt1717** [esphome/feature-requests#1704]
**Describe the problem you have/What new integration you would like**
I've got some of the Growatt SFP-5000US/ES working with the ShineWifi-F that they ship with them right now using the following:

```
output:
# Blue Led
  - id: light_bl
    platform: gpio
    pin: 16
# Green Led
  - id: light_gr
    platform: gpio
    pin: 0
# Red Led
  - id: light_rd
    platform: gpio
    pin: 2
    
uart:
  - id: uart1
    baud_rate: 9600
    tx_pin: GPIO1
    rx_pin: GPIO3

modbus:
  uart_id: uart1
  flow_control_pin: GPIO4

sensor:
  - platform: growatt_solar
    update_interval: 10s

    inverter_status:
      name: "${device_name} Status Code"

    phase_c:
      voltage:
          name: "${device_name} AC Voltage"
      current:
          name: "${device_name} AC Current"
          filters:
            - multiply: 0.001
      active_power:
          name: "${device_name} AC Power"

    pv1:
      voltage:
          name: "${device_name} PV Voltage"
      current:
          name: "${device_name} PV Current"
          filters:
            - multiply: 0.1
      active_power:
          name: "${device_name} PV Active Power"

    active_power:
      name: "${device_name} Grid Active Power"

    pv_active_power:
      name: "${device_name} PV Active Power"

    frequency:
      name: "${device_name} Frequency"

    energy_production_day:
      name: "${device_name} Today's Generation"
      filters:
        - multiply: 0.00001

```
However, the Frequency and PV Voltage are 0 as is the PV Active Power.

I saw that there was a commit from 4 days ago that might improve matters but not sure so I wanted to formally ask for support for the SFP series since this is a VERY popular model.

**Please describe your use case for this integration and alternatives you've tried:**
I've tried using both of these: https://github.com/WilbertVerhoeff/Growatt without any luck. The -S works about as well as the above.

**Additional context**
N/A
