### ISSUE TITLE
KY-031 Support

### ISSUE THREAD

**Issue by StealthyJedi** [esphome/feature-requests#1706]
**Describe the problem you have/What new integration you would like**

I would love to be able to use KY-031 knock sensors in my ESPhome projects
**Please describe your use case for this integration and alternatives you've tried:**

I want to try to put the sensors under my desk and be able to tap the desk to activate things in home assistant
**Additional context**

**Comment by martgras** [comment]
You do this already
Connect Out to a GPIO PIN (for example 5)  and use a binary sensor

```yaml
binary_sensor:
  - platform: gpio
    pin: 5
    name: "Living Room Window"
```
