### ISSUE TITLE
Improve options for partitioning a single light from an addressable led array

### ISSUE THREAD

**Issue by Weldawadyathink** [esphome/feature-requests#1713]
**Describe the problem you have/What new integration you would like**

When using the partition light platform, include an option to segment a single LED. For example, using an array of addressable led lights as different status lights in a project, you must include segment start and end number. A shorthand option would make the yaml easier to write. 

**Please describe your use case for this integration and alternatives you've tried:**

Segmenting an led is already possible, for example:
```
  - platform: partition
    id: light_high
    segments:
      - id: light_bus_board
        from: 3
        to: 3
```

This request is to add an option in the segments section to replace from and to when they are the same. For example:
```
  - platform: partition
    id: light_high
    segments:
      - id: light_bus_board
        single: 3
```

**Additional context**
