### ISSUE TITLE
Modbus `button`

### ISSUE THREAD

**Issue by nagyrobi** [esphome/feature-requests#1733]
**Describe the problem you have/What new integration you would like**
Beside the `switch` it would be nice if we also had possibility to configure `button` for a Modbus device.

**Please describe your use case for this integration and alternatives you've tried:**
My ventilation system has a filter change warning which needs to be manually reset after the air filter has been physically changed, to cancel the warning (and the builtin timer resets so that a new warning will be issued in the future; additionally not cancelling the warning will cause the device to stop operating to prevent damage to the equipment).

Currently it's implemented as a switch:

```
switch:
- platform: modbus_controller
  modbus_controller_id: ${modbus_ctrl_id}
  name: ${friendly_name} reset filter change warning
  entity_category: diagnostic
  icon: "mdi:air-filter"
  register_type: holding
  address: 47
  bitmask: 1
```

I can toggle the switch to ON, and it will reset the warning, and when the new controller state refresh comes, the switch will toggle itself back to OFF.

Would be a lot nicer if this kind of functionality would be simply implemented as a momentary push `button`.
Should support coils and r/w registers, and perhaps an option for setting the value (eg. send `0` or any numeric value at button press, default `1`) (eventually templatable?)

**Additional context**
@martgras
