### ISSUE TITLE
Option to lock a switch in on or off mode

### ISSUE THREAD

**Issue by manonfgoo** [esphome/feature-requests#1735]
**Describe the problem you have/What new integration you would like**
I would like to have an option to lock a switch to on or off state, the locked switch shall not be able to be toggled while locked.

```
switch:
  - platform: gpio
    pin: 25
    name: "Water Pump Relay"
    id: pump_relay
    lock_off:
      if:
        condition:
          sensor.in_range:
            id: temp
            below: 1.0
    lock_on:
      if:
        condition:
            binary_sensor.is_on: other_senor
    lock_priority: on   ## lock_on overrides lock_off


binary_sensor:
  - platform: gpio
    # ...
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.lock_off: fan_relay
        - switch.lock_on: pump_relay
```  

**Please describe your use case for this integration and alternatives you've tried:**
- I have the following use cases, Prevent  swichin of preconditions are not met 
   -  Force pump to be set off when a water senor shows that now water is present
   -  Force Relays to be shut when water is detected in basement

 - I have tried to implement this with a "dummy switch" but this is not relay very readable and intuitive.
 

**Additional context**
