### ISSUE TITLE
Request for friendly name for ESPHOME devices to use HA feature to reduce entity names

### ISSUE THREAD

**Issue by Bascht74** [esphome/feature-requests#1741]
**Describe the problem you have/What new integration you would like**
I can assign the esphome device a name with: 

```
substitutions:
  upper_devicename: "Lampe Aussen Hausbeleuchtung"
  devicename: "lampe-aussen-hausbeleuchtung" #(upper case and space not allowed)
esphome:
  name: $devicename
```

but I cannot assign a friendly name for Home Assistant: 
`friendly_name: ${upper_devicename} #--> doesn't work`

If I give e.g. a light entity a name: 
```
light:
  - platform: binary
[...]
    name: "${upper_devicename} Balkon"
```

It doesn't show the right way in Home Assistant: 
![image](https://user-images.githubusercontent.com/66269310/169696146-a67d058f-f791-4541-9e2f-a54eb6174e15.png)

If I rename the device name into the "friendly one" it works: 
![image](https://user-images.githubusercontent.com/66269310/169696178-55308713-496b-4de4-867d-34f891b125ce.png)

So it would be nice to have a "friendly" device name with uppercase and spaces via the yaml code. That way the look in HA would be much cleaner

### Anything in the logs that might be useful for us?

```txt
nothing
```

**Additional context**
It would be an alternative, if the `esphome name` accepts upper case and spaces and translates to lowe case and "-" were needed.

If you would be able to set an uppercase device name via the yaml you can make use of the truncating in Home Assistant (would be much clearer)
**Please describe your use case for this integration and alternatives you've tried:**

Example YAML snippet
```yaml
substitutions:
  upper_devicename: "Lampe Aussen Hausbeleuchtung"
  devicename: "lampe-aussen-hausbeleuchtung"

esphome:
  name: $devicename
#  friendly_name: ${upper_devicename} --> missing?

light:
  - platform: binary
    id: light1
    output: relay1
    name: "${upper_devicename} Balkon"
```

**Comment by nagyrobi** [comment]
https://github.com/esphome/feature-requests/issues/1539

**Comment by nagyrobi** [comment]
https://github.com/esphome/feature-requests/issues/1741

**Comment by robloh** [comment]
It looks like this is coming in the next release: https://github.com/esphome/esphome/pull/4296

**Comment by nagyrobi** [comment]
hooraaayy

**Comment by vincekovacs** [comment]
As I see, this pull request only allow to add friendly name to device but not for individual entities (switches, lights, inputs, etc).

It is possible to have an entity identifier used in HA regardless of the name?

Like this:

```yaml
light:
  - platform: binary
[...]
    name: "${upper_devicename} Balkon" // <-- display name in HA
    entity_id: "${devicename}_balkon" // <-- used in HA
```
