### ISSUE TITLE
Add the support of IR Remote Climate for De'Longhi Penguino PAC EX100 (IR mapping provided)

### ISSUE THREAD

**Issue by idefxH** [esphome/feature-requests#1743]
**Describe the problem you have/What new integration you would like**

Hello, I'd like to use my AC with IR Remote Climate, but it is not supported yet.
It is a De'Longhi Penguino PAC EX100, and here is the mapping with IR messages (all messages are nec format)

```
POWER (on/off):                 address=0xFF1F, command=0x7C83
Switch between modes :          address=0xFF1F, command=0x3EC1 #Climatisation, dehumidification, Fan only
Switch between fan levels:      address=0xFF1F, command=0x3FC0 #Climatisation mode: 4 modes, low, medium, high, auto. Fan mode: only low, medium and high
+ :                             address=0xFF1F, command=0x7B84 #Climatisation mode: From 18°c to 32°c, incr. 1. Timer setting: from 0.5h to 24h, incr .5h until 9.5, then incr 1
- :                             address=0xFF1F, command=0x7F80 #Climatisation mode: From 18°c to 32°c, incr. 1. Timer setting: from 0.5h to 24h, incr .5h until 9.5, then incr 1
Timer setting:                  address=0xFF1F, command=0x7E81 #Enter timer setting mode when activated. Validated if nothing is pressed for few seconds
Switch between air-flow modes:  address=0xFF1F, command=0x7A85 #2 modes. Static or moving
Auto mode:                      address=0xFF1F, command=0x7D82 #Automatic mode, no setting available (except Timer)
Silence mode switch:            address=0xFF1F, command=0x7986 #Override current fan level. If fan mode is click when in silent mode, fan mode reverts to previous setting
```
**Please describe your use case for this integration and alternatives you've tried:**

Doesn't work with existing delonghi IR Remote Climate integration (tested, not same commands nor address)

**Additional context**

N/A

**Comment by Px7-941** [comment]
Is there a way to use these IR commands in esphome?
How would I have to integrate it before we have "native" esphome support?

**Comment by idefxH** [comment]
Yes, I did something quite nasty, too nasty to contribute back, but it involves many things (
- an esphome device with IR
```
esphome:
  name: climate-ir

esp32:
  board: pico32
  framework:
    type: arduino

# Enable logging
logger:

esp32_ble_tracker:

globals:
  - id: ongoing_transmission
    type: bool
    restore_value: no
    initial_value: 'false'


      
remote_transmitter:
  id: trsmt
  pin: GPIO26
  carrier_duty_percent: 50%

bluetooth_proxy:

remote_receiver:
  id: rcvr
  pin: 
    number: GPIO32
    inverted: true
    mode:
      input: true
      pullup: true
  tolerance: 55%
  on_nec: 
    - then:
      - logger.log: 
          format: "Recieved nex: %X"
          args: 'x.command'
      - if:
          condition:
            lambda: 'return x.command == 0x9999;'
          then:
            - logger.log: "set ongoing_transmission to true"
            - globals.set:
                id: ongoing_transmission
                value: 'true'
          else:
            - if:
                condition:
                  lambda: 'return x.command == 0xFFFF;'
                then:
                  - logger.log: "set ongoing_transmission to false"
                  - globals.set:
                      id: ongoing_transmission
                      value: 'false'
                else:
                  - logger.log: 
                      format: "codix recieved, but wrong code: %X"
                      args: 'x.command'
                  - if:
                      condition: 
                        lambda: 'return id(ongoing_transmission);'
                      then: 
                        - logger.log: "ongoing sync, sorry"
                      else:
                        - homeassistant.service:
                            service: script.clim_remote_pressed
                            data_template: 
                              ir_value: !lambda 'return x.command;'
                        - logger.log:  "received remote signal"



switch:
  - platform: template
    name: "Clim on off"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFF1F
        command: 0x7C83


api:
  encryption:
    key: "Np7nJI9JQiPFEdw8hrCWDcto56XGEQmqUz2MY64xluU="
  services:
    - service: clim_remote_press
      variables: 
        command: int
      then:
        - logger.log: 
            format: "Recieved request: %X"
            args: 'command'
        - remote_transmitter.transmit_nec:
            address: 0x002F
            command: 0x9999
        - delay: 0.02s
        - remote_transmitter.transmit_nec:
            address: 0xFF1F
            command: !lambda 'return command;'
        - delay: 0.02s
        - remote_transmitter.transmit_nec:
            address: 0x002F
            command: 0xFFFF
        
        
ota:
  - platform: esphome
    password: "33832a155fbf29d88041692c898d6a68"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password



captive_portal:
```
A mqtt climate in your home assistant yaml config:
```
mqtt:
  climate:
    - name: mqtt_clim
      modes:
        - "off"
        - "cool"
        - "fan_only"
        - "dry"
        - "auto"
      swing_modes:
        - "on"
        - "off"
      fan_modes:
        - "high"
        - "medium"
        - "low"
        - "auto"
      preset_modes:
        - "comfort"
      max_temp: 32
      min_temp: 18
      preset_mode_command_topic: "mqtt_clim/ac/preset_mode/set"
      mode_command_topic: "mqtt_clim/ac/mode/set"
      temperature_command_topic: "mqtt_clim/ac/temperature/set"
      fan_mode_command_topic: "mqtt_clim/ac/fan/set"
      swing_mode_command_topic: "mqtt_clim/ac/swing/set"
      precision: 1.0
```
Then 2 pyscripts:
clim_remote_pressed.py:
```
#update clim_mode
def get_clim_mode():
    if state.get("input_boolean.ghost_clim_on_off") == "off":
        return "off"
    elif state.get("input_boolean.ghost_clim_auto_mode") == "on":
        return "auto"
    else:
        return state.get("input_select.ghost_clim_mode")

def get_fan_value(clim_mode):
    if clim_mode == "fan_only":
        return state.get("input_select.ghost_clim_fan_for_fan_only")
    elif clim_mode == "dry":
        return "auto"
    else:
        return state.get("input_select.ghost_clim_fan")

def next_fan(clim_mode, fan_value):
    if clim_mode == "fan_only":
        if fan_value == "low":
            return_val = "medium"
        elif fan_value == "medium":
            return_val = "high"
        elif fan_value == "high":
            return_val = "low"
        service.call("input_select", "select_option", entity_id="input_select.ghost_clim_fan_for_fan_only", option=return_val)
        trig= "input_select.ghost_clim_fan_for_fan_only == '" + return_val + "'"

    else:
        if fan_value == "low":
            return_val = "medium"
        elif fan_value == "medium":
            return_val = "high"
        elif fan_value == "high":
            return_val = "auto"
        elif fan_value == "auto":
            return_val = "low"
        service.call("input_select", "select_option", entity_id="input_select.ghost_clim_fan", option=return_val)
        trig= "input_select.ghost_clim_fan == '" + return_val + "'"
    task.wait_until( state_trigger=trig )
    return return_val

def toggle_silence_mode(clim_mode):
    if clim_mode != "dry" and clim_mode != "fan_only":
        if state.get("input_select.ghost_clim_preset_mode") == "none":
            return_val="comfort"
        else:
            return_val="none"
        service.call("input_select", "select_option", entity_id="input_select.ghost_clim_preset_mode", option=return_val)
        return (return_val)


@service
def clim_remote_pressed(ir_value=None):
    remote_ir_codes = { 'power': 31875,  'mode': 16065, 'fan': 16320, 'plus':31620, 'minus': 32640, 'timer': 32285, 'swing': 31365, 'home': 32130, 'silence': 31110 }

    #init vars and dictionnaries
    clim_mode = get_clim_mode()
    #log.warning("clim_remote_pressed, about to switch on_off")
    if ir_value == remote_ir_codes['power']:
        if clim_mode == "off":
            service.call("input_boolean", "turn_on", entity_id="input_boolean.ghost_clim_on_off")
            trig= "input_boolean.ghost_clim_on_off == 'on'"
            #log.warning("wait for on")
            task.wait_until( state_trigger=trig )
            #log.warning("on received!")
            clim_mode = get_clim_mode()
        else:
            service.call("input_boolean", "turn_off", entity_id="input_boolean.ghost_clim_on_off")
            trig= "input_boolean.ghost_clim_on_off == 'off'"
            ##log.warning("wait for off")
            task.wait_until( state_trigger=trig )
            ##log.warning("off received!")
            clim_mode = get_clim_mode()
            #add here the sync call


    fan_value = get_fan_value(clim_mode)


    #Starting now, clim_mode is not "off", and fan_value is set to the right value
    if clim_mode != "off":
        if ir_value == remote_ir_codes['mode']:
            if clim_mode == "cool":
                service.call("input_select", "select_option", entity_id="input_select.ghost_clim_mode", option="dry")
                trig= "input_select.ghost_clim_mode == '" + "cool" + "'"

            elif clim_mode == "dry":
                service.call("input_select", "select_option", entity_id="input_select.ghost_clim_mode", option="fan_only")
                trig= "input_select.ghost_clim_mode == '" + "dry" + "'"
            elif clim_mode == "fan_only":
                service.call("input_select", "select_option", entity_id="input_select.ghost_clim_mode", option="cool")
                trig= "input_select.ghost_clim_mode == '" + "fan_only" + "'"
            elif clim_mode == "auto":
                service.call("input_boolean", "toggle", entity_id="input_boolean.ghost_clim_auto_mode")
                trig= "input_boolean.ghost_clim_auto_mode == '" + "off" + "'"
            task.wait_until( state_trigger=trig )
            clim_mode= get_clim_mode()


        elif ir_value == remote_ir_codes['fan']:
            if clim_mode != "dry":
                fan_value=next_fan(clim_mode, fan_value)
                #log.warning(f"Fan, from {clim_mode}")

        elif ir_value == remote_ir_codes['plus']:
            if clim_mode == "cool":
                service.call("input_number", "increment", entity_id="input_number.ghost_clim_current_temp")

        elif ir_value == remote_ir_codes['minus']:
            if clim_mode == "cool":
                service.call("input_number", "decrement", entity_id="input_number.ghost_clim_current_temp")

        elif ir_value == remote_ir_codes['timer']:
                pass

        elif ir_value == remote_ir_codes['swing']:
            if clim_mode == "cool" or clim_mode == "fan_only" or clim_mode == "dry":
                service.call("input_boolean", "toggle", entity_id="input_boolean.ghost_clim_swing_mode")


        elif ir_value == remote_ir_codes['home']:
            service.call("input_boolean", "toggle", entity_id="input_boolean.ghost_clim_auto_mode") #Toggle auto mode
            clim_mode = get_clim_mode()

        elif ir_value == remote_ir_codes['silence']:
            toggle_silence_mode(clim_mode)


    service.call("pyscript", "clim_sync", from_value="Remote")

```

and clim_sync.py:

```
def get_clim_mode():
    #log.warning("inside get_clim_mode")
    if state.get("input_boolean.ghost_clim_on_off") == "off":
        return "off"
    elif state.get("input_boolean.ghost_clim_auto_mode") == "on":
        return "auto"
    else:
        return state.get("input_select.ghost_clim_mode")

def get_fan_value(clim_mode):
    if clim_mode == "fan_only":
        #log.warning("get_fan_value for Fan_only")
        return state.get("input_select.ghost_clim_fan_for_fan_only")
    else:
        return state.get("input_select.ghost_clim_fan")

def opposite_from(from_value):
    if from_value == "GUI":
        return "Remote"
    else:
        return "GUI"

def send_and_wait(command_to_send=0):
    service.call("esphome", "climate_ir_clim_remote_press", command=command_to_send )
    #log.warning(f"sent {command_to_send}, waiting for an event")
    task.wait_until(event_trigger="clim_remote_pressed_complete")
    #log.warning("Event recieved!")

def delta_fan_strenght(init_strength, target_strength, fan_only): #do not consider "auto" or "off" modes
    if fan_only == True:
        strength_order = { 'low': 1, 'medium': 2, 'high': 3}
    else:
        strength_order = { 'low': 1, 'medium': 2, 'high': 3, 'auto': 4}
    delta = strength_order[target_strength] - strength_order[init_strength]
    if delta >= 0:
        return delta
    else:
        if fan_only == True:
            return delta + 3
        else:
            return delta + 4
def set_next_fan(init_strength, fan_only):
    if fan_only == True:
        if init_strength == 'low':
            return_val = 'medium'
        elif init_strength == 'medium':
            return_val = 'high'
        elif init_strength == "high":
            return_val = 'low'
        service.call("input_select", "select_option", entity_id="input_select.ghost_clim_fan", option=return_val)
        return return_val
    else:
        if init_strength == 'low':
            return_val = 'medium'
        elif init_strength == 'medium':
            return_val = 'high'
        elif init_strength == "high":
            return_val = 'auto'
        elif init_strength == 'auto':
            return 'low'
        service.call("input_select", "select_option", entity_id="input_select.ghost_clim_fan_for_fan_only", option=return_val)
        return return_val



def update_fan(from_value, clim_mode):
    #Normally, at that stade, the mode is aligned. Therefore, cycling through the fan_modes should do it
    ghost_fan_value = get_fan_value (clim_mode)
    gui_fan_value = state.get("climate.mqtt_clim.fan_mode")
    #log.warning(f"entering update fan : ghost_fan_value: {ghost_fan_value}, gui_fan_value: {gui_fan_value}, clim_mode: {clim_mode}")
    if gui_fan_value == "auto" and clim_mode == "fan_only":
        #log.warning(f"Hum, auto and fan_only! ghost_fan_value: {ghost_fan_value}")
        service.call("climate", "set_fan_mode", fan_mode=ghost_fan_value, entity_id="climate.mqtt_clim" )
        gui_fan_value=ghost_fan_value
    if ghost_fan_value != gui_fan_value and (clim_mode == "cool" or clim_mode == "fan_only"):
        if from_value == "GUI":
            for x in range(delta_fan_strenght(ghost_fan_value, gui_fan_value, (clim_mode == "fan_only"))):
                service.call("esphome", "climate_ir_clim_remote_press", command=remote_ir_codes['fan'] )
                ghost_fan_value = set_next_fan(ghost_fan_value, (clim_mode == "fan_only") )
                task.sleep(.5)

            if clim_mode == "fan_only":
                service.call("input_select", "select_option", entity_id="input_select.ghost_clim_fan_for_fan_only", option=gui_fan_value)
            else:
                service.call("input_select", "select_option", entity_id="input_select.ghost_clim_fan", option=gui_fan_value)
                ghost_fan_value = get_fan_value (clim_mode)
        else:
            service.call("climate", "set_fan_mode", fan_mode=ghost_fan_value, entity_id="climate.mqtt_clim" )

def delta_clim_mode(init_mode, target_mode): #do not consider "auto" or "off" modes
    mode_order = { 'cool': 1, 'dry': 2, 'fan_only': 3}
    delta = mode_order[target_mode] - mode_order[init_mode]
    if delta >= 0:
        return delta
    else:
        return delta + 3

def set_next_clim_mode(init_mode):
    if init_mode == "cool":
        return_val = "dry"
    elif init_mode == "dry":
        return_val = "fan_only"
    elif init_mode == "fan_only":
        return_val = "cool"
    service.call("input_select", "select_option", entity_id="input_select.ghost_clim_mode", option=return_val)
    return return_val

def update_clim_mode(from_value): #To test: auto mode
    gui_clim_mode = state.get("climate.mqtt_clim")
    ghost_clim_mode = get_clim_mode()
    #log.warning(f"gui_clim_mode: {gui_clim_mode}, ghost_clim_mode: {ghost_clim_mode}" )
    if gui_clim_mode != ghost_clim_mode:
        if from_value == "GUI":
            if gui_clim_mode == "fan_only":
                service.call("input_select", "select_option", entity_id="input_select.ghost_clim_fan_for_fan_only", option="high")
            if ghost_clim_mode == "off": #turn clim on before anything else
                service.call("esphome", "climate_ir_clim_remote_press", command=remote_ir_codes['power'] )
                service.call("input_boolean", "turn_on", entity_id="input_boolean.ghost_clim_on_off")
                trig= "input_boolean.ghost_clim_on_off == 'on'"
                #log.warning(f"1 waiting until: {trig}")
                task.wait_until( trig )
                ghost_clim_mode = get_clim_mode()
            #From this point, we can expect clim to be on if gui_clim is on as well

            if gui_clim_mode == "off": #should never happen if the previous block is executed
                service.call("esphome", "climate_ir_clim_remote_press", command=remote_ir_codes['power'] )
                service.call("input_boolean", "turn_off", entity_id="input_boolean.ghost_clim_on_off")
                trig= "input_boolean.ghost_clim_on_off == 'off'"
                #log.warning(f"2 waiting until: {trig}")
                task.wait_until( trig )
                ghost_clim_mode = get_clim_mode()
            elif ghost_clim_mode == "auto":
                service.call("esphome", "climate_ir_clim_remote_press", command=remote_ir_codes['home'] )
                service.call("input_boolean", "turn_off", entity_id="input_boolean.ghost_clim_auto_mode")
                trig= "input_boolean.ghost_clim_auto_mode == 'off'"
                task.wait_until( trig )
                ghost_clim_mode = get_clim_mode()
            elif (gui_clim_mode  == "cool" or gui_clim_mode  == "dry" or gui_clim_mode  == "fan_only"): #and ghost_clim_mode != "off" and gui_clim_mode != "off"
                for i in range(delta_clim_mode(ghost_clim_mode, gui_clim_mode)):
                    service.call("esphome", "climate_ir_clim_remote_press", command=remote_ir_codes['mode'] )
                    ghost_clim_mode=set_next_clim_mode(ghost_clim_mode)
                    task.sleep(.5)
                service.call("input_select", "select_option", entity_id="input_select.ghost_clim_mode", option=gui_clim_mode)
                trig= "input_select.ghost_clim_mode == '" + gui_clim_mode + "'"
                task.wait_until( trig )
                ghost_clim_mode = get_clim_mode()


            elif gui_clim_mode == "auto":
                service.call("esphome", "climate_ir_clim_remote_press", command=remote_ir_codes['home'] )
                service.call("input_boolean", "turn_on", entity_id="input_boolean.ghost_clim_auto_mode")
                trig= "input_boolean.ghost_clim_auto_mode == 'on'"
                task.wait_until( trig )
                ghost_clim_mode = get_clim_mode()

        else:
            service.call("climate", "set_hvac_mode", hvac_mode=ghost_clim_mode, entity_id="climate.mqtt_clim" )


def update_temp(from_value, ghost_clim_mode):
    gui_temp = int(state.get("climate.mqtt_clim.temperature"))
    ghost_temp = int(float(state.get("input_number.ghost_clim_current_temp")))
    if gui_temp != ghost_temp and ghost_clim_mode == "cool":
        if from_value == "GUI":
            for i in range(abs(gui_temp - ghost_temp)):

        
                if gui_temp > ghost_temp:
                    service.call("esphome", "climate_ir_clim_remote_press", command=remote_ir_codes["plus"] )
                    service.call("input_number", "increment", entity_id="input_number.ghost_clim_current_temp")

                  
                else:
                    service.call("esphome", "climate_ir_clim_remote_press", command=remote_ir_codes["minus"] )
                    service.call("input_number", "decrement", entity_id="input_number.ghost_clim_current_temp")

                task.sleep(.5)
            service.call("input_number", "set_value", entity_id="input_number.ghost_clim_current_temp", value=gui_temp)


        else:
            service.call("climate", "set_temperature", temperature=ghost_temp, entity_id="climate.mqtt_clim" )

def update_swing(from_value, ghost_clim_mode):
    gui_swing = state.get("climate.mqtt_clim.swing_mode")
    ghost_swing = state.get("input_boolean.ghost_clim_swing_mode")
    if gui_swing != ghost_swing:
        if from_value == "GUI":
            service.call("esphome", "climate_ir_clim_remote_press", command=remote_ir_codes["swing"] )
            service.call("input_boolean", "toggle", entity_id="input_boolean.ghost_clim_swing_mode")
        else:
            service.call("climate", "set_swing_mode", swing_mode=ghost_swing, entity_id="climate.mqtt_clim" )

def cleanup():
    #log.warning(f"cleaning up cancelled")
    service.call("input_boolean", "turn_off", entity_id="input_boolean.ongoing_sync")

def toggle_silence_mode():
    if state.get("input_select.ghost_clim_preset_mode") == "none":
        return_val="comfort"
    else:
        return_val="none"
    service.call("input_select", "select_option", entity_id="input_select.ghost_clim_preset_mode", option=return_val)
    return (return_val)

def update_silence(from_value, ghost_clim_mode):
    #log.warning (f"insie: update_silence")
    gui_preset = state.get("climate.mqtt_clim.preset_mode")
    ghost_preset = state.get("input_select.ghost_clim_preset_mode")
    if gui_preset != ghost_preset:
        if ghost_clim_mode != "dry" and ghost_clim_mode != "fan_only":
            if from_value == "GUI":
                service.call("esphome", "climate_ir_clim_remote_press", command=remote_ir_codes['silence'] )
                toggle_silence_mode()
            else:
                service.call("climate", "set_preset_mode", preset_mode=ghost_preset, entity_id="climate.mqtt_clim" )

remote_ir_codes = { 'power': 31875,  'mode': 16065, 'fan': 16320, 'plus':31620, 'minus': 32640, 'timer': 32285, 'swing': 31365, 'home': 32130, 'silence': 31110 }

#@task_unique("clim_sync", kill_me = True)
@service
def clim_sync(from_value=None):
    try:
        previous_task = task.name2id("clim_syncGUI")
        previous_task.cancel()
    except NameError as e: #Cool, we can start
         pass

    task.unique("clim_sync" + from_value, kill_me = False)
   

    task.sleep(1)
    update_clim_mode(from_value)


    ghost_clim_mode = get_clim_mode()

    update_silence(from_value, ghost_clim_mode)


    update_fan(from_value, ghost_clim_mode)


    update_temp(from_value, ghost_clim_mode)


    update_swing(from_value, ghost_clim_mode)



```

And other fun stuff in your home assistant configuration that would take quite some time for me to isolate and share, as I did it > 1 year ago.

I should probably create a github project out of it, but I don't have much time right now. If you are interested, we can work on it together?
