### ISSUE TITLE
When renaming a device, also rename the fallback hotspot SSID

### ISSUE THREAD

**Issue by aaamoeder** [esphome/feature-requests#1744]
**Describe the problem you have/What new integration you would like**

As the title says. When renaming a device the SSID of the fallback hotspot remains the same causing possible confusion.

**Please describe your use case for this integration and alternatives you've tried:**

n/a

**Additional context**

n/a

**Comment by jangrewe** [comment]
```
substitutions:
  devicename: "foobar"

esphome:
  name: $devicename

wifi:
  ap:
    ssid: "$devicename Fallback Hotspot"
```
