### ISSUE TITLE
Easier usage of `user_characters` in lambdas of Character-Based LCD Displays

### ISSUE THREAD

**Issue by nagyrobi** [esphome/feature-requests#1763]
**Describe the problem you have/What new integration you would like**
[LCD displays have](https://esphome.io/components/display/lcd_display.html?highlight=print#user-defined-characters) a subset of `user_characters` which help with usage of diacritics in many languages.

The problem is that using these in strings is rather awkward, for example with the config below  for `Hőmérséklet` we have to use `H\x09m\x05rs\x05klet`, but even worse, for `Főcím` we need to use `F\x09""c\x07m` (note the `""` in the middle as `c` is also a hex number, and since the C standard does not define the maximum number of them in an `\x` escape sequence, it is interpreted as part of it, need to manually hack around with double-double quotes to prevent this, otherwise unexpected data appears on the screen).

Would be nice if we had a function to automatically replace these characters with the ones defined in `user_characters` for easier string definition in the YAML.

My proposal would be to add an optional `replacement_for` configuration variable to `user_characters` where the character to be replaced could be specified, and use a dedicated callable function `lcd_user_char()` within the lambdas to do the replacements.

For example:

```yaml
  user_characters:
    - position: 0 # 0x08
      data:  # back arrow, not used in replacements
        - 0b00100
        - 0b01000
        - 0b11110
        - 0b01001
        - 0b00101
        - 0b00001
        - 0b11110
        - 0b00000
    - position: 1 # 0x09
      replacement_for: "ő"
      data:
        - 0b00101
        - 0b01010
        - 0b01110
        - 0b10001
        - 0b10001
        - 0b10001
        - 0b01110
        - 0b00000
    - position: 2 # 0x02
      replacement_for: "ó"
      data:
        - 0b00010
        - 0b00100
        - 0b01110
        - 0b10001
        - 0b10001
        - 0b10001
        - 0b01110
        - 0b00000
    - position: 3 # 0x03
      replacement_for: "ű"
      data:
        - 0b00101
        - 0b01010
        - 0b10001
        - 0b10001
        - 0b10001
        - 0b10011
        - 0b01101
        - 0b00000
    - position: 4 # 0x04
      replacement_for: "ú"
      data:
        - 0b00010
        - 0b00100
        - 0b10001
        - 0b10001
        - 0b10001
        - 0b10011
        - 0b01101
        - 0b00000
    - position: 5 # 0x05
      replacement_for: "é"
      data:
        - 0b00010
        - 0b00100
        - 0b01110
        - 0b10001
        - 0b11111
        - 0b10000
        - 0b01110
        - 0b00000
    - position: 6 # 0x06
      replacement_for: "á"
      data:
        - 0b00010
        - 0b00100
        - 0b01110
        - 0b00001
        - 0b01111
        - 0b10001
        - 0b01111
        - 0b00000
    - position: 7 # 0x07
      replacement_for: "í"
      data:
        - 0b00010
        - 0b00100
        - 0b01100
        - 0b00100
        - 0b00100
        - 0b00100
        - 0b01110
        - 0b00000
```

**Please describe your use case for this integration and alternatives you've tried:**

So for `Hőmérséklet` we could have instead of `return "H\x09m\x05rs\x05klet";`, something like `return lcd_user_char("Hőmérséklet");`
or for `Főcím` we could have instead of `return "F\x09""c\x07m";`, something like `return lcd_user_char("Főcím");`

where `lcd_user_char()` function would parse the string for the characters to be replaced, and replace them with the hex codepoints corresponding in the config (taking care of the occurrence of `0-9-a-f` hex characters following).

**Additional context**

Would be extremely useful in the new LCD Menu too: https://github.com/esphome/esphome/pull/3406 which increases the string usage by a magnitude, compared to just a static info display.
