### ISSUE TITLE
User map for characters in `lcd_gpio` and `lcd_pcf8574`

### ISSUE THREAD

**Issue by nagyrobi** [esphome/feature-requests#1766]
**Describe the problem you have/What new integration you would like**

There are different versions of Character-Based LCD Displays, for example the more commons driven by the HD44780UA00 chip English-Japanese or the HD44780UA02 English-European:
![image](https://user-images.githubusercontent.com/1550668/173113487-9c98e866-8ee4-4a3c-a83f-61fe62057c5f.png)
but there are even more, Chinese and Russian versions too.

The problem is that special characters above ASCII appear on various addresses in these screens. For example the `°` symbol is not in the same location. Using `°` in yaml config directly won't render it correctly, `\xdf` is needed for the English-Japanese model, and `\xb0` for the less common English-European.

Now to simply display `°C` you can't just use `return "\xdfC";` because `C` is a hex number, and the C standard does not define the maximum number of them in an `\x` escape sequence, so it is interpreted as part of it. To overcome this, you need to manually hack around with double-double quotes like `return "\xdf""C";` otherwise unexpected data appears on the screen.

The LCD screens (and the `lcd_pcf8574` / `lcd_gpio` components) also support adding a subset of `user_characters` which help with usage of diacritics in many languages.

The other problem is that using all these in strings is rather awkward, for example with the config below  for `Hőmérséklet` we have to use `H\x09m\x05rs\x05klet`, but even worse, for `Főcím` we need to use `F\x09""c\x07m` (again need for a double-double quote).

**Proposed solution**

How about having a `user_map` configuration item where the user could define which characters/symbols have which hex address (based on table above + the `user_characters`) and from then, no more need to care about these in the rest of the config, replacements should be done automatically, no need for escapes and manual taking care of the occurrence of potential hex characters following them):

```yaml
display:
  - platform: lcd_pcf8574
    user_map:
     - °: "\xdf" # in the English-Japanese rom, \xb0 in English-European rom
     - ó: "\x02" # in user_characters
     - ö: "\xdf" # in the English-Japanese rom, \xf6 in English-European rom
     - ő: "\x09" # in user_characters
     - ú: "\x04" # in user_characters
     - ü: "\xf5" # in the English-Japanese rom, \xfc in English-European rom
     - ű: "\x03" # in user_characters
     - é: "\x05" # in user_characters
     - á: "\x06" # in user_characters
     - í: "\x07" # in user_characters
  user_characters:  # example below for Hungarian
    - position: 0 # \x08
      data:  # back arrow
        - 0b00100
        - 0b01000
        - 0b11110
        - 0b01001
        - 0b00101
        - 0b00001
        - 0b11110
        - 0b00000
    - position: 1 # \x09
      data:  # ő
        - 0b00101
        - 0b01010
        - 0b01110
        - 0b10001
        - 0b10001
        - 0b10001
        - 0b01110
        - 0b00000
    - position: 2 # \x02
      data:  # ó
        - 0b00010
        - 0b00100
        - 0b01110
        - 0b10001
        - 0b10001
        - 0b10001
        - 0b01110
        - 0b00000
    - position: 3 # \x03
      data:  # ű
        - 0b00101
        - 0b01010
        - 0b10001
        - 0b10001
        - 0b10001
        - 0b10011
        - 0b01101
        - 0b00000
    - position: 4 # \x04
      data:  # ú
        - 0b00010
        - 0b00100
        - 0b10001
        - 0b10001
        - 0b10001
        - 0b10011
        - 0b01101
        - 0b00000
    - position: 5 # \x05
      data:  # é
        - 0b00010
        - 0b00100
        - 0b01110
        - 0b10001
        - 0b11111
        - 0b10000
        - 0b01110
        - 0b00000
    - position: 6 # \x06
      data:  # á
        - 0b00010
        - 0b00100
        - 0b01110
        - 0b00001
        - 0b01111
        - 0b10001
        - 0b01111
        - 0b00000
    - position: 7 # \x07
      data:  # í
        - 0b00010
        - 0b00100
        - 0b01100
        - 0b00100
        - 0b00100
        - 0b00100
        - 0b01110
        - 0b00000
```
**Please describe your use case for this integration and alternatives you've tried:**
The new [LCD menu](https://github.com/esphome/esphome/pull/3406) component will likely raise the need to find a solution to these problems, as there the number of strings to be used will increase dramatically.

**Additional context**
https://github.com/esphome/esphome/discussions/3547#discussioncomment-2932369

**Comment by nagyrobi** [comment]
A very proffessional approach, but wouldn't it be an overkill?

**Comment by glmnet** [comment]
If Unicode chars can be directly mapped to rom codes I don't see the benefit of user defining them. Maybe just a config to select the display type.

**Comment by nagyrobi** [comment]
The problem is that in the existing roms (EN-JP, EN-EU, EN-CZ and EN-RU) not all the unicode chars are present, many diacritics are missing from all, that's why we have to use the `user_characters` setting and draw our own. And only 8 user chars are possible while there are more missing so the user really needs to compromise and cherry pick what's most useful out of the missing ones.

**Comment by nagyrobi** [comment]
> As a workaround you can have a `- include:` in the yaml with a replace function so you don't work too much escaping characters. The render is using lambdas anyway so it would end up being like: `it.print(replace_lcd(...`

Wow that's a great idea. Can you please show me an example?

**Comment by nagyrobi** [comment]
I can see https://esphome.io/custom/custom_component.html but that's not tailored towards an on-demand callable function...

**Comment by glmnet** [comment]
> > As a workaround you can have a `- include:` in the yaml with a replace function so you don't work too much escaping characters. The render is using lambdas anyway so it would end up being like: `it.print(replace_lcd(...`
> 
> Wow that's a great idea. Can you please show me an example for such a funcion?

put this inside a .h file where the yaml is and use the [`- include:` ](https://esphome.io/components/esphome.html#includes)

```cpp

std::string replace2(std::string str, std::string substr1, std::string substr2)
{
    for (size_t index = str.find(substr1, 0); index != std::string::npos && substr1.length(); 
        index = str.find(substr1, index + substr2.length() ) )
        str.replace(index, substr1.length(), substr2);
    return str;
}

std::string replace_lcd(std::string str) {
    // adapt here
    str = replace2(str, "è", "😀");
    str = replace2(str, "ó", "⭐");
    return str;
}

**Comment by nagyrobi** [comment]
@glmnet Thank you very much! Works!
Here's how: created file `char_replace.h` with the following contents (as per example chars above):

```c++
std::string replace2(std::string str, std::string substr1, std::string substr2)
{
    for (size_t index = str.find(substr1, 0); index != std::string::npos && substr1.length(); 
        index = str.find(substr1, index + substr2.length() ) )
        str.replace(index, substr1.length(), substr2);
    return str;
}

std::string replace_lcd(std::string str) {
    // adapt here
    str = replace2(str, "°", "\xdf"""); // in the English-Japanese rom, \xb0 in English-European rom
    str = replace2(str, "ó", "\x02"""); // in user_characters
    str = replace2(str, "ö", "\xef"""); // in the English-Japanese rom, \xf6 in English-European rom
    str = replace2(str, "ő", "\x09"""); // in user_characters
    str = replace2(str, "ú", "\x04"""); // in user_characters
    str = replace2(str, "ü", "\xf5"""); // in the English-Japanese rom, \xfc in English-European rom
    str = replace2(str, "ű", "\x03"""); // in user_characters
    str = replace2(str, "é", "\x05"""); // in user_characters
    str = replace2(str, "á", "\x06"""); // in user_characters
    str = replace2(str, "í", "\x07"""); // in user_characters
    return str;
}
```

Added to the yaml config of the node:
```yaml
esphome:
  ...
  includes:
    - char_replace.h
```

And in the LCD lambda: `it.print(0, 1, replace_lcd("Test óöőúüűéáí °C"));`
In the lcd_menu lambda: `text: !lambda return (replace_lcd("Test óöőúüűéáí °C"));`
