### ISSUE TITLE
Add Whynter ARC-14S Support to Climate IR

### ISSUE THREAD

**Issue by aldalen** [esphome/feature-requests#1767]
**Describe the problem you have/What new integration you would like**

I would like support for the ARC-14S standalone AC system in Climate IR.  I have tried other systems, but they don't work. 

**Please describe your use case for this integration and alternatives you've tried:**

Allows for full climate automation of this unit.  It is only controllable via the remote or buttons on the unit.  I have tried SmartIR and other options in the ClimateIR help page. 

**Additional context**

I captured a bunch of IR remote commands from my remote and built a spreadsheet that captures them + derives patterns.  I noticed that all commands came back with "Received NEC" and used the addr/cmd values to build a protocol table. 
https://docs.google.com/spreadsheets/d/14SvjwZCtIWM_aNN50qefxUmNAZliV9ABrFStE_0oLfI/edit#gid=0

I have quite a bit of programming experience and happy to contribute, but a little lost on how to get started with this.

**Comment by aeonsablaze** [comment]
I have the ARC-14SH (same unit, but with a heater) and have just finished decoding the signal from my remote. I'm assuming your remote would be pretty much the same. Each command sends the full state of the device in a 32 bit burst, broken down as follows:
```
[000100100] [001] [0100] [10000] [0] [0] [1] [00000000]
static      fan   mode   timer   cf  tmr pwr temp

static: These first nine bits don't change on any command
fan: 001=high
     010=medium
     100=low
mode: 0001=fan
      0010=dry
      0100=heat
      1000=cool
timer: contains the number of hours for the timer with the bits reversed
cf: temperature unit, 0 for celsius, 1 for fahrenheit
tmr: timer toggle, 0 for off, 1 for on
pwr: power toggle, 0 for off, 1 for on
temp: contains the target temperature with the bits reversed
     	if celsius, contains 0-16 (offset from 16 for a range of 16-32)
      	if fahrenheit, contains 61-89 (no offset, actual range)
```

My programming skills could best be described as "enthusiastic amateur", but I've had a peek at the already included protocols and I'm thinking I can take a stab at implementing this one. I'll report back here when I've made some progress. Or utterly failed. Whichever way it goes.

**Comment by aeonsablaze** [comment]
I've got support for this unit coded and fully functional. Pull request is submitted and pending.

@aldalen if you want to test in the meantime, you can add this to your config:

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/aeonsablaze/esphome
      ref: whynter-ac-support
    components: [ whynter ]
```

```yaml
    climate:
      - platform: whynter
        name: "AC"
        sensor: room_temp
        use_fahrenheit: true
        supports_heat: false

```
