### ISSUE TITLE
Add support for the Shelly 4PM (images attached)

### ISSUE THREAD

**Issue by baldarn** [esphome/feature-requests#1784]
Describe the problem you have/What new integration you would like

Add support for the Shelly 4PM

Please describe your use case for this integration and alternatives you've tried:

Shelly 4PM not currently supported. I have several of the devices and they’re relatively cheap considering they have 4 output so hopefully this can be achieved.

Additional context

[Shelly 4PM](https://shelly.cloud/shelly-pro-smart-home-automation-solution/#Pro-4PM)

some images of a disassebled one

![IMG_20220629_094826](https://user-images.githubusercontent.com/2814802/176383054-99ebda27-1f88-46dd-96d6-ac12a1c95627.jpg)
![IMG_20220629_094852](https://user-images.githubusercontent.com/2814802/176383086-4661ff44-59a9-4039-baed-4bc1732fda99.jpg)
![IMG_20220629_095055](https://user-images.githubusercontent.com/2814802/176383105-a0b949cd-32d9-4ab9-8bdf-0da26321c033.jpg)
![IMG_20220629_095108](https://user-images.githubusercontent.com/2814802/176383111-5e63a64f-2c0a-46df-8275-9ab6dab2850d.jpg)
![IMG_20220629_095214](https://user-images.githubusercontent.com/2814802/176383120-93d1bfb3-08f0-4d3b-92e4-9bf5c50526cd.jpg)
)

**Comment by nagyrobi** [comment]
How about the LAN port?

**Comment by angelnu** [comment]
It should work (I know the pins) and [esphome supports it](https://esphome.io/components/ethernet) BUT it cannot be used in parallel to the wifi.

Ideally, it would be possible to detect at boot if the cable is plugged and use the wifi as backup but I do not think is possible to compile both modules together.

**Comment by nagyrobi** [comment]
Yes of course, question was if LAN is supported at all ESPHome is either LAN _or_ WiFi... what's the LAN PHY inside?

**Comment by nagyrobi** [comment]
Also, is the energy meter properly measuring in 3-phase mode?

**Comment by nagyrobi** [comment]
Also, it looks like there are two hardware revisions already. The one in the photos above looks like V1.

**Comment by angelnu** [comment]
> Yes of course, ESPHome is either LAN _or_ WiFi...
> 
> Question was if LAN is supported at all... what's the LAN PHY inside?

It is an LAN8720A:
```
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
```
In fact on the same pins as for other Shelly Pros - https://devices.esphome.io/devices/Shelly-Pro-1

**Comment by angelnu** [comment]
> Also, it looks like there are two hardware revisions already. The one in the photos above looks like V1.
> 
> Wonder if, apart from the high voltage connection differences, are there different internals.

I do not think so... but since I only got v2 I cannot tell for sure. In Tasmota they have the same templates.

**Comment by angelnu** [comment]
# Update

I got the screen working with a basic menu. I also added support for the energy sensor (see https://github.com/esphome/esphome/pull/5439)

![image](https://github.com/esphome/feature-requests/assets/4406403/2ae52deb-6896-4f6a-b005-52fee5265048)

After the support for the sensor gets added I will submit an entry to esphome devices.

**Comment by angelnu** [comment]
In order to accelerate getting https://github.com/esphome/esphome/pull/5439 merged it would help if others could validate that it works for them.

So if you use the ADE7953 sensor used in the Shelly Pro series, please give it a try by adding

```yaml
external_components:
  # use rtttl and dfplayer from ESPHome's dev branch in GitHub
  - source:
      type: git
      url: https://github.com/angelnu/esphome-1
      ref: ade7953_split
```

to you yaml.

If you want to test with the Shelly Pro 4PM you might want to use my yaml as base: https://github.com/angelnu/esphome/blob/master/devices/shelly/pro4pm/base_v1.yaml

**Comment by mwetterw** [comment]
For your information, I'm currently adding support for **Shelly Pro 2 PM**:
https://github.com/esphome/feature-requests/issues/3033

**Comment by hapklaar** [comment]
> After the support for the sensor gets added I will submit an entry to esphome devices.

Would love to try esphome on my 4pm, but I couldn't find the device in the Esphome devices list. Did this not materialize?

**Comment by waza-ari** [comment]
@angelnu thanks for your work so far! Just got a Pro 4 PM, I'm using your base code and it works really okay I'd say.

Two questions: 

1. seeing that your PR for ade7953  support is merged, what would be missing in your eyes to get the devices added?
2. have you tried using `esp-idf` framework instead of `arduino`? I'd love to use it in order to use certificate validation with it (with Arduino I can use the client authentication but cannot do CA validation)

When using `esp-idf`, most of the readings are off by several orders of magnitude and the display doesn't work either. Before I start digging a bit more, did you play around with it already?

**Comment by angelnu** [comment]
I gave today esp-idf another try but the problem from https://github.com/esphome/issues/issues/6176 is still there. So remaining on framework arduino until either someone else fixes the SPI issue or I have time for it. Low in the prio list since it just work with Arduino so until the arduino framework is deprecated there is no urgency to change.

**Comment by angelnu** [comment]
The problem with the MCP23S17 is still there and now also with the arduino on esp-idf. As result it is not possible to get any new esphome firmware working on the device. I am therefore trying to debug this again...

# Update 1

I found that trying to write to one of the mcp23s17 GPIOs with:
```yaml
esphome:
  on_boot:
    priority: 600
    # ...
    then:
      - output.turn_off: devices_reset # This is a mcp23s17 GPIO reseting other devices in the bus
```
was failing. This code on the other side seems to work:
```yaml
output:
  - platform: gpio
    id: devices_reset
    pin:
      mcp23xxx: mcp23s17_hub
      # Use pin number 0
      number: 4
      mode:
        output: true
      inverted: true # As the output devices are low by default, this sets the output to high
```

I am now dealing with garbage reads from the ADE7953. I will try the circumvention from https://github.com/esphome/feature-requests/issues/3033

# Update 2

The trick was to do a reset of the ADE7953s:
```yaml
esphome:
  on_boot:
    - priority: 700
      then:
        - output.turn_off: devices_reset
        - delay: 10ms
        - output.turn_on: devices_reset
```

# Update 3

The problem was that the ADE7953s were switching to I2C mode when the CS pin was set to 1 (iddle). This resulted in the MISO port being kept HIGH. This prevented reading from the MCP23S17.

With the https://github.com/esphome/esphome/pull/14824 PR my configuration works: https://github.com/angelnu/esphome/blob/master/devices/shelly/pro4pm/base_v1.yaml
