### ISSUE TITLE
Add "before" turn_on/turn_off trigger

### ISSUE THREAD

**Issue by Niorix** [esphome/feature-requests#1796]
**Describe the problem you have/What new integration you would like**

I have esphome based cwww led dimmer. I want to have several objects like light with different settings. The main light and night light,  for example. Night light should automatically turn off the main light and vice versa. I created a configuration:
```yaml
esphome:
  name: cwww-test
  platform: ESP8266
  board: d1_mini
  on_boot:
    priority: 650
    then:
      - light.control:
          id: light_0
          brightness: 100%
          transition_length: 1.5s
      - light.control:
          id: nightlight_0
          brightness: 18%

logger:
  baud_rate: 115200
api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
web_server:
  port: 80
  auth:
    username: admin
    password: admin

light:
  - platform: cwww
    name: "main Light Enable"
    id: light_0
    restore_mode: ALWAYS_OFF
    gamma_correct: 1
    cold_white: light_cw
    warm_white: light_ww
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    constant_brightness: false
    on_turn_on:
      - light.turn_off: nightlight_0
  - platform: monochromatic
    name: "night Light Enable"
    id: nightlight_0
    restore_mode: ALWAYS_OFF
    gamma_correct: 1
    output: light_ww
    on_turn_on:
      - light.turn_off: light_0
output:
  - platform: esp8266_pwm
    id: light_cw
    frequency: 5000 Hz
    pin: 
      number: GPIO13
  - platform: esp8266_pwm
    id: light_ww
    frequency: 5000 Hz
    pin: 
      number: GPIO12
```
light_0 and nightlight_0 uses light_ww output. But after enable night light call turn_off action for main light. Since they use the same way out, the night light turns off itself
**Please describe your use case for this integration and alternatives you've tried:**

For example, the situation described above.
**Additional context**

Maybe this function can be implemented using two outputs with the same GPIO and Interlock (as well as Switch Interlock).
```yaml
light:
  - platform: cwww
    name: "Light Enable"
    id: light_0
    restore_mode: ALWAYS_OFF
    gamma_correct: 1
    cold_white: light_cw
    warm_white: light_ww
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    constant_brightness: false
    on_turn_on:
      - light.turn_off: nightlight_0
  - platform: monochromatic
    name: "nightLight Enable"
    id: nightlight_0
    restore_mode: ALWAYS_OFF
    gamma_correct: 1
    output: light_night
    on_turn_on:
      - light.turn_off: light_0
output:
  - platform: esp8266_pwm
    id: light_cw
    pin: 
      number: GPIO13
  - platform: esp8266_pwm
    id: light_ww
    interlock: [light_night]
    pin: 
      number: GPIO12
  - platform: esp8266_pwm
    id: light_night
    interlock: [light_ww]
    pin: 
      number: GPIO12
```yaml

<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE FEATURE REQUEST WILL BE CLOSED AUTOMATICALLY. -->
