### ISSUE TITLE
Web Server Component - show unit_of_measurement on template number

### ISSUE THREAD

**Issue by MagMeister** [esphome/feature-requests#1826]
Meanwhile, unit_of_measurement is shown in Home Assistant after a [feature request](https://github.com/esphome/feature-requests/issues/1366), but not yet in the state of the ESPHome web server.

**Comment by RoboMagus** [comment]
I cannot reproduce this issue. Is it still valid or can it be closed?

Config snippet and UI below:

```yaml
number:
- platform: template
  icon: "mdi:fan-speed-1"
  name: "Template Num"
  entity_category: config
  optimistic: true
  initial_value: 30
  unit_of_measurement: "%"
  min_value: 10
  max_value: 45
  step: 1
```
![image](https://user-images.githubusercontent.com/68224306/198722174-e039fc6c-2ecf-481e-8cbe-241458c11b2c.png)
