### ISSUE TITLE
Allow and merge duplicate keys with yaml substituiton file(s)

### ISSUE THREAD

**Issue by rradar** [esphome/feature-requests#183]
**Describe the problem you have/What new integration you would like**
I stumbled upon this problem here (https://github.com/esphome/issues/issues/208) and figured out that I can't do the following thing:

Having a common.yaml with all things I always need like this:

```yaml
wifi:
  ssid: 'MyVeryNiceWifiName'
  password: 'verysecurepassword1'

api:
  password: 'verysecurepassword2'

ota:
  password: 'verysecurepassword3'

sensor:
  - platform: wifi_signal
    name: "${upper_devicename} Signal"
    id: signal

switch:
  - platform: restart
    name: "${upper_devicename} Restart"
    id: restart

binary_sensor:
  - platform: status
    name: "${upper_devicename} Status"
    id: status

text_sensor:
  - platform: version
    name: "${upper_devicename} Version"
    id: version
```

...and I want to create a simple sensor node (wemos d1 mini) with just a binary sensor (pir) with this yaml:

```yaml
substitutions:
  devicename: test
  upper_devicename: Test

<<: !include common.yaml

esphome:
  platform: ESP8266
  board: d1_mini
  name: $devicename

logger:

binary_sensor:
  - platform: gpio
    pin: D7
    name: "${upper_devicename} PIR"
    device_class: motion
```

results in a working node but missing **all** binary_sensor entries from the common.yaml (in this case there is just one: status)

```yaml
  - platform: status
    name: "${upper_devicename} Status"
    id: status
```

There is **no error** and **no warning**. Just some loss (no binary sensor from the common.yaml) on the way.

It would be rather nice to merge all sensor/etc. while compiling the yaml(s).

**Please describe your use case for this integration and alternatives you've tried:**

Less code - more fun! :rocket: 

**Additional context**

Nope

**Comment by rradar** [comment]
closing as duplicate of #123 

Solution is to use `!include_dir_list` as described here: https://www.home-assistant.io/docs/configuration/splitting_configuration/

It's more complicated and needs more files (+folder structure) but what can we do? :disappointed:

**Comment by rradar** [comment]
I tried this one now but it will not work (can't compile):

```yaml
substitutions:
  devicename: test
  upper_devicename: Test
  device_hardware: D1 Mini

<<: !include 00-include/common.yaml

esphome:
  platform: ESP8266
  board: d1_mini
  name: $devicename

# Enable logging
logger:

binary_sensor: !include_dir_list 00-include/binary_sensor

  - platform: gpio
    pin: D7
    name: "${upper_devicename} PIR"
    device_class: motion

sensor: !include_dir_list 00-include/sensor

switch: !include_dir_list 00-include/switch

text_sensor: !include_dir_list 00-include/text_sensor
```

Actually I don't no how I can achieve what I want to achieve :weary: Would be nice to get a hint!
