### ISSUE TITLE
External Components: Git: specify a local path to clone to

### ISSUE THREAD

**Issue by crixionz** [esphome/feature-requests#1830]
**Describe the problem you have/What new integration you would like**

External Components: git source:
It would be very handy to be able to specify a local path where ESPHome clones the git repo to, other than the default hidden `.esphome` folder. Like this:
Example yaml

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/esphome/esphome
      ref: dev
      clone_path: "D:/Documents/esphome/.esphome/"
```

**Please describe your use case for this integration and alternatives you've tried:**

I like the ease of use of the git source over the local option.
I store my ESPHome config files in a folder that is included in an automatic backup, but I specify a `build_path` to a different drive so it's not bulking up the backup. 

```yaml
esphome:
  name: $name
  build_path: "D:/Documents/esphome/.esphome/build/$name"
```
This works really well, but all of the external components I use are cloned into the hidden `.esphome` folder and are subsequently included in my backup, which I don't like.
Specifying a clone_path would prevent this.

**Additional context**
