### ISSUE TITLE
Support restore_mode or similar in (Template) Switches

### ISSUE THREAD

**Issue by lcnittl** [esphome/feature-requests#1837]
**Describe the problem you have/What new integration you would like**

It would be nice if the Template Switch Platform (or the Switch Component) supported `restore_mode`, just like GPIO Switch Platform does:

```yaml
# Config example feature
switch:
  - platform: template
    id: chime_active
    name: Doorbell Chime Active
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
```

**Please describe your use case for this integration and alternatives you've tried:**

Currently, with only the `restore_state` option allowed:

```yaml
# Config example current - wrong initial state
switch:
  - platform: template
    id: chime_active
    name: Doorbell Chime Active
    optimistic: true
    restore_state: true
```

on the first boot (or if it cannot restore the state) this switch is turned off (thought, I would prefer to be able to have it turned on in this case).

A workaround it detailed in [Frenck's Blog](https://frenck.dev/diy-smart-doorbell-for-just-2-dollar/):

```yaml
# Config example current - correct initial state but cumbersome
globals:
  - id: chime
    type: bool
    restore_value: true
    initial_value: 'true'

switch:
  - platform: template
    name: Doorbell Chime Active
    id: chime_active
    restore_state: false
    turn_on_action:
      - globals.set:
          id: chime
          value: 'true'
    turn_off_action:
      - globals.set:
          id: chime
          value: 'false'
    lambda: |-
      return id(chime);
```

I would argue that supporting `restore_mode` would simplify the config file dramatically whilst also making it more easily understandable.

**Additional context**

Alternatively to a `restore_mode` option, could be a combination of `restore_value` and `initial_value`, as done for `globals`. As this is a switch, maybe `initial_state` would be a better option name. Yet, anything besides `restore_mode` would defer from the GPIO switch configuration. It is probably good to have switches to be configured similarly.

Maybe, `restore_mode` (or the alternative mechanism mentioned) could be implemented in the Switch Component as it could be useful for any switch, independent of platform.
