### ISSUE TITLE
add edge settings on pulse_meter

### ISSUE THREAD

**Issue by deathfrozen** [esphome/feature-requests#1852]
**Describe the problem you have/What new integration you would like**
The configuration of the edge for this integration is the same as in pulse_counter.

**Please describe your use case for this integration and alternatives you've tried:**
I am using the pulse_meter component to calculate energy and power consumption in an outdated energy meter. But LED on the  energy meter is constantly on, sometimes  discontinuing  by impulse. The pulse_meter component measures along the rising edge, and gives incorrect readings. I need to measure by the falling edge.

**Additional context**
The pulse_counter component in my case measures more accurately, but still does not give the necessary accuracy.

**Comment by cstaahl** [comment]
Hi!
You can have the pulse_meter count negative pulses by configuring the pin to invert the signal like so

```
sensor:
  - platform: pulse_meter
    pin:
      number: D5
      inverted: true
      mode:
        input: true
        pullup: true
    internal_filter: 90ms
    internal_filter_mode: PULSE
```
