### ISSUE TITLE
Add light.brightness condition

### ISSUE THREAD

**Issue by svh1985** [esphome/feature-requests#1860]
**Describe the problem you have/What new integration you would like**

I would like to request a light.brightness condition.
**Please describe your use case for this integration and alternatives you've tried:**

I'm coding dimmer logic and I want to stop dimming just before the light turns off because the toggle is for that 😄. 
**Additional context**

Example code:
```
          - while:
                condition:
                  - binary_sensor.is_on: switchID_1
                  - light.brightness:
                      id: dimmerID_1
                      above: 1
                then:
                  - light.dim_relative:
                      id: dimmerID_1
                      relative_brightness: -1%
                      transition_length: 0.01s
                  - delay: 0.01s
```
