### ISSUE TITLE
Quick Settings, substitutions but with a GUI

### ISSUE THREAD

**Issue by ebrithiljonas** [esphome/feature-requests#1866]
**Describe the problem you have/What new integration you would like**

Quick settings would be a way of changing some things in the config without opening it. They could be defined in the config file and then be shown in the ESPHome Dashboard. I have made a small example mockup for how it could look like:

Config Section:

```yaml
settings:
  - name:
      description: "Name"
      default: "Air Quality Sensor"
      type: String
  - sensor-prefix:
      description: "Sensor Prefix"
      default: ""
      type: String
  - voc-limit:
      description: "VOC Limit"
      default: 300
      type: Integer
      max: 1000
      min: 0
```
These settings could then be used in the rest of config, just like the substitutions.
And in the Dashboard it could look something like this:

![Screenshot from 2022-09-13 10-48-48](https://user-images.githubusercontent.com/11209045/189860965-8c374bb8-9f3f-47f9-a616-9501d9e58e0e.png)

![Screenshot from 2022-09-13 10-56-13](https://user-images.githubusercontent.com/11209045/189860993-3dce275d-449f-45f9-b7f4-8869f70fde33.png)

**Please describe your use case for this integration and alternatives you've tried:**

It would be easy for inexperienced users to change for example the name or a prefix of the device. This would be specially useful when you make devices and share or sell them cause the user wouldn't need to fiddle with a yaml config and could use a nice GUI to change curated settings by the creator.

**Additional context**
