### ISSUE TITLE
How to connect 36 powermeters with an S0 bus  to a ESP32 ?

### ISSUE THREAD

**Issue by zibous** [esphome/feature-requests#1895]
**Describe the problem you have/What new integration you would like**
How to connect 36 powermeters with an S0 bus  to a ESP32

**Please describe your use case for this integration and alternatives you've tried:**

platform: pulse_meter

Simple Testcase
![Bildschirmfoto 2022-09-26 um 17 32 59](https://user-images.githubusercontent.com/30198737/192318802-1fb2572b-1985-49b5-b6e4-483e112a0a4f.png)

```
# ----------------------------------------------------------------------------
# ALL eacWSZ-50A S0 Devices
# GPIO pin: 3, 12, 5, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 25, 26, 27, 34
#
# eacWSZ-50A S0 Smartmeter Device
#   - Impulsauflösung: 1000imp/kWh
#   - Impuls Anschluss:
#     Schaltspannung 5-27VDC
#     Strom≤27mA ≤100mW
#     Impulsweite 90ms
#     Impulsausgang
#      Klemme 20 und 21
#
#     Anschluss ESP32
#      S0:21 -----------> o ESP32 GND
#      S0:20 --┃--------> o ESP32 GPIO
#              ┗--10k-----o ESP32 +3.3V (5.0V)
#
# auto value = esphome::parse_float(x);
# ----------------------------------------------------------------------------
sensor:

  - platform: pulse_meter
    pin: GPIO4
    unit_of_measurement: 'kW'
    device_class: 'power'
    icon: 'mdi:flash'
    name: ${friendly_name}-S04 Current
    id: S04
    internal_filter: 90ms
    timeout: 300s
    accuracy_decimals: 3
    filters:
      - multiply: 0.06
      - delta: 0.01
    on_raw_value:
        then:
          - lambda: |-
             ESP_LOGI("main", "Publish Value %f", (x * 60));
             id(S04CW).publish_state(x * 60);

    total:
      name: ${friendly_name}-S04 Total
      id: S04_total
      unit_of_measurement: "kWh"
      accuracy_decimals: 2
      device_class: 'energy'
      state_class: total_increasing
      icon: "mdi:flash"
      filters:
        - multiply: 0.001
```
**Additional context**

How many powermeters with an S0 bus can I connect to an ESP32 (az-delivery-devkit-v4) ?  
I have 36 powermeters and should know how many ESP32 I need for it.  Is there an alternative via a multiplexer ?

![Schaltplan1](https://user-images.githubusercontent.com/30198737/192318895-20743994-d68b-4745-b000-4f528246e29f.png)
