### ISSUE TITLE
Add support for the new LilyGO T-Display-S3

### ISSUE THREAD

**Issue by hapklaar** [esphome/feature-requests#1902]
**Describe the problem you have/What new integration you would like**
Please add support for the T-Display-S3 module, so it is recognized in ESPHome

**Please describe your use case for this integration and alternatives you've tried:**
Using these devices for HA connected energy monitors

**Additional context**
Module info: https://github.com/Xinyuan-LilyGO/T-Display-S3

**Comment by hapklaar** [comment]
Was able to get this board working by connecting it to the Home Assistant host directly and flash using the following board config:

```
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 5.0.0
```

Did not get the display working other than the backlight lit up. Probably [because it needs a special version of the TFT_eSPI library](https://github.com/Xinyuan-LilyGO/T-Display-S3#quick-question-and-answer). Is it possible to use this custom library in ESPHome somehow?

```
display:
  - platform: st7789v
    model: custom
    height: 172
    width: 320
    offset_height: 0
    offset_width: 0
    backlight_pin: GPIO38
    cs_pin: GPIO6
    dc_pin: GPIO7
    reset_pin: GPIO5
    rotation: 90°
```
