### ISSUE TITLE
filter send_first_at bigger than send_every

### ISSUE THREAD

**Issue by prchal** [esphome/feature-requests#1933]
**Describe the problem you have/What new integration you would like**

After boot the window is not filled up by measured samples thus posting out not reasonable value. Being able to set high values for **send_first_at** while frequent updates by low **send_every** would be nice.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

examle:
```
    - sliding_window_moving_average:
         window_size: 256
         send_every: 16
         send_first_at: 256
```
