### ISSUE TITLE
Third Trigger on_stop for Rotary Encoders

### ISSUE THREAD

**Issue by Pippowicz** [esphome/feature-requests#1934]
**Describe the problem you have/What new integration you would like**

There is an on_clockwise and on_anticlockwise trigger for the rotary encoder. It would be nice to implement a third one:
on_stop. 

**Please describe your use case for this integration and alternatives you've tried:**

For my Garage Door i want to get state opening or closing. That works with the current setup. Whats missing is a third one
which triggers when no movement is happening on the encoder. This would result in a third possible state: stopped. 

The current Implementation gives back the last movement state.

**Additional context**
Perhaps it would be needed to also set a time to wait for stop to trigger.

**Comment by RoboMagus** [comment]
Accoding to the [Docs](https://esphome.io/components/sensor/rotary_encoder.html#on-clockwise-and-on-anticlockwise-triggers) these triggers `trigger on every step`. So the triggers are not really used to indicate _is moving_, but just the increment it has stepped. As such I do not think an `on_stop` trigger makes much sense.

I've modified a yaml config to somewhat match your usecase as I've done something similar using a restarting script and a timeout before it's action is performed:

```yaml

sensor:
  - platform: rotary_encoder
    id: my_rotary_encoder
    on_clockwise:
      - logger.log: "Turned Clockwise"
      - script.execute: stopped
    on_anticlockwise:
      - logger.log: "Turned Anticlockwise"
      - script.execute: stopped

script:
  - id: stopped
    mode: restart
    then:
      - delay: 500ms
      - logger.log: "Stopped turning"
```
