### ISSUE TITLE
remote receiver logs id association  

### ISSUE THREAD

**Issue by kfirsa** [esphome/feature-requests#194]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip on venv
**ESP (ESP32/ESP8266, Board/Sonoff):**

d1_mini_lite
**Affected component:**

Remote Receiver

**Description of problem:**
i am using multiple remote receiver, everything is working as expected (amazing work btw)
but in the logs i do not know from which id the event coming from

`[22:10:13][D][remote.raw:067]: Received Raw: 938, -104, 104, -521, 104, -312, 313, -312, 313, -10000`
`[22:10:16][D][remote.raw:067]: Received Raw: 417, -104, 416, -105, 104, -312, 104, -521, 104, -313, 104, -104, 104, -10000`

**Problem-relevant YAML-configuration entries:**
```yaml
logger:
  logs:
    remote.rc_switch: DEBUG
    remote.receiver: DEBUG

remote_receiver:
  - id: RX43392
    pin:
      number: D6
      inverted: True
      mode: INPUT_PULLUP
    buffer_size: 5kb
    dump: 
      - rc_switch
      - samsung
      - rc5
      - lg
      - jvc
  - id: RF
    pin:
      number: D5
      #buffer_size: 2kb
      inverted: True
      mode: INPUT_PULLUP
    dump: all
```
