### ISSUE TITLE
Light component - implement on_turn_on and on_turn_off

### ISSUE THREAD

**Issue by danps1** [esphome/feature-requests#198]
**Describe the problem you have/What new integration you would like**

Feature request to implement matching functionality from the switch component into the light component - automation triggers for on_turn_on and on_turn_off.

**Please describe your use case for this integration and alternatives you've tried:**

Use case 1 - I have touch light switches on the wall that have an LED which is either red or blue. It's nice to have them reflect the state of the light, but currently I have to do this with a lambda...
```
  on_loop:
    lambda: |-
      if (id(light_1).get_remote_values().get_state() != 0.0) {
        id(led_1).turn_on();
      } else {
        id(led_1).turn_off();
```
(thanks @OttoWinter for that one!)

This would be much neater and easier however with on_turn_on and on_turn_off.

Use case 2 - I have grouped lights with multiple light switches. Currently I use HA automations for both turn off and turn on group functionality, but it would be great if instead I could do this...

```
light:
  - platform: binary
    name: "Stairs_1"
    id: light_1
    output: relay_1
    on_turn_on:
      then:
        - homeassistant.service:
            service: light.turn_on
            data:
              entity_id: light.stairs     
    on_turn_off:
      then:
        - homeassistant.service:
            service: light.turn_off
            data:
              entity_id: light.stairs  
```
**Additional context**

Switch functionality referenced...
https://esphome.io/components/switch/index.html#switch-on-turn-on-switch-on-turn-off-trigger
