### ISSUE TITLE
Idea for sprinkler application

### ISSUE THREAD

**Issue by Hoaarst** [esphome/feature-requests#1982]
**Describe the problem you have/What new integration you would like**
Dear Keith, dear all,
I am using the sprinkler application which I like very much, good job :)
I have just a minor wish for improvement. As far as I could find out the sprinkler application goes one valve after the other. My pump is strong enough to deal with more than one valve at the same time. So, it would be very good if I could group valves to be run as groups one after the other.
For sure I could solve this on the hardware side if I put more than one valve on a relais but then I loose the oppotunity to open a single valve. Therefore I prefer a software solution.

**Please describe your use case for this integration and alternatives you've tried:**
I tried several way to group valves but I have not been successful yet.
If I was blind, only, please excuse myself. I am not too familiar in programming. Any help will be highly appreciated. Thanks.

**Additional context**

**Comment by nagyrobi** [comment]
You could create [template switches](https://esphome.io/components/switch/template.html) to act as valve groups:
```yaml
switch:
  - platform: template
    id: valve_group_1
    internal: true
    turn_on_action:
      - switch.turn_on: valve_01
      - switch.turn_on: valve_02 
    turn_off_action:
      - switch.turn_off: valve_01
      - switch.turn_off: valve_02 
```
Setting `internal: true` will not expose the group switch to Home Assistant but `sprinkler` could still use by `id`.
