### ISSUE TITLE
Update only selected feature

### ISSUE THREAD

**Issue by newlund** [esphome/feature-requests#1990]
Nice to be able to update all ESPs in the HA esphome integration.
But would also like an option to "update selected"

If you have 10+ esphome devices and half of them have already been updated it is rather tedious to update them one by one. Would be nice to be able to select all that needs updating and press "update selected".

**Comment by Dutchy-79** [comment]
Same, I have one sleeping device and that doesn't want to be updated therefore the entire update all does not work. So update all selected or all except selected would be great.

Maybe in the yaml
include_in_update: true

**Comment by total1ty** [comment]
Yes, please. I also have a (growing) esphome Setup with 25+ devices and modular config, using packages etc.

It is extremely tideous to flash all affected devices manually after a change in a base config. I have to wait for every single compile and OTA to complete until I can start the next. 
Updating simultaneously in different Tabs/Browser Windows doesn't work either, the newer compile job makes the running job fail if you try that.

A way to mark/select the devices with e.g. checkboxes and putting an "update" button where the "update all" button is. When you press it the selected devices get updated automatically, one after another. That would be a really handy feature. 
Since the "update all" functionality is already implemented it should be fairly doable regarding the coding effort ;)

**Comment by randybb** [comment]
Create a script which will compile everything and then with another script you can flash everything and then the whole update process takes few minutes (using it with 40 devices in PROD instance).

**Comment by total1ty** [comment]
There's already a button for updating everything automatically ;)
I would like to be able to specifically select which devices I update, which of course would be best in a graphical way.

In other words:
I don't want to update my 12 Shelly Plug S when I've only changed a value in a NodeMCU base config. Especially when testing or troubleshooting, this would be a huge help.

And it's not only about the time savings, but also about device longevity, see e.g. https://www.esp32.com/viewtopic.php?t=709#p30724

Btw, what makes the "Update All" button even more impractical is the fact that it doesn't check if a device config has been changed or the device even is online.
So ESPHome compiles every single device firmware in order, only to fail the update because a device is offline, or to needlessly re-flash dozens of devices, killing their flash memory.

**Comment by Dutchy-79** [comment]
For me it's a few Christmas related devices that are offline and therefore I have problems with the update all button.

**Comment by tungmeister** [comment]
@c-lega could you post again but in a code block? I've attempted to implement this but I can't work out the 'for_each' part - I've done as below but the script isn't loading as I'm getting an error related to this part
```
    update_esphome:
      alias: Update ESPHome devices
      mode: single
      icon: mdi:cellphone-arrow-down
      variables:
        devices: >-
          {{ states.update | selectattr('state', 'in', 'on') | map(attribute='entity_id') | list }}
      repeat:
        for_each: "{{ devices }}"
      sequence:
        - choose:
          - conditions:
              - condition: template
                value_template: "{{ is_state_attr(repeat.item, 'title', 'ESPHome') }}"
            sequence:
              - service: update.install
                data: {}
                target:
                  entity_id: "{{ repeat.item }}"
              - wait_template: "{{ is_state(repeat.item, 'off') }}"
                continue_on_timeout: true
                timeout: "00:05:00"
          default: []
```
