### ISSUE TITLE
Add `restore_mode:` option for locks

### ISSUE THREAD

**Issue by HarvsG** [esphome/feature-requests#2006]
**Describe the problem you have/What new integration you would like**

I want to be able to configure a lock like this:
```yaml
output:
  - platform: gpio
    pin:
      number: 20
      mode: output
    id: PB
    inverted: true

lock:
  - platform: output
    name: "Shared Door"
    output: 'PB'
    restore_mode: ALWAYS_OFF
```
I have to invert the output to get 'locked' and 'unlocked' right showing up in the UI (I use a relay to close a circuit which powers the solenoid that opens the door) so a GPIO output 'ON' opens the door, and 'OFF' locks it. However the result is that on reboot of the device the door unlocks itself (unsafe). So having a restore mode on the lock (or Output) could help me make this safe by default.

**Please describe your use case for this integration and alternatives you've tried:**

Considered using a switch which does support `restore_mode` and then using that as the platform for the lock as a middleman but lock does not support the switch platform
**Additional context**

ESP on PicoW, running a custom circuit.
