### ISSUE TITLE
Make log optional in web_server

### ISSUE THREAD

**Issue by stevetz** [esphome/feature-requests#2025]
I’d like to present family members with a simple webui - where they don’t need to see the logs.

Similarly adding an optional variable to the implemented `ota:` one would be really useful, to me at least.

I’m afraid I have no understanding of how much work this would take to add, so please forgive me if it’s ridiculous!

**Comment by ssieb** [comment]
I don't understand what you're suggesting about the `ota:`.  Can you clarify?

**Comment by stevetz** [comment]
My apologies, I meant that just to compare a new potentially optional setting for the log might be implemented similarly to the optional ota -
```
web_server:
  ...
  ota: false
  # the feature request would be this
  log: false
```
