### ISSUE TITLE
Add support for Shelly Plus Addon

### ISSUE THREAD

**Issue by raidr1** [esphome/feature-requests#2034]
**Describe the problem you have/What new integration you would like**

Add support for Shelly Plus Addon

**Please describe your use case for this integration and alternatives you've tried:**

it would be nice to integrate with all Shelly Plus devices

**Additional context**

**Comment by nagyrobi** [comment]
The addon is just a galvanic isolated adapter for GPIO pins. It's transparent to ESPHome.

**Comment by DHowett** [comment]
I don’t believe it’s a simple passthrough. It connects to the serial/debug header on the Plus devices and expands the host device with support for 1-Wire, one additional ADC and one additional GPIO. Those aren’t exposed via that header.

In addition, Shelly documents the addon as using a …

> Shelly proprietary serial interface to connect to a Shelly Plus device
> _[source](https://kb.shelly.cloud/knowledge-base/shelly-plus-add-on)_

**Comment by jtricerolph** [comment]
I opened mine up and the pins trace through to seperate pins on the isolator chip, I'm pretty sure it's not using uart based on the chip model number.

**Comment by jtricerolph** [comment]
> Thanks for tracing these out! That makes sense. Yeah, RX0/TX0 can be re-muxed to be I/O, and then we have IO19 and IO0 on the pin header. Good call.
> 
> I'm interested in the extra analog input. None of those four pins seem (according to the datasheet; I don't know if they do in practice) to support ADC... 🤷🏻 

Don't quote me on the above tracing but the following 😅
But one I put that I think is the analoge trace goes through a seperate chip labeled 3PEAK 393a BQLh and although can't find an exact match on Google maybe it's doing some pre processing for that?

**Comment by jowgn** [comment]
![0CF3BC53-1468-4A15-A742-52045F2A8AF8](https://user-images.githubusercontent.com/24966042/213034223-7e832bab-33d7-476b-9c71-7111f71d8b96.jpeg)
![5F66C44A-66F3-4552-949A-E2C755C303D9](https://user-images.githubusercontent.com/24966042/213034229-af666ddd-258d-4682-b55b-4208f7890532.jpeg)
![6944DD18-D6B2-432A-A344-1ECA459CBBC8](https://user-images.githubusercontent.com/24966042/213034232-1c88f0ab-f153-43a9-a5e3-a744c10e95f5.jpeg)
![82947CAB-0ECB-4161-A0E0-192E71057F1D](https://user-images.githubusercontent.com/24966042/213034240-87bf255f-fb91-4221-9f5a-f0d1f0273d89.jpeg)

**Comment by OldSilvaRanga** [comment]
Any movement on the use of the Addon within ESPHome?  Would be a great addition to the existing shelly gear.

**Comment by pdw-mb** [comment]
> But one I put that I think is the analoge trace goes through a seperate chip labeled 3PEAK 393a BQLh and although can't find an exact match on Google maybe it's doing some pre processing for that?

It's this one - [LM393A datasheet](https://datasheet.lcsc.com/lcsc/2203101903_3PEAK-LM393A-SR_C2690180.pdf)

**Comment by andypnz** [comment]
Is there any possibility of using the addon with ESPHome? Thanks you!

**Comment by pdw-mb** [comment]
I've spent some time figuring out how the ADC works on this.  It actually appears as the duty cycle on the RX pin (GPIO3).  This config appears to read it correctly:

```
sensor:
  - platform: duty_cycle
    pin: 3
    name: Duty Cycle Sensor
    update_interval: 5s
```

The board is generating a sawtooth input to one pin of the comparator, with the analog input on the other, giving a digital output with duty cycle representing the analog input.  I don't fully understand the circuit, as it appears that the frequency and amplitude of the signal vary according to the resistors.

I think the other pins are: GPIO19 - digital input, GPIO0 1-wire TX, GPIO1 1-wire RX.  I've not tried, but I think that  https://github.com/esphome/esphome/pull/1346 would allow you to use the DS18B20 sensors with it, if you set `pin: 1`, `pin_a: 0`.  It looks like the PR needs some work to sort out some compilation issues.

**Comment by ashp8i** [comment]
I have the dht working [https://github.com/ashp8i/esphome-configs/tree/main/my_external_components/test4/shelly_dht](https://github.com/ashp8i/esphome-configs/tree/main/my_external_components/test4/shelly_dht)

using the following config: -
```
sensor:
  - platform: shelly_dht
    pin: GPIO1
    pin_a: GPIO0
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s
```

I need to find a way how to leave the original component alone but add ifdef or new methods for the shelly that uses two pins, same goes for the dallas, my plan for the dallas side is to add support for 1-Wire via RMT peripheral (ESP32's) and make the bitbanging more robust for the ESP8266, and support Switch and I2C bridge, sorry not high-jacking thread, trying to give this some direction.

**Comment by amzaldua** [comment]
Is it possible to integrate a CT sensor with the Shelly 1 Plus using the add-on module? Currently, my Shelly Plus 1PM, connected to my boiler, is experiencing issues with overheating. Could using a Shelly Plus 1 with a dry contact potentially resolve this problem?

**Comment by yasapl** [comment]
> I've spent some time figuring out how the ADC works on this. It actually appears as the duty cycle on the RX pin (GPIO3). This config appears to read it correctly:
> 
> ```
> sensor:
>   - platform: duty_cycle
>     pin: 3
>     name: Duty Cycle Sensor
>     update_interval: 5s
> ```
> 
> The board is generating a sawtooth input to one pin of the comparator, with the analog input on the other, giving a digital output with duty cycle representing the analog input. I don't fully understand the circuit, as it appears that the frequency and amplitude of the signal vary according to the resistors.
> 
> I think the other pins are: GPIO19 - digital input, GPIO0 1-wire TX, GPIO1 1-wire RX. I've not tried, but I think that [esphome/esphome#1346](https://github.com/esphome/esphome/pull/1346) would allow you to use the DS18B20 sensors with it, if you set `pin: 1`, `pin_a: 0`. It looks like the PR needs some work to sort out some compilation issues.

Hi, would you be able to suggest a configuration for an NTC resistor to use ut as a temperature sensur (underfloor heating, 10Kohm at 25deg C)? Seems that the original shelly fw does support it so the hardware should be OK.

Thank you in advance!
Yasa

**Comment by pdw-mb** [comment]
> Hi, would you be able to suggest a configuration for an NTC resistor to use it as a temperature sensor (underfloor heating, 10Kohm at 25deg C)? Seems that the original shelly fw does support it so the hardware should be OK. I know I could use dallas sensor but the ntc is already buried in the floor.

This is actually exactly what I use my Shelly add-ons for :smiley: 

```yaml
  - platform: ntc
    sensor: resistance_sensor
    calibration:
      - 11.4kOhm -> 26.6°C
      - 13.17kOhm -> 24°C
      - 16.17kOhm -> 18.8°C
    name: Floor Temperature
    id: floor_temperature

  # Example source sensors:
  - platform: resistance
    id: resistance_sensor
    sensor: add_on_adc
    configuration: DOWNSTREAM
    resistor: 10kOhm
    name: Resistance Sensor

  - platform: duty_cycle
    pin: 3
    id: add_on_adc
    name: "Add-on ADC"
    update_interval: 5s
    unit_of_measurement: "V"
    filters:
      - offset: -2.0
      - multiply: 0.033
```

The calibration was based on measuring the existing NTC and taking readings from the existing floor controller.

I can't remember how I arrived at the `offset` value for the duty cycle filter.  The `0.033` is to transfer 100% duty to 3.3V.

**Comment by yasapl** [comment]
Thank you @pdw-mb. I will definitely try in once my add-on arrives.

**Comment by larsskogshusabf** [comment]
Me too. My Addon arrives on Friday.

**Comment by KaufDirEins** [comment]
Any news on using dallas ? My addon arrived today. And i cant get it to work

**Comment by JKoss2** [comment]
Does anyone think it would be possible to run a PWM signal on GPIO19 of the add-on? Perhaps in combination with a DHT22 (since that uses GPIO1 according to [this comment](https://github.com/arendst/Tasmota/discussions/18885#discussioncomment-7295482) )? The PWM signal would be to adjust the speed of a fan. I know its possible to control a PWM fan in ESPHome, but I am unsure if the galvanic isolation of the add-on would affect the signal.

**Comment by m1k3f15h** [comment]
Hy @KaufDirEins 

> Any news on using dallas ? My addon arrived today. And i cant get it to work

Did you already get them to work?

Mike

**Comment by ShifuSonny** [comment]
any new info?

Sonny

**Comment by m1k3f15h** [comment]
hy @ShifuSonny 
I Use this: https://github.com/persuader72/esphome-components
and it works perfect!

**Comment by klim123123** [comment]
> hy @ShifuSonny
> I Use this: https://github.com/persuader72/esphome-components
> and it works perfect!

Temperature Sensor AddOn for Shelly 1/1PM and Shelly Plus Addon are not the same.

**Comment by m1k3f15h** [comment]
> > hy @ShifuSonny
> > I Use this: https://github.com/persuader72/esphome-components
> > and it works perfect!
> 
> Temperature Sensor AddOn for Shelly 1/1PM and Shelly Plus Addon are not the same.

Hy
Oh.. I didn't see this :O

but i use the component with the shelly plus addon!

mike

**Comment by klim123123** [comment]
> but i use the component with the shelly plus addon!

please provide your configuration

**Comment by pdw-mb** [comment]
> Does anyone think it would be possible to run a PWM signal on GPIO19 of the add-on? 
> 
> Edit (11Jul2024): After testing that the PWM signal correctly controls a fan via the 7 pin female header on the back of a Shelly Plus 1PM, I've concluded that the galvanic isolation in the Shelly Plus Add-On prevents the PWM signal from passing through to the add-on terminals.

Late reply to this one, but yes, that is the case. The opto-isolator only passes each pin in one direction, so GPIO19 can only be used as an input.  That's also why the "1-wire" connection is broken out into separate TX and RX pins.

**Comment by m1k3f15h** [comment]
Did anyone get the Digital Input on the Shelly Plus Addon to work? (Shelly2PM)

**Comment by aizerin** [comment]
I made addon works with Shelly 1PM Gen3. DHT + NTC. I used configuration from posts above and just changed pins to match new shelly device.

Full config reference:

```
substitutions:
  friendly_name: thermo_obyvak
  floor_max_temp: "37.0"
  floor_cooldown_temp: "35.0"

esphome:
  name: thermo-one
  friendly_name: $friendly_name

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/ashp8i/esphome-configs
      path: my_external_components/test4
    components: [ shelly_dht ]

logger:
  baud_rate: 0

api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "xxx"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password

uart:
  id: bl0942_uart
  tx_pin: GPIO6
  rx_pin:
    number: GPIO7
    mode:
      pullup: true
      input: true
  baud_rate: 9600
  stop_bits: 1

output:
  - id: relay_output
    platform: gpio
    pin: GPIO4

binary_sensor:
  - id: relay_switch
    name: relay_switch
    platform: gpio
    pin: GPIO10
    filters:
      - delayed_off: 50ms
  - id: relay_button
    name: relay_button
    platform: gpio
    pin: GPIO1
    filters:
      - delayed_off: 50ms
  - id: internal_error_overtemp
    name: internal_error_overtemp
    device_class: problem
    entity_category: diagnostic
    platform: template
    condition:
      any:
        - binary_sensor.is_on: internal_error_overtemp # Latch ON
        - sensor.in_range:
            id: internal_temperature
            above: 75.0
    on_press:
      then:
        - switch.turn_off: relay
  - platform: template
    id: floor_limit_active
    name: floor_limit_active

switch:
  - platform: template
    id: relay
    name: relay
    device_class: outlet
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      if:
        condition:
          all:
            - binary_sensor.is_off: floor_limit_active
            - or:
                - lambda: "return isnan(id(floor_temperature).state) || (id(floor_temperature).state < ${floor_max_temp});"
            - any:
                - sensor.in_range:
                    id: internal_temperature
                    below: 75.0
                - all:
                    - lambda: "return isnan(id(internal_temperature).state);"
                    - binary_sensor.is_off: internal_error_overtemp
        then:
          - output.turn_on: relay_output
          - binary_sensor.template.publish:
              id: internal_error_overtemp
              state: OFF
          - switch.template.publish:
              id: relay
              state: ON
        else:
          - switch.template.publish:
              id: relay
              state: OFF
    turn_off_action:
      then:
        - output.turn_off: relay_output
        - switch.template.publish:
            id: relay
            state: OFF

sensor:
  - id: internal_temperature
    name: internal_temperature
    platform: ntc
    sensor: internal_temperature_sensor_resistance
    icon: mdi:thermometer
    unit_of_measurement: °C
    accuracy_decimals: 1
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 25°C
  - id: internal_temperature_sensor_resistance
    name: internal_temperature_sensor_resistance
    platform: resistance
    sensor: temperature_sensor_voltage
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - id: temperature_sensor_voltage
    name: temperature_sensor_voltage
    platform: adc
    pin: GPIO3
    attenuation: 11db
  - platform: bl0942
    uart_id: bl0942_uart
    update_interval: 5s
    voltage_reference: 14414.46229102
    # voltage_reference: 15873.35944299
    # current_reference: 251213.46469622
    current_reference: 255426.68842278
    voltage:
      id: bvoltage
      name: bvoltage
      icon: mdi:alpha-v-circle-outline
      device_class: voltage
    current:
      id: bcurrent
      name: bcurrent
      icon: mdi:alpha-a-circle-outline
      device_class: current
    power:
      id: bpower
      name: bpower
      icon: mdi:transmission-tower
      device_class: power
    frequency:
      id: bfreq
      name: bfreq
      accuracy_decimals: 2
      icon: mdi:cosine-wave
      device_class: frequency
    energy: 
      id: benergy
      name: benergy
      icon: mdi:lightning-bolt
      device_class: energy
  - platform: shelly_dht
    pin: 21
    pin_a: 9
    model: DHT22
    temperature:
      id: room_temperature
      name: room_temperature
      icon: mdi:thermometer
      unit_of_measurement: °C
      accuracy_decimals: 1
    humidity:
      id: room_humidity
      name: room_humidity
      icon: mdi:water-percent
      unit_of_measurement: '%'
      accuracy_decimals: 1
    update_interval: 5s
    
  - platform: duty_cycle
    name: duty_cycle
    pin: 20
    id: floor_ntc_duty
    update_interval: 5s

  - platform: template
    id: floor_v
    name: floor_v
    unit_of_measurement: "V"
    accuracy_decimals: 3
    update_interval: 5s
    lambda: |-
      return (id(floor_ntc_duty).state - 2) * 0.033;

  - platform: resistance
    id: floor_resistance_sensor
    name: floor_resistance_sensor
    sensor: floor_v
    configuration: DOWNSTREAM
    resistor: 10kOhm

  - platform: ntc
    sensor: floor_resistance_sensor
    calibration:
      b_constant: 3950
      reference_resistance: 10kOhm
      reference_temperature: 25°C
    icon: mdi:thermometer
    unit_of_measurement: °C
    accuracy_decimals: 1
    id: floor_temperature
    name: floor_temperature
    on_value_range:
      - above: ${floor_max_temp}
        then:
          - binary_sensor.template.publish:
              id: floor_limit_active
              state: ON
          - switch.turn_off: relay
      - below: ${floor_cooldown_temp}
        then:
          - binary_sensor.template.publish:
              id: floor_limit_active
              state: OFF
          - if:
              condition:
                all:
                  - lambda: "return id(room_thermostat).mode != CLIMATE_MODE_OFF;"
                  - lambda: "return id(room_thermostat).action == CLIMATE_ACTION_HEATING;"
              then:
                - switch.turn_on: relay

climate:
  - platform: thermostat
    id: room_thermostat
    name: room_thermostat
    sensor: room_temperature
    heat_deadband: 1
    heat_overrun: 0.5
    min_heating_off_time: 10s
    min_heating_run_time: 10s
    min_idle_time: 10s
    heat_action:
      - if:
          condition:
            binary_sensor.is_off: floor_limit_active
          then:
            - switch.turn_on: relay
          else:
            - switch.turn_off: relay
    idle_action:
      - switch.turn_off: relay
    visual:
      min_temperature: 10 °C
      max_temperature: 25 °C
      temperature_step: 1 °C
```
