### ISSUE TITLE
GPIO Output Condition

### ISSUE THREAD

**Issue by fran6120** [esphome/feature-requests#2050]
I think it would be great to add a condition to perform "automations and templates" and be able to check the status of an output, as it already exists for the binary sensor and switch components.

**Describe the problem you have/What new integration you would like**

You can check the state of a binary_sensor or switch:

``` yaml
on_...:
  if:
    condition:
      # Same syntax for is_off
      switch.is_on: my_switch
```

but not the state of a GPIO output:

``` yaml
on_...:
  if:
    condition:
      # Same syntax for is_off
     output.is_on: my_output
```
**Please describe your use case for this integration and alternatives you've tried:**

A workaround is set a "globals" in configuration and use "global.set" action on every "output.turn_...." action, to set an state.

``` yaml
globals:
  - id: my_output_state
    type: bool
    restore_value: no
    initial_value: 'false'
```

In my case, i manage the output through a button template:

``` yaml
output:   
  - platform: gpio
    pin: GPIO12
    id: my_output
    inverted: false

button: 
  - platform: template
    name: "My Button"
    on_press:
      - output.turn_on: my_output
      - globals.set:
          id: my_output_state
          value: 'true'
      - delay: 2min 
      - output.turn_off: my_output
      - globals.set:
          id: my_output_state
          value: 'false'
```

Then, i can check the state of the global, (based on output state) through a lambda:

``` yaml
on_...:
  if:
    condition:
      - lambda: 'return id(my_output_state) == false;'
```

**Additional context**

I really don't know if there would be any impact on performance or RAM usage, beyond simplifying the setup.

Anyway, thanks for this amazing work.
