### ISSUE TITLE
Allow user to pick ABC period for Senseair S8

### ISSUE THREAD

**Issue by DavyLandman** [esphome/feature-requests#2054]
**Describe the problem you have/What new integration you would like**

The senseair s8 (added in esphome/esphome#705) sensor is much appreciated. 

One of the benefits of the s8 (vs the mh-z19b) is that the ABC can be stretched over multiple days, so it's less sensitive to daily fluctuations.

Currently, the user gets no control. And the default period is enabled (which seems to be 24h).

**Please describe your use case for this integration and alternatives you've tried:**

From the [senseair s8 manual](https://rmtplusstoragesenseair.blob.core.windows.net/docs/Dev/publicerat/TDE2067.pdf):
![image](https://user-images.githubusercontent.com/179603/211758746-3a4823b5-3171-4eb2-a64c-a7011e807f81.png)

You can set the ABC period to anything 1 and 180 hours (where 180 hours is 7.5 days).

I expected one of the optional config parameters of the sensor to be this period, but currently there is only an action that you can trigger: `SenseAirABCEnableAction`. This seems a bit strange, as it's more of a setup of the sensor than something I want to trigger at a specific point during the runtime.

Something like this:

```yaml
sensor:
  - platform: senseair
    co2:
      name: "SenseAir CO2 Value"
      abc_period: 24h
    update_interval: 60s
```

I understand it would make the commands a bit more work, as the current code has hard-coded the bytes (and the corresponding crc16 values), but it would help use the benefits of this sensor more.

**Additional context**

**Comment by DavyLandman** [comment]
Update, the new default is the max (7d) so thats a lot better.

And while there is no way to automatically set if for the sensor, you can use this boot trigger to turn it one:

```
esphome:
  name: ....
  on_boot:
    priority: 200
    then:
      - senseair.abc_enable: <sense_air-id>
```
