### ISSUE TITLE
Run_duration added to deep_sleep.enter Action

### ISSUE THREAD

**Issue by comet424** [esphome/feature-requests#2060]
**Describe the problem you have/What new integration you would like**

i use esp32 in my car and after 15 min i want it to sleep itself..  well there is a problem it seems.  when there is no wifi connection.. its endless looping and not running the deep_sleep:   run_duration 15min...  it only runs when wifi is connected...   so if not easily fixed add a feature
**Please describe your use case for this integration and alternatives you've tried:**

deep sleep mode  never enters  if there is no wifi connected to the ESP.. its stuck in a priority of only getting wifi and nothing else.. or its stuck in a do loop endless loop till wifi is connected
**Additional context**

feature request be to do it this way

``` 
on_boot:
    then:
      - deep_sleep.enter: deep_sleep_1

deep_sleep:
  run_duration: 15min
  id: deep_sleep_1
```
this way  it runs the deep sleep.     as i can see  there is only  sleep_duration  not a run_duration
or have it 

```
on_boot:
    then:
      - deep_sleep.enter: 
        -  run_duration: 15min  
```
this way it can run even when wifi is not connected first
as in my car you cant bring your home wifi connection with ya unless i through a router in my trunk  just for the esp32

another suggestion
since you need an ID to enter deep sleep.. then you should have multiple Deep Sleeps

```
on_boot:
  then:
    -deep_sleep.enter: deep_sleep_2

deep_sleep:
   - id: deep_sleep_1
     run_duration: 15 min
   - id: deep_sleep_2
     run_duration: 5min
   - id: deep_sleep_3  
     sleep_duration: 20min
   - id: deep_sleep_instant
     sleep_duration: 0s
     run_duration: 0s 
```
and if i a button press then youd do  - deep_sleep.enter: deep_sleep_instant
this way you can have multiple deep sleeps you want and a instant deep sleep that goes by sleep duration and run duration at 0s  

this way you could have a button instantly sleeping .. and also a timed version.. since  you cant do both  least not when you dont have wifi
