### ISSUE TITLE
Debounce for on_touch trigger

### ISSUE THREAD

**Issue by MorganMLGman** [esphome/feature-requests#2063]
**Describe the problem you have/What new integration you would like**

Hi, It would be beneficial to add debounce filter on on_touch event within touch screen component. I know this is possible with binary_sensor defined as zone on touch screen, but debounce for the whole screen is also sometimes needed. It would prevent registering some fake click with cheaper screens or accidental user touches. 

**Please describe your use case for this integration and alternatives you've tried:**

I tried adding delay after on_touch trigger and then check if touch is still occurring, but I think it isn't possible, because there is no is(touchscreen).state 

**Additional context**

**Comment by Skons** [comment]
Poor mans debounce. The number is there so the max value can be tweaked easily

``` yaml
globals:
  - id: touchscreen_debounce
    type: int
    restore_value: no
    initial_value: '0'

number:
  - id: touchscreen_max_debounce
    platform: template
    name: Touchscreen max debounce
    optimistic: true
    initial_value: 5
    restore_value: true
    min_value: 0
    max_value: 100
    step: 1
    mode: box

touchscreen:
  on_update:
    - script.execute: touchscreen_debounce_script
  on_touch:
    - delay: 150ms
    - if:
        condition:
          lambda: 'return (id(touchscreen_debounce) > id(touchscreen_max_debounce).state);'
        then:
          - script.execute: ...

script:
  - id: touchscreen_debounce_script
    mode: restart
    then:
      - lambda: 'id(touchscreen_debounce) += 1;'
      - delay: 100ms
      - lambda: 'id(touchscreen_debounce) = 0;'
```

This is no complete solution though. Your buttons could still be hit and changed, so if that needs to be prevented

``` yaml
      - slider:
          on_value:
            - if:
                condition:
                  lambda: 'return (id(touchscreen_debounce) > id(touchscreen_max_debounce).state);'
                then:
                    ...
```
