### ISSUE TITLE
Add binary sensor option to generic output switch

### ISSUE THREAD

**Issue by tradeJmark** [esphome/feature-requests#2085]
**Describe the problem you have/What new integration you would like**

To quote from the source code comments about Switch components, "A switch is basically just a combination of a binary sensor (for reporting switch values) and a write_state method that writes a state to the hardware." Since an Output is more or less a wrapper around a `write_state` sort of method, it's fair to say that a switch is essentially a combination of a binary sensor and an output. However, currently there is no switch platform that will combine an existing binary sensor with an output. The closest is the Generic Output Switch, which will use an Output to write its state, but it doesn't take a binary sensor to confirm the state of the switch, it operates in optimistic mode. I propose adding an optional binary sensor argument to the generic output switch that would take it out of optimistic mode and use the sensor to determine state.

**Please describe your use case for this integration and alternatives you've tried:**
You can already implement this as a template switch with boilerplate that goes roughly like this:
```yaml
switch:
  platform: template
  name: "a switch for the example"
  id: my_switch
  optimistic: False
  turn_on_action:
    output.turn_on: an_output
  turn_off_action:
    output.turn_off: an_output
  lambda: return id(a_binary_sensor).state;
```
It's just a bit hacky and unclean. It would be much nicer and more user-friendly to be able to provide the generic output platform with a binary sensor, and then the config would collapse down to this:
```yaml
switch:
  platform: output
  name: "a cleaner switch"
  id: clean_switch
  output: an_output
  status_sensor: a_binary_sensor
```
`status_sensor` as a name is up for debate, maybe it's just as good to name it `binary_sensor`, although I'd probably prefer the former name as being a little more descriptive.

**Additional context**

I'd be perfectly happy to take a crack at implementing this myself, just want to post it here first to make sure people are onboard and to solicit opinions about the name of the argument.
