### ISSUE TITLE
[Sensor Component][Ultrasonic Distance Sensor][xx-SR04x] Add serial mode support

### ISSUE THREAD

**Issue by ESP4Ever** [esphome/feature-requests#2090]
**Describe the problem you have/What new integration you would like**

Widely used ultrasonic range sensors like HC-SR04, JSN-SR04T etc. can work in a serial mode which seems to be more precise  and less resource consuming but this mode is not implemented in ESPHome. Can you please add it?

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by Mafus1** [comment]
Hi, I added support for serial polling mode. I also opened a PR here: https://github.com/esphome/esphome/pull/6023
I'm just waiting for somebody to review it. 
If you have a JSN-SR04T lying around, I would appreciate it if you could test my implementation. Just add it as a custom component.
```yaml
external_components:
  # use jsn_sr04t from my fork in GitHub
  - source:
      type: git
      url: https://github.com/Mafus1/esphome # ESPHome fork
      ref: add-component-sensor-jsnsr04t # branch with new components
    components: [ jsn_sr04t ]

uart:
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600

sensor:
  - platform: "jsn_sr04t"
    name: "Distance"
    update_interval: 1s
```
