### ISSUE TITLE
Before Deep sleep enter send action to ha

### ISSUE THREAD

**Issue by tiimsvk** [esphome/feature-requests#2095]
**Describe the problem you have/What new integration you would like**
Hello.
it is possible to implement a function that would send the function to the home assistant just before starting deep sleep and only then disconnect the wifi.

Something similar to the on_shutdown function, which, however, is not completely reliable, sometimes sends and sometimes does not send a command via wifi.

something along the lines of:
```
if:
   condition
      deep_sleep.before_enter: component_name
then:
   switch.turn_on: ...
```

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**
