### ISSUE TITLE
Add a documentation to devices in the ESPHome add-on for HA

### ISSUE THREAD

**Issue by roberttco** [esphome/feature-requests#2097]
**Describe the problem you have/What new integration you would like**
Each device card in the Add-on UI has links for editing, visiting (if a web server is configured), and look at logs.  It would be handy to be able to add details about the device and access it via the card as well.  Maybe to continue the paradigm of a documentation link that other cards have in the integrations, maybe it would make sense to add this to the action menu, or just a link on the card proper.

**Please describe your use case for this integration and alternatives you've tried:**
Not really any alternatives other than adding comments to the code.  In fact, maybe that is what you would display.  Display the content of a specially delineated block of comments in the code 🤔

Another use case would be to have an auto-populated section that has the devices IP address, device hostname, MAC, etc.  or a direct link to the device information as if you had found it in the Devices & Services list.

**Additional context**
Just wanting to make it easy to differentiate between devices that have similar names and/or get information about the device.

**Comment by nagyrobi** [comment]
I use `project` configuration for this puprose...

```
substitutions:
  device_name: ble-erzekelok-proxy
  device_description: "ESP32-POE-ISO kontroller: BTHome érzékelők, RFBridge rádiós vezérlés"

esphome:
  name: ${device_name}
  comment: "${device_description}"
  project:
    name: esphome,robi.${device_name}
    version: ${device_description}
```

Results in:
![image](https://user-images.githubusercontent.com/1550668/216837973-661dbc7f-3476-4d00-964c-c0625689d3b4.png)
