### ISSUE TITLE
Allow !secret to be used for encryption key

### ISSUE THREAD

**Issue by aceindy** [esphome/feature-requests#2099]
**Describe the problem you have/What new integration you would like**
In the past I used to use HA's secret file to store my passwords for all my devices

Now with the new encryption it seems it is not possible to use a secret anymore.
# Enable Home Assistant API
```yaml
api:
  encryption:
    key: !secret api_encryption
```

results in: 1 of 1 problem
expected a dictionary.

It would be handy to use a key from secrets, so all will use the same ;)

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by randybb** [comment]
You have it wrong:
```yaml
api:
  encryption:
    key: !secret api_encryption
```
