### ISSUE TITLE
Add list of supported wakeup pins for ESP32-S3

### ISSUE THREAD

**Issue by lehovec** [esphome/feature-requests#2111]
**Describe the problem you have/What new integration you would like**

Missing configuraton of allowed wakeup pins for esp32s3. In file `esphome/components/deep_sleep/__init__.py` I see allowed pins for esp32s2 but none for esp32s3 (which has same allowed wakeup pins as s2 variant by [docs](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/system/sleep_modes.html#_CPPv428esp_sleep_enable_ext1_wakeup8uint64_t28esp_sleep_ext1_wakeup_mode_t))

**Please describe your use case for this integration and alternatives you've tried:**

I am trying to add esp32s3 (specifically Lilygo T5 4.7 plus) and I want to wake up device with button on GPIO21 pin. But can't install with config:

```yaml
deep_sleep:
  run_duration: ${run_time}
  sleep_duration: ${sleep_time}
  id: deep_sleep_1
  esp32_ext1_wakeup:
    pins: GPIO21
    mode: ALL_LOW
```
because it cause `Only pins 0, 2, 4, 12, 13, 14, 15, 25, 26, 27, 32, 33, 34, 35, 36, 37, 38, 39 support wakeup` warning (it thinks that it's classic esp32 board). 

**Additional context**
