### ISSUE TITLE
Expose Deep sleep wakeup cause

### ISSUE THREAD

**Issue by Lumpusz** [esphome/feature-requests#2113]
Esp32 can tell what was the cause of deep sleep wakeup. This is being used already internally to figure out different timeouts based on the cause, but it would be nice to expose this to an automation in on_boot.
Example use case: battery powered rain gauge, when it is woken up by GPIO because the bucket was tripping, capture rainfall data, when it is waken up by timeout, just measure temperature, wind speed, direction etc.

**Comment by jul-fls** [comment]
Hi, is there any new informations about this feature progress ?
In my case i have an esp32 hooked up to 2 reed switches to sense my mailbox (1 reed switch for the mail slot and another reed switch for the package door) and it's continuously in deep sleep but when woken up the door or mail slot may have already been closed again so it doesn't detect why it has been woken up i use this configuration 
```yml
deep_sleep:
  id: deep_sleep_1
  run_duration: 30s
  sleep_duration: 86400s
  wakeup_pin_mode: INVERT_WAKEUP
  esp32_ext1_wakeup: 
    mode: ANY_HIGH
    pins: 
      - GPIO0
      - GPIO4
```
and i'm looking for a solution to tell to home assistant which pin has been triggered so i can detect if it's because of the mail slot or the package door, does someone have an idea how to do this ?
Thank you very much for looking into this.
Best regards.

**Comment by meanmrgreen** [comment]
> 

I have this same problem, and a mailbox that needs this :)

I just tested a possible workaround.

If i create a binary template sensor 
```- platform: template
name: "${device_name} Pin wakeup"
id: pinwakeup
````
    
Then create a script that runs on boot that checks the state of my reed sensor as soon as the sensors are setup but before wifi and other stuff is setup.
````
  on_boot:
    priority: 600
    then: 
      - script.execute: pinwakeup
````

   ````
  - id: pinwakeup
    then:
    - if:
        condition:
         - binary_sensor.is_on: reedswitch
        then:
         - binary_sensor.template.publish:
             id: pinwakeup
             state: ON
        else:
         - binary_sensor.template.publish:
            id: pinwakeup
            state: OFF
  ````
            
This seems to be working pretty good, unless im really really fast opening and closing the reed switch, im talking maybe 0.1 seconds or something.  Then when the esp wakes up, connects to to homeassistant it will then send the on state from the reed sensor that woke it up.

Worked great with any opening that was around like half a second/second. Not perfect but still better than needing it to be open for 10-20s to register the state.
