### ISSUE TITLE
Repurpose ESPHome devices in Home Assistant

### ISSUE THREAD

**Issue by anoblet** [esphome/feature-requests#2114]
**Describe the problem you have/What new integration you would like**
The ability to repurpose ESPHome devices within Home Assistant so that they retain their data.

**Please describe your use case for this integration and alternatives you've tried:**
I have a few Athom smart plugs that are able to monitor energy consumption. I often repurpose them, especially during summer and winter months for air conditioners and space heaters. If I upload a new configuration to a smart plug, it gets registered in Home Assistant as a new device under the same integration or name. In order to get energy reporting working for the new device, I have to remove the integration for the old device, losing historical data, and register the new device. It would be helpful if both devices could exist, even if one was considered offline thus retaining historical data.

**Additional context**
I'm not sure if this is an ESPHome issue or a Home Assistant issue.

**Comment by nagyrobi** [comment]
When you repurpose, what do you change in the config?

**Comment by anoblet** [comment]
Sample config:

```
substitutions:
  friendly_name: "Bedroom Heater"
  name: bedroom-heater
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
->
```
substitutions:
  friendly_name: "Bedroom Air Conditioner"
  name: bedroom-air-conditioner
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

**Comment by nagyrobi** [comment]
To achieve the behavior you want, you should try to use different IP addresses for the device in their different scopes, so they become uniquely differentiated by HA.

Something like this added to your code above, and change `device_ip` too:

```yaml
substitutions:
  device_ip: 192.168.1.11

wifi:
  manual_ip:
    static_ip: ${device_ip}
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  use_address: ${device_ip}
```
