### ISSUE TITLE
ESP32 Camera image rotation (0, 90, 180, 270)

### ISSUE THREAD

**Issue by anverx** [esphome/feature-requests#2142]
**Describe the problem you have/What new integration you would like**

Let the esp rotate camera images before serving them. I've designed a case for the camera (link below)  which allows physical rotation of the camera.  I can make the case much, much smaller if the camera image can be rotated in software.  Maybe the camera module can be configured to rotate the image?  
Only 0, 90, 180 and 270 rotations are useful.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

link to the enclosure design: https://www.printables.com/model/176992-housing-for-esp32-cam

**Comment by fonske** [comment]
With vertical_flip and horizontal_mirror you can adjust these views.

```
# ESP32-CAM ESP-EYE
esp32_camera:
  external_clock:
    pin: GPIO4
    frequency: 20MHz
  i2c_pins:
    sda: GPIO18
    scl: GPIO23
  data_pins: [GPIO34, GPIO13, GPIO14, GPIO35, GPIO39, GPIO38, GPIO37, GPIO36]
  vsync_pin: GPIO5
  href_pin: GPIO27
  pixel_clock_pin: GPIO25

# Camera settings
  resolution: 640x480
  jpeg_quality: 10
  vertical_flip: false
  horizontal_mirror: false
  special_effect: none
  contrast: 0
  brightness: 0
  saturation: 0
  agc_mode: AUTO
  aec2: false
  ae_level: 0
  aec_value: 300
  aec_mode: AUTO
  agc_value: 0
  agc_gain_ceiling: 2X
  wb_mode: AUTO
  test_pattern: false
  max_framerate: 30 fps
  idle_framerate: 1.0 fps
#  max_framerate: 10.0
#  idle_framerate: 0.1

  name: Prusa camera

# Flashlight
output:
  - platform: gpio
    pin: GPIO21
    id: gpio_21
  - platform: gpio
    pin: GPIO22
    id: gpio_22
```
