### ISSUE TITLE
Request for rest_command for uploading pvoutput

### ISSUE THREAD

**Issue by fonske** [esphome/feature-requests#2150]
**Describe the problem you have/What new integration you would like**

Support for function:  rest_command 
Like in home assistant

**Please describe your use case for this integration and alternatives you've tried:**

Upload to pvoutput with automation (5 minutes) en rest_command
In home assistant it works.

**Additional context**

**Example:**
```
automation:
  - id: 4f863af550147e2b3170
    alias: update pvoutput
    trigger:
      platform: time_pattern
      minutes: /5
    condition:
      and:
        - condition: numeric_state
          entity_id: sensor.zeversolar_sensor_current_power
          above: 10
    action:
      service: rest_command.update_pvoutput
      data: {}
    mode: single
```
```
rest_command:
  update_pvoutput:
    url: "https://pvoutput.org/service/r2/addstatus.jsp"
    method: post
    headers:
      X-Pvoutput-Apikey: !secret pvoutput_api_key
      X-Pvoutput-SystemId: !secret pvoutput_system_id_1
      Content-Type: 'application/x-www-form-urlencoded'
    payload: >-
      d={{now().strftime("%Y%m%d")}}                                          {#- date -#}
      &t={{now().strftime("%H:%M")}}                                          {#- time -#}
      &v1={{states('sensor.zeversolar_sensor_energy_today')|float(0)*1000 |round(0)}}        {#- Energy generation (Wh) -#}
      &v2={{states('sensor.zeversolar_sensor_current_power')|float(0) |round(0)}}            {#- Power generation (W) -#}
      &c1=1                                                                   {#- cumulative mode -#}
```
