### ISSUE TITLE
Support removing components defined in packages

### ISSUE THREAD

**Issue by LordMike** [esphome/feature-requests#2163]
**Describe the problem you have/What new integration you would like**
We can extend components defined in packages like this:

```yaml
packages:
  athom.rgbct-light: github://athom-tech/athom-configs/athom-rgbct-light.yaml

button:
  - id: !extend Reset
    name: Overriden name
```

But I'd like to use a package, _and_ be able to _remove_ a component. I imagine something like this:

```
button:
  - id: !remove Reset
```

**Please describe your use case for this integration and alternatives you've tried:**
I'd like to use the packages defined by the vendor of my device, in this case Athom Tech. But sometimes they define odd components that I'd like to not have, but I can't remove them. 

A workaround is to disable or hide the component. In this case, with button, I can mark it as internal. I think the best solution would be to completely remove it from the configuration, which potentially could mean that "button" wasn't even compiled in to the final firmware. At the minimum, it's not managed in memory.

```yaml
button:
  - id: !extend Reset
    internal: true
```

**Additional context**
N/A
