### ISSUE TITLE
Sending DTMF codes after answering of a call. SIM800L

### ISSUE THREAD

**Issue by runestone74** [esphome/feature-requests#2169]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by runestone74** [comment]
Made a custom template that works in the meantime, maybe someone else will have use for that :)

```
  - platform: template
    name: "SIM800_PRESS_5"
    turn_on_action:
      - uart.write: "AT+CLDTMF=2,\"5\"\r\n"
    restore_mode: ALWAYS_OFF
```
