### ISSUE TITLE
New internal ESPHome Trend Sensor requested

### ISSUE THREAD

**Issue by jazzmonger** [esphome/feature-requests#2185]
**Describe the problem you have/What new integration you would like**

Create a new "Trend sensor" in ESPHome based on an internal sensor value.

**Please describe your use case for this integration and alternatives you've tried:**

Creating an ESPHome template sensor based on a home assistant trend sensor works great as long as home assistant is available. 
**Additional context**

Only works if home assistant is available. My use case must work without home assistant being available,

basically implement the same functionality as exists in home assistant:
```
binary_sensor:
  - platform: trend
    sensors:
      house_stove_pipe_temp_falling:
        entity_id: sensor.house_uart_pipe_temp
        sample_duration: 10
        max_samples: 10
        min_gradient: -0.2 #5 degrees / 10s
        device_class: cold
    
      house_stove_pipe_temp_rising:
        entity_id: sensor.house_uart_pipe_temp
        sample_duration: 10
        max_samples: 10
        min_gradient: 0.2 #5 degrees / 10s
        device_class: heat 
```
