### ISSUE TITLE
Script Triggers

### ISSUE THREAD

**Issue by clinta** [esphome/feature-requests#2195]
**Describe the problem you have/What new integration you would like**

I'd like to be able to define a trigger for any script. Any trigger that is supported by a component should be able to be referenced.

So this:
```yaml
light:
  - platform: cwww
    id: my_light
    [...]
    on_state:
      - script.execute: my_script
```

Could optionally be written like this:

```yaml
script:
  - id: my_script
    triggers:
      - light.on_state:
          id: my_light
    then:
      [...]
```

**Please describe your use case for this integration and alternatives you've tried:**

I like to make my configs as modular and reusable as possible, making frequent use of packages. So I have one package that defines the pins, and settings for a light. Then I have another package that does automatons based on the light state. Using substitutions this automations package can be applied to multiple lights with different IDs. This is difficult because the automatons need to be triggered by `on_state` in the light configuration. So the light package is no longer independent cause it's config references a script in the automatons package.

I've tried setting a default noop script in the light package, referenced with a substitution. Then when the main config combines the packages, it substitutes the `on_light_state` variable with the automation script. This is okay, but it's not the cleanest. And I need a second noop script and variables like `on_light_state_2` to be able to trigger multiple scripts from the same light event.

**Additional context**
