### ISSUE TITLE
Add Support for the PCAL6416A GPIO Expander (Inkplate 10)

### ISSUE THREAD

**Issue by AlexanderGlogger** [esphome/feature-requests#2204]
**Describe the problem you have/What new integration you would like**

Inkplate 10 e-paper display, switched with version 1.3, to use a different GPIO expander (PCAL6416A) compared to the older version (MCP23017). The PCAL6416A GPIO expander is currently not supported by esphome.

**Please describe your use case for this integration and alternatives you've tried:**

I would like to use the Inkplate 10 with esphome, but it's not woking because of the changed GPIO expander.

Yaml file i used:

```
esphome:
  name: inkplate

esp32:
  board: esp-wrover-kit

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}

captive_portal:

ota:

api:


i2c:

mcp23017:
  - id: mcp23017_hub
    address: 0x20

display:
- platform: inkplate6
  id: inkplate_display
  model: inkplate_10
  update_interval: 60s

  ckv_pin: 32
  sph_pin: 33
  gmod_pin:
    mcp23xxx: mcp23017_hub
    number: 1
  gpio0_enable_pin:
    mcp23xxx: mcp23017_hub
    number: 8
  oe_pin:
    mcp23xxx: mcp23017_hub
    number: 0
  spv_pin:
    mcp23xxx: mcp23017_hub
    number: 2
  powerup_pin:
    mcp23xxx: mcp23017_hub
    number: 4
  wakeup_pin:
    mcp23xxx: mcp23017_hub
    number: 3
  vcom_pin:
    mcp23xxx: mcp23017_hub
    number: 5


  lambda: |-
    it.fill(COLOR_ON);
    it.line(0, 0, 1200, 825, COLOR_OFF);
    it.line(1200, 0, 0, 825, COLOR_OFF);
```

Error i get in the logs:

```
rst:0x1 (POWERON_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
[I][logger:258]: Log initialized
[C][ota:469]: There have been 0 suspected unsuccessful boot attempts.
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[I][i2c.arduino:175]: Performing I2C bus recovery
[C][mcp23017:010]: Setting up MCP23017...
[E][component:113]: Component mcp23xxx_base was marked as failed.
[C][wifi:037]: Setting up WiFi...
[C][wifi:038]:   Local MAC: C0:49:EF:2F:A2:F0
[D][wifi:386]: Starting scan...
[W][inkplate:265]: Power supply not detected
[W][inkplate:265]: Power supply not detected
[W][inkplate:265]: Power supply not detected
[W][inkplate:265]: Power supply not detected
[W][inkplate:265]: Power supply not detected
[W][inkplate:265]: Power supply not detected
[W][inkplate:265]: Power supply not detected
[W][inkplate:265]: Power supply not detected
[W][inkplate:265]: Power supply not detected
E (11780) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (11780) task_wdt:  - loopTask (CPU 1)
E (11780) task_wdt: Tasks currently running:
E (11780) task_wdt: CPU 0: IDLE
E (11780) task_wdt: CPU 1: loopTask
E (11780) task_wdt: Aborting.

abort() was called at PC 0x400f46c4 on core 0

Backtrace:0x40083d55:0x3ffbea5c |<-CORRUPTED

ELF file SHA256: 0000000000000000

Rebooting...
```

**Additional context**

The Ardino library for the PCAL6416A GPIO expander provided by soldered
[https://github.com/SolderedElectronics/Soldered-PCAL6416A-IO-Expander-Arduino-Library](url)

When it helps, I am happy to help with testing.
