### ISSUE TITLE
Use RGB led as status led

### ISSUE THREAD

**Issue by exico91** [esphome/feature-requests#2230]
**Describe the problem you have/What new integration you would like**

Some ESP boards have a RGB led instead of a "dumb led". Its not possible to use a RGB led as a status led at the moment. It would be nice if we can set a RGB led as status led, maybe with a fixed color.

**Please describe your use case for this integration and alternatives you've tried:**

Some boards that have a RGB light instead of a normal led are: (not exaustive, these are the ones that i know of) Wemos S3 Mini, S3, S3 PRO, C3 mini v2, C3 pico.
The only option now is to wire an external led on those boards if you want a status led

**Additional context**

I'm repeating myself but it would be nice to have a rgb light as a functional status led, even with a fixed color.
Would that be feasible?

**Comment by kaechele** [comment]
Would #1603 do what you want?

**Comment by ssieb** [comment]
You can use https://esphome.io/components/light/status_led.html with a template output that sets the state of the RGB LED.

**Comment by exico91** [comment]
> Would #1603 do what you want?

Not really, from what I understand you can use the rgb light for different events. What i want is the same behavior as:
status_led:
  pin: somepin
IDK, maybe choose a color/intensity and use that for the status_led

> You can use https://esphome.io/components/light/status_led.html with a template output that sets the state of the RGB LED.

Can you elaborate please?

**Comment by ssieb** [comment]
```yaml
output:
  - platform: template
    id: status_output
    type: binary
    write_action:
      - if:
          condition:
             lambda: return state > 0;
          then:
            - light.turn_on:
                ... red
          else:
            - light.turn_on:
                ... green
```

**Comment by exico91** [comment]
Hello,

sorry for the wait, I just acquired some wemos C3 mini v2 with the RGB and I was testing them out.

From what i understand the complete code will be something like this:

`light:
  - platform: status_led
    name: "status led"
    output: statusoutput
  - platform: neopixelbus
    variant: WS2812
    pin: 7
    num_leds: 1
    name: "Status LED RGB"
    id: statusledlight
    icon: "mdi:led-outline"

output:
  - platform: template
    id: statusoutput
    type: binary
    write_action:
      - if:
          condition:
             lambda: return state > 0;
          then:
            - light.turn_on: 
                id: statusledlight
                red: 1.0
                green: 0.0
                blue: 0.0
                brightness: 30%
          else:
            - light.turn_on: 
                id: statusledlight
                green: 1.0
                red: 0.0
                blue: 0.0
                brightness: 30%`
I added some adjustments, it was too bright otherwise.

The light stay on a solid green. There is a way to simulate an error? I would like it to change color in two occasions: 
1. When the wifi connection is lost
2. Since i use these C3 mini as bluetooth proxy i would like it to blink blue when there is a bluetooth transmission, would that be possible?

**Comment by jhenkens** [comment]
On an `lolin_s3_mini`, I used the following to calm down the log, and actually make it strobe. Key differences - `50ms` transition length, and adding conditional setting via a proxy template switch.

```

light:
  - platform: status_led
    id: status_light
    output: status_output
  - platform: neopixelbus
    id: esp32s3_rgb_led
    name: Status RGB LED
    type: RGB
    variant: 800KBPS
    pin: 47
    num_leds: 1
    icon: mdi:led-outline
    entity_category: config
    restore_mode: ALWAYS_OFF
    method:
      type: esp32_rmt
      channel: 0          

switch:
  - platform: template
    id: status_led_switch
    # name: "Status LED Switch"
    optimistic: true
    on_turn_on:
      - light.turn_on: 
          id: esp32s3_rgb_led
          red: 100%
          green: 0%
          blue: 0%
          brightness: 30%
          transition_length: 50ms
    on_turn_off:
      - light.turn_off: 
          id: esp32s3_rgb_led
          transition_length: 50ms

output:
  - platform: template
    id: status_output
    type: binary
    write_action:
      - if:
          condition:
             lambda: return state > 0;
          then:
            - if:
                condition:
                  switch.is_off: status_led_switch
                then:
                  switch.turn_on: status_led_switch
          else:
            - if:
                condition:
                  switch.is_on: status_led_switch
                then:
                  switch.turn_off: status_led_switch
```

I still think enabling arbitrary backing lights, rather than just an output, would be good.

**Comment by strzegus** [comment]
Has anyone tried to control the built-in RGB LED on the ESP32-S3-DevKitC-1 board in ESP HOME?

**Comment by randybb** [comment]
@strzegus There are many clones of the original board https://docs.espressif.com/projects/esp-idf/en/stable/esp32s3/hw-reference/esp32s3/user-guide-devkitc-1.html - on the original board is the addressable RGB led connected to GPIO38, so basically you can use the previous config, just change `pin: 47` to `pin: 38`.  Based on it's schematics there is SK6812.

**Comment by nielsnl68** [comment]
I create a component  based on the current status components that allows you to create scripts for every status including your own. https://github.com/esphome/esphome/pull/5814 
Could that resolve your question?

**Comment by MattWestb** [comment]
Also some Minis / Zero board is not having power LED so shall being good possible configuring permanent color for power (red or orange but red is best and blue for hart beet > Blue / Magenta pulsing).
Minimum shall being taking away the block if the function status can only being used with monochrome lights then its only mapping it to one color function in the pixel LED.

**Comment by strzegus** [comment]
udało się kod wygląda tak

light:

# LED RGB NA ESP32 POKAZUJĄCE AKTUALNĄ PRACĘ URZĄDZENIA
  - platform: esp32_rmt_led_strip
    id: led_ww
    rgb_order: GRB
    pin: 48
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    name: "on board light"

binary_sensor:

  - platform: template
    name: "GTK" 
    id: GTK
    internal: True
    lambda: |-
      if (id(PC_W).state <= 100 && id(PC_W).state > 40 ) {
        // PC is on.
        return true;
      } else {
        // PC is off.
        return false;
      }
    on_press:
      then:
        - light.turn_on:
           id: led_ww
           green: 0% 
           red:  100% 
           blue: 0% 
           brightness: 30%
           effect: Fast Pulse

  - platform: template
    name: "PC_czuwanie" 
    id: PC_czuwanie
    internal: True
    lambda: |-
      if (id(PC_W).state <= 40 && id(PC_W).state >= 7 ) {
        // PC is on.
        return true;
      } else {
        // PC is off.
        return false;
      }
    on_press:
      then:
        - light.turn_on:
           id: led_ww
           green: 100% 
           red:  0% 
           blue: 0% 
           brightness: 30%
 
  - platform: template
    name: "PC_eco" 
    id: PC_eco
    internal: True
    lambda: |-
      if (id(PC_W).state <= 600 && id(PC_W).state > 100 ) {
        // PC is on.
        return true;
      } else {
        // PC is off.
        return false;
      }
    on_press:
      then:
        - light.turn_on:
           id: led_ww
           green: 100% 
           red:  100% 
           blue: 0% 
           brightness: 30%

  - platform: template
    name: "PC_normal" 
    id: PC_normal
    internal: True
    lambda: |-
      if (id(PC_W).state <= 1000 && id(PC_W).state > 600 ) {
        // PC is on.
        return true;
      } else {
        // PC is off.
        return false;
      }
    on_press:
      then:
        - light.turn_on:
           id: led_ww
           green: 50% 
           red:  100% 
           blue: 0% 
           brightness: 30%

  - platform: template
    name: "PC_turbo" 
    id: PC_turbo
    internal: True
    lambda: |-
      if (id(PC_W).state > 1000) {
        // PC is on.
        return true;
      } else {
        // PC is off.
        return false;
      }
    on_press:
      then:
        - light.turn_on:
           id: led_ww
           green: 0% 
           red:  100% 
           blue: 0% 
           brightness: 30%

  - platform: template
    name: "DEF" 
    id: DEF
    internal: True
    lambda: |-
      if (id(GPCWU).state < 20) {
        // PC is on.
        return true;
      } else {
        // PC is off.
        return false;
      }
    on_press:
      then:
        - light.turn_on:
           id: led_ww
           green: 0% 
           red:  0% 
           blue: 100% 
           brightness: 30%
           effect: pulse

**Comment by Flo-R1der** [comment]
Hey, I was also working on the status LED and created a package. Maybe it helps you too guys:  
**[ESPHome_RGB-Status-LED_Package](https://github.com/Flo-R1der/ESPHome_RGB-Status-LED_Package)**

### 💡 LED Colors and States

#### System States

The **LED system status** follows a strict top-down priority. The highest matching state always wins.
If a condition is no longer fulfilled, the LED falls back to the previous applicable state.

| Priority | Color + Effect            | System State             | Notes                                    |
| -------- | ------------------------- | ------------------------ | ---------------------------------------- |
|   1      | **Red**<br>fast pulsing   | Booting / initialization | Shown before WiFi stack is ready         |
|   2      | **Yellow**<br>static      | Boot completed           | Waiting for WiFi / network issue?        |
|   3      | **White**<br>static       | WiFi connected           | network OK, Home Assistant not connected |
|   4      | **Green**<br>static       | Home Assistant connected | FULLY STARTED - Normal operating mode    |

#### Custom States

Additionally there are **LED working states** provided, which can be triggered from your main device configuration.
They are meant to signals states separate from the main priority logic.
They temporarily override the LED as long as the script is active, similar to the beacon state.

| Script ID              | Color + Effect             | Notes (Examples)                                                       |
| ---------------------- | -------------------------- | ---------------------------------------------------------------------- |
| `led_working_status_1` | **Blue**<br>slow pulsing   | Example: device performing a background task; BT-beacon detected; etc. |
| `led_working_status_2` | **Purple**<br>slow pulsing | Example: special output is turned on; long-running I²C read; etc.      |
| `led_working_status_*` | _add more if you like_     |                                                                        |

To set and reset the working light you can call the following scripts:
- `- script.execute: led_working_status_1` (_or any other number_)
- `- script.execute: led_system_status` (_to reset the LED to the system-status_)

### 🛠️ Set Up

Add the package to your device configuration:

```yaml
packages:
  rgb_status_led: 
    url: https://github.com/Flo-R1der/ESPHome_RGB-Status-LED_Package
    file: status_led_package.yaml
```

Make sure your project defines the required GTB LED light with the **ID `system_status_led`**. The following `light` configuration has proven to work on a [LOLIN C3 Mini](https://www.espboards.dev/esp32/lolin-c3-mini/) (`board: lolin_c3_mini`):

```yaml
light:
  - platform: esp32_rmt_led_strip
    id: system_status_led             # DO NOT CHANGE
    pin: GPIO7                        # check your board
    rgb_order: GRB                    # check your board
    num_leds: 1
    chipset: ws2812                   # check your board
    name: "onboard LED"
    disabled_by_default: true
    default_transition_length: 200ms
    icon: mdi:led-outline
    restore_mode: ALWAYS_OFF
    effects:
      - pulse:
          name: "Slow Pulse"          # REQUIRED
          update_interval: 2s         # can be adjusted
      - pulse:
          name: "Fast Pulse"          # REQUIRED
          update_interval: 500ms      # can be adjusted
```

> [!NOTE]  
> The package does **not** depend on any specific LED chipset or ESP32 variant.  
> If you prefer another LED type (NeopixelBus, FastLED, CWWW RGB LED), simply keep the ID identical.
