### ISSUE TITLE
Add additional microphones to voice_assistant

### ISSUE THREAD

**Issue by ha88rgc** [esphome/feature-requests#2258]
**Describe the problem you have/What new integration you would like**
I'm trying to use an i2s microphone array (6+1) https://www.dfrobot.com/product-1976.html - one mono, and three stereo microphones with an ESP32. So far, `voice_assistant` only allows for the creation of one microphone instance. I can currently successfully use either the mono mic or one of the stereo mics. I'd be awesome to be able to declare 1+ microphones for `voice_assistant` as this would allow the use of a real 360 degree microphone array, which is quite important for a voice assistant and is used by Google and Amazon alike in their products I believe.

```
microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_din_pin: ${i2sDin}
    adc_type: external
    pdm: false
    channel: right
  
  - platform: i2s_audio
    id: echo_microphone2
    i2s_din_pin: ${i2sDin2}
    adc_type: external
    pdm: false
    channel: right

...

voice_assistant:
  microphone: echo_microphone2

```

**Please describe your use case for this integration and alternatives you've tried:**
The use case is **Homeassistant's Year of Voice!!** The DF Robot mic array mentioned above fits the bill perfectly with 6+1 mics and 12 rgb leds for visual feedback. The only thing missing is the `wake word` and more than one microphone!

**Additional context**
