### ISSUE TITLE
Triggers for wifi/api connect/disconnect

### ISSUE THREAD

**Issue by fdcastel** [esphome/feature-requests#2272]
**Describe the problem you have/What new integration you would like**

In many cases we need to execute code when Wi-Fi connection (or HA api) is lost / restored. 

Currently there are no triggers for these events:

- `wifi.on_connect`
- `wifi.on_disconnect`
- `api.on_connect`
- `api.on_disconnect`

A recent PR (#746) added something similar for MQTT only.

**Please describe your use case for this integration and alternatives you've tried:**

Many examples found on internet suggest a workaround like:

```yaml
interval:
  - interval: 1s
    then:
      - if:
          condition:
            - not: wifi.connected
          then:
            - (...)
      - if:
          condition:
            - wifi.connected
          then:
            - (...)
```

While the above code works, polling is not the best way to solve this problem. A trigger could (presumably) reduce cpu usage.

**Additional context**

The above workaround has also two additional problems:

- The user is left to implement its own way to detect a _change_ in the state (otherwise the code will repeatedly run each 1s)
- The code is a bit verbose

All this could be solved with appropriate triggers for each event.

**Comment by uddinkayyum** [comment]
I agree it's absolutely need when esphome running critical appliances (eg. motor_pump, heater, washing_machine etc) but also, It's need improvment with additional parameter so they can be more useful, like event instead of conditions.
additional parameter:
1. which host is disconnected/connected.
2. heatbeat timeout, so event not fire if event restore to previous value.

```
api:
   ...
   on_disconnect:
   ip: 192.168.1.101
   heartbeat: 15s
   then:
      - script.execute: pump_failsafe
```
