### ISSUE TITLE
Support for MAX17048 used in many Adafruit Feathers for I2C battery monitoring

### ISSUE THREAD

**Issue by circuit69** [esphome/feature-requests#2277]
**Describe the problem you have/What new integration you would like**

Adafruit is using a MAX17048 to monitor the battery status, this uses I2C, a component that supports this chip would be a huge help using these popular dev boards.

**Please describe your use case for this integration and alternatives you've tried:**

The MAX17048 chip is becoming more common on Adafruit boards, showing voltage and battery percent.

**Additional context**

What is the process for creating something like this, is there a guide or tutorial?

**Comment by max246** [comment]
Could have a look in the next coming weeks.

**Comment by JingleheimerSE** [comment]
Stumbled on this which might be helpful: [https://community.home-assistant.io/t/adafruit-max17048-lipo-battery-gauge-with-esphome/524005/6](https://community.home-assistant.io/t/adafruit-max17048-lipo-battery-gauge-with-esphome/524005/6)

**Comment by lboue** [comment]
I am currently working on a external component that supports this MAX17048 chip.

**Comment by ilikecake** [comment]
What is the status of this? I recently created a component for the [LC709203F](https://github.com/esphome/esphome/pull/8037) (the other battery monitor that Adafruit uses). I was planning to make a similar component for this when I needed it, but if you already have it done, that would save me some time. :)

**Comment by JL00001** [comment]
> What is the status of this? I recently created a component for the [LC709203F](https://github.com/esphome/esphome/pull/8037) (the other battery monitor that Adafruit uses). I was planning to make a similar component for this when I needed it, but if you already have it done, that would save me some time. :)

There seems to be one already on github.

https://github.com/Option-Zero/esphome-components/tree/main/components/max17048

sample YAML.
```
external_components:
  - source: github://Option-Zero/esphome-components
    components: [max17048]
sensor:
  - platform: max17048
    battery_voltage:
      name: Battery voltage
      id: batt_v
    battery_level:
      # This uses the SOC (state of charge) value from the MAX17048.
      # Take it with a grain of salt.

      # There is a sophisticated algorithm that takes into account
      # the battery's voltage, current, temperature, and more.
      # However, don't expect it to be too accurate without battery-specific calibration.
      # As the data sheet says (emphasis mine), the chip has 
      # "a preloaded ROM model that performs well for *some* batteries."
      name: Battery level
      id: batt_pct
    rate:
      name: Battery discharge rate
      id: batt_discharge_rate
```

I am not the creator, nor the supporter, nor is this officially maintained by the ESP Github; I am just you a few weeks ahead, but this could be a starting off point for the official MAX17048 component.

The data sheet [LINK](https://www.analog.com/media/en/technical-documentation/data-sheets/max17048-max17049.pdf) describes a config register for different battery chemistry as well as several other features that could be useful.
