### ISSUE TITLE
not support board   bpi_leaf_s3

### ISSUE THREAD

**Issue by kylinfedora** [esphome/feature-requests#2288]
**Describe the problem you have/What new integration you would like**

the platformio/espressif32 is support bpi_leaf_s3, https://registry.platformio.org/platforms/platformio/espressif32/boards?p=1
but esphome is not support it ,it is say "This board is unknown, please set the variant manually."
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by jasonschroeder** [comment]
this is working for me:

```yaml


esp32:
  board: bpi_leaf_s3
  framework:
    type: esp-idf
    
```
