### ISSUE TITLE
Support for Switch with Time Bound

### ISSUE THREAD

**Issue by aura6174** [esphome/feature-requests#2297]
**Describe the problem you have/What new integration you would like**

There are switch which is controlling heavy appliance ex. (motor pump, heater, gyser) but some time they are accidentally turn on by kids or something wrong happen which trigger turn on. On day time user can response to turn off but what happen when this trigger at night time 10:00PM to 7:00AM this can lead to resource waste ex. (water, electricity).
**Please describe your use case for this integration and alternatives you've tried:**

This happen already with me a lot of time, accidentally touch on companion app, binary sensor linked to switch.
This was a force mode switch never turn on that range until bypass pressed.
**Additional context**

```
- platform: gpio
    name: "Motor Pump"
    pin: D5
    id: relay1
    icon: mdi:engine
    time_bound:
      after: 10:00PM
      before: 7:00AM
```
with additional bypass switch in companion app so manually control if switch need to turn in that time.
