### ISSUE TITLE
Range filter for sensor component

### ISSUE THREAD

**Issue by ghost** [esphome/feature-requests#2298]
**Describe the problem you have/What new integration you would like**

Simply ignore value if sensor publish out of range value.
**Please describe your use case for this integration and alternatives you've tried:**

```
- platform: sensor
  name: "flow meter"
  ...
   filters:
    - lambda: |-
          if (x > -20 && x < 60) {
            return x;
          } else {
            return 0;
          }
```
**Additional context**

```
   filters:
      - range:
           - above: -20
           - below: 60
```
