### ISSUE TITLE
Unique id for esphome component show in Homeassistant

### ISSUE THREAD

**Issue by aura6174** [esphome/feature-requests#2299]
**Describe the problem you have/What new integration you would like**

So, everything work fine until meshed with component name (rename) now this new name publish to Home assistant now every automation linked to previous name, need reconfigure this was a pain if there are 10's of automation linked to single esphome component. Meanwhile everything break because of just a rename, this can be resolve by unique id coz esphome is part of homeassistant.
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

homeassistant automation
```
trigger:
  - platform: device
    type: turned_on
    unique_id: 1c112172b374ee24fe01f5d338946657
```
esphome config
```
fan: 
  - platform: binary
    name: Fan
    output: relay2
    id: fan1
    unique_id: 1c112172b374ee24fe01f5d338946657
```
