### ISSUE TITLE
Suspend update for PollingComponent

### ISSUE THREAD

**Issue by snechiporenko** [esphome/feature-requests#2301]
**Describe the problem you have/What new integration you would like**

When a device is playing music or voice and has a configured screen, there is a temporary pause in the sound playback when the screen refreshes. It appears as a quarter-second click. The following entries can be seen in the logs:
```
[12:06:00][V][component:204]: Component st7789v.display took a long time for an operation (0.37 s).
[12:06:00][V][component:205]: Components should block for at most 20-30ms.
```

**Please describe your use case for this integration and alternatives you've tried:**

I suggest adding a component with the ability to temporarily pause its operation (refresh). It doesn't necessarily have to be done for the screen; it would be beneficial to have this feature for all components. Here's an example of implementation:
```yaml
then:
  - component.suspend: main_display
  - delay: 2s
  - component.update: main_display
  - delay: 2s
  - component.resume: main_display
```
It is important to allow for manual updates of a component even when it is in a suspended state.

**Additional context**

Use voice_assistant: with display:
