### ISSUE TITLE
add variable time format for UPTIME sensor

### ISSUE THREAD

**Issue by theniz** [esphome/feature-requests#231]
**Describe the problem you have/What new integration you would like**

for now, uptime sensor supports only seconds. 
with the seconds, I can not calculate how long it works instantly.
**Please describe your use case for this integration and alternatives you've tried:**

in HA, I used to converte minutes to time format like 1day, 22hours, 14minutes.
my yaml code is like this,
HA Uptime to Date format - HA Online
    ha_online:
      friendly_name: "HA Online"
      unit_of_measurement: "time"
      value_template: >-
        {% set time = (((states.sensor.ha_uptime.state) | round ) * 60 | int) | int %}
        {% set minutes = ((time % 3600) / 60) | int %}
        {% set hours = ((time % 86400) / 3600) | int %}
        {% set days = (time / 86400) | int %}
        {%- if time < 60 -%}
          Less than a minute
        {%- else -%}
          {%- if days > 0 -%}
            {{ days }}d
          {%- endif -%}
          {%- if hours > 0 -%}
            {%- if days > 0 -%}
              {{ ' ' }}
            {%- endif -%}
            {{ hours }}h
          {%- endif -%}
          {%- if minutes > 0 -%}
            {%- if days > 0 or hours > 0 -%}
              {{ ' ' }}
            {%- endif -%}
            {{ minutes }}m
          {%- endif -%}
        {%- endif -%}

It worked very smooth. 
but when I applied same code to esphome, it didn't work. in my understanding i needed to change some codes for esphome. i am noob for c++, i can not.

**Additional context**

i am very appreciated that uptime sensor provide data as time format which couldl be easily understood.
thank you.

**Comment by pavolholes** [comment]
I have more simple sensor to do this in Home Assistant, you can try to use it in a meantime:

**configuration.yaml:**
```yaml
- platform: template
  sensors:
    workroom_uptime:
      icon_template: mdi:clock
      device_class: timestamp
      value_template: "{{ (as_timestamp(now())  - (states('sensor.workroom_uptime')) | float) | timestamp_custom('%Y-%m-%dT%H:%M:%S+01:00',True) }}"
```
**Result:**
![image](https://user-images.githubusercontent.com/35877348/58357535-804b3380-7e7b-11e9-9f3c-78b8e4bc8e6b.png)
No credits to me, I found it somewhere at Discord :)
