### ISSUE TITLE
Technoline WS2300-15 Wind Speed/Direction Sensor

### ISSUE THREAD

**Issue by drobishman** [esphome/feature-requests#2314]
**Describe the problem you have/What new integration you would like**
I noticed that ESPHome only supports the TX20/TX23 anemometer, which are very hard to find. I have a Tehnoline WS2300-15 and unfortunately I cannot use it. I would like to be able to use this sensor in my weather station project.

**Please describe your use case for this integration and alternatives you've tried:**
At the moment I use it with tasmota so that I can integrate it into my project but I want to have everything in ESPHome.
I tried to use it with TX20/TX23 but I don't receive data, as far as I know it has a different datagram.

**Additional context**
I found some information regarding the datagram, I hope it can be helpful: http://www.sdpro.eu/jm/images/allegati/WS2300-15.pdf 
Thanks in advance!

**Comment by nagyrobi** [comment]
Ran into the same issue, and thus I bought pr-3000-fsjt-n01 and pr-3000-fxjt-n01 wind speed and direction sensors. I chose the MODBUS (RS485) version. 

Did not have time to implement it with ESPHome but I definitely intend to.

**Comment by SeByDocKy** [comment]
> pr-3000-fsjt-n01

There are a lot of Modbus 4S485 wind sensor. Most got slight diference in their protocol. Please find  a ESPhome model with such modbus sensor: https://github.com/SeByDocKy/myESPhome/blob/main/code/weather-station..yaml

**Comment by drobishman** [comment]
I think I will order as you suggest, anemometer and wind direction via MODBUS RS485, it seems to me a very good alternative. I found something on Aliexpress and was thinking of buying it: https://www.aliexpress.com/item/1005005500304078.html
Do these devices give relevant data? I'm thinking of controlling the closing of an awning depending on this sensor. WS2300-15 with tasmota does not always transmit relevant data.

**Comment by Marcin685** [comment]
Hello, 
Can I find a program for ESPHOME somewhere to read data from the wind speed sensor?

**Comment by canaula** [comment]
Hello! 
 I am in the same situation, lost.  
Has anyone implemented this wind sensor with "esphome"?

**Comment by mhansel0970** [comment]
Hi,
I have a Technoline WS2300-15, too. I built an arduino uno a few years ago to read out the wind sensor (look at the link in this thread at the beginning) and showing the data on a 20x4 led display. 
Meanwhile I tried to adapt the code of the tx20 implementation (tx20.h) so that it fits for the WS2300-15, but I can't get the program to run.
I am therefore also looking for someone who has implemented this in esphome!

**Comment by nagyrobi** [comment]
OK, the wind speed meter on Aliexpress (black plastic), type **pr-3000-fsjt-n01** works with this config, using an RS485/TTL adapter:

```yaml
uart:
  rx_pin: GPIOXX
  tx_pin: GPIOXX
  baud_rate: 4800

modbus:
  id: modbus1

modbus_controller:
- id: wind_speed_meter
  address: 1
  modbus_id: modbus1
  setup_priority: -10
  command_throttle: 200ms
  update_interval: 5s #or whatever you need


sensor:
- platform: modbus_controller
  modbus_controller_id: wind_speed_meter
  name: "Wind speed"
  device_class: wind_speed
  id: wind_speed
  register_type: read
  address: 1
  unit_of_measurement: "m/s"
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
    - multiply: 0.1
```

**Comment by nagyrobi** [comment]
The seller offers a helper application for Windows, called `485 Parameter Configuration Tool V5.0.7.1.exe`. The sensor can be connected to the PC with a USB-to-RS485 adapter, and the configuration tool makes it easily possible to change the modbus address to something else, eg. `2` (just type it in the _Addr_ box and press _Setup_ button).

After that it becomes possible to simply connect the sensors in parrallel on the same cable, to a single RS485-TTL adapter attached to a single UART on the ESP:

```yaml
uart:
  rx_pin: GPIOXX
  tx_pin: GPIOXX
  baud_rate: 4800

modbus:
  id: modbus1

modbus_controller:
- id: wind_speed_meter
  address: 1
  modbus_id: modbus1
  setup_priority: -10
  command_throttle: 200ms
  update_interval: 30s #, but updating from interval instead

- id: wind_direction_meter
  address: 2
  modbus_id: modbus1
  setup_priority: -10
  command_throttle: 200ms
  update_interval: 30s #, but updating from interval instead

sensor:
- platform: modbus_controller
  modbus_controller_id: wind_speed_meter
  name: Szélsebesség
  device_class: wind_speed
  id: wind_speed
  register_type: read
  address: 1
  unit_of_measurement: "m/s"
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
    - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: wind_direction_meter
  name: "Wind direction gear"
  icon: mdi:compass-rose
  register_type: read
  address: 1
  value_type: U_WORD
  accuracy_decimals: 0

- platform: modbus_controller
  modbus_controller_id: wind_direction_meter
  name: "Wind direction degree"
  icon: mdi:compass-rose
  register_type: read
  address: 2
  value_type: U_WORD
  accuracy_decimals: 0
  unit_of_measurement: "°"
```
