### ISSUE TITLE
Enhance CANBUS send documentation & add send_raw() function

### ISSUE THREAD

**Issue by nliaudat** [esphome/feature-requests#2317]
**Describe the problem you have/What new integration you would like**

The canbus integration is missing send action documentation

**Please describe your use case for this integration and alternatives you've tried:**

I use it in https://github.com/nliaudat/esp_canbus to control an climate component. 
Reading the data is great, but if I want to send custom commands, the current documentation lacks of informations. 

**Additional context**

I've tried many combinations (found on the web) to send my data but nothing works : 

```
select:
  - platform: template
    name: "Debug"
    id: canbus_debug_tag
    optimistic: true
    options:
      - "none"
      - "GET-Humidity-set"
      - "GET-Humidity-extract-air"
      - "GET-Extract-air-temp"
      - "SET-Humidity-set"
    set_action:
      then:
          - delay: 500ms
          - if: ## GET_REQUEST : Humidity set value
              condition:
                - lambda: |-
                    return (id(canbus_debug_tag).state) == "GET-Humidity-set";
              then:
                - canbus.send: 
                # 0x21 -> MessageID = 33 
                # 0xE0 -> Priority = 224
                # 0x0A -> device type = 10
                # 0x08 -> device id = 8
                # 0x01 -> len = 1
                # 0x40 -> GET Request
                # 0x32 -> fn group = 50
                # 0x00 -> function group = 0
                # 0x9e -> datapoint = 158 [#40687 (9eef)]
                # 0xef -> datapoint part 2 = 202
                    data: [ 0x21, 0xE0, 0x0A, 0x08, 0x01, 0x40, 0x32, 0x00, 0x9E, 0xef ] ## datapoint = 40687 (9eef)
                    use_extended_id: true
                    #remote_transmission_request: true
          - if: ## GET_REQUEST : Humidity extract air
              condition:
                - lambda: |-
                    return (id(canbus_debug_tag).state) == "GET-Humidity-extract-air";
              then:
                - canbus.send: 
                # 0x32 -> fn group = 50
                # 0x00 -> function group = 0
                # 0x92 -> datapoint 37600 (92E0)
                # 0xE0 -> datapoint part 2 
                    data: [ 0x32, 0x00, 0x92, 0xE0 ] ## datapoint = 37600 (92E0)
                    #data: [ 0x92, 0xE0 ] ## datapoint = 37600 (92E0)
                    use_extended_id: true
                    remote_transmission_request: true
          - if: ## GET_REQUEST : 37602: Extract air temp.
              condition:
                - lambda: |-
                    return (id(canbus_debug_tag).state) == "GET-Extract-air-temp";
              then:
                        - lambda: |-
                                uint32_t can_id = 8;
                                bool use_extended_id = 1;
                                std::vector< uint8_t > data{0x21, 0xE0, 0x0A, 0x08, 0x01, 0x40, 0x32, 0x00, 0x92, 0xE2 };
                                id(cbus)->send_data(can_id, use_extended_id, data);
          - if: ## SET_REQUEST = 0x46 : Humidity set value
              condition:
                - lambda: |-
                    return (id(canbus_debug_tag).state) == "SET-Humidity-set";
              then:
                - canbus.send: 
                # 0x21 -> MessageID = 33 
                # 0xE0 -> Priority = 224
                # 0x0A -> device type = 10
                # 0x08 -> device id = 8
                # 0x01 -> len = 1
                # 0x46 -> SET Request
                # 0x32 -> fn group = 50
                # 0x00 -> function group = 0
                # 0x9e -> datapoint = 158 [#40687 (9eef)]
                # 0xef -> datapoint = 202
                # data -> 0x28 = 40
                    data: [ 0x21, 0xE0, 0x0A, 0x08, 0x01, 0x46, 0x32, 0x00, 0x9E, 0xef, 0x28 ] 
                    use_extended_id: true
```

**Comment by nliaudat** [comment]
how can I send   `can0  1FE04208   [6]  01 40 32 00 92 E2`  (from dump) ?

I tried : 
```
                       - canbus.send: 
                              # can0  1FE04208   [6]  01 40 32 00 92 E2
                              #data: [ 01, 40, 32, 00, 92, E2 ]
                              #from hex to dec : 
                              #data: [ 1, 64, 50, 0, 146, 226 ]
                              #from octal to dec
                              data: [ 1, 32, 26, 0, 0, 0 ]
                              can_id: 0x1F
                              use_extended_id: true
                        - delay: 2s 
                        - canbus.send: 
                              can_id: 0x1F
                              data: [ 1, 64, 50, 0, 146, 226 ]
                              use_extended_id: true
                        - delay: 2s 
                        - canbus.send: 
                              can_id: 0x1F
                              data: [ 0x01, 0x40, 0x32, 0x00, 0x92, 0xE2 ]
                              use_extended_id: true
```
