### ISSUE TITLE
Import image entities from home-assistant

### ISSUE THREAD

**Issue by wtremmel** [esphome/feature-requests#2339]
**Describe the problem you have/What new integration you would like**

Import images just like sensors or text sensors, config could be like:
```
image:
  - platform: homeassistant
    entity_id: image.mynetwork_qr_code
    id: mynetwork_qr_code
    resize: 50x05
```

**Please describe your use case for this integration and alternatives you've tried:**

This could be used to display network qrcodes on any display

**Additional context**
