### ISSUE TITLE
Error handling for automation sequences

### ISSUE THREAD

**Issue by clydebarrow** [esphome/feature-requests#2357]
**Describe the problem you have/What new integration you would like**

I propose that the syntax for an automation block be enhanced by adding keywords for error handling. For example:

```
    on_...:
      then:
        - some.action:
        - another.action:
      except:
        - script.execute:
            id: send_notification
            message: x
        - light.turn_on: error_led
      finally:
        - script.execute: reset_to_nominal_state
  ```

The expectation is that an action in the `then` block may signal an error, terminating the execution of the block and triggering the automation block following `except` (with parameter `x` representing the error.)

The `finally` block will be executed either on normal termination or abnormal. The `finally` block would also be executed if the automation block was terminated by a `script.stop` action.

The definition of what constitutes an error in execution of an action will be up to the action. Most existing actions would not throw errors.

**Please describe your use case for this integration and alternatives you've tried:**

I'm working on enhancements to the `ble_client` component and actions within that component (e.g. `ble_client.ble_write`) can fail. There is currently no way to handle that. In general any action that depends on a communication channel subject to outages would have the same possibility of failure.

**Additional context**
