### ISSUE TITLE
Support for Shelly BLU Button1

### ISSUE THREAD

**Issue by masterfish1** [esphome/feature-requests#2403]
**Describe the problem you have/What new integration you would like**

Support for Shelly BLU Button1 tracking mode

**Please describe your use case for this integration and alternatives you've tried:**

This device is supported by BTHome for button presses but it doesn't support tracking. Tracking is supported by the BLE Passive Monitor but it has to be in range of a single Bluetooth adaptor. This could make good use of ESPHome's Bluetooth proxy option.

**Additional context**

Sample YAML for BLE Passive Monitor

```
ble_monitor:
  devices:
  - mac: 'XX:XX:XX:XX:XX:XX'
    track_device: True
    tracker_scan_interval: 30
    consider_home: 180
    name: 'Shelly BLU'
    reset_timer: 1
```
