### ISSUE TITLE
Override option for monochromatic transitions that is accessible by other sensors

### ISSUE THREAD

**Issue by TheGorf** [esphome/feature-requests#2406]
**Describe the problem you have/What new integration you would like**
Currently when using a monochromatic and ledc platform to access the PWM output on a GPIO pin, setting the default_transition_length is used to cause the fade effect to transition something like a light on and off. However it appears that once that transition is started, there is not a way to interrupt it. Long running transitions override any "on" value that is attempted to be set. As an example in my use case:

```
`# Main terrarium lights
output:
  - platform: ledc
    pin: GPIO23
    id: terrarium_light_pwm_output
    frequency: "1000Hz"

light:
  - platform: monochromatic
    name: "Terrarium Lights - Fade"
    id: terrarium_lights_fade
    output: terrarium_light_pwm_output
    default_transition_length: 1800s

  - platform: monochromatic
    name: "Terrarium Lights - Fast"
    id: terrarium_lights_fast
    output: terrarium_light_pwm_output

#Override Buttons for lights
binary_sensor:
  - platform: gpio
    pin:
      number: 22
      mode: INPUT_PULLUP
      inverted: True
    name: "swFASTON"
    filters:
      - delayed_on: 10ms  
    on_press:
      then:
        - light.turn_on: terrarium_lights_fast`
```

Here we can see that two different lights are driving the same output. One light has a long transition time of 1800s. During that transition time, if the mechanical button is pushed, it does indeed immediately turn the light on to full brightness, but because the long transition is still ongoing, it immediately resets the lights output to wherever the long transition is still at. 

**Please describe your use case for this integration and alternatives you've tried:**
The use case is really to override long running transitions so that mid-transition you can immediately transition to full on or full off.  Currently the only alternative i've come up with is an electromechanical one involving physically changing connections to the light via switch and relay. This is undesirable as it leaves me without a software way to do it. 

**Additional context**
I could see two implementation options right off the top of my head. 1> Monochromatic lights driving an float output (ledc) should have an additional state between On and Off. Something like Transitioning. That would allow you to set the state to "On" and immediately set the output to 100%. 2> The ability to override an exposed variable for the transition completion percentage.
