### ISSUE TITLE
Add multiple Grove TB6612FNG drivers

### ISSUE THREAD

**Issue by simonyel** [esphome/feature-requests#2411]
**Describe the problem you have/What new integration you would like**
o Would love to ability to configure multiple instances of the driver boards

**Please describe your use case for this integration and alternatives you've tried:**
 I am making a chemical dispenser for my aquarium and need the ability to drive 4 pumps. To do this I would need two Grove TB6612FNG drivers. Currently, I don't see an option to configure multiples. 

**Additional context**

![PXL_20231015_024847871 PORTRAIT](https://github.com/esphome/feature-requests/assets/30694967/be85a050-44c8-4a59-8f05-556e9d38c9b6)
![PXL_20231015_024659552 PORTRAIT ORIGINAL](https://github.com/esphome/feature-requests/assets/30694967/b6061bcb-ac4d-496a-8535-e83cf8d42061)
![image](https://github.com/esphome/feature-requests/assets/30694967/a83ad925-3683-461a-b477-7a08232f8115)

**Comment by simonyel** [comment]
@max246

**Comment by max246** [comment]
Usually you would use the same i2c bus but with a different address. 
I am not sure the esp has two different i2c controllers and if that the case, I suppose you could setup at the moment without doing any changes.

**Comment by simonyel** [comment]
I'll change the address if it comes to that. Would that make the code change easier for you?

- Simon Yelfimov (mobile)
________________________________

**Comment by max246** [comment]
Right , what it can be done is :

`
  void set_i2c_addr(uint8_t addr);
`

I can expose this as action and you would need to run the system once and trigger the action to change the address, you can have two on the same bus.

I can see here in the example of setup a new motor, you just going to copy and paste the block , change the address and id.
https://esphome.io/components/grove_tb6612fng.html

**Comment by simonyel** [comment]
I got the address changed for my second driver via Arduino IDE. Now the driverA is at 0x14, and driverB is at 0x15. What's next?

**Comment by max246** [comment]
Please take this as assumption since I dont have two motors board:

I would guess you will have to do something like 


```
grove_tb6612fng:
    id: test_motor_a
    name: motor_outside
    address: 0x14

grove_tb6612fng:
    id: test_motor_b
    name: motor_outside
    address: 0x15
```


then when you control the motor you use the  ID to identify which motor you want to control.

**Comment by simonyel** [comment]
You can't have duplicate `grove_tb6612fng:` keys, nor can I nest a list of them under a single entry.

**Comment by simonyel** [comment]
> You can't have duplicate `grove_tb6612fng:` keys, nor can I nest a list of them under a single entry.

For instance. I can't do:
`grove_tb6612fng:
  - id: driverA
    name: "Driver A"
    address: 0x14   
  - id: driverB
    name: "Driver B"  
    address: 0x15`

or 
`grove_tb6612fng:
    id: test_motor_a
    address: 0x14

grove_tb6612fng:
    id: test_motor_b
    address: 0x15`

**Comment by simonyel** [comment]
Any thoughts?

**Comment by max246** [comment]
Sorry, got busy with work....

I talked to jess and I just need to add an extra parameter in the code to allow multi blocks.

I will make the change over the weekend, you might need to test my PR if you can

**Comment by simonyel** [comment]
I will gladly test and report back.

**Comment by max246** [comment]
ok done it.

I have updated the doc and tested the code, it works. 

Check the doc PR to understand how to setup a multi conf

https://github.com/esphome/esphome/pull/5492

**Comment by simonyel** [comment]
I changed the config, but where do I pull the test component? This still won’t compile with the prod release.

**Comment by simonyel** [comment]
Here is my config: 

```
substitutions:
  device_name: 'quadpump'
  friendly_name: quadpump
  device_comment: "Mounted in the aquarium cabinet"
  entity_prefix: "qp1"
  device_type: "SVYtech"
  
packages:
  core: !include _config/core.yaml
    
esphome:
  name: quadpump
  friendly_name: quadpump

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<redacted>"

status_led:
  pin:
    number: GPIO2 
    inverted: false  

external_components:
  - source: github://pr#5492
    components: [ grove_tb6612fng ]
    refresh: 0s

i2c:
  sda: GPIO19
  scl: GPIO23
  scan: true    

grove_tb6612fng:
  - address: 0x14   
    id: driverA
  - address: 0x15
    id: driverB


globals:
  - id: pump1_runtime
    type: int
    restore_value: yes
    initial_value: '0'
  - id: pump2_runtime
    type: int
    restore_value: yes
    initial_value: '0'  
  - id: pump3_runtime
    type: int
    restore_value: yes
    initial_value: '0'  
  - id: pump4_runtime
    type: int
    restore_value: yes
    initial_value: '0'          

button:
  - platform: template
    name: $entity_prefix Dispense 1
    id: run_pump1
    on_press:
      then:
        - grove_tb6612fng.run:
            id: driverA
            channel: 0
            speed: 90
            direction: FORWARD
        - delay: !lambda 'return id(pump1_runtime);'
        - grove_tb6612fng.break:
            id: driverA
            channel: 0             
        - grove_tb6612fng.stop:
            id: driverA
            channel: 0 
  - platform: template
    name: $entity_prefix Dispense 2
    id: run_pump2
    on_press:
      then:
        - grove_tb6612fng.run:
            id: driverA
            channel: 1
            speed: 90
            direction: FORWARD
        - delay: !lambda 'return id(pump2_runtime);'
        - grove_tb6612fng.break:
            id: driverA
            channel: 1    
        - grove_tb6612fng.stop:
            id: driverA
            channel: 1    
  - platform: template
    name: $entity_prefix Dispense 3
    id: run_pump3
    on_press:
      then:
        - grove_tb6612fng.run:
            id: driverB
            channel: 0
            speed: 90
            direction: FORWARD
        - delay: !lambda 'return id(pump3_runtime);'
        - grove_tb6612fng.break:
            id: driverB
            channel: 0             
        - grove_tb6612fng.stop:
            id: driverB
            channel: 0 
  - platform: template
    name: $entity_prefix Dispense 4
    id: run_pump4
    on_press:
      then:
        - grove_tb6612fng.run:
            id: driverB
            channel: 1
            speed: 90
            direction: FORWARD
        - delay: !lambda 'return id(pump4_runtime);'
        - grove_tb6612fng.break:
            id: driverB
            channel: 1    
        - grove_tb6612fng.stop:
            id: driverB
            channel: 1    

switch:                 
  - platform: template
    id: sw_feed_pump1
    name: $entity_prefix Feed pump 1
    turn_on_action:
      then:
        - switch.template.publish:
            id: sw_feed_pump1
            state: ON
        - grove_tb6612fng.run:
            id: driverA
            channel: 0
            speed: 90
            direction: FORWARD
    turn_off_action:
      then:
        - grove_tb6612fng.break:
            id: driverA
            channel: 0             
        - grove_tb6612fng.stop:
            id: driverA
            channel: 0        
        - switch.template.publish:
            id: sw_feed_pump1 
            state: OFF          
  - platform: template
    id: sw_feed_pump2
    name: $entity_prefix Feed pump 2
    turn_on_action:
      then:
        - switch.template.publish:
            id: sw_feed_pump2
            state: ON
        - grove_tb6612fng.run:
            id: driverA
            channel: 1
            speed: 90
            direction: FORWARD
    turn_off_action:
      then:
        - grove_tb6612fng.break:
            id: driverA
            channel: 1             
        - grove_tb6612fng.stop:
            id: driverA
            channel: 1        
        - switch.template.publish:
            id: sw_feed_pump2
            state: OFF                                    
  - platform: template
    id: sw_feed_pump3
    name: $entity_prefix Feed pump 3
    turn_on_action:
      then:
        - switch.template.publish:
            id: sw_feed_pump3
            state: ON
        - grove_tb6612fng.run:
            id: driverB
            channel: 0
            speed: 90
            direction: FORWARD
    turn_off_action:
      then:
        - grove_tb6612fng.break:
            id: driverB
            channel: 0             
        - grove_tb6612fng.stop:
            id: driverB
            channel: 0        
        - switch.template.publish:
            id: sw_feed_pump3 
            state: OFF          
  - platform: template
    id: sw_feed_pump4
    name: $entity_prefix Feed pump 4
    turn_on_action:
      then:
        - switch.template.publish:
            id: sw_feed_pump4
            state: ON
        - grove_tb6612fng.run:
            id: driverB
            channel: 1
            speed: 90
            direction: FORWARD
    turn_off_action:
      then:
        - grove_tb6612fng.break:
            id: driverB
            channel: 1             
        - grove_tb6612fng.stop:
            id: driverB
            channel: 1        
        - switch.template.publish:
            id: sw_feed_pump4
            state: OFF
number:
  - platform: template
    id: pump1_dose
    name: $entity_prefix Dose 1
    min_value: 0.1
    max_value: 2.5
    step: 0.1
    optimistic: True
    restore_value: True
    on_value:
      - globals.set:
          id: pump1_runtime
          value: !lambda 'return id(pump1_dose).state * 1000;'
  - platform: template
    id: pump2_dose
    name: $entity_prefix Dose 2
    min_value: 0.1
    max_value: 2.5
    step: 0.1
    optimistic: True
    restore_value: True
    on_value:
      - globals.set:
          id: pump2_runtime
          value: !lambda 'return id(pump2_dose).state * 1000;'
  - platform: template
    id: pump3_dose
    name: $entity_prefix Dose 3
    min_value: 0.1
    max_value: 2.5
    step: 0.1
    optimistic: True
    restore_value: True
    on_value:
      - globals.set:
          id: pump3_runtime
          value: !lambda 'return id(pump3_dose).state * 1000;'
  - platform: template
    id: pump4_dose
    name: $entity_prefix Dose 4
    min_value: 0.1
    max_value: 2.5
    step: 0.1
    optimistic: True
    restore_value: True
    on_value:
      - globals.set:
          id: pump4_runtime
          value: !lambda 'return id(pump4_dose).state * 1000;'
```
