### ISSUE TITLE
Restart/Reinitialise SPI action

### ISSUE THREAD

**Issue by samuelolteanu** [esphome/feature-requests#2412]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

I'm using a max7219 7 digit display together with a relay and a triac (servo controlled) after that relay for limiting the power of an electric water boiler on the same esp for solar pv matching reasons. The moment relay is closed, the triac will make some noise/spikes/whatever they do and the display sometimes will show nonsense, dimm, not show anything or anything in between. Tried a power supply with two outputs, same thing, and then i gave up and made an HA automation to restart the esp after each time relay is opening the circuit.
Is it possible to restart only the SPI component without wifi disconnect?
**Additional context**

**Comment by xdecock** [comment]
Would it be possible to test something like that?
```
# Script to restart max7219
script:
  - id: restart_max7219
    then:
      - lambda: id(id_of_max7219).setup()

... on_xxxx:
      then:
        script.execute: restart_max7219
```

From what i read i don't see any obvious memory leak in the setup
