### ISSUE TITLE
add esp-idf media_player support

### ISSUE THREAD

**Issue by alfwro13** [esphome/feature-requests#2429]
**Describe the problem you have/What new integration you would like**

Please add support for media_player component on esp-idf framework.  Many esphome features now recommend using esp-idf framework (i.e. bluetooth proxy) however media player still only work on arduino framework.

**Please describe your use case for this integration and alternatives you've tried:**

Currently media player is only available on arduino framework and when trying to compile this code:
````
i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: 44
    i2s_bclk_pin: 36

media_player:
  - platform: i2s_audio
    name: Media Player
    id: media_out
    i2s_audio_id: i2s_out
    dac_type: external
    i2s_dout_pin: 35
    mode: mono
````
I get: This feature is only available with frameworks [‘arduino’].

**Additional context**
