### ISSUE TITLE
BME680 BSEC support framework esp-idf

### ISSUE THREAD

**Issue by tiimsvk** [esphome/feature-requests#2431]
**Describe the problem you have/What new integration you would like**
is it possible to add support for this sensor via BSEC using ESP-IDF?
well thank you

```
bme680_bsec:

esp32:
  board: esp32dev
  framework:
    type: esp-idf
```

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**
