### ISSUE TITLE
INA226 configure the "Operating mode" to save power

### ISSUE THREAD

**Issue by gargamelonly** [esphome/feature-requests#2458]
**Describe the problem you have/What new integration you would like**

The device has a power-down or triggered mode setting in the Configuration Register (00h) (Read/Write)
MODE: Operating Mode
Bits 0-2 Selects continuous, triggered, or power-down mode of operation. 
These bits default to continuous shunt and bus measurement mode.
Currently there is no option in ESPHome to change this mode or any other custom parameter for the setup.
I would like to see an option to write to this register.
https://github.com/Zanduino/INA/wiki/setMode()

**Please describe your use case for this integration and alternatives you've tried:**

My setup is battery operated with the INA226 used to monitor battery voltage and current consumption to calculate remaining battery charge and circuit consumption. While the INA226 is not being read it has a current draw of 220uA while it supports a power-down mode when the power consumption of the device drops to about 2uA considerably saving more power.
When requesting to do a measurement the device mode needs to change to "triggered" then back to "power-down".
There is no alternate way to reduce the power consumption of the device.

**Additional context**

Currently it is fixed and cannot be modified:
```
void INA226Component::setup() {
  ESP_LOGCONFIG(TAG, "Setting up INA226...");
  // Config Register
  // 0bx000000000000000 << 15 RESET Bit (1 -> trigger reset)
  if (!this->write_byte_16(INA226_REGISTER_CONFIG, 0x8000)) {
    this->mark_failed();
    return;
  }
  delay(1);

  uint16_t config = 0x0000;

  // Averaging Mode AVG Bit Settings[11:9] (000 -> 1 sample, 001 -> 4 sample, 111 -> 1024 samples)
  config |= 0b0000001000000000;

  // Bus Voltage Conversion Time VBUSCT Bit Settings [8:6] (100 -> 1.1ms, 111 -> 8.244 ms)
  config |= 0b0000000100000000;

  // Shunt Voltage Conversion Time VSHCT Bit Settings [5:3] (100 -> 1.1ms, 111 -> 8.244 ms)
  config |= 0b0000000000100000;

  // Mode Settings [2:0] Combinations (111 -> Shunt and Bus, Continuous)
  config |= 0b0000000000000111;

  if (!this->write_byte_16(INA226_REGISTER_CONFIG, config)) {
    this->mark_failed();
    return;
  }
```

**Comment by latonita** [comment]
@gargamelonly is it still needed?

**Comment by gargamelonly** [comment]
Yes please.
Appreciate it.

**Comment by latonita** [comment]
@gargamelonly try https://github.com/esphome/esphome/pull/6394
please try with usual config (continuous mode)
and with "operating_mode: low_power"

**Comment by gargamelonly** [comment]
I know my next question is not in the scope of this issue...

I get an error in ESPHOME saying that the "operating_mode" is an error. 
Running ESPHOME 2024.4.1 on docker.

**Comment by latonita** [comment]
Please attach your config file

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gargamelonly** [comment]
```
esphome:
  name: sensor-test
  on_boot:
    then:
      - script.execute: consider_deep_sleep

esp8266:
  board: nodemcuv2
...
i2c:
  sda: 12
  scl: 14
  scan: False

status_led:
  pin: GPIO2

sensor:
  - platform: bmp280
    temperature:
      name: "BoxTemperature"
    pressure:
      name: "BoxPressure"
    address: 0x76
    update_interval: 60s
  - platform: sht3xd
    temperature:
      name: "AirTemperature"
    humidity:
      name: "AirHumidity"
    address: 0x44
    update_interval: 60s
  - platform: ina226
    address: 0x40
    #operating_mode: low_power  # continuous (default) or low_power
    shunt_resistance: 0.1 ohm
    current:
      name: "Current"
    power:
      name: "Power"
    bus_voltage:
      name: "Bus_Voltage"
    shunt_voltage:
      name: "Shunt_Voltage"
    max_current: 3.2A
    update_interval: 60s
...
```

**Comment by latonita** [comment]
you shall use external component, since this is not yet merged into main branch.
make sure you have this section in yaml:
```
external_components:
  - source: github://pr#6394
    refresh: 10s
    components: [ina226]

```
