### ISSUE TITLE
More generic PID Controller, don't limit it to hw output

### ISSUE THREAD

**Issue by samuelolteanu** [esphome/feature-requests#2463]
**Describe the problem you have/What new integration you would like**

I find this PID controller component to be something that I looked for, for a long time, but didn't know existed. However, the current ESPHome implementation [artificially I think] requires to control a float output. It should set a template number instead wich it  would make it more generic. I'm aware that there may be some safety concerns for when that number unexpectedly might not set actions further (eg disabled automation in HA could make controller pump heat at maximum power because the sensor does not respond properly or at all).
EDIT: Found "Template output" wich would mainly solve my problem.

**Please describe your use case for this integration and alternatives you've tried:**

PID Controller limited to float output only.

**Additional context**

**Comment by nagyrobi** [comment]
Template Output is what you need.

**Comment by samuelolteanu** [comment]
This does not compile:

```
output:
  - platform: template
    id: output_for_pid
    type: float
    write_action:
      - number.set:
            id: template_number
            value: !lambda 'return x;'
#same with value: !lambda 'return state;'

```
/config/esphome/esp32s2-8.yaml: In lambda function:
/config/esphome/esp32s2-8.yaml:132:30: error: 'class esphome::template_::TemplateFloatOutput' has no member named 'state'
       return id(output_for_pid).state;
                              ^~~~~
/config/esphome/esp32s2-8.yaml: In lambda function:
/config/esphome/esp32s2-8.yaml:295:14: error: 'x' was not declared in this scope
             value: !lambda 'return x;'
              ^
