### ISSUE TITLE
Add support for the Steinhart-Hart equation for calibration

### ISSUE THREAD

**Issue by magnusoverli** [esphome/feature-requests#247]
Hi!
I am trying to use a NTC thermistor to measure temps using my ESP32. This connects to the ADC pin (using a voltage divider). The issue is that a thermistor is not linear in its resitance along the tmeperature axis. To make measurements using a thermistor usable, one uses the Steinhart-Hart equation, as described here: https://www.ametherm.com/thermistor/ntc-thermistors-steinhart-and-hart-equation

It takes three pairs of constants and a corresponding resistance value, and let you read out the temperature measured by the thermistor.
 
I was hoping the equation could be implented in ESPhome, so that the end user was left with only gathering data on their thermistor.

The config could look something like this:
```
- adc-temp-sensor
  name: Temp sensor
  unit_of_measurement: "°C"
  accuracy_decimals: 1
  filters:
    - sliding_window_moving_average:
        window_size: 10
        send_every: 10
  shh-calibration:
    - t1: 0       //temperature reading 1
    - r1: 20k   //resistance reading 1
    - t2: 10     //temperature reading 2
    - r2: 15k   //resistance reading 2
    - t3: 20     //temperature reading 2
    - r3: 10k   //resistance reading 2
```

I know one can use other temp sensors directly connected to the ESP, but in a lot of use cases the user is forced to use an already existing sensor. For example in my case, I am trying to control the floor heating. That is a tiled floor where the sensor is embedded into the concrete underneath the tiles. There simply is no other way of going about it.
This can also be used enable the use of high temperature sensor in hostile environments and reading the temps directly on an ESP. 

I think this is a versatile addition to ESPhome and it woul enable the use of MANY devices that doesn't need further support in ESPhome, outside this calibration tool.
