### ISSUE TITLE
Provide offline/fallback logic

### ISSUE THREAD

**Issue by CleverCompiler** [esphome/feature-requests#2486]
**Describe the problem you have/What new integration you would like**

I would like to have fallback logic for when my Home Assistant is down for maintenance so that light switches with esphome could still toggle their relays like legacy switches would.

**Please describe your use case for this integration and alternatives you've tried:**
 
My use case would be say I have a Martin Jerry wall switch running esphome but I send the button pushes to Home Assistant so I can trigger scene switching but if HA is down because I'm restoring a backup or changing my network switch I would want my Switch to behave like a normal switch in that room.

**Additional context**

I'm not looking for automations or even device to device communication just an if offline toggle relay fallback logic.

**Comment by randybb** [comment]
This was always possible. Something like:
```yaml
  - platform: gpio
    name: ${name} Right Button
    pin:
      number: 27
      inverted: true
    on_click:
      if:
        condition:
          api.connected:
        then:
          - homeassistant.service:
              service: light.toggle
              data:
                entity_id: light.patio_light
        else:
          - switch.toggle: relay_2
```
