### ISSUE TITLE
Alternative method for h-bridge light

### ISSUE THREAD

**Issue by MiguelAngelLV** [esphome/feature-requests#2501]
**Describe the problem you have/What new integration you would like**

The actual method for h bridge light change the direction in each loop each 16ms (as minimal), so, so, each light have a max of 30hz (60 of total).

This cause flicking sometimes-

**Please describe your use case for this integration and alternatives you've tried:**
I am trying some alternatives and I get a big improve using cwww component with inverted PWM and max 50% power:

```yaml
output:
  - platform: ledc
    id: pina
    inverted: true
    pin: 
      number: 5
      inverted: True
    channel: 0
    max_power: 50%
  - platform: ledc
    id: pinb
    pin: GPIO6
    channel: 2
    max_power: 50%


light:
  - platform: cwww
    name: "Lights"
    cold_white: pina
    warm_white: pinb
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
```

I think this approach could be used in h-bridge method instead change direction in each loop.

**Additional context**

**Comment by CurlyWirly** [comment]
I tried this with a set of 3 wire fairy bead lights connected to a small board using a DRV8333 h-bridge. Your cwww settings worked very well compared to the H-Bridge platform which for me flickered quite badly.
I tried changing the LED-C frequency when using the h-bridge platform but this didn't fix it.

Thankyou

**Comment by SodaWithoutSparkles** [comment]
I tried the above code with a DRV8871 H-bridge for driving 24V LED strips directly. The LED strips is using a anti-parallel wiring, marked C-Y+ and C+Y-, so either cold white or warm white can be turn on at the same time.

The above code works without flicker. However, looking at the power consumption, it doesn't drive up to the full wattage. This is the improved code that uses constant brightness, which does use all available power when using just a single color. Also, this uses phase angles instead of inverted, which makes more sense to me. This way the lights also wont flash at boot.

```yaml
output:
  # H-Bridge 1 (CWWW Light 1)
  - platform: ledc
    pin: GPIO3
    id: h_bridge_1a
    frequency: 2441 Hz
    channel: 0
  - platform: ledc
    pin: GPIO4
    id: h_bridge_1b
    frequency: 2441 Hz
    channel: 1
    phase_angle: 180
    # Use channels (2,3), (4,5), etc for more lights
    # If not paired then the phase angle might not be guaranteed?

light:
  - platform: cwww
    name: "CWWW Light 1"
    cold_white: h_bridge_1a
    warm_white: h_bridge_1b
    cold_white_color_temperature: 6500 K      # Change these two
    warm_white_color_temperature: 2700 K    # according to your light's spec
    constant_brightness: true
```
