### ISSUE TITLE
Delayed initialization I2C bus

### ISSUE THREAD

**Issue by tiimsvk** [esphome/feature-requests#2529]
**Describe the problem you have/What new integration you would like**
Is it possible to integrate in the code an option where the time delay of initialization of the i2c bus would be set?

```
i2c:
  sda: "$i2c_sda_pin"
  scl: "$i2c_scl_pin"
  scan: True
  delay: 300ms # delay after boot
```

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**
