### ISSUE TITLE
Support for removing elements imported by a remote package

### ISSUE THREAD

**Issue by mdbooth** [esphome/feature-requests#2530]
**Describe the problem you have/What new integration you would like**
I would like some way to remove configuration directive imported by a remote package.

**Please describe your use case for this integration and alternatives you've tried:**
My plug has the following configuration:

```yaml
substitutions:
  device_name: "dehumidifier-plug"
  friendly_name: "Dehumidifier Plug"
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${device_name}
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

[The imported configuration enables web_server](https://github.com/athom-tech/athom-configs/blob/600ddf21e308d025fc68e7fd2638d50dcfda417c/athom-smart-plug-v2.yaml#L35-L36). However, I have been experiencing stability issues with these plugs and I would like to try disabling it. I am looking for some incantation which I can add to my configuration which will disable web_server in the expanded output I see when selecting 'Validate`.

It looks like `!remove` ([documentation](https://esphome.io/guides/configuration-types.html#remove)) would let me do this, but it seems that I can only `!remove` if I used `!include`, which I did not because the package is remote. That same documentation does state:
> Since packages are incorporated using the !include system...

So I wonder if this is either nearly possible already, or possible with some unintuitive or undocumented syntax.

**Additional context**
