### ISSUE TITLE
Allow specifying `vars:` for Remote/Git Packages

### ISSUE THREAD

**Issue by barndawgie** [esphome/feature-requests#2542]
**Describe the problem you have/What new integration you would like**
We would like to create configurations in which we instantiate multiple copies of our components, but with different configuration. We are trying to do this using remote packages, but hitting an issue where `vars:` is not supported for remote packages as they are for `!include` packages.

E.g. we would like to create config like the following:
```yaml
econet:
  url: https://github.com/bitfliq/esphome-econet
  ref: zones-initial
  file: econet_hvac_base.yaml
zone1:
  url: https://github.com/bitfliq/esphome-econet
  ref: zones-initial
  file: econet_hvac_zone_template.yaml
  vars:
    zoneid: "1"
    zonename: "Zone1"
    requestmod: 4
    thermostat_address: 0x380
zone2:
  url: https://github.com/bitfliq/esphome-econet
  ref: zones-initial
  file: econet_hvac_zone_template.yaml
  vars:
    zoneid: "2"
    zonename: "Zone2"
    requestmod: 5
    thermostat_address: 0x381
```

**Please describe your use case for this integration and alternatives you've tried:**
Our ESPHome component (https://github.com/esphome-econet/esphome-econet) can be used to control a thermostat. For homes with multi-zone HVAC systems, we'd want to instantiate multiple thermostats on a single ESPHome controller.

**Additional context**
Some additional details around this ask were discussed in ESPHome discord: https://discord.com/channels/429907082951524364/1191494270624993420
