### ISSUE TITLE
Pylontech/ add State of Health - residualmA - Cycle

### ISSUE THREAD

**Issue by Dackara** [esphome/feature-requests#2544]
**Describe the problem you have/What new integration you would like**
Hello, and sorry my English is bad...
First of all, thanks to `functionpointer` for his work!
I would like the functions `State of Health`, `Number of batteries`, `residualmA` and `Cycle` be added.

**Please describe your use case for this integration and alternatives you've tried:**
To obtain this information, you must use the command `pwrsys` , `getpwr1` and 2, 3 ,.... , `stat1` and and 2, 3 ,....
If it's useful I can provide my personal file (I sent it by PM to @functionpointer on Discord)

**Additional context**

**Comment by Dackara** [comment]
Also, the `voltage_low` and `voltage_hight` is define on `°C`. But this is not Temperature but a Voltage !
So I already fix that in my repository for now and i try to write the others `cmd`.

For use my patch :
- Replace `voltage_low` to `cell_low:` and `voltage_high` to `cell_high`   #(is the voltage of one cellule)
 In your confuguration files use that to your YAML :

```
external_components:
  - source: github://dackara/esphome-pylontech@official-patched
    refresh: 0s
sensor:
    cell_low:
      id: ${pylon_id}${pylon_number}_low_voltage_cell
      name: '${pylon_name} ${pylon_number} low voltage cell'
    cell_high:
      id: ${pylon_id}${pylon_number}_high_voltage_cell
      name: '${pylon_name} ${pylon_number} high voltage cell'
#    voltage_low:
#      id: bat1_low_voltage
#      name: "Battery1 low voltage" 
#    voltage_high:
#      id: bat1_high_voltage
#      name: "Battery1 high voltage"  
```
