### ISSUE TITLE
autoclose value for time_based cover

### ISSUE THREAD

**Issue by djsomi** [esphome/feature-requests#2573]
An autoclose value for time_based cover would be nice.

Most of the Gate electronics works this way: After fully opened there is a time to wait  and gate closing automatically. 
If using RF signals only to operate, and does not have any opened/closed binary state input, an autoclose time would be useful to get the gate status back to Closed after the defined time. 

Maybe it can be coded within the actual framework, if yes please share a working solution.

**Comment by nagyrobi** [comment]
```
cover:
  - platform: ...
    id: my_gate
    # ...
    on_open:
      - logger.log: "Gate Open!"
      - delay: 3min #you can use a lambda here, pointing at a number if you want it configurable
      - logger.log: "Gate Closing!"
      - cover.close: my_gate
```
