### ISSUE TITLE
Support for Agratto Climate (IR)

### ISSUE THREAD

**Issue by Fusseldieb** [esphome/feature-requests#2580]
**Describe the problem you have/What new integration you would like**
We have an Agratto HVAC, but it is unfortunately not supported. I've tried multiple other brands to make sure, but neither of them did work.

**Please describe your use case for this integration and alternatives you've tried:**
I've put an ESP with an IR sensor inside the unit and want to turn it on/off/change temps. I've only realized it isn't supported after already successfully mounting it inside the unit :)

**Additional context**
If necessary, I'd be more than happy to provide a recorded remote using an ESP device.

**Comment by Fusseldieb** [comment]
Turns out, it is the same as `aux`!

```
climate:
  - platform: heatpumpir
    protocol: aux
    horizontal_default: auto
    vertical_default: auto
    min_temperature: 16
    max_temperature: 32
    name: "HVAC"
    # sensor: ambient_temp # If you have a temperature sensor. I do.
```

This works
