### ISSUE TITLE
Initialize all unused GPIO with pull-ups to prevent power draw

### ISSUE THREAD

**Issue by twasilczyk** [esphome/feature-requests#2587]
**Describe the problem you have**
Floating GPIO causes unnecessary power draw and instability

**Please describe your use case for this integration and alternatives you've tried:**
Alternative: manually setting all unused GPIO to input with pull-up

**Additional context**
https://github.com/esphome/issues/issues/1950
https://github.com/esphome/issues/issues/5085
https://github.com/esphome/feature-requests/issues/2586
https://www.reddit.com/r/Esphome/comments/ppzd08/is_it_normal_for_a_smart_plug_to_feel_warmer_when/
https://community.home-assistant.io/t/esp-overheat-without-ha/508317/3
https://community.home-assistant.io/t/device-overheating-on-esphome-but-fine-on-tasmota/464181/8

**Suggested feature**
ESPHome should enumerate all unused GPIOs (I think it should have that information in board config?) and set default for all as GPIO input with pull-up. Example from https://github.com/esphome/issues/issues/5085#issuecomment-1897557212:
```
binary_sensor:
  - platform: gpio
    id: gpio16
    pin:
      number: GPIO16
      mode:
        input: true
        pullup: true
```
