### ISSUE TITLE
Add support for AS7343 spectral sensor

### ISSUE THREAD

**Issue by Beul85** [esphome/feature-requests#2597]
**Describe the problem you have/What new integration you would like**

Add support for the AS7343 spectral sensor.

**Please describe your use case for this integration and alternatives you've tried:**

Diy Par Meter Project.

**Additional context**

The older AS7341 is already integrated in esphome and nearly identical (11vs14 channels) to the AS7343.

**Comment by HerzBeatz** [comment]
I would love to see this integrated into esphome.
With this sensor you can make a cheap PPFD device which costs $500 online .

**Comment by latonita** [comment]
@Beul85 @HerzBeatz I can take care of it. Do you have esp32 and the sensor connected? 
I don't have the device, but with wireguard it will be easy for me to work on the driver.

**Comment by Beul85** [comment]
Hello, 
esp32 and sensor as7343 are connected und wireguard is installed. I would love your help. what do i do next?

**Comment by latonita** [comment]
Drop me an email Anton.viktorov at live.com

BR, Anton
________________________________

**Comment by Beul85** [comment]
I sendet you a email with reference esp32 as7343

**Comment by latonita** [comment]
@Beul85 I made initial version, please check if it works at all
https://github.com/esphome/esphome/pull/6285

**Comment by HerzBeatz** [comment]
@latonita is there any chance that you could do this PPFD calibation for the as7341 as well? it looks like that the PPFD reading from 7343 is very close to a high end PPFD reader.

**Comment by latonita** [comment]
@HerzBeatz  did you try 7343 and compared to some calibrated devices?
Unfortunately its impossible to do proper measurements without 1) diffuser and 2) calculated glass attenuation factor.
Numbers out of the box can be very inacurate.
Plus sensor doesnt really work with high lux (1000+) without glass attenuation filters.
after i review and upload basic features I will look at 7341.

**Comment by harpi4** [comment]
@latonita 
Hello, 1st time contributing to an open source project, so please, bear with me if I'm not following some proper guidelines yet.

I'm very interested in this feature request and would be happy to help with it if I'm being guided.
I do have bought a couple of those sensors.

In esphome, I've set it that way:

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/latonita/esphome
      ref: as7343
    components: [as734x]
sensor:
  - platform: as734x
    type: AS7343
    gain: X4
    atime: 29
    astep: 299
    update_interval: 5s

    # Raw integer counts per channel
    counts:
      f1:
        name: "380nm"
      f2:
        name: "415nm"
      fz:
        name: "445nm"
      f3:
        name: "480nm"
      f4:
        name: "515nm"
      fy:
        name: "555nm"
      f5:
        name: "590nm"
      fxl:
        name: "630nm"
      f6:
        name: "680nm"
      f7:
        name: "730nm"
      f8:
        name: "910nm"
      nir:
        name: "NIR"
      clear:
        name: "Clear"

    # Calculated outputs
    illuminance:
      name: "Illuminance (Lux)"
    irradiance:
      name: "Irradiance (W/m²)"
    ppfd:
      name: "PPFD"
    irradiance_par:
      name: "PAR"
    color_temperature:
      name: "CCT"
    saturation_level:
      name: "Saturation %"
    rgb_hex:
      name: "RGB Hex"
```

`RGB Hex` remains empty.
Also, about the 380nm, I believe I do not have any UV indeed at the moment (256 is a suspicious number bit-wise!).

This is the result I have right now:

 | Sensor                | Value            |
|--------------------|------------------|
| 380nm                | 256 #            |
| 415nm                | 1,792 #          |
| 445nm                | 3,584 #          |
| 480nm                | 2,816 #          |
| 515nm                | 4,096 #          |
| 555nm                | 5,376 #          |
| 590nm                | 2,304 #          |
| 630nm                | 4,608 #          |
| 680nm                | 3,328 #          |
| 730nm                | 1,024 #          |
| 910nm                | 1,536 #          |
| CCT                     | 6,709 K          |
| Clear                   | 7,552 #          |
| Illuminance (Lux)  | 199 lx           |
| Irradiance (W/m²)  | 0.763 W/m²       |
| NIR                  | 1,792 #          |
| PAR                  | 0.673 W/m²       |
| PPFD                 | 2.951 μmol/s⋅m²  |
| RGB Hex              |                  |
| Saturation %         |80%                  |

I'm running ESPHome in Home Assistant with HAOS on a RPi 4.
Let me know how I can help.

**Comment by freshykr** [comment]
> [@latonita](https://github.com/latonita) Hello, 1st time contributing to an open source project, so please, bear with me if I'm not following some proper guidelines yet.
> 
> I'm very interested in this feature request and would be happy to help with it if I'm being guided. I do have bought a couple of those sensors.
> 
> In esphome, I've set it that way:
> 
> external_components:
>   - source:
>       type: git
>       url: https://github.com/latonita/esphome
>       ref: as7343
>     components: [as734x]
> sensor:
>   - platform: as734x
>     type: AS7343
>     gain: X4
>     atime: 29
>     astep: 299
>     update_interval: 5s
> 
>     # Raw integer counts per channel
>     counts:
>       f1:
>         name: "380nm"
>       f2:
>         name: "415nm"
>       fz:
>         name: "445nm"
>       f3:
>         name: "480nm"
>       f4:
>         name: "515nm"
>       fy:
>         name: "555nm"
>       f5:
>         name: "590nm"
>       fxl:
>         name: "630nm"
>       f6:
>         name: "680nm"
>       f7:
>         name: "730nm"
>       f8:
>         name: "910nm"
>       nir:
>         name: "NIR"
>       clear:
>         name: "Clear"
> 
>     # Calculated outputs
>     illuminance:
>       name: "Illuminance (Lux)"
>     irradiance:
>       name: "Irradiance (W/m²)"
>     ppfd:
>       name: "PPFD"
>     irradiance_par:
>       name: "PAR"
>     color_temperature:
>       name: "CCT"
>     saturation_level:
>       name: "Saturation %"
>     rgb_hex:
>       name: "RGB Hex"
> `RGB Hex` remains empty. Also, about the 380nm, I believe I do not have any UV indeed at the moment (256 is a suspicious number bit-wise!).
> 
> This is the result I have right now:
> 
> Sensor	Value
> 380nm	256 #
> 415nm	1,792 #
> 445nm	3,584 #
> 480nm	2,816 #
> 515nm	4,096 #
> 555nm	5,376 #
> 590nm	2,304 #
> 630nm	4,608 #
> 680nm	3,328 #
> 730nm	1,024 #
> 910nm	1,536 #
> CCT	6,709 K
> Clear	7,552 #
> Illuminance (Lux)	199 lx
> Irradiance (W/m²)	0.763 W/m²
> NIR	1,792 #
> PAR	0.673 W/m²
> PPFD	2.951 μmol/s⋅m²
> RGB Hex	
> Saturation %	80%
> I'm running ESPHome in Home Assistant with HAOS on a RPi 4. Let me know how I can help.

Let you know that you've helped me.

good boy broaw..

**Comment by Garklein** [comment]
@harpi4 I think I got the RGB output working: https://github.com/Garklein/esphome/commit/f11549c1eb55ab1726eb2ef14571cadb73e94ad6

Though I'm not exactly sure how to test it, hopefully the values are reasonable (and correct)!

Edit: tested, it works well (shining a flashlight on the surface then using the sensor outputs the right RGB).

**Comment by freshykr** [comment]
@latonita @harpi4 @goatboynz

I built upon your work,
using it for indoor plant cultivation to test light spectrums.
My assistant, Victor (Geminay), and I addressed some "as7343" hardware limitations,
by writing code to compensate. It might not be 100% accurate, but it works, for $18.

My apologies, this translation was done using translate.google.co.th.
If you can't read it, blame translate.google

#How to Use#
Use to measure the brightness of LED lights in indoor grow lighting.
If you are using it to measure other types of light intensity, you may need to change the "gain: X" value accordingly. There is a switch to toggle between "gain: 0.5" and "gain: 16".
"gain: 0.5" is used to measure visible spectrum  such as PPFD.
"gain: 16" is used to measure special spectrums such as UVA and FAR-RED.

If you don't have a PPFD meter and a LUX meter,
you can take the sensor as7343 displayed PPFD value and multiply it by 3.5,
and the Illuminance (Lux)  multiplied by <s>2</s> -> 3.9 , 
_***edit:** If it's not within the specified saturation(200%-222%), this value may be inaccurate. we recommend using it with the VEML7700 or your mobile-phone (eg. luxmeter app)._ 
based on a saturation value of 222%.
This will give you an approximate true value.

and..

This includes displaying the results in Spectrum Card format.
https://community.home-assistant.io/t/spectrum-card/949555

My assistant and I have fixed your Spectrum Card, so it works with the 7343 sensor.
Please perform a manual installation of the Spectrum Card.
And replace the original .js file in the link with the existing one.


h77ps://drive.google.com/file/d/1bMDzH3eZNBTTesbX91c6bHX6_ViYj_mi/view?usp=sharing

<img width="558" height="503" alt="Image" src="https://github.com/user-attachments/assets/038da2d9-6ee5-43b4-bb36-fa8c65df5ab2" />

I'm not very good with Kitub and community functions. This is more convenient for me.
You can try it out.

- bugfix 730nm 590nm offset and include multiplied value PPFD and Illuminance 5/6/2026
```
esphome:
  name: light-sensor
  friendly_name: light-sensor

esp32:
  variant: esp32c3
  flash_size: 4MB
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "goodboy broawww"

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5dBm

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true

sensor:
  - platform: veml7700
    address: 0x10
    update_interval: 5s
    auto_mode: false
    gain: 1/8x
    integration_time: 100ms
    ambient_light:
      name: "Illuminance"
    full_spectrum:
      name: "Full Spectrum Illuminance"

  - platform: as734x
    type: AS7343
    id: my_as7343
    gain: X0.5
    atime: 29
    astep: 599
    update_interval: 5s

    counts:
      f1: { name: "380nm Raw", id: raw_380nm, internal: false }
      f2: { name: "415nm Raw", id: raw_415nm, internal: false }
      fz: { name: "445nm Raw", id: raw_445nm, internal: false }
      f3: { name: "480nm Raw", id: raw_480nm, internal: false }
      f4: { name: "515nm Raw", id: raw_515nm, internal: false }
      fy: { name: "555nm Raw", id: raw_555nm, internal: false }
      f5: { name: "590nm Raw", id: raw_590nm, internal: false }
      fxl: { name: "630nm Raw", id: raw_630nm, internal: false }
      f6: { name: "680nm Raw", id: raw_680nm, internal: false }
      f7: { name: "730nm Raw", id: raw_730nm, internal: false }
      f8: { name: "910nm Raw", id: raw_910nm, internal: false }
      nir: { name: "NIR Raw", id: raw_nir, internal: false }
      clear: { name: "Clear Raw", id: raw_clear, internal: false }

    illuminance:
      name: "Illuminance (Lux)"
      filters:
        - multiply: 3.9
      accuracy_decimals: 0

    ppfd:
      name: "PPFD"
      filters:
        - multiply: 3.5
      accuracy_decimals: 0

    irradiance:
      name: "Irradiance (W per m²)"
      accuracy_decimals: 3

    irradiance_par:
      name: "PAR"
      accuracy_decimals: 3
        
    color_temperature:
      name: "CCT"
      internal: true
    saturation_level:
      name: "Saturation %"
    rgb_hex:
      name: "RGB Hex Internal"
      internal: true

  - platform: template
    name: 380nm
    id: as7343_380nm
    lambda: |-
      return id(raw_380nm).state <= 768.0 ? 0.0 : id(raw_380nm).state;
    update_interval: 5s
    unit_of_measurement: counts
  - platform: template
    name: 415nm
    id: as7343_415nm
    lambda: |-
      return id(raw_415nm).state <= 256.0 ? 0.0 : id(raw_415nm).state;
    update_interval: 5s
    unit_of_measurement: counts
  - platform: template
    name: 445nm
    id: as7343_445nm
    lambda: |-
      float raw_b = id(raw_445nm).state;
      float raw_g = id(raw_515nm).state;
      if (raw_b <= 256.0) return 0.0;
      if (raw_g <= 256.0) raw_g = 0.0;
      if (isnan(raw_b) || isnan(raw_g)) return 0.0;

      float leak = raw_g * 0.0616;
      float net = (raw_b - leak) * 0.89;
      return (net > 0.0 ? net : 0.0);
    update_interval: 5s
    unit_of_measurement: counts
  - platform: template
    name: 480nm
    id: as7343_480nm
    lambda: |-
      float raw_480 = id(raw_480nm).state;
      float raw_g = id(raw_515nm).state;
      if (raw_480 <= 256.0) return 0.0;
      if (raw_g <= 256.0) raw_g = 0.0;
      if (isnan(raw_480) || isnan(raw_g)) return 0.0;

      float leak = raw_g * 0.0640;
      float net = raw_480 - leak;
      return net > 0.0 ? net : 0.0;
    update_interval: 5s
    unit_of_measurement: counts
  - platform: template
    name: 515nm
    id: as7343_515nm
    lambda: |-
      float raw_g = id(raw_515nm).state;
      float raw_b = id(raw_445nm).state;
      if (raw_g <= 256.0) return 0.0;
      if (raw_b <= 256.0) raw_b = 0.0;
      if (isnan(raw_g) || isnan(raw_b)) return 0.0;

      float leak = raw_b * 0.0833;
      float net = raw_g - leak;
      return net > 0.0 ? net : 0.0;
    update_interval: 5s
    unit_of_measurement: counts
  - platform: template
    name: 555nm
    id: as7343_555nm
    lambda: |-
      float raw_555 = id(raw_555nm).state;
      float raw_b   = id(raw_445nm).state;
      float raw_r   = id(raw_680nm).state;
      if (raw_555 <= 256.0) return 0.0;
      if (raw_b <= 256.0) raw_b = 0.0;
      if (raw_r <= 256.0) raw_r = 0.0;
      if (isnan(raw_555) || isnan(raw_b) || isnan(raw_r)) return 0.0;

      float leak_b = raw_b * 0.1042;
      float leak_r = raw_r * 0.0719;
      float net = raw_555 - leak_b - leak_r;
      return net > 0.0 ? net : 0.0;
    update_interval: 5s
    unit_of_measurement: counts
  - platform: template
    name: 590nm
    id: as7343_590nm
    lambda: |-
      float raw_590 = id(raw_590nm).state;
      float raw_r   = id(raw_680nm).state;
      float raw_g   = id(raw_515nm).state;
      float raw_b   = id(raw_445nm).state;
      float raw_ir  = id(raw_730nm).state;

      if (raw_r  <= 256.0) raw_r = 0.0;
      if (raw_g  <= 256.0) raw_g = 0.0;
      if (raw_b  <= 256.0) raw_b = 0.0;

      if (raw_590 <= 256.0) return 0.0;
      if (isnan(raw_590) || isnan(raw_r) || isnan(raw_g) || isnan(raw_b) || isnan(raw_ir)) return 0.0;

      ESP_LOGD("viktoros_ecu", "--- 590nm Raw Signal Captured: %.1f counts ---", raw_590);

      bool red_led_on = (raw_r > 30000.0);

      float pure_ir = raw_ir - 768.0;
      if (red_led_on) pure_ir -= 1024.0;
      if (pure_ir < 0.0) pure_ir = 0.0;

      bool ir_led_on = (pure_ir > 256.0);

      float net = raw_590;

      if (red_led_on) net -= 8448.0;

      if (ir_led_on) {
        float leak_ir_coeff = (pure_ir < 1300.0) ? 2.6500 : 2.0541;
        net -= pure_ir * leak_ir_coeff;
      }

      return net > 0.0 ? net : 0.0;
    update_interval: 5s
    unit_of_measurement: counts
  - platform: template
    name: 630nm
    id: as7343_630nm
    lambda: |-
      float raw_630 = id(raw_630nm).state;
      float raw_b = id(raw_445nm).state;
      float raw_g = id(raw_515nm).state;
      if (raw_630 <= 256.0) return 0.0;
      if (raw_b <= 256.0) raw_b = 0.0;
      if (raw_g <= 256.0) raw_g = 0.0;
      if (isnan(raw_630) || isnan(raw_b) || isnan(raw_g)) return 0.0;

      float leak_b = raw_b * 0.0078;
      float leak_g = raw_g * 0.1884; 

      float net = raw_630 - leak_b - leak_g;
      return net > 0.0 ? net : 0.0;
    update_interval: 5s
    unit_of_measurement: counts
  - platform: template
    name: 680nm
    id: as7343_680nm
    lambda: |-
      float raw_680 = id(raw_680nm).state;
      float raw_ir = id(raw_730nm).state;
      if (raw_680 <= 256.0) return 0.0;
      if (raw_ir <= 768.0) raw_ir = 0.0; 
      if (isnan(raw_680) || isnan(raw_ir)) return 0.0;

      float leak_ir = raw_ir * 0.0769;
      float net = raw_680 - leak_ir;

      return (net > 0.0 ? net : 0.0) * 0.78;
    update_interval: 5s
    unit_of_measurement: counts
  - platform: template
    name: 730nm
    id: as7343_730nm
    lambda: |-
      return id(raw_730nm).state <= 768.0 ? 0.0 : id(raw_730nm).state;
    update_interval: 5s
    unit_of_measurement: counts
select:
  - platform: template
    name: "AS7343 Gain Selector"
    id: gain_selector
    icon: "mdi:tune"
    optimistic: true
    options: ["X0.5", "X16"]
    initial_option: "X0.5"
    set_action:
      lambda: |-
        if (x == "X0.5") id(my_as7343).set_gain(as734x::Gain::GAIN_0_5X);
        else id(my_as7343).set_gain(as734x::Gain::GAIN_16X);
        id(my_as7343).update();
        id(gain_selector).publish_state(x);
```

**Comment by JaneDoe84** [comment]
@latonita 

Hello latonia,
i send you an email right now, did not found this section first.
maybe the infos are here better for all to see, so i post them here too:

**Open-Source Photosynthetically Active Radiation Sensor for Enhanced Agricultural and Agrivoltaics Monitoring:**
research work with full as7341 esp32 project code and some interesting calibration ways.
example calibration data for mars hydro 1000 vs 500$ par sensor
https://www.preprints.org/manuscript/202504.1750
this one use a normal transparent diffusor, like plastic from cd-cover.

**PAR-Light-Sensor:**
https://github.com/ryan-ext/PAR-Light-Sensor
research work with full as7341 project code
based on this research with spiderfarmer se1000:
https://www.ctahr.hawaii.edu/oc/freepubs/pdf/FST-68.pdf
this one use a 6mm (1/4 inch) opal white plexi diffusor

**ESP32 + AS7341 Ambient Light Sensor for Home Assistant**
https://github.com/yimeng-tong/outdoor_light_sensor
examples for calucalating LUX values.

im actual working on a way to let the as7341 calculate ppfd too.
the first project seems the best, as the diffusor is more easy to get.
in case your work by using it in home office, the different usage cases like indoor/outdoor would also be nice.
there is also code to calibrate the sensor, in case a user have a pricy par sensor to compare.
best case would be if the home office com. can share later calibrated data, so over time for a lot lights theres data.
or the infos can help you, make your caluclation better.

what diffusor did you use on your code ?

**Comment by latonita** [comment]
@freshykr wow, spectrum card is fantastic! i used to use just bar chart.
can you please give an overview whats the logic behind the calculations in the yaml? I would be happy to integrate that


@JaneDoe84 i dont have proper diffusor anymore, so i can't normally test spectral sensors.

**Comment by JaneDoe84** [comment]
> [@JaneDoe84](https://github.com/JaneDoe84) i dont have proper diffusor anymore, so i can't normally test spectral sensors.

Ah so if i understand correct, the AS7341 need a diffusor and the AS7343 not ?
I wonder because i see in your Code a formula to calculate ppfd values.
I see the section were i need to enter the glass values, but im unsure how to get them.
Is there some kind of guide how to use the sensor in home assistant with your code ?

**Comment by JaneDoe84** [comment]
@freshykr 
> 
> I built upon your work, using it for indoor plant cultivation to test light spectrums. My assistant, Victor (Geminay), and I addressed some "as7343" hardware limitations, by writing code to compensate. It might not be 100% accurate, but it works, for $18.

What kind of diffusor (Material, Size) do you use ?
Any information on this would be very helpfull.
Thank you !

**Comment by latonita** [comment]
> > [@JaneDoe84](https://github.com/JaneDoe84) i dont have proper diffusor anymore, so i can't normally test spectral sensors.
> 
> Ah so if i understand correct, the AS7341 need a diffusor and the AS7343 not ? I wonder because i see in your Code a formula to calculate ppfd values. I see the section were i need to enter the glass values, but im unsure how to get them. Is there some kind of guide how to use the sensor in home assistant with your code ?

Both AS7341 and AS7343 require diffusors to work reliably. Well with multiple sensors has sharp and high edges and any direct light produces shadows and affects measurement.

**Comment by JaneDoe84** [comment]
@latonita Thank you very much; I've managed to get it working in the meantime.
Thank you so much, I've got it working now. I coded new functions and I use 6 mm thick, opal-white Plexiglas as Diffusor; most online shops send out a free sample, for which you only have to cover the shipping costs.
I came up with a simple way to calibrate the sensor for this. It now works with any LED lamp once calibrated, and you don't need an expensive measuring device or a smartphone app for the calibration.

**Comment by skynetforcats** [comment]
Also interested in AS7343 getting implemented :)

**Comment by freshykr** [comment]
@latonita 
I know absolutely nothing about YAML, haha. Sorry! Because mostly I give ideas and have my assistant Viktor (Gemini) translate them into code.
But it's probably similar to expanding the sensor's perception range while using graphs, but either way, you've kept your code's core excellent. 😂
The little things you do are significant, like the butterfly effect theory.
If you tell me "I couldn't get any bigger," I'll tell you this is how to get any bigger... ッ

@JaneDoe84 
Most standard materials are opaque plastic or acrylic; we just need to find the correct compensation. And as Latonita mentioned,
if you don't use a light diffuser, the measurement won't be accurate because the sensor will be blocked by the sharp, high edges of the light. In my case, I use a plastic template sheet spread along the entire length of my grow system because the lights I use are custom-made. My plants use light in the 390nm and 730nm range, so I needed an AS7373 sensor. Finally, it's good that you can make these sensors yourself; most of them are expensive.
And we only use them once during the initial setup of the grow system.

The research link you sent is interesting. We're trying to prove that with inexpensive tools, we can overcome their limitations using coding, if there's a way to do so. For indoor plant cultivation, just the measuring tools could cost around $780.

**Comment by latonita** [comment]
please test https://github.com/esphome/esphome/pull/18012

**Comment by latonita** [comment]
AS7343 support is landing now. The original PR (esphome/esphome#6285) was closed for being too large, so the work is split into three smaller PRs that stack in order:

- **1/3** — esphome/esphome#17038 — the unified `as734x` component: AS7341 and AS7343 behind one platform, selected with `type:`, publishing the raw per-channel counts.
- **2/3** — esphome/esphome#18011 — basic counts, calibration (dark current, channel correction, glass attenuation factor), saturation level, LED control.
- **3/3** — esphome/esphome#18012 — illuminance (lux), irradiance, photopic irradiance, PAR, PPFD, colour temperature and RGB.

Each builds on the one before it, so #17038 merges first. Splitting it this way keeps each review small; the end result covers everything #6285 did.

Testing and feedback are very welcome. @harpi4's readings posted on #6285 turned out to pin down two real bugs, both now fixed: the channel data was byte-swapped (which is why every raw count came out as a multiple of 256, and why saturation reported 84% when it was really under 1%), and the RGB output stayed empty whenever the tristimulus sum went negative.

One thing worth repeating for anyone comparing against a lux or PAR meter: both parts sit in a deep well with sharp edges, so a diffuser is needed for sensible readings. Without one the absolute values depend heavily on where the lamp is. On my own bench two sensors side by side under the same lamp read 991 lx and 1833 lx purely because of position. The component ships with `glass_attenuation_factor: 1.0` and that setting is the per-installation trim; it scales lux, irradiance and PPFD together and leaves colour temperature and RGB untouched.

**Comment by latonita** [comment]
<img width="825" height="995" alt="Image" src="https://github.com/user-attachments/assets/c31c6ebf-9b14-474d-bce5-721e35f61348" />

**Comment by latonita** [comment]
@JaneDoe84 @freshykr can you try the latest version + hass chart? 
PR https://github.com/esphome/esphome/pull/18012
docs here https://deploy-preview-7123--esphome.netlify.app/components/sensor/as734x/

**Comment by harpi4** [comment]
@latonita 

If this helps (otherwise, let me know what I can do):

Tested PR #18012 with an AS7343 on ESP32

```yaml
external_components:
  - source: github://pr#18012
    components: [as7341, as734x]
    refresh: 1h

defaults:
  sensor_name: "AS7343 Spectral"
  sensor_id: as7343_spectral
  sensor_i2c_id: bus_a
  sensor_address: 0x39

  sensor_gain: X4
  sensor_atime: 29
  sensor_astep: 599
  sensor_update_interval: 30s
  sensor_normalize_basic_counts: "ALL"
  sensor_glass_attenuation_factor: "1.0"

  sensor_f1_internal: false
  sensor_f2_internal: false
  sensor_fz_internal: false
  sensor_f3_internal: false
  sensor_f4_internal: false
  sensor_fy_internal: false
  sensor_f5_internal: false
  sensor_fxl_internal: false
  sensor_f6_internal: false
  sensor_f7_internal: false
  sensor_f8_internal: false
  sensor_nir_internal: false
  sensor_clear_internal: false

  sensor_f1_basic_internal: false
  sensor_f2_basic_internal: false
  sensor_fz_basic_internal: false
  sensor_f3_basic_internal: false
  sensor_f4_basic_internal: false
  sensor_fy_basic_internal: false
  sensor_f5_basic_internal: false
  sensor_fxl_basic_internal: false
  sensor_f6_basic_internal: false
  sensor_f7_basic_internal: false
  sensor_f8_basic_internal: false
  sensor_nir_basic_internal: false
  sensor_clear_basic_internal: false

  sensor_illuminance_internal: false
  sensor_irradiance_internal: false
  sensor_irradiance_photopic_internal: false
  sensor_ppfd_internal: false
  sensor_irradiance_par_internal: false
  sensor_color_temperature_internal: false
  sensor_saturation_internal: false
  sensor_rgb_hex_internal: false

sensor:
  - platform: as734x
    type: AS7343
    id: ${sensor_id}
    i2c_id: ${sensor_i2c_id}
    address: ${sensor_address}
    gain: ${sensor_gain}
    atime: ${sensor_atime}
    astep: ${sensor_astep}
    update_interval: ${sensor_update_interval}
    normalize_basic_counts: ${sensor_normalize_basic_counts}

    calibration:
      glass_attenuation_factor: ${sensor_glass_attenuation_factor}
```

The package was instantiated with all spectral raw/basic channels plus NIR exposed:

```yaml
packages:
  spectral_as7343: !include
    file: esphome_packages/spectral_sensor_as7343.yaml
    vars:
      sensor_name: "AS7343"
      sensor_id: as7343
      sensor_i2c_id: bus_a
      sensor_f1_basic_internal: false
      sensor_f2_basic_internal: false
      sensor_fz_basic_internal: false
      sensor_f3_basic_internal: false
      sensor_f4_basic_internal: false
      sensor_fy_basic_internal: false
      sensor_f5_basic_internal: false
      sensor_fxl_basic_internal: false
      sensor_f6_basic_internal: false
      sensor_f7_basic_internal: false
      sensor_f8_basic_internal: false
      sensor_nir_internal: false
```

Observed AS7343 values:
Channel | Raw | Basic
-- | -- | --
380 nm | 192 | 0.075043
415 nm | 769 | 0.299683
445 nm Blue | 908 | 0.345205
480 nm | 491 | 0.186228
515 nm Green | 1286 | 0.477870
555 nm | 2316 | 0.836398
590 nm | 638 | 0.224530
630 nm Red | 2309 | 0.845075
680 nm Deep Red | 2007 | 0.743402
730 nm Far Red | 779 | 0.281218
910 nm NIR | 119 | 0.041118
NIR | 94 | 0.035797
Clear | 2717 | 1.000000

Derived values:
- Saturation: 15.2%
- Illuminance: 43,236 lx
- Irradiance: 127.71 W/m²
- Irradiance Photopic: 63.30 W/m²
- PAR: 135.73 W/m²
- PPFD: 622.1 µmol/m²/s
- CCT: 3,844 K
- RGB Hex: `#c49c7c`

The sensor initialized and is producing readings successfully with PR #18012.

I also noticed this compiler warning during the build:

```text
../src/esphome/components/as734x/as734x.cpp:37:13: warning:
'const char* esphome::as734x::{anonymous}::model_name(esphome::as734x::Model)'
defined but not used [-Wunused-function]
```

Apart from this unused-function compiler warning, the build completed and the AS7343 is working correctly.

I use `JGS1 Quartz Glass` as a cover for the sensor.
