### ISSUE TITLE
Trigger BLE Scan on Demand

### ISSUE THREAD

**Issue by OkhammahkO** [esphome/feature-requests#261]
**Describe the problem you have/What new integration you would like**

- Add component.update support for esp32_ble_tracker sensors.

- I want to be able to trigger a scan on demand as an alternative to setting short scan intervals which kills my 2.4GHZ.

I guess this would look like:
```
binary_sensor:
  - platform: ble_presence
    mac_address: C1:DE:8E:XX:YY:58
    id: mibandpresence_1
    name: "Presence MiBand EntryESP"

script:
  - id: update_ble
    then:
      - component.update: mibandpresence_1
      - lambda: 'id(mibandpresence_1).update();'
```

**Please describe your use case for this integration and alternatives you've tried:**

- I would use a xiaomi motion detector positioned outside my apartment and pointing at the elevator door to first detect motion (they do this very fast), and then trigger an "arrival scan" for my BLE devices to confirm it is me approaching the door. Then my ESP32 would unlock my smart lock (already working).

- I tried component.update but I think it failed on compile, so I guess it's not supported?

**Additional context**
ESPHome is awesome. Thanks.

Home assistant Q:
https://community.home-assistant.io/t/esphome-ble-scanner-arrival-presence-detection-trigger-a-scan-on-demand/114911
