### ISSUE TITLE
Add component for BL0910 energy IC

### ISSUE THREAD

**Issue by MarcoCITA** [esphome/feature-requests#2618]
**Describe the problem you have/What new integration you would like**

Add support for the BL0910 integrated circuit
**Please describe your use case for this integration and alternatives you've tried:**

Component for IC BL0910 not present.
**Additional context**

**Comment by latonita** [comment]
are there any devices or breadboards easily available ?

**Comment by MarcoCITA** [comment]
I don't tink. I only see the [kincony M30](https://www.kincony.com/esp32-energy-monitor-board.html) (code and schematic on the bottom of the page). Also saw these repositoryes correlated to esp and the ic [BL0940 Energy Meter w Arduino](https://github.com/mcmchris/BL0940-Energy-Meter-w-Arduino) and [CircuitSetup Expandable 6 Channel ESP32 Energy Meter](https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter). Don't know if it can help.

**Comment by JustNoot** [comment]
I have ordered the PCBs and looked around for some custom components. Looks simple enough, but I will update in a week.
Here is the board:
![image](https://github.com/esphome/feature-requests/assets/3305753/a89f5005-5c63-46b4-9644-681c449797f6)

**Comment by MarcoCITA** [comment]
![PCB](https://github.com/esphome/feature-requests/assets/53432302/a49f6d5a-877a-466d-9235-a5a9b4849f2d)
Here is mine, hope it works :)

**Comment by yiannosi** [comment]
> I have ordered the PCBs and looked around for some custom components. Looks simple enough, but I will update in a week. Here is the board: ![image](https://private-user-images.githubusercontent.com/3305753/312747072-a89f5005-5c63-46b4-9644-681c449797f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDE4MzksIm5iZiI6MTcxNTQwMTUzOSwicGF0aCI6Ii8zMzA1NzUzLzMxMjc0NzA3Mi1hODlmNTAwNS01YzYzLTQ2YjQtOTY0NC02ODFjNDQ5Nzk3ZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMDQyNTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmVjYWIwNmQ3ZjQ0NGQzNGJlZTczZDYzNWEyZTk4M2IyM2UyNTA2MWIzZjBlMGJiMmM4MGE4ZTA5NjhjOTM5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l1oMwG8ADdUBcPB1Ral8kVIs2J3DrqEsmEWloS7zhCo)

@latonita 
Look real professional!
How did it go? Did it work?
By the way.. care to share the schematic?

**Comment by JustNoot** [comment]
@yiannosi  https://github.com/JustNoot/10CH-Energy-Meter The schematic is available.
The boards arrived but we decided that this will be better as a Modbus device. For context I am creating a company with a friend and we essentially make smart homes for people. The places we did so far presented us with some challenges that could have been solved easier with a bus system instead of WiFi. So our products will be mainly Modbus and CAN based with an ESP32 controller for smart home integration if needed, this way it could be used in industrial settings as a standalone device with standardized communication. I will open source the schematic and code after testing is done.
![image](https://github.com/esphome/feature-requests/assets/3305753/0f08bf64-9710-46e6-ba85-eea3540b58ea)
![image](https://github.com/esphome/feature-requests/assets/3305753/f4ade9eb-0681-4da2-b94f-5978a219c59b)

**Comment by yiannosi** [comment]
> @yiannosi https://github.com/JustNoot/10CH-Energy-Meter The schematic is available.
> The boards arrived but we decided that this will be better as a Modbus device. For context I am creating a company with a friend and we essentially make smart homes for people.

Thanks for the link.
I am also using an RS485 link for most of my home automation devices. This requires wiring when the house was built and I have used cat5e. However for those cases that there is no provision for wiring, I use wifi.

**Comment by jimmyw** [comment]
Hi, i got a branch with a working bl-0910 implementation.

Plan to clean it up, and send a PR.
Please help me test it.

https://github.com/jimmyw/esphome/tree/bl0910/esphome/components/bl0910

Example here: https://github.com/jimmyw/esphome/blob/bl0910/bl-0910/bl-0910.yml

**Comment by jimmyw** [comment]
Here is my board, is designed to be a 4 unit din rail, and they have angled pin headers, that connects up to 6 modules in serial. It was cheaper to produce pcb this way, than produce one that had 30 channels in one.

https://github.com/jimmyw/energymeter/

![image](https://github.com/user-attachments/assets/0d575dc5-d855-404b-89a6-55ddc058edc6)

https://github.com/jimmyw/energymeter/blob/main/energymeter.pdf

**Comment by MarcoCITA** [comment]
@jimmyw what is "MAGIC1 = 12875.0f;" in your code and how can i set the CT rateo in esphome .yaml file?

**Comment by jimmyw** [comment]
The  magics are from the app node, got a google translated version here:
https://github.com/jimmyw/energymeter/blob/main/datasheets/BL0910%20APP%20Note_V1.02-eng.pdf
And the chineese:
https://www.belling.com.cn/media/file_object/bel_product/BL0910/datasheet/BL0910%20APP%20Note_V1.02.pdf

Putting them side by side, makes you able to get the formulas out.

I am currently working on to set the CT-Ratio directly in the yml file per clamp. You also need to specify the burden resistor value, as these some times are included in the CT-Clamp and some times on the pcb.

**Comment by yiannosi** [comment]
Nice design.
i made a similar one based for a 3phase energy meter. It supports Operation of BL0910 on 3U6I mode. It would be nice to be able to configure  this mode on esphome as well.

**Comment by jimmyw** [comment]
Contributions is always welcome!

**Comment by jimmyw** [comment]
@MarcoCITA Have another look now in my repo, added so you can adjust reference values in the yml file, and also described the formula with examples from 3 different schematics.

**Comment by jimmyw** [comment]
@yiannosi I removed all assumptions that we are running in 1U10I mode, so now by setting the correct register BL0910_REG_MODE in setup(), this should work with no issues.

I can help you get it working, but then you need to send me a meter to test on :)

**Comment by jimmyw** [comment]
FYI. Opened up a draft PR https://github.com/esphome/esphome/pull/7402
Needs final testing, and documentation before ready to merge.

**Comment by jesserockz** [comment]
@jimmyw Please make sure you have seen my comment on your PR 
https://github.com/esphome/esphome/pull/7402#issuecomment-2325789347

**Comment by jimmyw** [comment]
@jesserockz, @athom-tech, @tarontop  Bad timing, i forked dev and started working on this just this weekend and did not know about the bl0906. (I just searched for bl0910)

They are similar chips, but all the conversions and register values are different, so some kind of abstraction is needed to support both in the same sensor. My sensor was much more basic written. Also the 0906 sensor is UART based and not SPI, even if the chip supports both.

Another thing with the 0906 sensor is all the constants are compiled in assuming burden resistor values, and turns on the CT clamp, i designed mine so you calculate the values and insert them in the yml.

To be honest, i just got my little project up running and working now, i`m not sure i have the time/energy to try to merge this two sensors into one, so i think i need some help from you in that case.

Was hoping just to document and wrap it up, and share in case someone else was interested.

If someone likes to pick this up, or at least help to get started?

**Comment by jesserockz** [comment]
No, of course. I only wrote that comment in haste to make sure you were aware of it. Since they are quite different it seems then they can stay separate. But please use a similar config structure and update the sensors in a similar way (1 channel per `loop()`)

Ill try leave some inline comments/sugestions on the PR

**Comment by jimmyw** [comment]
@jesserockz 
I found so many different kind of schematics using this chip, its also supports multiple modes, measuring 1 X Voltage and 10 X Current, or 3 x Votlage, and 6X Current.

Also all the surrounding component choices, and the type of current clamps makes all values differ.
I decided to just add a multiplier ref field to every sensor, documenting on how to calculate the values clearly in the documentation.

The other sensor (bl0906) seems to be written with a specific product in mind. Not sure how esphome handle this kind of situations, but i think it would be great with some kind of inheritance system when you can declare a specific product implementation, or just the raw sensor.

Also, kind of great if you could do the constants calculation in the python layer, so that you only assign const values to the code generating the project.

**Comment by MarcoCITA** [comment]
@jimmyw Tried running the component with the RP2040 but i get `[bl0910:341]: Checksum error calculated: 68 != read: 0` for every measure.
![Log](https://github.com/user-attachments/assets/73f6a182-fb31-4fdb-b273-7a0ef7b027f8)

This is the the code with the ref values for my board.
```
esphome:
  name: misuratore-energia
  friendly_name: misuratore-energia

rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

external_components:
  - source: github://pr#7402
    components: [ bl0910 ]

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    id: my_ota
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 
    gateway: 
    subnet: 
  power_save_mode: none

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19
  miso_pin: GPIO16

# BURDEN1 = 3.3 ohm (R2)
# BURDEN2 = 100.0 ohm (R33)
# BURDEN3 = 110.0 kohm (R36 + R37 + R38 + R39 + R40 + R41)
# CT_TURNS = 1000.0

# IREF = (12875.0 * 3.3) / (1.097 * 1000 / 1000.0) = 38730,628988149
# UREF = (13162.0 * 100.0) / (1.097 * 110000 ) = 10,9074334963
# PREF = (40.4125 * 3.3 * 100.0 * 1000.0 / 1000) / (1.097 * 1.097 * 110000) = 0,1007450501
# EREF = (3600000.0 * 16.0 * 0,1007450501) / (4194304.0 * 0.032768 * 16.0) = 2,6388601717

sensor:
  - platform: bl0910
    update_interval: 1s
    cs_pin: GPIO17

    # In mode 0, channel 11 is the voltage reference
    voltage_11:
      name: BL0910 RMS Voltage
      uref: 10.9074334963
    current_1:
      name: BL0910 Current 1
      iref: 38730.628988149
    current_2:
      name: BL0910 Current 2
      iref: 38730.628988149
    current_3:
      name: BL0910 Current 3
      iref: 38730.628988149
    current_4:
      name: BL0910 Current 4
      iref: 38730.628988149
    current_5:
      name: BL0910 Current 5
      iref: 38730.628988149
    current_6:
      name: BL0910 Current 6
      iref: 38730.628988149
    current_7:
      name: BL0910 Current 7
      iref: 38730.628988149
    current_8:
      name: BL0910 Current 8
      iref: 38730.628988149
    current_9:
      name: BL0910 Current 9
      iref: 38730.628988149
    current_10:
      name: BL0910 Current 10
      iref: 38730.628988149

    active_power_1:
      name: BL0910 Active Power 1
      pref: 0.1007450501
    active_power_2:
      name: BL0910 Active Power 2
      pref: 0.1007450501
    active_power_3:
      name: BL0910 Active Power 3
      pref: 0.1007450501
    active_power_4:
      name: BL0910 Active Power 4
      pref: 0.1007450501
    active_power_5:
      name: BL0910 Active Power 5
      pref: 0.1007450501
    active_power_6:
      name: BL0910 Active Power 6
      pref: 0.1007450501
    active_power_7:
      name: BL0910 Active Power 7
      pref: 0.1007450501
    active_power_8:
      name: BL0910 Active Power 8
      pref: 0.1007450501
    active_power_9:
      name: BL0910 Active Power 9
      pref: 0.1007450501
    active_power_10:
      name: BL0910 Active Power 10
      pref: 0.1007450501

    energy_1:
      name: BL0910 Energy 1
      eref: 2.6388601717
    energy_2:
      name: BL0910 Energy 2
      eref: 2.6388601717
    energy_3:
      name: BL0910 Energy 3
      eref: 2.6388601717
    energy_4:
      name: BL0910 Energy 4
      eref: 2.6388601717
    energy_5:
      name: BL0910 Energy 5
      eref: 2.6388601717
    energy_6:
      name: BL0910 Energy 6
      eref: 2.6388601717
    energy_7:
      name: BL0910 Energy 7
      eref: 2.6388601717
    energy_8:
      name: BL0910 Energy 8
      eref: 2.6388601717
    energy_9:
      name: BL0910 Energy 9
      eref: 2.6388601717
    energy_10:
      name: BL0910 Energy 10
      eref: 2.6388601717

    power_factor_1:
      name: BL0910 PowerFactor 1
    power_factor_2:
      name: BL0910 PowerFactor 2
    power_factor_3:
      name: BL0910 PowerFactor 3
    power_factor_4:
      name: BL0910 PowerFactor 4
    power_factor_5:
      name: BL0910 PowerFactor 5
    power_factor_6:
      name: BL0910 PowerFactor 6
    power_factor_7:
      name: BL0910 PowerFactor 7
    power_factor_8:
      name: BL0910 PowerFactor 8
    power_factor_9:
      name: BL0910 PowerFactor 9
    power_factor_10:
      name: BL0910 PowerFactor 10

    frequency:
      name: BL0910 Frequency
    temperature:
      name: BL0910 Temperature
```

**Comment by jimmyw** [comment]
Looks like spi error, try lowering the speed and see if that helps

**Comment by MarcoCITA** [comment]
> Looks like spi error, try lowering the speed and see if that helps

Ok, problem solved. I wired incorrectly the PCB. One more question, i wired a 60W light bulb but i get 60.000W(60Kw). Current measured seems ok but with wrong power values i get wrong energy and power factor values.
![Misuratore](https://github.com/user-attachments/assets/03d441ed-c443-4d6c-beb9-201df0d53329)

**Comment by jimmyw** [comment]
I think your IREF is wrong, Maybe you entered kohms instead of ohms somewhere?
Try divide your iref value by 10k

I documented the formulas here:
https://deploy-preview-4221--esphome.netlify.app/components/sensor/bl0910.html

**Comment by yiannosi** [comment]
> Contributions is always welcome!
I am developing code for arduno on ESP32. Have no experience for development  for ESPHome
However i have an issue for 3U6I mode of operation:
The frequency doesnt get reported properly! 
I suspect the reason is that the chip's Vp,Vn inputs are not used in this mode (as opposed to single phase 1U10I) since the phase voltages are measured in inputs 8,9,10 instead.

Anyone has any other ideas?

**Comment by jimmyw** [comment]
You need to configure the correct mode (3U6I) using the MODE register in the init function. Else it will think it meassures current on the pins instead of voltage i guess.

**Comment by yiannosi** [comment]
> You need to configure the correct mode (3U6I) using the MODE register in the init function. Else it will think it meassures current on the pins instead of voltage i guess.

Yes I already did that. 
`bl0910_write_data(BL0910_REG_MODE, 0x08, 0x00, 0x00);   // set 3U6I mode , bit [19] =1`
I can measure correct voltage on the voltage pins according to 3U6I .
The only problem is the frequency which appears either zero or some other wrong value.

**Comment by MarcoCITA** [comment]
> I think your IREF is wrong, Maybe you entered kohms instead of ohms somewhere? Try divide your iref value by 10k
> 
> I think power of ct 2 and 3, should means 3W and 5W, and that is probably within the error margin for this chip.
> 
> I documented the formulas here: https://deploy-preview-4221--esphome.netlify.app/components/sensor/bl0910.html

By dividing iref i get wrong currents.
I multiplied UREF*1000; PREF*1000 and EREF*1000 and it's shows correct values, the remaining thing that doesn't seem to work is PowerFactor values, when mains is disconnected it shows 450°, when i power i light bulb it shows 2.370° and when powering up a blender it shows random values >200° and then gets stuck at that value even when blender is off.

**Comment by MarcoCITA** [comment]
Component seems to be working. Only one "problem", when rebooting the microcontroller the energy values to home assistant return to 0kwh. It's possible to implement something like "restore_mode: RESTORE_LAST_VALUE” so values don't get to 0?

**Comment by jimmyw** [comment]
There is no flash state on the chip, so it will reset. I think that homeassistant will detect an handle this case counting up energy.

Not sure how other devices handle it.

**Comment by MarcoCITA** [comment]
I found another annoying thing. With my PV panels when power flows from inverter to grid power goes to negative values (and it's correct) but energy increases the same way when I'm getting power from grid. It's possible to get 2 entity from esphome one for energy to grid and one for energy to grid?.
Tankyou.

![Image](https://github.com/user-attachments/assets/982e2b04-8c4a-4967-874f-686d655137a6)
![Image](https://github.com/user-attachments/assets/0b677124-34f2-4a02-b51b-f075c40293b3)

**Comment by Roving-Ronin** [comment]
@MarcoCITA , Did you solve this ?

> Component seems to be working. Only one "problem", when rebooting the microcontroller the energy values to home assistant return to 0kwh. It's possible to implement something like "restore_mode: RESTORE_LAST_VALUE” so values don't get to 0?

If not, have a look at this code for an Athom Smart Plug, or specifically the 'sub yaml section' that is called with the sensors. 
At Line 78 it creates a global ---> https://github.com/Roving-Ronin/myHomeAssistant/blob/dfc3514f30bd68e297aaf2695649e29c590335cb/esphome/sensors/athom-power-plugs.yaml#L78

```
globals:
  - id: total_energy
    type: float
    restore_value: yes
    initial_value: '0.0' 
```

At https://github.com/Roving-Ronin/myHomeAssistant/blob/dfc3514f30bd68e297aaf2695649e29c590335cb/esphome/sensors/athom-power-plugs.yaml#L229   Theres an internal sensor used to calculate the Energy being used and that updates the energy total global reading (which is the value you want to keep between reboots and reflashing updates and only resets to 0 if you do a factory reset of the device) 

```
    energy:
      name: "Energy"
      id: energy
      unit_of_measurement: kWh
      accuracy_decimals: 3      
      filters:
        - throttle: ${sensor_update_interval}
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
      on_value:
        then:
          - lambda: |-
              static float previous_energy_value = 0.0;
              float current_energy_value = id(energy).state;
              id(total_energy) += current_energy_value - previous_energy_value;
              previous_energy_value = current_energy_value;
              id(energy_total_sensor).update();
      internal: true
```

As the above sensor needs to be hidden/ internal as its a lambda that calculates and updates the global. We then have a final sensor (Enery Total Sensor) that publishes the value of the global.
https://github.com/Roving-Ronin/myHomeAssistant/blob/dfc3514f30bd68e297aaf2695649e29c590335cb/esphome/sensors/athom-power-plugs.yaml#L311

```
  - platform: template
    name: "Energy - Total"
    id: energy_total_sensor
    unit_of_measurement: kWh
    device_class: "energy"
    state_class: "total_increasing"
    accuracy_decimals: 3
    icon: "mdi:lightning-bolt"
    lambda: |-
      return id(total_energy);
    web_server:
      sorting_group_id: group_energy
      sorting_weight: 6
```

Hopefull this is of assistance to work out for storing the value you want to remain and not reset to 0 all the time :-)
