### ISSUE TITLE
Configuration Types - feature to overwrite existing sensor filters

### ISSUE THREAD

**Issue by Masterz69** [esphome/feature-requests#2621]
**Describe the problem you have/What new integration you would like**
At moment `!extend` add entries for specified configuration `id` (if not exists) or replace (if exists, f.e. that happens with `name`).

For `sensor` `filters` it add entries at the end of existing list of filters.
So, right now IMHO not possible to replace f.e. `lambda` in `filters`.

I've got both `lambda`s one by one - from included file and specified in `!extend`. See below.
No yet checked another filters - is `!extend` will change f.e. `quantile` settings or just add one more at the end.

Would be nice to have possibility to overwrite sensor filters entries from included configuration.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

```yaml
sensor:
  - platform: whatever
    id: xxx
    filters:
      - lambda: return x*2;
```
``` yaml
packages:
  xxx: !include xxx.yaml

sensor:
  - id: !extend xxx
    filters:
      - lambda: return x*3;
```

Result so far:
``` yaml
sensor:
  - id: !extend xxx
    filters:
      - lambda: return x*2;
      - lambda: return x*3;
```
