### ISSUE TITLE
Expiry/Timeout for esp32_ble_tracker sensors - already opened request but closed with workaround #1687

### ISSUE THREAD

**Issue by gryzli133** [esphome/feature-requests#2637]
**Describe the problem you have/What new integration you would like**
platform: pvvx_mithermometer is missing attribute: expire_after

**Please describe your use case for this integration and alternatives you've tried:**
I use a lot of Xiaomi BLE sensors around my house. After disconnection there is no information about problem with the signal, just showing last valid value -> normally the sensors go to unavailable. F.E. Last reported temperature from outside was in the morning, but all day long the same temperature is shown. 

**Additional context**
sensor:
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:1D:07:1B"
    temperature:
      name: "BLE Biuro Temperature"
    humidity:
      name: "BLE Biuro Humidity"
    battery_level:
      name: "BLE Biuro Battery-Level"
    battery_voltage:
      name: "BLE Biuro Battery-Voltage"
    signal_strength:
      name: "BLE Biuro Signal"      
    expire_after: 300s #Not possible to compile with this option...

**Comment by nagyrobi** [comment]
See: https://esphome.io/components/sensor/#timeout

```yaml
sensor:
- platform: pvvx_mithermometer
  mac_address: "A4:C1:38:B1:CD:7F"
  temperature:
    name: "PVVX Temperature"
    filters:
      - timeout: 300s 
  humidity:
    name: "PVVX Humidity"
    filters:
      - timeout: 300s
```

sent value will be NaN after timeout (_unknown_).
