### ISSUE TITLE
Setting domain for multiple wifi networks

### ISSUE THREAD

**Issue by alexiri** [esphome/feature-requests#2651]
**Describe the problem you have/What new integration you would like**
When configuring multiple wifi networks for a device, we should also be able to configure different domains. Each network may have a different domain and it makes little sense that it can't be set per network. Essentially, I'd like to be able to do this:

```
wifi:
  networks:
  - ssid: FirstNetworkToConnectTo
    password: VerySafePassword
    domain: .home
  - ssid: SecondNetworkToConnectTo
    password: VerySafePassword
    domain: .work.com
```

**Please describe your use case for this integration and alternatives you've tried:**
Right now you've got to pick a single domain for all networks and just assume that the device won't work correctly in the others.

**Additional context**
