### ISSUE TITLE
Add support for Hynetek HUSB238 USB Power Delivery (PD) controller

### ISSUE THREAD

**Issue by lboue** [esphome/feature-requests#2674]
**Describe the problem you have/What new integration you would like**

Add support for Hynetek HUSB238 USB Power Delivery (PD) controller.
The [Hynetek HUSB238](https://en.hynetek.com/2421.html) is a highly integrated USB Power Delivery (PD) controller as sink role for up to 100W power rating. The HUSB238 is compatible with PD3.0 and Type-C V1.4, and it can also support Apple Divider 3, BC1.2 SDP, CDP and DCP while the source is attached.

**Please describe your use case for this integration and alternatives you've tried:**

Remote control of a circuit's supply voltage with [Adafruit USB Type C Power Delivery Dummy Breakout](https://www.adafruit.com/product/5807) boad.

**Additional context**

Arduino Library
 * [Adafruit_HUSB238](https://github.com/adafruit/Adafruit_HUSB238)

**Comment by latonita** [comment]
so how do you want to use it? 
what features you want from the component?

**Comment by lboue** [comment]
> so how do you want to use it? 
> 
> what features you want from the component?
> 
> 

I would set the desired PD voltage and current using i2c bus.

**Comment by latonita** [comment]
> > so how do you want to use it? 
> > 
> > what features you want from the component?
> > 
> > 
> 
> I would set the desired PD voltage and current using i2c bus.

Please elaborate)
Is it one time pre pre-built in yaml or some dynamic?

Please propose config of your dream. :)

**Comment by lboue** [comment]
> > > so how do you want to use it? 
> > > 
> > > what features you want from the component?
> > > 
> > > 
> > 
> > I would set the desired PD voltage and current using i2c bus.
> 
> Please elaborate)
> Is it one time pre pre-built in yaml or some dynamic?
> 
> Please propose config of your dream. :)
> 
> Any data this device produces so we need to show it as sensor? 

I'd like to use a selector to dynamically choose the voltage value.

Values can be read back for display.

**Comment by lboue** [comment]
I found 2 other libraries for that chip:

- https://github.com/Duckle29/HUSB238
- https://github.com/luoluomeng/HUSB238Driver

**Comment by latonita** [comment]
OK, good. I had no time yet to look deeper into this, but already manage to make base for the componenet

**Comment by lboue** [comment]
> OK, good. I had no time yet to look deeper into this, but already manage to make base for the componenet

@latonita Thank you for your time. Don't hesitate to make the branch public so that I can contribute too.

**Comment by latonita** [comment]
@lboue you may try what is there so far

```

external_components:
  - source: github://pr#6693
    refresh: 10s
    components:
      - husb238

husb238:
  id: husb_01

binary_sensor:
  - platform: husb238
    attached: "PD Attached"

sensor:
  - platform: husb238
    voltage: "Contracted Voltage"
    current: "Contracted Current"
    selected_voltage: "Selected Voltage"

text_sensor:
  - platform: husb238
    status: "Last request status"
    capabilities: "Capabilities"

```
