### ISSUE TITLE
Add SPI Support for BMP388 and BMP390

### ISSUE THREAD

**Issue by shingle01** [esphome/feature-requests#2680]
**Describe the problem you have/What new integration you would like**

As per feature request #1321 

BMP388 and BMP390 sensors supports I2C as well as SPI but ESPHome currently supports only I2C for it. It would be great if SPI support was added for this sensor as well.

**Please describe your use case for this integration and alternatives you've tried:**

Same as above

**Additional context**

Same as above

**Comment by latonita** [comment]
@shingle01 do you own i2c or spi?

**Comment by shingle01** [comment]
The BMP388 I have supports both.

**Comment by latonita** [comment]
Okay, I will take care of this in upcoming days  if you can test

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by latonita** [comment]
@shingle01 
try new PR
```
esphome:
  name: bmp3xx-test

esp32:
  board: esp32dev
  framework:
    type: arduino

# esp8266:
#   board: nodemcuv2

logger:
  level: DEBUG


external_components:
  - source: github://pr#6652
    refresh: 10s
    components: [bmp3xx_base, bmp3xx_i2c, bmp3xx_spi]

spi:
  clk_pin: 19
  mosi_pin: 20
  miso_pin: 21

i2c:
  sda: GPIO14
  scl: GPIO26
  scan: true
  frequency: 5kHz

sensor:
  - platform: bmp3xx_spi
    cs_pin: 13
    temperature:
      name: "Outside Temperature"
      oversampling: 16x
    pressure:
      name: "Outside Pressure"
    update_interval: 60s
  - platform: bmp3xx_i2c
    address: 0x77
    temperature:
      name: "Outside Temperature"
      oversampling: 16x
    pressure:
      name: "Outside Pressure"
    update_interval: 60s
```
