### ISSUE TITLE
Add support for WeAct Studio 1.54 Inch Epaper Module EPD

### ISSUE THREAD

**Issue by lboue** [esphome/feature-requests#2697]
**Describe the problem you have/What new integration you would like**

Add support for WeActStudio.EpaperModule: [WeAct Studio 1.54 Inch Epaper Module EPD](https://github.com/WeActStudio/WeActStudio.EpaperModule/tree/master) (ref GDEH0154D67).

- 200x200 pixels
- 3.3V I/O
- 4 lines SPI
- SSD1681

![3](https://github.com/esphome/feature-requests/assets/938089/eeb34c67-da7b-44c9-a0bb-1cefff52eb8c)

**Additional context**

- [WeAct-EpaperModule-1.54 Board Shape.pdf](https://github.com/WeActStudio/WeActStudio.EpaperModule/blob/master/Hardware/WeAct-EpaperModule-1.54%20Board%20Shape%20%E5%A4%96%E5%BD%A2.pdf)
- [EpaperModuleTest_Arduino_ESP32C3.ino](https://github.com/WeActStudio/WeActStudio.EpaperModule/blob/master/Example/EpaperModuleTest_Arduino_ESP32C3/EpaperModuleTest_Arduino_ESP32C3.ino): demo Arduino sketch
- [GxEPD2](https://github.com/ZinggJM/GxEPD2): GxEPD2 Arduino Display Library for SPI E-Paper Displays

**WeAct boards**
- [Add support for 2.9" WeAct 3 color epaper display #6226](https://github.com/esphome/esphome/pull/6226)
- [add support for weact eink (2.13 maybe 2.9) #2101](https://github.com/esphome/feature-requests/issues/2101)

**Comment by latonita** [comment]
@lboue Hi, did you try waveshare epaper component?
I suppose it shall work with ssd1681

**Comment by latonita** [comment]
@lboue This display finally came to me from aliexpress... and it properly works with existing component.

I attached it to my esp32dev module like this:

```yaml

spi:
  clk_pin: GPIO18 # scl
  mosi_pin: GPIO23 # sda

display:
  - platform: waveshare_epaper
    model: 1.54inv2
    cs_pin: GPIO17
    dc_pin: GPIO22
    reset_pin: GPIO19
    busy_pin: GPIO21
    update_interval: 15s
    full_update_every: 30
    lambda: |-
      it.print(10, 10, id(font1), "Hello World!");
```

I might update documentation so it will include WeAct name so it can be found by search function on the site.
