### ISSUE TITLE
Add note to documentation re deep sleep

### ISSUE THREAD

**Issue by sandybrownlee** [esphome/feature-requests#2719]
**Describe the problem you have/What new integration you would like**

Add a note like this to the deep sleep component page:
some devices, e.g. D1 mini, need GPIO7 pulled high for deep sleep to function  currently. This post:
[[GeoX234](https://github.com/GeoX234) commented [on Mar 27](https://github.com/esp8266/Arduino/issues/6007#issuecomment-2024041618)] suggests connecting GPIO7/SD0/MISO via 10k resistor to 3.3v as a fix. This worked for me.

**Please describe your use case for this integration and alternatives you've tried:**

The device won't wake up from deep sleep, though there is a dim flash of the blue activity LED at the time it should wake up. soldering the 10k resistor causes wake up to run correctly.

**Additional context**

**Comment by jkufner** [comment]
Something similar for M5 coreInk. It shutdowns completely in deep sleep and does not wake up. To prevent the loss of power, it requires to set the pin 12 to high, so that the power is not cut.

`````yaml
esphome:
  on_boot:
    then:
       - lambda: |-
          pinMode(GPIO_NUM_12, OUTPUT);
          digitalWrite(GPIO_NUM_12, HIGH);
          gpio_hold_en(GPIO_NUM_12);
`````

It would be really nice to have in the docs. It would save me a lot of time.
