### ISSUE TITLE
Add option to not prepend friendly_name to Home Assistant entities

### ISSUE THREAD

**Issue by DrBlokmeister** [esphome/feature-requests#2732]
**Describe the problem you have/What new integration you would like**

When adding a friendly_name to a device, this name is displayed in the ESPHome dashboard, improving user friendliness. However, this also prepends the friendly_name to entities in Home Assistant. When using a configuration like:
```yaml
substitutions:
  device_name: "Plug Electric Car"

esphome:
  friendly_name: ${device_name}

sensor:
  - platform: total_daily_energy
    name: "${device_name} Energy Today"
    power_id: "power"
```
Home Assistant will add the entity sensor.plug_electric_car_plug_electric_car_energy_today, which is unwanted.

It would be nice if we got the option to disable prepending of the friendly_name to any entities in Home Assistant.

**Please describe your use case for this integration and alternatives you've tried:**

Currently two options are available: 
- not using friendly name, which makes the ESPHome dashboard look more ugly.
- Not manually prepending the device name to the entities. However, when I have many entities referring to the same packaged file (such as network diagnostics) and these entities do not have a friendly name defined, suddenly the naming of the sensor would just be sensor.wifi_signal for a random device.

**Additional context**

I was a bit unsure if this is an ESPHome feature request or a Home Assistant feature request. If I'm in the wrong category, please let me know.
