### ISSUE TITLE
Add ability to restore valve state on reboot

### ISSUE THREAD

**Issue by olafz** [esphome/feature-requests#2739]
**Describe the problem you have/What new integration you would like**
I would like to see the ability to restore a valve state on bootup. This proposed feature is similar to what is already possible with a switch (`restore_mode`).

**Please describe your use case for this integration and alternatives you've tried:**
I have two valves that I control via ESPHome. In my case, I have setup a template valve that controls two separate switches (one to close the valve, one to open the valve). This works flawlessly, with one exception: the state of the valve does not survive a reboot. So for example; if I close a valve and reboot the ESP, the valve reports as open again.

I've tried to "fix" this with global variables and lambdas, but the far-more easy way would be to have the `restore_mode` also for valves.

Portion of the relevant config:

```yaml
...

valve:
  - platform: template
    id: air_inlet
    open_action:
      - switch.turn_off: close_air_inlet
      - switch.turn_off: open_air_inlet
      - delay: 100ms
      - switch.turn_on: open_air_inlet
      - valve.template.publish:
        id: air_inlet
        current_operation: OPENING
      - delay: 180s # valve takes a while to fully open
      - switch.turn_off: open_air_inlet
      - valve.template.publish:
        id: air_inlet
        current_operation: IDLE
        state: OPEN
    close_action:
      ...

```

**Additional context**

**Comment by olafz** [comment]
After diving [into the source code](https://github.com/esphome/esphome/blob/release/esphome/components/template/valve/template_valve.h#L10-L14), I _think_ this should work with

```yaml
valve:
  - platform: template
    ...
    restore_mode: RESTORE
```
