### ISSUE TITLE
Speaker Request for external option remove speaker

### ISSUE THREAD

**Issue by comet424** [esphome/feature-requests#2741]
**Describe the problem you have/What new integration you would like**

id like to see  option for remote speaker option under the
```
speaker:   
```
not just is2 
this way i can have a microphone on the the desk...  and i could output to multiple speakers  as as 
```
group.whatever
```
or a single speaker  sitting on the ceiling  so it could be louder...   and this way you can have multiple   microphones in a single room  and they all out to 1 Single big speaker on the ceiling..   

so you could have 5 microhpones in 1 room and they all link to 1 speaker on the ceiling  not to the specific esp device
**Please describe your use case for this integration and alternatives you've tried:**

id like to see under the 
```
speaker:
```
option to use a remote speaker  like a another wifi speaker  so when using the voice assistant  you dont need a speaker on the the device.. just a mic... and you can output to like
```
voice_assistant:
  microphone: mic
  use_wake_word: true
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0
  speaker: big_speaker
  id: assist
sensor:
  - platform: homeassistant
    id: big_speaker
    entity_id: media_player.speaker_3_esphome_i2s_media_player
```

**Additional context**
