### ISSUE TITLE
Support for Display Driver: EK9716BD3 & EK73002ACGB

### ISSUE THREAD

**Issue by lboue** [esphome/feature-requests#2745]
**Describe the problem you have/What new integration you would like**

Support for Display Driver: EK9716BD3 & EK73002ACGB

**Please describe your use case for this integration and alternatives you've tried:**

[CrowPanel 7.0" -HMI ESP32 Display 800x480 RGB TFT LCD Touch Screen](https://www.elecrow.com/esp32-display-7-inch-hmi-display-rgb-tft-lcd-touch-screen-support-lvgl.html)

**Additional context**

**Comment by lboue** [comment]
I'm currently testing with this with ESPHome [RPI_DPI_RGB Display Driver](https://esphome.io/components/display/rpi_dpi_rgb#rpi-dpi-rgb-display-driver) component. I hope it will work but I'm not sure.

**Comment by lboue** [comment]
I've finally managed to get something on my [Elecrow CrowPanel 7.0"](https://www.elecrow.com/esp32-display-7-inch-hmi-display-rgb-tft-lcd-touch-screen-support-lvgl.html):

```
#-------------------------------------------
# Touchscreen gt911 i2c
#-------------------------------------------
touchscreen:
  platform: gt911
  id: my_touchscreen
  display: my_display
  interrupt_pin: 38

i2c:
  sda: 19
  scl: 20
  scan: true

display:
  - platform: rpi_dpi_rgb
    id: my_display
    data_pins:
      red:
        - 14
        - 21
        - 47
        - 48
        - 45
      green:
        - 9
        - 46
        - 3
        - 8
        - 16 
        - 1
      blue:
        - 15
        - 7
        - 6
        - 5
        - 4
    de_pin: 41
    hsync_pin: 39
    vsync_pin: 40
    pclk_pin: 0

    hsync_front_porch: 40
    hsync_pulse_width: 48
    hsync_back_porch: 13

    vsync_front_porch: 1
    vsync_pulse_width: 31
    vsync_back_porch: 13

    pclk_inverted: true
    pclk_frequency: 8500000

    color_order: RGB

    auto_clear_enabled: false
    update_interval: 5s
    dimensions:
      width: 800
      height: 480
```

**Comment by koma6379** [comment]
Hello,
I have a question,
can you post the whole yaml?
Thanks Matthias

**Comment by boussouira** [comment]
@lboue Do other things work on this CrowPanel 7.0 board? It's by far the cheapest and seem well made

**Comment by AndyDann** [comment]
Hi, I would also be grateful if you could post your full yaml. I have just purchased a 7" version and having problems integrating your code that you mentioned works.
With thanks
Andy

**Comment by AndyDann** [comment]
After some "playing" I have now been able to get the 7" CrowPanel board (v3) working with LVGL

Here's my code for reference... you'll need to change the images of course from my code.

Hope this helps someone and thanks for the above code.

`esphome:
  name: "crowpanel7"
  friendly_name: CrowPanel 7
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio
  #  board_upload.maximum_ram_size: 524288

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    #version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz
  
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "AIdWswWRR5YSvp7Itw7qPNe5WmkBqWoszqfjWgEuCNI="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: github://pr#7184
    refresh: 10min
    components: [lvgl]

# Define a PWM output on the ESP32
output:
  - platform: ledc
    pin: 2
    frequency: 1220
    id: gpio_backlight_pwm

light:
  - platform: monochromatic # Define a monochromatic, dimmable light for the backlight
    output: gpio_backlight_pwm
    name: CrowPanel7 Backlight
    id: back_light
    restore_mode: ALWAYS_ON

i2c:
  sda: 19
  scl: 20
  scan: true

display:
  - platform: rpi_dpi_rgb
    id: main_display
    data_pins:
      red:
        - 14        #r1
        - 21        #r2
        - 47        #r3
        - 48        #r4
        - 45        #r5
      green:
        - 9         #g0
        - 46        #g1
        - 3         #g2
        - 8         #g3
        - 16        #g4
        - 1         #g5
      blue:
        - 15        #b1
        - 7         #b2
        - 6         #b3
        - 5         #b4
        - 4         #b5
    de_pin: 41
    hsync_pin: 39
    vsync_pin: 40
    pclk_pin: 0

    hsync_front_porch: 40
    hsync_pulse_width: 48
    hsync_back_porch: 13

    vsync_front_porch: 1
    vsync_pulse_width: 31
    vsync_back_porch: 13

    pclk_inverted: true
    pclk_frequency: 8500000

    color_order: RGB

    auto_clear_enabled: false # takes 2.8 seconds to clear the display
    update_interval: 5s

    dimensions:
      width: 800
      height: 480

image:

  - file: images/Solar_Battery.png
    id: solarbattery
    resize: 60x60
    type: RGB565   
    use_transparency: true

lvgl:
  log_level: INFO
  color_depth: 16
  bg_color: 0x000020
  border_width: 0
  outline_width: 0
  shadow_width: 0
  text_font: unscii_16
  align: center
  style_definitions:
    - id: font_style
      text_font: MONTSERRAT_32
      align: center
      text_color: 0xFFFFFF
      bg_opa: TRANSP
      bg_color: 0
      radius: 3
      pad_all: 2
 
  widgets:

    - button:
        x: 150
        y: 200
        width: 70
        height: 28
        id: btn_low
        checkable: false
        widgets:
          - label:
              align: center
              text_font: MONTSERRAT_18
              text: "Low"
    - image:
        x: 400
        y: 240
        id: weather_icon_today
        src: solarbattery


`

**Comment by heibertelf** [comment]
>     hsync_front_porch: 40
>     hsync_pulse_width: 48
>     hsync_back_porch: 13
> 
>     vsync_front_porch: 1
>     vsync_pulse_width: 31
>     vsync_back_porch: 13

I found EK9716BD datasheet, and it has different values:
![image](https://github.com/user-attachments/assets/ccc720a8-e6c6-4576-8fd9-770fb9d9c324)
so maybe for some displays this configuration could be more correct:
```
    hsync_front_porch: 40
    hsync_pulse_width: 48
    hsync_back_porch:  40

    vsync_front_porch: 13
    vsync_pulse_width: 1
    vsync_back_porch:  31

```

**Comment by jtbnz** [comment]
> > ```
> > hsync_front_porch: 40
> > hsync_pulse_width: 48
> > hsync_back_porch: 13
> > 
> > vsync_front_porch: 1
> > vsync_pulse_width: 31
> > vsync_back_porch: 13
> > ```
> 
> I found EK9716BD datasheet, and it has different values: ![image](https://github.com/user-attachments/assets/ccc720a8-e6c6-4576-8fd9-770fb9d9c324) so maybe for some displays this configuration could be more correct:
> 
> ```
>     hsync_front_porch: 40
>     hsync_pulse_width: 48
>     hsync_back_porch:  40
> 
>     vsync_front_porch: 13
>     vsync_pulse_width: 1
>     vsync_back_porch:  31
> ```
> 
> If I understand the matching values correctly, of course. Works fine with my 800[480 7' esp32 display ![image](https://github.com/user-attachments/assets/e458e0aa-befe-4a82-bbcc-d8a4fbf92327) ![image](https://github.com/user-attachments/assets/9b0da937-eac0-45e1-bbe3-b172ec590f5e)

Hi, I have the same viewe display and I am able to display and however the colors are 8bit did you have this problem?  

`# Touchscreen configuration
touchscreen:
  platform: gt911
  id: touch
  #interrupt_pin: 18 # no idea why but removing this made it work!
  reset_pin: 38
  calibration:
    x_min: 0
    x_max: 800
    y_min: 0
    y_max: 475

  on_touch:
    - lambda: |-
        ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
            touch.x,
            touch.y,
            touch.x_raw,
            touch.y_raw
            );

# I2C bus configuration
i2c:
  sda: GPIO19
  scl: GPIO20
  frequency: 100kHz
  scan: True

# Display configuration
display:
  - platform: rpi_dpi_rgb
    id: disp
    data_pins:
      red:
        - 14
        - 21
        - 47
        - 48
        - 45
      green:
        - 4
        - 16
        - 15
        - 7
        - 6
        - 5
      blue:
        - 1
        - 9
        - 46
        - 3
        - 8
    de_pin: 40
    hsync_pin: 39
    vsync_pin: 41
    pclk_pin: 42

    hsync_front_porch: 40 
    hsync_pulse_width: 48 
    hsync_back_porch: 40 

    vsync_front_porch: 13
    vsync_pulse_width: 1 
    vsync_back_porch: 31

    pclk_inverted: true
    #pclk_frequency: 16MHz
    color_order: RGB
    auto_clear_enabled: false
    update_interval: never
    dimensions:
      width: 800
      height: 480`

**Comment by jtbnz** [comment]
I gave up trying to get this to work on the VIEWE UEDX80480070E with the platform: rpi_dpi_rgb driver as it would ony display 16 colors.  For anyone else trying to get this to work, here is my working (for me!) external component.  The screen shot is using lvgl https://github.com/jtbnz/esphome_UEDX80480070ESP32

<img width="800" height="505" alt="Image" src="https://github.com/user-attachments/assets/03856054-7bd0-49ec-a75b-9660e5541ef7" />

Example yaml: 

```
external_components:
  - source:
      type: git
      url: https://github.com/jtbnz/esphome_UEDX80480070ESP32
      ref: main
    components: [viewe_display]
display:
  - platform: viewe_display
    id: my_display
    brightness: 100%
    rotation: 0
    auto_clear_enabled: false
```
