### ISSUE TITLE
Remote Receiver new protocols

### ISSUE THREAD

**Issue by skowron0** [esphome/feature-requests#2754]
**Describe the problem you have/What new integration you would like**

Hello, I have a 433MHz wireless doorbell from Zamel. Is there a chance to add a new protocol to rc_switch? I took a reading with Universal Radio Hacker and from what I see, the bit lasts about 1000us, synchronization: 1 high bit, 9 low bits. Can I somehow manually add the protocol in the yaml file?

**Please describe your use case for this integration and alternatives you've tried:**

If I add it, I can use it in HA automation.

**Additional context**

Attached is a dump from the Universal Radio Hacker program.

[doorbell_zamel.zip](https://github.com/user-attachments/files/15760361/doorbell_zamel.zip)

**Comment by skowron0** [comment]
Ok, working this:

 ```
 - platform: remote_receiver
    name: "Dzwonek brama"
    rc_switch_raw:
      code: '1110111001111101'
      protocol:
        pulse_length: 1050
        sync: [4, 1]
        zero: [1, 1]
        one: [3, 1]
        inverted: True
```

Can I somehow add this protocol to the receiver module so that I can see the code of another ringtone in the logs?
