### ISSUE TITLE
LTR390 different gain and resolution for ALS and UV

### ISSUE THREAD

**Issue by tgrosz** [esphome/feature-requests#2765]
**Describe the problem you have/What new integration you would like**

The LTR390 uses one gain and resolution setting for both ALS and UV measurements. Outdoors it's not the best solution.

**Please describe your use case for this integration and alternatives you've tried:**

I'd like to use smaller gain and resolution for ALS measurement outdoors, so that both ALS and UV measurements would be usable

**Additional context**

In arduino lib example code, they are used with different values
https://registry.platformio.org/libraries/levkovigor/LTR390/examples/ltr390/ltr390.ino

**Comment by latonita** [comment]
@tgrosz ltr390 doesnt support different gains for als/uv. That library is just switching gain and mode and then read data.
I think I can update the component to do similar approach.

**Comment by latonita** [comment]
@tgrosz try it.

Gain can be set as usual - same value for ALS and UV (
```yaml
    gain: X18
```
or granular
```yaml
    gain:
      ambient_light: X9
      uv: X3
```


```yaml
external_components:
 - source: github://pr#7026
   components: [ltr390]

sensor:
  - platform: ltr390
    uv_index:
      name: "UV Index"
    uv:
      name: "UV Sensor Counts"
    light:
      name: "Light"
    ambient_light:
      name: "Light Sensor Counts"
    gain:
      ambient_light: X9
      uv: X3
```

**Comment by tgrosz** [comment]
Hi @latonita , thanks - as I see it's working OK.
My idea was the same - to set the gain before reading the value

**Comment by latonita** [comment]
@tgrosz please test separate resolution. 
similarly:
```yaml
resolution:
  abient_light: 20
  uv: 13
```
