### ISSUE TITLE
Add support for Trotec Pac 2010 E A/C

### ISSUE THREAD

**Issue by marius-arch** [esphome/feature-requests#2786]
**Describe the problem you have/What new integration you would like**
I would like to control my A/C via infrared using the ESP Home IR Remote Climate. Currently my  Airconditioner is not supported.

**Please describe your use case for this integration and alternatives you've tried:**
Support for the Trotec PAC 2010 E would allow me integrating it into my HomeAssistant.

**Additional context**

**Comment by nagyrobi** [comment]
Did you try the `zhlt01` climate or protocol, or the `zhjg01` protocol from [IR Remote Climate](https://esphome.io/components/climate/climate_ir)? These are remotes used with many locally branded air conditioners.

**Comment by marius-arch** [comment]
Ok thank's, i will give that a try

**Comment by nagyrobi** [comment]
To try `zhjg01` you need this, until it's merged and released:
```
external_components:
  - source: github://pr#6996
    components: 
      - heatpumpir
    refresh: 5min
```
