### ISSUE TITLE
Climate IR support for Ferroli split unit

### ISSUE THREAD

**Issue by seven7seven** [esphome/feature-requests#2788]
**Describe the problem you have/What new integration you would like**

Support for IR control for Ferroli Split Units, ex. Ferroli Reflex C 12 UI split-type AC units, using the Climate component.

**Please describe your use case for this integration and alternatives you've tried:**

Tried the following integrations:
- midea_ir
- zhlt01
- daikin_ir
- also tried manually capturing IR signals, in both RAW and some formats that looked consistent (ex. AEHA)

No luck with any,

**Additional context**

Here's some additional info on the unit and remote (I was not able to find more online about models, protocols etc.), neither generically nor esphome-related.
![IMG_7230](https://github.com/esphome/feature-requests/assets/169333/1b741350-a84b-47f9-ab9d-d8540db1403d)
![IMG_7243](https://github.com/esphome/feature-requests/assets/169333/cf4e3b58-1525-49e0-8e8d-202ef71e4771)

Thank you!

**Comment by nagyrobi** [comment]
> Tried the following integrations:

Try also `zhjg01`. You need this, until it's merged and released:
```
external_components:
  - source: github://pr#6996
    components: 
      - heatpumpir
    refresh: 5min
```

**Comment by seven7seven** [comment]
> Try also `zhjg01`. You need this, until it's merged and released:

Thanks, just ran it with:

```
external_components:
  - source: github://pr#6996
    components: 
      - heatpumpir
    refresh: 5min

climate:
  - platform: heatpumpir
    horizontal_default: auto
    vertical_default: auto
    max_temperature: 30
    min_temperature: 16
    protocol: zhjg01
    name: "Bedroom AC"
    receiver_id: recvr
    transmitter_id: trans
    sensor: temperature
```

The on-board receiver does register pronto signals being sent, but as the others I've tried the AC does not operate.

The remote's pronoto codes are also quite different from the ones sent by the climate remote.

I assume it's some sort of othger standard, but have not been able to identify it.

Thanks!

**Comment by seven7seven** [comment]
Solved using:

```
climate:
  - platform: tcl112
    name: "Bedroom AC"
    transmitter_id: trans
```

Ferroli apparently uses the fuego protocol.
