### ISSUE TITLE
Update SGP4x to return raw VOC and raw NOX values

### ISSUE THREAD

**Issue by mericas** [esphome/feature-requests#2795]
**Describe the problem you have/What new integration you would like**

SGP4x reads a raw value from the device and uses it to update the VOC and/or NOX index which is an indicator of relative gas levels over time.  This is the standard usecase for environments where elevated gas levels are temporary.  If the elevated gas level continue for a long period, inside a 3D Printer chamber for example, the index will eventually drift toward 100.  I would like to expose the raw values to use them as an indicator of actual, not relative, gas levels.

**Please describe your use case for this integration and alternatives you've tried:**

I have a SGP40 sensor inside my 3D printer chamber and another one outside the chamber.  I want to monitor the effectiveness of my charcoal filter and also detect if any VOC is leaking to the room.  The index alone is helpful but for very long prints will start to move toward 100.

**Additional context**

**Comment by igiannakas** [comment]
I've had the same use case - have created a branch where I've successfully exported the raw value of the sensor. 

I haven't raised a PR as this needs testing. Would appreciate feedback!

You can use it like so:
1. Include the below external component in your config file which overrides the ESPHome sgp4x sensor
```
external_components:
  - source:
      type: git
      url: https://github.com/igiannakas/esphome
      ref: sgp40
    components: [ sgp4x ]
```
2. Output the sensor like so:

```
sensor:
  - platform: sgp4x
    i2c_id: bus_b
    update_interval: 2s
    voc:
      name: "VOC"
    voc_raw:
      name: "VOC - Raw"
    compensation:
      temperature_source: intake_temp
      humidity_source: intake_hum
```

Ultimately I want to use this to control my Stealthmax unit and its new servo vent flap via home assistant and via automated espHome code. Not there yet, but this was needed to be able to get consistent VOC readings that don't converge down to 100.

Here's how it looks in HA:

![Image](https://github.com/user-attachments/assets/ae325ad6-c52d-4345-a485-fa4d6e672b81)

**Please note that a higher sensor value -> cleaner air, from what I understand.** To use ideally you should identify a baseline value with an average measurement in clean air over say 12 hours, and then subtract that value from the VOC raw values.

For example like so:
```
    voc_raw:
      name: "Intake - VOC - Raw"
      filters:
        - lambda: return -(x - 31200);
```

If anyone tests this please do offer feedback!!
