### ISSUE TITLE
Allow homeassistant.service to submit arrays

### ISSUE THREAD

**Issue by kirichkov** [esphome/feature-requests#280]
**Describe the problem you have/What new integration you would like**

The homeassistant `device_tracker.see` service allows submission of GPS coordinates. These coordinates are submit as array with the elements - latitude and longitude. Currently when one adds an array to the `data` part of a `homeassistant.service` action gets an error:

```
string value cannot be dictionary or list.
gps: 
  - 00.000000
  - 11.000000
```

**Please describe your use case for this integration and alternatives you've tried:**

I'm firing up the homeassistant service `device_tracker.see` to integrate the ESPHome's BLE presence binary_sensor with the person's component. I've described my approach in https://github.com/esphome/feature-requests/issues/204

**Additional context**

Here's the config I have:
```
binary_sensor:
  - platform: ble_presence
    mac_address: AA:BB:CC:DD:EE:FF
    name: Tracked device
    id: tracked_device
    on_state:
      then:
        - if:
            condition: 
              binary_sensor.is_on: tracked_device
            then:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: tracked_device
                    location_name: 'home'
                    gps: [00.000000, 11.111111]
                    gps_accuracy: 10
            else:
              - homeassistant.service:
                  service: device_tracker.see
                  data:
                    dev_id: tracked_device
                    location_name: 'not_home'
```
