### ISSUE TITLE
Add support ST77916 RGB QSPI display

### ISSUE THREAD

**Issue by xiasi0** [esphome/feature-requests#2803]
Schematic diagram
[jc3636w518.zip](https://github.com/user-attachments/files/16201959/jc3636w518.zip)

**Comment by bitbank2** [comment]
I added support for this display to my bb_spi_lcd library. What functions does ESPHome need from the display library? Just pushing pixels? text? boxes?

**Comment by xiasi0** [comment]
[url](https://community.home-assistant.io/t/guition-4-480x480-esp32-s3-4848s040-smart-display-with-lvgl/729271)
This is equipment from the same brand
[url](https://esphome.io/components/display/qspi_amoled.html)
ESPHome should need to initialize this display.
ESPHome currently only supports qspi-amoled. qspi-lcd is not yet supported.

**Comment by xiasi0** [comment]
> [4848S040](https://community.home-assistant.io/t/guition-4-480x480-esp32-s3-4848s040-smart-display-with-lvgl/729271) This is equipment from the same brand [Quad SPI AMOLED Displays](https://esphome.io/components/display/qspi_amoled.html) ESPHome should need to initialize this display. ESPHome currently only supports qspi-amoled. qspi-lcd is not yet supported.

**Comment by xiasi0** [comment]
> I added support for this display to my bb_spi_lcd library. What functions does ESPHome need from the display library? Just pushing pixels? text? boxes?

[[4848S040](https://community.home-assistant.io/t/guition-4-480x480-esp32-s3-4848s040-smart-display-with-lvgl/729271)](https://community.home-assistant.io/t/guition-4-480x480-esp32-s3-4848s040-smart-display-with-lvgl/729271)
This is equipment from the same brand
[Quad SPI AMOLED Displays](https://esphome.io/components/display/qspi_amoled.html)
ESPHome should need to initialize this display.
ESPHome currently only supports qspi-amoled. qspi-lcd is not yet supported.

**Comment by bitbank2** [comment]
QSPI amoled and QSPI LCD are identical interfaces. The only difference will be the initialization sequence. I support both types in my bb_spi_lcd library.

**Comment by xiasi0** [comment]
> QSPI amoled and QSPI LCD are identical interfaces. The only difference will be the initialization sequence. I support both types in my bb_spi_lcd library.

Yes, currently ESPHome can initialize two display models, RM67162 or RM690B0。 I don't know how to reference your display library in ESPHome. Hope you can provide tips and assistance

**Comment by xiasi0** [comment]
> QSPI amoled and QSPI LCD are identical interfaces. The only difference will be the initialization sequence. I support both types in my bb_spi_lcd library.

```
display:
  - platform: qspi_amoled
    model: RM690B0
    data_rate: 80MHz
    spi_mode: mode0
    dimensions:
      width: 360
      height: 360
      offset_width: 16
    color_order: rgb
    invert_colors: false
    brightness: 255
    cs_pin: 10
    reset_pin: 47
    update_interval: never
    auto_clear_enabled: false
    id: my_display
```
I referenced the wrong display model, resulting in a complete display error
