### ISSUE TITLE
Allow lambdas in Remote transmitter Actions for `repeat` settings

### ISSUE THREAD

**Issue by nagyrobi** [esphome/feature-requests#2825]
**Describe the problem you have/What new integration you would like**
Trying to use lambdas in the `repeat` parameter: https://esphome.io/components/remote_transmitter#remote-transmitter-actions. This compiles but doesn't work:
```yaml
              - remote_transmitter.transmit_dooya:
                  repeat:
                    times: !lambda 'return id(timess).state;'
                    wait_time: !lambda 'return id(waittim).state;'
                  id: 0x009632B6
                  channel: 185
                  button: 5
                  check: 5 
```
It doesn't repeat the transmission, it sends it only once.

The IDs referenced in the lambdas are number components, which would offer a user interface to configure repeat parameters at runtime.

**Please describe your use case for this integration and alternatives you've tried:**
This, however, works:
```yaml
              - remote_transmitter.transmit_dooya:
                  repeat:
                    times: 3
                    wait_time: 100ms
                  id: 0x009632B6
                  channel: 185
                  button: 5
                  check: 5 
```
Transmission is repeated.

**Additional context**
I am checking the transmissions with a `remote_receiver` on another node.

Although the docs doesn't specifically state that these would be templatable variables, there's no error printed during compile when using templates. In ESPHome, when a configuration option is not templatable but a template is used, at compile it should error out, but here it doesn't. That leads the user to think templates should work.

I am submitting this as a feature request and not a bug, because instead of correcting the yaml parser to error out in this case, I'd rather like them to be templatable as described for my use case.
