### ISSUE TITLE
Allow micro_wake_word model to be set from a template select value

### ISSUE THREAD

**Issue by raetha** [esphome/feature-requests#2828]
**Describe the problem you have/What new integration you would like**
Trying to create a template select in Home Assistant that can set/change the wake word used by micro_wake_word. However when using what I believe is the proper lambda syntax to load the value, an error is generated when trying to install the new package.

I should add that when all current models are added to the micro_wake_word configuration, the device will respond to all of the wake words, not just the desired one. That would work if there was a way to enable/disable each wake word independently in some way that could be controlled from Home Assistant.

**Please describe your use case for this integration and alternatives you've tried:**
I'm using BigBobbas ESP32-S3-Box-3 configuration for a HA voice assistant that can also be a media receiver. Since the audience of users might have different preferences on wake word, I'm trying to assist with finding a way to make it selectable without having to recompile ESPHome to change and experiment with what someone likes best.

**Additional context**
Here is my YAML for micro_wake_word:
```
select:
  - platform: template
    entity_category: config
    name: Wake word model
    id: wake_word_model
    optimistic: true
    restore_value: true
    options:
      - alexa
      - hey_jarvis
      - hey_mycroft
      - okay_nabu
    initial_option: hey_jarvis
micro_wake_word:
  vad:
  models: 
    - model: !lambda 'return id(wake_word_model).state;'
```

Here are the logs when trying to install the configuration to the S3:
```
INFO ESPHome 2024.7.2
INFO Reading configuration /config/living-room-satellite.yaml...
INFO Updating https://github.com/gnumpi/esphome_audio@dev-next
INFO Detected timezone 'America/New_York'
Failed config

micro_wake_word: [source /config/living-room-satellite.yaml:650]
  vad: 
  models: 
    - 
      Not a valid model name, local path, http(s) url, or github shorthand.
      model: !lambda |-
        return id(wake_word_model).state;
```
