### ISSUE TITLE
USB UAC Support

### ISSUE THREAD

**Issue by netham45** [esphome/feature-requests#2842]
**Describe the problem you have/What new integration you would like**

I would like support for USB UAC audio devices on ESP32S2/ESP32S3.

**Please describe your use case for this integration and alternatives you've tried:**

esphome has no feature for USB audio as far as I know, however it could improve the number of quality audio output options available along with their ease of use. I am using a standalone project for it at the moment. I'm using an esp32s3 with a usb dongle dac for my own esp-idf project and it's been working well.

**Additional context**

https://github.com/esp-arduino-libs/ESP32_USB_Stream/ - Espressif Arduino library
https://components.espressif.com/components/espressif/usb_host_uac/versions/1.0.0 - esp-idf library

**Comment by nagyrobi** [comment]
_Note: For physical device with both microphone and speaker, the driver will treat it as two separate logic devices._

**Comment by ab-tools** [comment]
Hello ESPHome team,

I would be very interested in this feature!

I'm a developer myself, but no ESPHome coding experience, so while I'm very happy to support with any testing needed, probably I won't be able to implement this feature fully myself.

I do have a simple test with a ESP32-P4 and ESP-IDF directly running though and the USB UAC streams are detected at least (with the driver library @netham45 and @nagyrobi are referring to above).

To make this usable from ESPHome, I would expect the main part would be to add a new `platform: usb_audio` which would allow defining something like this:
```
usb_audio:
  - id: usb_output
  - id: usb_input

microphone:
  - platform: usb_audio
    id: usb_mics
    sample_rate: 16000
    bits_per_sample: 32bit
    i2s_audio_id: usb_input
    channel: stereo

speaker:
  - platform: usb_audio
    id: usb_audio_speaker
    sample_rate: 48000
```

Is there anything I could do to support getting USB UAC implemented in ESPHome?

Thanks a lot
Andreas
