### ISSUE TITLE
Support for MCP 23018 (similar to MCP 23017)

### ISSUE THREAD

**Issue by crgarcia12** [esphome/feature-requests#2848]
**Describe the problem you have/What new integration you would like**

`MCP23107` is a very popular IO port expander, but recently it has been discovered a bug that reduce the ports to 14 (for input)
There is a very similar working alternative: `MCP23108`

MCP23018 Datasheet: [](https://ww1.microchip.com/downloads/aemDocuments/documents/APID/ProductDocuments/DataSheets/MCP23018-Data-Sheet-DS20002103.pdf)
MCP23017 Datasheet: [] (https://ww1.microchip.com/downloads/aemDocuments/documents/APID/ProductDocuments/DataSheets/MCP23017-Data-Sheet-DS20001952.pdf)

**Please describe your use case for this integration and alternatives you've tried:**

I am working on two projects where I need 16 IOs:
A centralized light (and others) control system: [link](https://github.com/crgarcia12/electronics-homeassistant-lightscontroll)
A workbench controller: [link](https://github.com/crgarcia12/electronics-workbench-controller)

**Additional context**

**Comment by robin-thoni** [comment]
I just tested using an mcp23018 chip w/ an ESPHome mcp23017 hub, and it seems to work for now:
```
mcp23017:
  - id: mcp23018_relays
    address: 0x27
  - id: mcp23018_inputs
    address: 0x20

switch:
  - platform: gpio
    name: "Relay 1"
    pin:
      mcp23xxx: mcp23018_relays
      # Use pin A0
      number: 7
      mode:
        output: true
      inverted: true

binary_sensor:
  - platform: gpio
    name: "Input 1"
    pin:
      mcp23xxx: mcp23018_inputs
      number: 7
      # One of INPUT or INPUT_PULLUP
      mode:
        input: true
        pullup: true
      inverted: true
```

I'll report back if I find some features not working as expected.
