### ISSUE TITLE
Tuya Climate support Enum for Eco/Sleep Mode

### ISSUE THREAD

**Issue by dexn** [esphome/feature-requests#2849]
**Describe the problem you have/What new integration you would like**

Some Tuya thermostats use Tuya's 'mode' instruction set for Eco Mode and Sleep Mode (https://developer.tuya.com/en/docs/iot/f?id=K9gf45ld5l0t9). That is an Enum data type. 

I think it would be great if Tuya Climate supported something like
```
climate:
  - platform: tuya
    ...
    working_mode:
      eco:
        datapoint: 8
        off_value: 0
        on_value: 1
      sleep:
        datapoint: 7
        off_value: 0
        on_value: 1
```
which would then function the same as `eco_mode`.

**Please describe your use case for this integration and alternatives you've tried:**

I'm using `fan_mode` as a workaround since it supports Enum. 

**Additional context**

Personally, I'm only interested in the eco option. I just thought I should include the sleep option since that is the same situation and could arise in the future.
