### ISSUE TITLE
Add LVGL Multi-Display Per-Page Support

### ISSUE THREAD

**Issue by ConnorVG** [esphome/feature-requests#2873]
**Describe the problem you have/What new integration you would like**
We currently have an integration for LVGL that allows us to use the vast library to render components to our screens (such as meters to GC9A01 circular displays). Many displays utilize CS which allows us to have multiple displays on one device (awesome and already implemented in ESPHome). To my knowledge, which I have tried to research as much as possible, it is not currently possible to set a render target on a `lvgl.page.show` and also no way to have multiple `lvgl` base components in a yaml. With these two being true there is currently no way to have multiple displays on one ESP device with each display rendering a different LVGL page.

**Please describe your use case for this integration and alternatives you've tried:**
Dashboard displays and meter panels for nice measurement visibility of sensors. More than one screen allows for not having to use an ESP for each of the sensors that would want to be displayed in some fixed real life panel.

**Additional context**
I found this a limiting factor whilst designing a 3-display dashboard to fit under my monitor on my desk in the style of a "instrument cluster" such as the ones found in vehicles.

I've attached a reference image as an example of what I mean:
![{7FF701E2-1F5E-4A3D-8AF6-487CB7DCD6F9}](https://github.com/user-attachments/assets/faf9be9e-149d-4980-b9e3-6bf7b34f7ee9)

**Comment by ConnorVG** [comment]
@Greg-79 you can add multiple but they will currently show the same thing if using lvgl:
Each display needs defining in the display config section: https://esphome.io/components/display/#display-rendering-engine
LVGL config needs to have displays defined: https://esphome.io/components/lvgl/#main-configuration

**Comment by Greg-79** [comment]
Hi! On own esphome engine, I can connect both 4 and 5 displays by writing code under the lambda.  And how to register a second display in LVGL?

**Comment by clydebarrow** [comment]
> Where can I point to the second display?

Under the `displays:` key. 🤔 

```
lvgl:
  displays:
    - display_id: my_display
    - display_id: my_other_display
```

**Comment by clydebarrow** [comment]
@ConnorVG If you could try this out for your application that would be helpful.

**Comment by philpownall** [comment]
Oh, I should add to the above that I am able to use LVGL on two screens if I don't use pages.  But, pages are nice...

LVGL Definition:
```
lvgl:
  - id: lvgl_1
    displays: display_1
    buffer_size: 25%
    bg_color: black
    widgets:
      - slider:
          x: 4
          y: 26
          width: 110
          height: 8
          outline_width: 2
          outline_color: white
          outline_pad: 4
          id: slider1_id
          value: 20
          bg_color: black
          min_value: 10
          max_value: 30
  - id: lvgl_2
    displays: display_2
    buffer_size: 25%
    bg_color: black
    widgets:
      - slider:
          x: 6
          y: 28
          width: 110
          height: 8
          outline_width: 2
          outline_color: white
          outline_pad: 4
          id: slider2_id
          value: 0
          bg_color: black
          min_value: -30
          max_value: 30

```
