### ISSUE TITLE
Change user and password HTTP authentication on the Web Server Component

### ISSUE THREAD

**Issue by rp2019433** [esphome/feature-requests#2883]
**Describe the problem you have/What new integration you would like**
According to the Web Server Component documentation, it's possible to set a user and password to control who is allowed to access web interface.

https://esphome.io/components/web_server.html
```
# Example configuration entry
web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
```

But for an already deployed device, if this password has to be changed, a new ESPHome code has to be built and uploaded to the device. What may not be convenient.

**I was wondering if it's possible to create a feature "Change HTTP authentication user/password" on Web Server interface to allow a user to easily modify user/password from Web Server authentication.**

![image](https://github.com/user-attachments/assets/59dda932-d4a4-4ee5-9bfb-9055ed3a8162)

**Please describe your use case for this integration and alternatives you've tried:**
An already deployed device, if this password has to be changed, a new ESPHome code has to be built and uploaded to the device. What nay be not convenient.
For a simple user/password change, it would be achieved via Web Server interface.
