### ISSUE TITLE
Touch controller CST328

### ISSUE THREAD

**Issue by stream74** [esphome/feature-requests#2895]
I couldn't find any specific information about ESPHome integration for the CST328 touchscreen controller on the [Waveshare ESP32-S3-Touch-LCD-2.8 board](https://www.waveshare.com/esp32-s3-touch-lcd-2.8.htm)

There's a possibility that an ESPHome integration for this specific combination of components might not yet exist. 

Board: ESP32-S3-Touch-LCD-2.8
Characteristics:

Controller: ESP32-S3
LCD Type: TFT
LCD Controller Display: ST7789
Touch: CST328

**Comment by B48D81EFCC** [comment]
Maybe the CST816 component is covering the CST328 controller as well, since the component works not only with CST816 but with CST816T, CST816S, CST820, CST826 and CST716 too.

https://esphome.io/components/touchscreen/cst816.html

**Comment by stream74** [comment]
Yes, that's the platform I tried among others, but apparently it didn't work.

touchscreen:
  platform: cst816
  id: my_touchscreen
  interrupt_pin: GPIO4
  reset_pin: GPIO2

**Comment by mike2194** [comment]
any movement on this?
thanks for your testing and research

**Comment by gheinert** [comment]
I have installed the driver below as a local external component in ESP-Home .
It seems to work. Touches are now recognised. 

https://github.com/BluetriX/esphome-CST328-Touch.git

**Comment by OBSSD** [comment]
Has there been any progress on getting this released?  I was also able install it as an external component, but the coordinates are off when the screen is rotated 90 degrees.  Here's the log of how it was behaving (coordinates are only as precise as my fingertip):
Bottom left:  x=0, y=237, raw_x=1, raw_y=4
Top left:     x=0, y=60, raw_x=1, raw_y=239
Top Right:    x=319, y=62, raw_x=315, raw_y=237
Bottom right: x=319, y=239, raw_x=317, raw_y=1

And some snippets from my YAML:
```
external_components:
  - source: github://pr#8011
    components: [cst328]

# Touch I2C (dedicated lines on the board)
i2c:
  - id: touch_i2c
    sda: GPIO1
    scl: GPIO3
    scan: true

# Display SPI (board internal wiring)
spi:
  - id: display_spi
    clk_pin: GPIO40
    mosi_pin: GPIO45

display:
  - platform: mipi_spi
    model: st7789v
    id: main_display
    spi_id: display_spi
    cs_pin: GPIO42
    dc_pin: GPIO41
    reset_pin: GPIO39
    dimensions:
      width: 320
      height: 240
    rotation: 90
    color_order: bgr
    spi_mode: MODE0
    update_interval: 1s
    lambda: |-
      it.fill(Color(0, 0, 0));

touchscreen:
  - platform: cst328
    id: touch_panel
    i2c_id: touch_i2c
    address: 0x1A
    interrupt_pin: GPIO4
    transform:
      swap_xy: true
      mirror_x: false
      mirror_y: true
    calibration:
      x_min: 1
      x_max: 320
      y_min: 1
      y_max: 240
    on_touch:
      - lambda: |-
          ESP_LOGI("touch_debug", "Touch x=%d y=%d raw_x=%d raw_y=%d",
                   touch.x, touch.y, touch.x_raw, touch.y_raw);
```
