### ISSUE TITLE
Implement FPS counter for LVGL

### ISSUE THREAD

**Issue by kyvaith** [esphome/feature-requests#2896]
**Describe the problem you have/What new integration you would like**
Show FPS counter in LVGL screens
**Please describe your use case for this integration and alternatives you've tried:**
Optimize screens for best performance

**Additional context**

In raw LVG we can define `#define LV_USE_PERF_MONITOR 1` to have FPS counter shown.
![image](https://github.com/user-attachments/assets/e70347c4-cb37-4c83-856c-6cdcc7c2d524)

**Comment by clydebarrow** [comment]
You can simply add the define in your yaml:

```
esphome:
  ...
  platformio_options:
    build_flags: ["-DLV_USE_PERF_MONITOR"]  
```
