### ISSUE TITLE
MAX44009 / GY-49 ambient light sensor support ?

### ISSUE THREAD

**Issue by vincegre** [esphome/feature-requests#29]
Is it planned to get support or is there a workaround already for MAX44009 / GY-49 ambient light sensor ? It's an I2C module pretty efficient for light sensing.
Basic description of it here: https://www.aliexpress.com/snapshot/0.html?spm=a2g0s.9042647.6.2.2bfd4c4ddKFYKF&orderId=507448985225914&productId=32804395737

Thanks

Vincèn

**Comment by vincegre** [comment]
@OttoWinter any chance to get that sensor implemented anytime soon ? thanks ;)

**Comment by Tim-Dixon** [comment]
In case anyone stumbles across this thread, which seems to be the only one regarding this sensor, the above code provided me with some errors after implementation due to changes in the esphome library. I by no means can write in C++, however by attemting to read the error codes, I was able to sucessfully compile the program with the below code. Pay attention to the I2C pins defined in both the C++ code, and make sure you define them in your YAML config. If there are any errors or something I missed I'm open to anyone's help. Like I said, this is merely a few changes after reading error codes from compiling. Hope this helps! :)

```
#include "esphome.h"
#include "Max44009.h"

using namespace esphome;

class MAX44009Sensor : public sensor::PollingSensorComponent {
 public:
    Max44009 tsl = Max44009(0x4A, 21, 22); //these are the i2c pins being used

  MAX44009Sensor(const std::string &name, uint32_t update_interval) : sensor::PollingSensorComponent(
    name, update_interval) {}
  
  void update() override {
    float lux = tsl.getLux(); // in lux
    int err = tsl.getError();
    if(err) 
      ESP_LOGI("luxmeter", "Got error code: %1i", err);  
    else   
      //ESP_LOGD(TAG, "Got lux=%.1flux", lux);   
      publish_state(lux); 
  }

   std::string icon() override {
    return "mdi:theme-light-dark";
  }

    std::string unit_of_measurement() override { return "Lux"; }
  int8_t accuracy_decimals() override { return 2; } // 2 decimal places of accuracy.
};
'
```

**Comment by jamien82** [comment]
Hi,
Im having trouble with this verifying.
Any ideas

```
esphome:
  name: weather
  platform: ESP8266
  board: d1_mini_pro
  includes:
  - Max44009jamie.h

wifi:
  ssid: "embedded"
  password: "esp8266esp8266"

# Enable logging
logger:

i2c:
  sda: 4
  scl: 5
  scan: True

ads1115:
  - address: 0x48
  
dallas:
  - pin: GPIO2
  
sensor:
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 6.144
    name: "ADS1115 Channel A0-GND"
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 60s
  - platform: dallas
    address: 0x40031724D569FF28
    name: "Temperature #1"
  - platform: custom
    auto *luxmeter = App.register_component( new MAX44009Sensor("Light Level", 30 * 1000)); 
    App.register_sensor(luxmeter);
    sensors:
    - name: "My Custom lux Sensor"
      unit_of_measurement: lux
      accuracy_decimals: 1
    
  
   
 
    
    
# Enable Home Assistant API
api:

ota:

```
Validate window
```
INFO Reading configuration...
ERROR Error while reading config: Invalid YAML syntax. Please see YAML syntax reference or use an online YAML syntax validator:

while scanning a simple key
  in "/config/esphome/weather.yaml", line 45, column 5:
        auto *luxmeter = App.register_co ... 
        ^
could not find expected ':'
  in "/config/esphome/weather.yaml", line 46, column 5:
        App.register_sensor(luxmeter);
        ^
```

**Comment by randybb** [comment]
Any news about official integration?

**Comment by LiuVik** [comment]
> В случае, если кто-то наткнется на этот поток, который, кажется, является единственным относительно этого датчика, приведенный выше код предоставил мне некоторые ошибки после реализации из-за изменений в библиотеке esphome. Я никоим образом не могу писать на C++, однако, пытаясь прочитать коды ошибок, я смог успешно скомпилировать программу с приведенным ниже кодом. Обратите внимание на контакты I2C, определенные в обоих кодах C++, и убедитесь, что вы определяете их в своей конфигурации YAML. Если есть какие-то ошибки или что-то, что я пропустил, я открыт для любой помощи. Как я уже сказал, это всего лишь несколько изменений после считывания кодов ошибок из компиляции. Надеюсь, это поможет! :)
> 
> ```
> #include "esphome.h"
> #include "Max44009.h"
> 
> using namespace esphome;
> 
> class MAX44009Sensor : public sensor::PollingSensorComponent {
>  public:
>     Max44009 tsl = Max44009(0x4A, 21, 22); //these are the i2c pins being used
> 
>   MAX44009Sensor(const std::string &name, uint32_t update_interval) : sensor::PollingSensorComponent(
>     name, update_interval) {}
>   
>   void update() override {
>     float lux = tsl.getLux(); // in lux
>     int err = tsl.getError();
>     if(err) 
>       ESP_LOGI("luxmeter", "Got error code: %1i", err);  
>     else   
>       //ESP_LOGD(TAG, "Got lux=%.1flux", lux);   
>       publish_state(lux); 
>   }
> 
>    std::string icon() override {
>     return "mdi:theme-light-dark";
>   }
> 
>     std::string unit_of_measurement() override { return "Lux"; }
>   int8_t accuracy_decimals() override { return 2; } // 2 decimal places of accuracy.
> };
> '
> ```

Hi Tim.
help me pls - MAX44009 do not working ,i create MAX4409.h with yours code, put's him into hassio and in config i showed next:
i2c:
  sda: 4 
  scl: 5 
  scan:  True
  id:  bus_a

sensor:
  platform: |-
    custom auto *luxmeter = App.register_component( new MAX44009Sensor("Light Level", 30 * 1000)); App.register_sensor(luxmeter);
  sensors: 
    - name: My Custom lux Sensor
      unit_of_measurement: lux
      accuracy_decimals: 1

whats wrong ?

**Comment by Tim-Dixon** [comment]
@LiuVik can you give us a little more information on your setup and where you placed files, code, etc? Your text was a little confusing.

**Comment by egranto** [comment]
Create a file on  _\\homeassistant\config\esphome_ i named mine **cjmcu.h**
add 
`#include "esphome.h"
#include <Max44009.h>
#include <Wire.h>

class max44009 : public PollingComponent, public Sensor {
Max44009 light = Max44009(0x4A, 4, 5); //these are the i2c pins being used
 public:

   // constructor
  max44009() : PollingComponent(60000) {}
 
  void setup() override {
	  Wire.begin();
  }
  void update() override {
    float lux = light.getLux(); // in lux
      publish_state(lux); 
  }
  std::string icon() override {
    return "mdi:theme-light-dark";
  }

    std::string unit_of_measurement() override { return "Lux"; }
    int8_t accuracy_decimals() override { return 2; } // 2 decimal places of accuracy.
};`

on your YAML just need 
`
  includes:
    - cjmcu.h

`
and then 
`  - platform: custom
    lambda: |-
      auto my_sensor = new max44009();
      App.register_component(my_sensor);
      return {my_sensor}; 

    sensors:
      name: "Light Sensor:"`

**Comment by grimmsq** [comment]
Hello, I've been struggling with these for some time now, maybe you can help me

**I've created a file called lux.h that I placed in \config\esphome with the following content**

"#include "esphome.h"
#include "Max44009.h"
class max44009 : public PollingComponent, public Sensor {
 public:
  Max44009 light = Max44009(0x4A, 4, 5); //these are the i2c pins being used
// constructor
  max44009() : PollingComponent(60000) {}


void update() override {
  float lux = light.getLux(); // in lux
  int err = light.getError();
  if(err) 
      ESP_LOGI("luxmeter", "Got error code: %1i", err);  
    else   
      //ESP_LOGD(TAG, "Got lux=%.1flux", lux);   
      publish_state(lux); 
}
std::string icon() override {
return "mdi:theme-light-dark";
}

std::string unit_of_measurement() override { return "Lux"; }
int8_t accuracy_decimals() override { return 2; } // 2 decimal places of accuracy.
};"

**After that I added this in the .yaml file**

esphome:
  name: seraf
  platform: ESP8266
  board: d1_mini
  includes:
    - lux.h
  libraries:
    - "MAX44009 library"
  
wifi:
  ssid: "XXXXX"
  password: "XXXXX"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Seraf Fallback Hotspot"
    password: "XXXXX"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
i2c:
 sda: 4
 scl: 5
 scan: True
 id: bus_a
ota:
sensor:
 - platform: custom
    lambda: |-
      auto my_sensor = new max44009();
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      name: "Light Sensor:"

**When I compile it i get the following error:**

In file included from src/main.cpp:19:0:
src/lux.h:8:3: error: 'Max44009' does not name a type
   Max44009 light = Max44009(0x4A, 4, 5); //these are the i2c pins being used
   ^
src/lux.h: In member function 'virtual void max44009::update()':
src/lux.h:14:15: error: 'light' was not declared in this scope
   float lux = light.getLux(); // in lux

Can you please tell me what am I doing wrong?
Thanks in advance!

**Comment by nvvasilev** [comment]
Hello, @grimmsq 
I managed to make the sensor work with the following configuration:

In the ESPHome config folder I created the file `ESPHomeMax44009Sensor.h`. 
Here is the path to the file: `homeassistant/config/esphome/CustomLibs/ESPHomeMax44009Sensor.h`
My .yaml file is one directory up in: `homeassistant/config/esphome/weatherstation.yaml`.

Here is the contents of the **ESPHomeMax44009Sensor.h**:

```
#include "esphome.h"
#include "Max44009.h"

class MAX44009Sensor : public PollingComponent, public Sensor  {
 public:
  Max44009 myLux = Max44009(0x4A, 4, 5); //these are the i2c pins being used

  MAX44009Sensor() : PollingComponent(15000) {} // 15 seconds update interval
  
  void setup() override {}
  
  void update() override 
  {
    float lux = myLux.getLux(); // in lux
    
    publish_state(lux); 
  }
};
```

And this is how I use it in **weatherstation.yaml**:

```
substitutions:
  display_name: outsideWeather

esphome:
  name: weather_station
  platform: ESP8266
#  board: d1_mini_pro
  board: d1_mini
  includes:
    - CustomLibs/ESPHomeMax44009Sensor.h
  libraries:
    - "Max44009"

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_pass
  fast_connect: true
  manual_ip:
    static_ip: !secret ip_weatherstation
    gateway: !secret ip_gateway
    subnet: !secret ip_subnet
    dns1: !secret ip_dns1

#api:

# Enable logging
logger:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: solarsensor/birthdisable
    payload: disable
  will_message:
    topic: solarsensor/willdisable
    payload: disable

ota:

i2c:
 - id: ic_1
   sda: 4
   scl: 5
   scan: false

sensor:
  - platform: hdc1080
    temperature:
      name: ${display_name} HDC1080 Temp
    humidity:
      name: ${display_name} HDC1080 Humi
    address: 0x40
    update_interval: 30s

  - platform: dht
    temperature:
      name: ${display_name} DHT Temperature
    humidity:
      name: ${display_name} DHT Humidity
    pin: D4
    update_interval: 30s

  - platform: custom
    lambda: |-
      auto lux_sensor = new MAX44009Sensor();
      App.register_component(lux_sensor);
      return {lux_sensor};
  
    sensors:
      name: ${display_name} Lux
      unit_of_measurement: lx

  - platform: adc
    pin: A0
    name: ${display_name} Battery
    update_interval: 15s
    filters:
      - multiply: 5.5238


deep_sleep:
  run_duration: 40s
  sleep_duration: 5min
```
I followed the official ESPHome Custom Sensor Component guide [here](https://esphome.io/components/sensor/custom.html) and the digiblurDIY's video about Solar Powered Weather Station [here](https://www.youtube.com/watch?v=VUqOIPVbeF0).

This works for me and I hope it works for you as well.
