### ISSUE TITLE
Enable online_image and/or http_request for platform: host 

### ISSUE THREAD

**Issue by kkilchrist** [esphome/feature-requests#2918]
**Describe the problem you have/What new integration you would like**  
Add support for the `http_request` component on the host platform in ESPHome, or override / bypass the http_request check in the online_image component.

**Please describe your use case for this integration and alternatives you've tried**  
I’m working on an on-device `libwebp` decoder for `online_image`. WebP images are much smaller than PNG (e.g., 2 KB vs 33 KB for a test image), which makes them ideal for low-bandwidth scenarios and fast transmission in IoT environments. Additionally, WebP supports both lossless and lossy compression. 

Enabling the host platform (macOS) would make debugging much faster. The host platform already has networking support (e.g., for API access), so hopefully this is not a huge ask.

**Additional context**

**Comment by kkilchrist** [comment]
Made some pretty exciting progress on this today, after some trial and error (trying to use platformio packages, etc etc), turns out,  a wrapper around the local lib curl works great on MacOS. 

I also had to make some updates to the json component (which uses platform flags to allocate a read buffer). 

Anyway, this allows HTTP requests to be on the host platform. I've only tested GET, but it works on my machine for both http and https endpoints. 

For those interested, I’ve added the component to my GitHub fork. 

Here's a sample YAML:
```yaml
esphome:
  name: local-http-request
  platformio_options:
    build_flags: 
      - -lcurl

host: 

external_components:
  - source:
      type: git
      url: "https://github.com/kkilchrist/esphome"
      ref: "http_request_curl"
    components: [ "http_request", "json" ]

http_request:
  id: http_request_component
  timeout: 1s  

interval:
  - interval: 10s  
    then:
      - logger.log: "Making HTTP request"
      - http_request.get:
          url: "https://jsonplaceholder.typicode.com/todos/2"
          capture_response: true  # Capture the response for use in the Lambda function; when set to true, the response data will be captured and placed into the body variable as a std::string for use in lambdas
          on_response:
              - logger.log:
                  format: 'Response status: %d, Duration: %u ms'
                  args:
                    - response->status_code
                    - response->duration_ms
              - lambda: |-
                  ESP_LOGI("main", "Response body: %s", body.c_str());

logger:
  level: INFO  # Enable debug level logging to see detailed logs
```

This wasn't a small task as I had originally hoped, but it's progress!

**Comment by lanrat** [comment]
Hello @kkilchrist, I just ran across this issue looking to solve the same problem for implementing gif support for online_image.

How stable is your solution? And how far along is your webp support? If it supports animated webp images, it is likely a better alternative top gif support.

Thanks.

**Comment by regystro** [comment]
This feature would be very useful to speed up the testing process. I use a waveshare e-paper display in some projects with LVGL, and compiling, uploading and testing scripts is almost instantaneous using host platform as opposed to the normal way. This allows faster previews for positioning display components, choosing font sizes, an so on.

Any progress in your WIP? What I've tested so far, does not work in Linux/WSL environment.

Cheers.

**Comment by clydebarrow** [comment]
```
host:
  mac_address: "62:23:45:AF:B3:DD"

http_request:
  id: http_request_id

external_components:
  - source: github://pr#7908
    components: [image,online_image,animation]
  - source: github://pr#8040
    components: [http_request]
  - source: github://pr#8039
    components: [json]

online_image:
  - id: edge_1
    url: http://localhost/AlphaEdge.png
    resize: 100x100
    format: png
    type: RGB
    update_interval: 60s
    use_transparency: opaque
```
