### ISSUE TITLE
Allow removal of the "Highlight Border" when using LVGL

### ISSUE THREAD

**Issue by blockarchitech** [esphome/feature-requests#2926]
**Describe the problem you have/What new integration you would like**

I would like to be able to remove the highlighted/focused border/outline around LVGL widgets.

**Please describe your use case for this integration and alternatives you've tried:**

I currently have seperate, custom theming for focused widgets. I would not like the border to be there anymore, as it is a slight eyesore. I have tried the following:
```yaml
bg_color: 0xFFFFFF
text_color: 0x000000
border_width: 0
outline_width: 0
focused:
  bg_color: 0x2F8CD8
  border_width: 0
  outline_width: 0
```
...however the border still shows.
**Additional context**

N/A
