### ISSUE TITLE
automation on deep sleep begin

### ISSUE THREAD

**Issue by fondberg** [esphome/feature-requests#294]
**Describe the problem you have/What new integration you would like**

Automation trigger right before deep sleep begins

**Please describe your use case for this integration and alternatives you've tried:**

Be able to turn off any GPIO switches that possibly powers sensors. 

**Additional context**

Possible configuration:
```yaml
deep_sleep:
  id: deep_sleep_1
  run_duration: 2min
  sleep_duration: 5min
  on_sleep:
    then:
       ...
```
