### ISSUE TITLE
ESPHome ac-dimmer with MCP23S17 Component

### ISSUE THREAD

**Issue by NytoxRex0** [esphome/feature-requests#2945]
### The problem

The "_Gate_Pin_" from _AC_Dimmer_ component is not available to use for pins of the _MCP23S17_. This device should be more than fast enough for this application, please alter the code to allow this configuration.

### Which version of ESPHome has the issue?

2024.8.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.9.1

### What platform are you using?

ESP32

### Board

WROOM-S2

### Component causing the issue

ac-dimmer, MCP23S17

### Example YAML snippet

```yaml
spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

mcp23s17:
  - id: 'mcp23s17_hub'
    cs_pin: GPIO02
    deviceaddress: 0

output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 
      mcp23xxx: mcp23s17_hub
      # Use pin number 0
      number: 0
      # One of INPUT or INPUT_PULLUP
      mode:
        output: true
      inverted: false
    zero_cross_pin:
      number: GPIO35
      mode:
        input: true
      inverted: yes

light:
  - platform: monochromatic
    output: dimmer1
    name: Dimmerized Light
```

**Comment by diemon24** [comment]
> ### The problem
> 
> The "_Gate_Pin_" from _AC_Dimmer_ component is not available to use for pins of the _MCP23S17_. This device should be more than fast enough for this application, please alter the code to allow this configuration.
> 
> ### Which version of ESPHome has the issue?
> 
> 2024.8.3
> 
> ### What type of installation are you using?
> 
> Docker
> 
> ### Which version of Home Assistant has the issue?
> 
> 2024.9.1
> 
> ### What platform are you using?
> 
> ESP32
> 
> ### Board
> 
> WROOM-S2
> 
> ### Component causing the issue
> 
> ac-dimmer, MCP23S17
> 
> ### Example YAML snippet
> 
> spi:
>   clk_pin: GPIO14
>   mosi_pin: GPIO13
>   miso_pin: GPIO12
> 
> mcp23s17:
>   - id: 'mcp23s17_hub'
>     cs_pin: GPIO02
>     deviceaddress: 0
> 
> output:
>   - platform: ac_dimmer
>     id: dimmer1
>     gate_pin: 
>       mcp23xxx: mcp23s17_hub
>       # Use pin number 0
>       number: 0
>       # One of INPUT or INPUT_PULLUP
>       mode:
>         output: true
>       inverted: false
>     zero_cross_pin:
>       number: GPIO35
>       mode:
>         input: true
>       inverted: yes
> 
> light:
>   - platform: monochromatic
>     output: dimmer1
>     name: Dimmerized Light
> ### Anything in the logs that might be useful for us?
> 
> _No response_
> 
> ### Additional information
> 
> _No response_

Hi. I faced the same issue in ESPHome version 2025.8.4. I think this request has not been resolved. Did you manage to find a solution to use this?

<img width="631" height="342" alt="Image" src="https://github.com/user-attachments/assets/b19af988-1717-46ec-8579-15bf49575f02" />

**Comment by ssieb** [comment]
It is not fast enough and can't be used, particularly not in interrupts.

**Comment by diemon24** [comment]
> It is not fast enough and can't be used, particularly not in interrupts.

What do you mean, please clarify? The MCP expander is not fast enough to turn on in zero state?

**Comment by ssieb** [comment]
The time to run the i2c transaction is too long and we can't do i2c transactions from an interrupt context anyway.

**Comment by NytoxRex0** [comment]
Hi, diemon24,
Indeed the i2c protocol is apparently not fast enough or capable for triggering as interrupt. Therefore I have chosen a different path to extend the ports on the ESP board. The ESP boards sends commands to Arduino nano's via UART, these Arduino nano's generate the timing for the dimmers. For more information, see my (incomplete) repository here: https://github.com/NytoxRex0/NDDimmerboard

**Comment by diemon24** [comment]
> Hi, diemon24,
> Indeed the i2c protocol is apparently not fast enough or capable for triggering as interrupt. Therefore I have chosen a different path to extend the ports on the ESP board. The ESP boards sends commands to Arduino nano's via UART, these Arduino nano's generate the timing for the dimmers. For more information, see my (incomplete) repository here: https://github.com/NytoxRex0/NDDimmerboard
> 

Hello. 
Thank you for your participation in my problem. 

I am using Esp32c3 super mini as a controller + MCP23017. 
The i2c bus settings are made for a frequency of 1700 kHz, which is supported by the hardware of MCP23017. 

The load is controlled via MOC3021 and a simistor. My load is reactive - these are LED lamps ~220 V without dimming. Otherwise, I would not have chosen a circuit on simistors. 

As far as I understand, zero control is mandatory for an inductive load due to the effect on the opening / closing of the simistor. But the reactive load has a high inrush current, which I would like to reduce by turning on the load when crossing zero. 

The frequency in the ~220V network is 50 Hz, and the i2c bus settings are 1700 kHz. I think I don't understand the issue well, but now the lack of transfer speed on the i2c bus looks strange to me, because the bus transfers data at a higher frequency. Do I understand correctly that this means that the slowdown is related to the ESP itself: processing the zero state on another GPIO and transferring information to the i2c bus occurs slower than the next half-period in the ~220V network? 

Although this also looks strange, because the ESP DAC frequency is also quite high. Please help me figure this out.


<img width="620" height="130" alt="Image" src="https://github.com/user-attachments/assets/18c2d8e1-dd11-4956-a67f-42618d8af182" />

<img width="345" height="204" alt="Image" src="https://github.com/user-attachments/assets/79fddffc-97e9-41cb-b943-ff7525f8f4c4" />

<img width="451" height="137" alt="Image" src="https://github.com/user-attachments/assets/bf8f860a-309a-43ae-b82a-b0c0a9aa82ca" />

I have zero control on the GPIO0 ESP32, and the entire load is on the MSP23017.

**Comment by diemon24** [comment]
> > https://github.com/NytoxRex0/NDDimmerboard

Thank you, I have read the description and yaml for ESPHome. But I could not see the zero control in this configuration for ESPHome: 
https://github.com/NytoxRex0/NDDimmerboard/blob/main/ESPHome/ESPHome_Code

**Comment by diemon24** [comment]
> The time to run the i2c transaction is too long and we can't do i2c transactions from an interrupt context anyway.

But it is available for dimmable load and I know for sure that it works well. But for non-dimmable load it is not available. :(

**Comment by NytoxRex0** [comment]
I'm not sure on this either, however my understanding is the following:
The i2c bus frequency is the data frequency, this is sent out at that frequency. However a command consists of many bits, so the data transfer rate will be much lower. Then the data has to arrive fully, after which the data has arrived it has to be 'translated' from high low signals into the exact data in memory. Then the microcontroller has to process the data and find out what to do with it.
All these steps (thus delays) defeat the purpose of an interrupt.
Using a HW interrupt pin of the microcontroller itself, halts all code that is running and 'prioritizes' the code defined in the interrupt. Therefore the delay will be minimal.

As for the power factor of the LED lights, most new LED drivers have built in power factor correction. LED lights themselves are purely resistive. If I understand correctly, you want to use it only as a switch, not a dimmer. Then switching at the zero point would be smart, to reduce the inrush current and decrease the load on the switching electronics.

diemon24:
As for my implementation, I have offloaded the zero crossing and generating the switching signals to the Arduino Nanos. So the ESP Home config only has 'fake' or virtual dimmers, which send out the power state (0-100%) to the Nanos. The Nanos then generate the required timing. In the Arduino config you can find the code including the zero crossing.

**Comment by diemon24** [comment]
> If I understand correctly, you want to use it only as a switch, not a dimmer. Then switching at the zero point would be smart, to reduce the inrush current and decrease the load on the switching electronics.

That's right. I don't think it's necessary, but it would be right because many LED lamps have a high starting current, which can reach x10 of the constant load current. Having a power reserve on the triacs and the correct track width on the board, this is not felt, but I would like to eliminate this risk using zero crossing control

**Comment by ssieb** [comment]
If you're not dimming then why are you using a dimmer?  Just turn it on and off, the zero crossing doesn't matter.

**Comment by diemon24** [comment]
> I'm not sure on this either, however my understanding is the following:
> The i2c bus frequency is the data frequency, this is sent out at that frequency. However a command consists of many bits, so the data transfer rate will be much lower. Then the data has to arrive fully, after which the data has arrived it has to be 'translated' from high low signals into the exact data in memory. Then the microcontroller has to process the data and find out what to do with it.
> All these steps (thus delays) defeat the purpose of an interrupt.
> Using a HW interrupt pin of the microcontroller itself, halts all code that is running and 'prioritizes' the code defined in the interrupt. Therefore the delay will be minimal.

But it is available and works for dimming and it looks weird

**Comment by diemon24** [comment]
> If you're not dimming then why are you using a dimmer? Just turn it on and off, the zero crossing doesn't matter.

Yes, I can use it in a simple way. In the previous answer I wrote that the starting current is a threat, so I want to get rid of this risk.

**Comment by ssieb** [comment]
I missed that comment, but there's no threat and the zero-crossing thing isn't going to make any difference.

**Comment by diemon24** [comment]
> I missed that comment, but there's no threat and the zero-crossing thing isn't going to make any difference.


Ok. Thank you very much!

**Comment by ssieb** [comment]
If you're really concerned about it, you could get a zero-crossing triac driver optocoupler.

**Comment by nagyrobi** [comment]
Yeah, a SSR (Solid State Relay) is a cheap alternative which can only switch at zero cross, and it's also opto-coupled.
I ran into a similar issue by getting welded contacts of small PCB relays when switching LED lights on and off. A SSR in place of the relay is a reliable solution working for 2 years now.

**Comment by diemon24** [comment]
Thank you 👍

**Comment by diemon24** [comment]
> Yeah, a SSR (Solid State Relay) is a cheap alternative which can only switch at zero cross, and it's also opto-coupled.
> I ran into a similar issue by getting welded contacts of small PCB relays when switching LED lights on and off. A SSR in place of the relay is a reliable solution working for 2 years now.

It's a pity that it is impossible to make centralized control of zero transition on large boards where many channels are used (in my case there are 16), apparently I will have to use MOC3021M, which switches to zero

**Comment by ssieb** [comment]
What do you mean "centralized control"?  What would be the point?  You need a driver for each triac anyway.

**Comment by diemon24** [comment]
> What do you mean "centralized control"? What would be the point? You need a driver for each triac anyway.

I meant that the decentralized function can be implemented on optocouplers with a zero transition function, for example, MOC3021M. My controller has 16 ports, for each port I have an optocoupler MOC3021 without zero transition control. I wanted to use zero control in the zero_cross function on the ESP - this is centralized control. Decentralized can be implemented in hardware by installing MOC3021M on each channel. For example, my controller of 16 channels is universal and I can use different types of load. On each channel I want to use MOC3021 without zero control by default. But if I need to turn on any channel for an inductive load, I could use the pull-up of the RC damper for the triac and software enablement of control. This allows you to make the controller universal

**Comment by diemon24** [comment]
Okay, I'm using this solution to get zero control with MOC3021 without hardware zero control 

<img width="758" height="264" alt="Image" src="https://github.com/user-attachments/assets/95383617-1b9e-4463-b950-0280d449bb10" />


```
mcp23017:
  - id: 'mcp23017_hub_01'
    address: 0x25


binary_sensor:
  - platform: gpio
    pin: 0
    name: "Null control"
    id: null_control
    internal: True
    on_press:
      then:
        - switch.turn_on: switch_control
    on_release: 
      then:
        - switch.turn_off: switch_control

switch:
  - platform: template
    id: switch_control
    name: "Switch null control"
    internal: true
    optimistic: true

  - platform: gpio
    name: "Output channel 1"
    id: out_channel_1
    pin:
      mcp23xxx: mcp23017_hub_01
      number: 8
      mode:
        output: true
      inverted: false
    internal: True
    restore_mode: ALWAYS_OFF

  - platform: template
    optimistic: true
    id: ch_light_1
    name: "Light channel 1"
    on_turn_on: 
      then:
        - switch.control:
            id: switch_control
            state: false
        - if:
            condition:
              - lambda: !lambda return id(switch_control).state == 0;
            then:
              - switch.turn_on: out_channel_1
    on_turn_off: 
      then:
        - switch.turn_off: out_channel_1
```
