### ISSUE TITLE
OV7670 Support

### ISSUE THREAD

**Issue by BafS** [esphome/feature-requests#2946]
**Describe the problem you have/What new integration you would like**

The OV7670 is a really cheap camera and it would be great to have it supported. #835 opened an issue but unfortunately it is now locked.

**Please describe your use case for this integration and alternatives you've tried:**

I'm not able to use the camera with ESPHome. The alternative is to use https://github.com/bitluni/ESP32CameraI2S (more info there: https://bitluni.net/esp32-i2s-camera-ov7670)

I tried this without success:

```yml
# OV7670
esp32_camera:
  name: My Camera
  external_clock:
    pin: GPIO32
    frequency: 20MHz
  i2c_pins:
    sda: GPIO21
    scl: GPIO22
  data_pins: [GPIO4, GPIO12, GPIO13, GPIO14, GPIO15, GPIO16, GPIO17, GPIO27]
  vsync_pin: GPIO34
  href_pin: GPIO35
  pixel_clock_pin: GPIO33
  resolution: 640x480
  jpeg_quality: 10
  max_framerate: 6 fps
  idle_framerate: 0.1 fps
```

I have this in the logs:

```
[22:57:02][E][esp32_camera:123]:   Setup Failed: ESP_ERR_NOT_SUPPORTED
[22:57:02][E][component:082]:   Component esp32_camera is marked FAILED
```

**Additional context**
