### ISSUE TITLE
Support conditional in Binary Light

### ISSUE THREAD

**Issue by andreas-bulling** [esphome/feature-requests#2960]
I have numerous ESPHome devices installed. In all of them, I include a Template Select to allow the Binary Sensor (physical switch) to be enabled/disabled. This is super useful to prevent the kids from playing around with the physical switches in their rooms.

```
binary_sensor:
  - platform: gpio
    id: sw
    internal: true
    pin: 
      number: GPIO5
    on_press:
    - if:
        condition: # only toggle relay if button is enabled
          lambda: 'return (id(select_switch).state == "Enabled");'
        then:
          light.toggle: roomlight
        
select:
    # option to disable switch
  - platform: template
    name: "${device_upper} Enable/Disable"
    id: select_switch
    optimistic: true
    options:
      - Enabled
      - Disabled
    initial_option: Enabled
    restore_value: true
    icon: mdi:circle-double
```

What cannot be disabled this way, however, are the controls in HomeAssistant. Because the Binary Light (that triggers a GPIO Output) doesn't support a conditional I cannot disable the controls.

It'd be great if this was possible in a similar way as for the Binary Sensor above.
