### ISSUE TITLE
Set inverted pin for ESP32 RMT LED Strip

### ISSUE THREAD

**Issue by Eelviny** [esphome/feature-requests#2964]
**Describe the problem you have/What new integration you would like**

I would like to set the pin configuration for `esp32_rmt_led_strip` to inverted:

```
light.esp32_rmt_led_strip: [source christmas-lights.yaml:70]
platform: esp32_rmt_led_strip
rgb_order: RGB

This variable only supports pin numbers, not full pin schemas (with inverted and mode).
pin: 
  number: GPIO8
  inverted: True
num_leds: 50
rmt_channel: 1
chipset: ws2811
```

**Please describe your use case for this integration and alternatives you've tried:**

I currently have a circuit that uses an N-channel mosfet with a resistor that pulls up to 5V. If I power the mosfet from my esp32, it drives the signal low. I want to use this 5V to drive the signal for my WS2811 lights, but I'm not able to as the esp32_rmt_led_strip does not support inverted pins, so the signal going to my lights is currently inverted.

Having an inverted signal would allow for a simple logic level shifter using 1 cheap n-channel mosfet and a pull-up resistor. Alternatively, I could re-do my circuit with extra components but would be great to solve this in software.

**Additional context**
