### ISSUE TITLE
Cookbook entry how to make a buzzer work

### ISSUE THREAD

**Issue by rradar** [esphome/feature-requests#298]
**Describe the problem you have/What new integration you would like**

Many people don't know how to buzzer (including me)

**Please describe your use case for this integration and alternatives you've tried:**

I tried to clap my hands but can't get this automated with my esp

**Additional context**

Would be nice to have not only a single buzzzzzz in the cookbook but also buzzing a little jingle or something :smile_cat:

**Comment by rradar** [comment]
Let's start with a sketch for a passive buzzer which finally works :1st_place_medal:



```
output:
  - platform: esp8266_pwm
    pin: D7
    id: 'buzzer'

switch:
  - platform: template
    name: buzzzzzz
    turn_on_action:
      then:
        - output.esp8266_pwm.set_frequency:
            id: buzzer
            frequency: 800Hz
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 120ms
        - output.turn_off: buzzer
        - delay: 200ms
        - output.esp8266_pwm.set_frequency:
            id: buzzer
            frequency: 600Hz
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 120ms
        - output.turn_off: buzzer

```
