### ISSUE TITLE
Suport for CrowPanel E-Paper displays

### ISSUE THREAD

**Issue by girlpunk** [esphome/feature-requests#2980]
**Describe the problem you have/What new integration you would like**
Support for CrowPanel E-Paper (E-Ink) displays, utilising the same APIs and graphics libraries as the WaveShare ones

**Please describe your use case for this integration and alternatives you've tried:**
I have attempted using the exisitng WaveShare components, however as the drivers for these panels are different (the SSD1683), they are not compatible.

**Additional context**
Example use case: https://www.elecrow.com/wiki/CrowPanel_ESP32_E-paper_5.79-inch_HMI_Display.html
Driver datasheet: https://www.elecrow.com/download/product/DIS08792E/SSD1683_Datasheet.PDF

**Comment by brillb** [comment]
I would also like these, as they are manufactured in a fully ready-to-go case, which simply accepts USB-C power input and then ready to go.  Similar to the waveshare cloud devices, but in more form factors/sizes and button controls.

**Comment by droberin** [comment]
Hi.
I also tried Waveshare drivers on one of these 4.2 inches e-paper screen device:

```yaml
esphome:
  name: fishfoodscreen
  friendly_name: FishFoodScreen

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "SomeSecretPasswordo=="

ota:
  - platform: esphome
    password: "someOTAPasswordo=="

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

spi:
  clk_pin: GPIO12
  mosi_pin: GPIO11

display:
  - platform: waveshare_epaper
    model: 4.20in
    cs_pin: GPIO45
    dc_pin: GPIO46
    busy_pin: GPIO48
    reset_pin: GPIO47
    rotation: 270
    update_interval: 30s
    id: my_epaper_display
    lambda: |-
      it.fill(COLOR_OFF);
      it.printf(50, 120, id(font_large), TextAlign::CENTER, "%s", id(datetime_text).state.c_str());
      it.update();

# Font for text rendering
font:
  - file: "fonts/Arial.ttf"
    id: font_large
    size: 32

# Home Assistant datetime helper
text_sensor:
  - platform: homeassistant
    entity_id: input_datetime.plecomida
    id: datetime_text
    on_value:
      then:
        - component.update: my_epaper_display
```

It doesn't show any error but also screen never gets updated whatsoever. It was a good test...

**Comment by janwest2** [comment]
I have the same issue, any news?

**Comment by SeanTheITGuy** [comment]
If anyone wants to tackle this for esphome, I've recently added support to circuitpython for the Crowpanel 4.2", so the appropriate settings and init strings are available.

**Comment by WebSpider** [comment]
Linking PR: https://github.com/adafruit/circuitpython/pull/10107

**Comment by Dave-Casey** [comment]
I'm not experienced in C or custom components in ESPHome but I was feeling brave the other afternoon but got stuck, I don't know how to even include external components in the build.  I added this to my YAML but it doesn't get added to the build.  Ideas?
`external_components:
  - source: "/config/esphome/"
    components: [ssd1683]`

**Comment by semvis123** [comment]
I've made a simple working version for the crowpanel 4.2 epaper display, its a bit rough, and doesn't implement LUT, but it works good enough for me :)
See:
https://github.com/semvis123/esphome-crowpanel-4.2-epaper

**Comment by Dave-Casey** [comment]
This is exciting @semvis123 , aside from copying the font files into my directory, is it as simple as updating the yaml file or do I need to do other steps to get this working in my environment?

**Comment by semvis123** [comment]
@Dave-Casey thanks for your interest, it should be as easy as adjusting the yaml file.

0. Add the crowpanel epaper component as an external component.
1. Define pins and display, see my yaml file.
2. Define the display lambda in the yaml.
3. Copy the font and icons. (And choose the codepoints you want to use)

For steps 1-3 you can look at my yaml file as a reference. 

See: https://esphome.io/components/external_components.html

**Comment by Dave-Casey** [comment]
I followed this and adapted my yaml to match yours with the exception of the unique instance stuff.  I created a components folder and copies over your folder contents.  I now get this error: 

`File "/config/esphome/components/crowpanel_epaper/display.py", line 47, in <module>
    cv.Required(CONF_DC_PIN): cv.output_pin,
                              ^^^^^^^^^^^^^
AttributeError: module 'esphome.config_validation' has no attribute 'output_pin'
Failed config

display.crowpanel_epaper: [source /config/esphome/display-1.yaml:69]
  
  Platform not found: 'display.crowpanel_epaper'.
  platform: crowpanel_epaper`

Interesting enough output_pin does not appear in the display.py file, it's using cv.output_pin_schema.
I apologize, I'm in a bit over my head on this one.

**Comment by semvis123** [comment]
@Dave-Casey I've fixed my repo, noticed that the folder structure was not completely correct for the external components.
You might need to delete the .esphome folder to purge the cache.

Also I've added a minimal example: 
https://github.com/semvis123/esphome-crowpanel-4.2-epaper/blob/minimal-example/esphome.yaml

**Comment by Dave-Casey** [comment]
Thanks @semvis123 

"Hello world!"

Just wanted to confirm that your code is working on my device now. I had to slightly adjust the YAML example to include the espnow_receiver component as an external component (hosted locally). Here’s a sanitized snippet of what my working config looks like:

```
external_components:
  - source: github://semvis123/esphome-crowpanel-4.2-epaper
    components: [crowpanel_epaper]
  - source:
      type: local
      path: components/espnow_receiver
    components: [espnow_receiver]
```

Now I need to figure out how to adapt this to my own projects — let me know as you add improvements!
