### ISSUE TITLE
Home Assistant events as Automation Triggers

### ISSUE THREAD

**Issue by Anonym-tsk** [esphome/feature-requests#301]
**Describe the problem you have/What new integration you would like**
I want to use [Home Assistant events](https://www.home-assistant.io/docs/configuration/events/) as Automation Triggers in ESPHome.

**Please describe your use case for this integration and alternatives you've tried:**
I can import `sensor` or `switch` from Home Assistant to ESPHome and subscribe to state changes, but i can't subscribe to other events, for example `telegram_callback`.

**Additional context**
Example configuration:
```
api:
  events:
    - event: telegram_callback
      then:
        - light.turn_on:
            id: my_light
            brightness: !lambda 'return event.data.brightness;'
```
