### ISSUE TITLE
Support for SHARP GP2Y0A710K Distance Sensor

### ISSUE THREAD

**Issue by JoachimVeulemans** [esphome/feature-requests#3011]
**Describe the problem you have/What new integration you would like**
Support for the SHARP GP2Y0A710K distance sensor that can report back the measured distance.
![{088FDD80-7767-4956-986D-F8B6F1C45F75}](https://github.com/user-attachments/assets/01f5ba97-6495-4691-91f7-d51a9b983c34)

**Please describe your use case for this integration and alternatives you've tried:**
Other distance sensor components use a trigger & result pin. This device only has 1 output pin.
![{DCD68BEF-97A3-4909-B5DB-822DE5EB75AF}](https://github.com/user-attachments/assets/45848a90-34eb-4ba1-9778-db292b6c9183)

**Additional context**
Documentation: https://global.sharp/products/device/lineup/data/pdf/datasheet/gp2y0a710k_e.pdf

**Comment by latonita** [comment]
@JoachimVeulemans I dont believe you need any component for this.
Since the device reports analog value just read ADC, multiply by appropriate number.

The following is purely theoretical yaml how it could look like:
```yaml

# ADC sensor reading the voltage output from the sensor.
sensor:
  - platform: adc
    pin: A0  # change to the correct ADC pin
    name: "Sharp GP2Y0A710K Voltage"
    id: sharp_voltage
    update_interval: 1s
    # If using a voltage divider, adjust the multiplier accordingly:
    filters:
      - multiply: 3.3  # example: converts raw ADC value to voltage. calibrate by real readings and your particular surface color/type

  # Template sensor to convert voltage to a distance (cm)
  - platform: template
    name: "Sharp GP2Y0A710K Distance"
    lambda: |-
      // 'v' is the measured voltage from the sensor
      float v = id(sharp_voltage).state;
      // Insert your calibration function here.
      // The following is a placeholder example and must be adjusted:
      // e.g., distance (cm) = a * pow(v, b) where a and b are determined via calibration.
      float distance = (v > 0.0) ? (27.86 / (v - 0.42)) : 0.0;
      return distance;
    unit_of_measurement: "cm"
    update_interval: 1s
```
