### ISSUE TITLE
modbus_controller button component to send fixed command without expected answer

### ISSUE THREAD

**Issue by avilleret** [esphome/feature-requests#3026]
**Describe the problem you have/What new integration you would like**

I need a modbus_controller button component to be able to send a single command to a device.

**Please describe your use case for this integration and alternatives you've tried:**

As a user, I would like to be able to save the parameter of my Aldes Inspirair ventilation system.
As described in the Modbus documentation for this device, I have to write value $1234 to register $14.
To do so, a push button in the user interface might be useful. 

**Additional context**

I can't find an easy way to do so currently but button component seems to be a good candidate.
However there is no button in modbus_controller yet.

**Comment by brambo123** [comment]
You can use a template button to update a modbus_component number.

Something like this (untested):
```
number:
  - platform: modbus_controller
    modbus_controller_id: modbus1
    id: reg14
    address: 14
    value_type: U_WORD

button:
  - platform: template
    name: "Save settings"
    on_press:
      - number.set:
          id: reg14
          value: 1234
```
