### ISSUE TITLE
Default AP ssid

### ISSUE THREAD

**Issue by NoNaMoe** [esphome/feature-requests#303]
**Describe the problem you have/What new integration you would like**

Would be neat/less cluttered if AP (Access Point) SSID defaults to the ESPHome node name, rather than being a required field.

Example config:
```
esphome:
  name: dryer_pow_monitor
  platform: ESP8266
  board: esp01_1m

wifi:
  ap:

...
```

**Please describe your use case for this integration and alternatives you've tried:**
Seems like it would be a sane default to have.

Alternative might be to use a template/lambda, but ive tried this. ap.ssid is currently not templatable (why would it be):
```
wifi: [source .\dryer_pow_monitor.yaml:16]
  ap:  [source .\dryer_pow_monitor.yaml:17]

    This option is not templatable!.
    ssid: !lambda |-
      return "blah"; [source .\dryer_pow_monitor.yaml:17]
```
... and there doesnt seem to be a easy way to get 'name' from the Core/esphome component API anyway?
