### ISSUE TITLE
UART: Add trigger on_received

### ISSUE THREAD

**Issue by iBobik** [esphome/feature-requests#3037]
**Describe the problem you have/What new integration you would like**

I write custom interation with the UART device using existing uart.write action and debug sequence where I call other actions.

Using debug sequence seems like a workaround and I am not sure how long it will work the same way, because it was not intended for it.

**Please describe your use case for this integration and alternatives you've tried:**

Create trigger intended for custom integrations written in the yaml:
```
uart:
  ...
  receiver:
    after:
      delimiter: "\n“
  on_received:
    - value: 'light on'
      then:
        - light.turn_on: light_1
    - value: 'light off'
      then:
        - light.turn_off: light_1
```
```
uart:
  ...
  receiver:
    after:
      bytes: 1
  on_received:
    - value: 123
      then:
        - light.turn_on: light_1
    - value: ['FF']
      then:
        - light.turn_off: light_1
```

**Additional context**
