### ISSUE TITLE
Add lv_cpicker in LVGL component

### ISSUE THREAD

**Issue by bennydiamond** [esphome/feature-requests#3048]
**Describe the problem you have/What new integration you would like**

LVGL's `lv_cpicker` component is missing in LVGL.
https://docs.lvgl.io/7.11/widgets/cpicker.html

**Please describe your use case for this integration and alternatives you've tried:**

Would be very useful for HMI devices targeted at controlling RGB lighting devices.
If not present all I could think to do is add a couple of buttons with preset colors, which is a bit limiting.

**Additional context**

`lv_colorwheel` is also a thing although I thing `lv_cpicker` would be more useful.
https://docs.lvgl.io/8.3/widgets/extra/colorwheel.html

**Comment by bennydiamond** [comment]
That makes sense as to why it wasn't already supported then!

Are there alternative widgets offered in ESPHome that would offer similar functionnality?
As I said, I would like to control a RGG bulb from an HMI and I would really like a widget that lets me pick any color rather than resorting to having a couple preset colors exposed as buttons on my  HMI.

Thank you.

**Comment by nagyrobi** [comment]
@clydebarrow

**Comment by clydebarrow** [comment]
I have a proof of concept colour picker working, but it needs some more attention.

**Comment by bennydiamond** [comment]
> I have a proof of concept colour picker working, but it needs some more attention.

My curiosity is piqued.
Do you have an example I could maybe give a go at it?

**Comment by clydebarrow** [comment]
```
external_components:
  - source: github://clydebarrow/esphome@lvgl-color-picker
    refresh: 30s
    components: [lvgl]

lvgl:
  widgets:
    - color_picker:
        id: picker
        width: 400px
```
