### ISSUE TITLE
Automation for camera

### ISSUE THREAD

**Issue by petrepa** [esphome/feature-requests#305]
**Describe the problem you have/What new integration you would like**

Would like the possibility to turn off camera features and activate them via automations. A button press can for example activate the camera for a given intervall.

Something like this:
``` 
 - platform: gpio
    pin:
      number: GPIO34
      mode: INPUT_PULLUP
      inverted: True
    name: doorbell button
    on_press:
      then:
        - camera.turn_on: my_camera
        - delay: 30s
        - camera.turn_off: my_camera
```

**Please describe your use case for this integration and alternatives you've tried:**

I would use this for my ESP based video doorbell, so the camera is only active for some while after the doorbell button is pressed. This so I will not have surveillance out onto the public street continuously, which can be illegal some places.  

**Additional context**
