### ISSUE TITLE
Add option to suppress color in mqtt log_topic messages

### ISSUE THREAD

**Issue by barcar** [esphome/feature-requests#3051]
**Describe the problem you have/What new integration you would like**

I would like to have an option to suppress the ANSI color codes from the MQTT messages emitted when log_topic is configured.

Something like the last 3 lines of this YAML snippet:

```
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: ${mqtt_client}
  topic_prefix: "esphome/${name}"
  discovery_prefix: ${topic_prefix}_discovery
  discovery: false
  log_topic: 
    topic: ${topic_prefix}/${name}/log
    include_color: false
```

**Please describe your use case for this integration and alternatives you've tried:**

MQTT log messages contain the ANSI color codes which makes them difficult to read. For example:

`[0;33m[W][component:238]: Components should block for at most 30 ms.[0m`

I would prefer them to be simply:

`[W][component:238]: Components should block for at most 30 ms.`

There do not seem to be any ways to pre-process these messages before they are sent.

**Additional context**

Nothing to add.
