### ISSUE TITLE
Add support to GROVE ULTRASONIC SENSOR 3-pin hardware in ESPHome

### ISSUE THREAD

**Issue by jpatriarca** [esphome/feature-requests#3056]
**Describe the problem you have/What new integration you would like**

Due to the ESPHome 2025.02 update and the removal of customer platform configuration, we need to change the code in an advanced way due to the last of support to the Grove Ultrasonic Sensor with a unique signal and return pin.

**Please describe your use case for this integration and alternatives you've tried:**

So far, and until last update, we would achieve to make the sensor work with the following YAML configuration:

```
esphome:
  name: $device_name
  includes:
    - custom_us_sensor_esp32.h
  libraries:
    - "Grove Ultrasonic Ranger"
```

Then, for the sensor, with the following configuration:

```
sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new MyCustomSensor();
      App.register_component(my_sensor);
      return {my_sensor};

    sensors:
      name: Garage $friendly_name Distance
      unit_of_measurement: cm
      id: garage_sensor
      internal: True
```

With this configuration, I could get the values in centimeters and use it in a template to get a door status.

The library in use, where we configure the pin to be user, is as follow:

```
#include "esphome.h"
#include "Ultrasonic.h"

Ultrasonic ultrasonic(13);

class MyCustomSensor : public PollingComponent, public Sensor {
 public:

  MyCustomSensor() : PollingComponent(1000) { }

  void setup() override {
    
  }

  void update() override {
    int distance = ultrasonic.MeasureInCentimeters();
    publish_state(distance);
  }
};
```

**Additional context**

To avoid this customization and to be able to use Grove Ultrasonic sensor without customizations and compliant with your platform security, I suggest to create the device with support to the 3-pin hardware like this:

```
sensor:
  - platform: ultrasonic
    pin: D17
    name: Garage $friendly_name Distance
    unit_of_measurement: cm
    id: garage_sensor
    update_interval: 1s
    internal: true
```

or even with the possibility to use the following configuration that is not currently allowed in ESPHome:

```
sensor:
  - platform: ultrasonic
    trigger_pin: D17
    echo_pin: D17
    name: Garage $friendly_name Distance
    unit_of_measurement: cm
    id: garage_sensor
    update_interval: 1s
    internal: true
```
Thanks for the time you spent to read this and hoping for the development of support for this device in ESPHome.
