### ISSUE TITLE
Ability to Set Duty Time Sensor

### ISSUE THREAD

**Issue by myztillx** [esphome/feature-requests#3075]
**Describe the problem you have/What new integration you would like**

Add the ability to set the time for duty time. This would allow you to store the value in a global variable on an interval. The value could then be restored to the sensor value on startup. Currently, without being able to set the duty_time, the only way to restore the value is using `restore`. This method gives the warning that it could wear out the flash.

**Please describe your use case for this integration and alternatives you've tried:**

The use case it to try and preserve the flash.

**Additional context**

Example
```yaml
sensor:
  - platform: duty_time
    id: duty_time_daily
    name: Daily Runtime
    lambda: |-
      return id(valve).state;
    restore: False
    update_interval: 60s

# Global variables store the duty times
# This is to preserve flash and not write every few seconds.
globals:
  - id: global_duty_time_daily
    type: int
    restore_value: True

interval:
  # Save to global
  - interval: 5min # whatever interval
    then:
      - lambda: |-
          id(global_duty_time_daily) = id(duty_time_daily).state;

esphome:
  on_boot: 
    then:
      - duty_time.set:
          id: duty_time_daily
          value: !lambda 'return id(global_duty_time_daily);'
```

**Comment by pksoft585** [comment]
For a similar option (setting the startup state), I modified the existing **duty_time** to a local external component. All I had to do was modify a few lines of code—the reset function uses a parameter, so it is possible to either reset or set the state to the desired value using this function. See **duty_time_sensor.h**:

```
class DutyTimeSensor : public sensor::Sensor, public PollingComponent {
 public:
  ...
  void reset(uint32_t default_value = 0) { this->set_value_(default_value); }

...

template<typename... Ts> class ResetAction : public BaseAction<Ts...> {
 public:
  TEMPLATABLE_VALUE(uint32_t, value)
  
  void play(Ts... x) override { 
    this->parent_->reset(this->value_.value(x...)); 
  }
};
```

and next v **esphome** (I used a _number_ because of the possibility of setting the value from the interface, but using _globals_ is similar):

```
esphome:
  name: lilygo-t-display-s3
  friendly_name: Duty Time Meter

external_components:
  - source:
      type: local
      path: my_components
    components: [ duty_time ]

...

number:
  - platform: template
    name: "Start value"
    id: start_value
    icon: mdi:timer-cog
    update_interval: never
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 10000
    step: 1
    unit_of_measurement: "s"

...

# Set start_value
id(lilygo_t_display_s3_duty_time).reset((uint32_t) id(start_value).state);

# Reset value to zero
id(lilygo_t_display_s3_duty_time).reset();
```
The feature request could take a long time...
