### ISSUE TITLE
Add support for sensor platform: AP3216 (CJMCU 3216) ambient light and proximity sensor

### ISSUE THREAD

**Issue by sfields-forever** [esphome/feature-requests#3086]
**Describe the problem you have/What new integration you would like**
Add support for sensor platform: AP3216 (CJMCU 3216) ambient light and proximity sensor

**Please describe your use case for this integration and alternatives you've tried:**
I have an AP3216 (CJMCU 3216) sensor, but as far as I can see, ESPHome doesn't support it. It features a high-resolution lux sensor with calibration, accurate distance measurement, and an interrupt mode. The sensor also offers anti-flicker rejection (rejecting 50/60Hz), high sensitivity in darkened glass, and window loss compensation. While it works seamlessly with ESP, it is not supported by ESPHome.

**Additional context**
See also
https://wolles-elektronikkiste.de/en/ap3216-cjmcu-3216-ambient-light-and-proximity-sensor
https://github.com/wollewald/AP3216_WE
(https://github.com/igorantolic/ai_ap3216_ambient-light-and-proximity-sensor-library)

**Comment by 10-thousand** [comment]
Hello! I created an external component (https://github.com/10-thousand/esphome-AP3216/tree/main) for AP3216 (CJMCU 3216). 
You can test it now. 

Add external component to you project:
```
external_components:
  - source: github://10-thousand/esphome-AP3216@main
    components: [ap3216]
```

and AP3216 sensor:
```
i2c:
  sda: GPIO21  // your sda
  scl: GPIO22   // your scl
sensor:
  - platform: ap3216
    mode: ALS_PS
    operating_mode: VALUE
    ambient_light: "Ambient light"
    ps_counts: "Proximity"
    infrared_counts: "Infrared"
    ir_data: "Ir data"
    is_near: "is_near"
    
    address: 0x23
    update_interval: 60s
```
