### ISSUE TITLE
Allow throttling of text_sensor (and all sensors?)

### ISSUE THREAD

**Issue by jdanders** [esphome/feature-requests#3089]
**Describe the problem you have/What new integration you would like**
I would like text_sensor specifically (but maybe there are other sensor types that could use this too) to allow throttling of data published. I would think this would be implemented with a `throttle` filter added to the text_sensor component. 

Looking at `binary_sensor`, for example, there is a `settle` filter that seems to accomplish the same goal, but has a different name than `throttle` in the main `sensor` component.

Candidate filters to be ported to other types of sensors based on time:
* `throttle`
* `heartbeat`
* `timeout`
* `debounce`

Candidate sensor types that could be time filtered (quick Google search):
* `binary_sensor`
* `text_sensor` (my use case)

Seems like most other sensors respond to commands rather than generate uncontrolled input.

**Please describe your use case for this integration and alternatives you've tried:**
In my particular case I have a UART sensor that puts out updates at a fairly high rate. In order to manage my Home Assistant database size, I'd like to limit that with a `throttle` filter. 

**Additional context**
My sensor is coming from the [esphome-econet](https://github.com/esphome-econet/esphome-econet) component.

**Comment by nagyrobi** [comment]
A workaround is to set the UART text sensor ad internal, and define a new template text sensor which is updated from a lambda of the internal sensor only when the text changes.

**Comment by ssieb** [comment]
Just use a lambda filter instead of publishing to another one.

**Comment by jdanders** [comment]
> A workaround is to set the UART text sensor as internal, and define a new template text sensor which is updated from a lambda of the internal sensor only when the text changes.

This is not the request. The throttle filter is time-based. So the sensor value might be changing value 100 times per second, but I only want to send an update every 60 seconds. 

> Just use a lambda filter instead of publishing to another one.

Yes, agreed that this can be solved with lambda. However, the only way I can figure of a way to do it requires creating at least a variable per sensor to track whether an update has been sent per time period or not. There are lots of sensors that I want to time-throttle and it would be awesome if esphome could do it for me instead of doubling the number of lines of code.

I've done something like this in the past. It's a lot of code -- recommendations for improvement is welcome.
```yaml
globals:
  # only needed once
  - id: ticks_since_start
    type: int
    restore_value: no
    initial_value: "0"
  # need one per sensor
  - id: sensor1_tick
    type: int
    restore_value: no
    initial_value: "0"
# only needed once
interval:
  - interval: ${tick_duration}
    then:
      - lambda: |-
           id(ticks_since_start) += 1;
sensor:
# actual sensor
  - platform: template
    id: sensor1
    lambda: !lambda |-
      if (id(ticks_since_start) >  id(sensor1_tick)) return x;
      else return id(sensor1).state;
```

All that could be replaced with:
```yaml
sensor:
  - platform: template
    id: sensor1
    filters:
    - throttle: ${tick_duration}
```

**Comment by ssieb** [comment]
> lambda: !lambda |-
>       if (id(ticks_since_start) >  id(sensor1_tick)) return x;
>       else return id(sensor1).state;

That doesn't actually do anything.  `x` == `id(sensor1).state`.
```yaml
sensor:
  - platform: whatever
    id: sensor1
    filters:
      lambda: |-
        static uint32_t last_publish = 0;
        if (millis() - last_publish < ${throttle_ms}) return {};
        last_publish = millis();
        return x;
```

But sure, a `throttle:` filter for `text_sensor:` is a bit strange, but valid.  Why is a text sensor changing values so much?
