### ISSUE TITLE
Add support for BMM150 geomagnetic sensor and BMI270 attitude sensor

### ISSUE THREAD

**Issue by FritzTheCatfish** [esphome/feature-requests#3119]
**Describe the problem you have/What new integration you would like**

Please add support for BMM150 geomagnetic sensor and BMI270 attitude sensor. These sensors are included in M5stack Atom S3R board.

**Please describe your use case for this integration and alternatives you've tried:**

There are examples for the BMI270 for esphome as https://github.com/kkuphal/m5stick-esphome-magnetometer-water-meter/tree/main but they are specific to that case and not for a general use

**Additional context**

**Comment by lboue** [comment]
I found componants here:

**BMM150**
- https://github.com/brianhealey/M5CoreS3-Esphome/tree/main/components/m5cores3_bmm150

**BMI270**
- https://github.com/patrick3399/esphome_components/tree/main/components/bmi270
- https://github.com/erikcoin/esphome-lilygo-t547plus/tree/dev/components/bmi270
- https://github.com/brianhealey/M5CoreS3-Esphome/tree/main/components/m5cores3_bmi270

**Comment by oxc** [comment]
See also #3052 

There the following sensor implementation is linked:
https://github.com/DennisGaida/m5stack-atoms3r-components/tree/main/components/bmi270_bmm150

**Comment by lboue** [comment]
I tested it and it doesn't work with the M5Tab.

**Comment by andyearnshaw** [comment]
The BMI270 is working for me on my AtomS3R in ESPHome:

```yaml
motion:
  - platform: bmi270
    address: 0x68
    update_interval: 50ms

sensor:
  - platform: motion
    type: acceleration_x
    id: accel_x
    internal: true
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1
      - delta: 0.02
  - platform: motion
    type: acceleration_y
    id: accel_y
    internal: true
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1
      - delta: 0.02
  - platform: motion
    type: acceleration_z
    id: accel_z
    internal: true
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1
      - delta: 0.02
```
