### ISSUE TITLE
Add support for BH1900NUX Temperature Sensor

### ISSUE THREAD

**Issue by B48D81EFCC** [esphome/feature-requests#3135]
**Describe the problem you have/What new integration you would like**
I would like to have support for BH1900NUX (BH1900NUX-TR) from Rohm Semiconductor.

**Please describe your use case for this integration and alternatives you've tried:**
Temperature measurement

**Additional context**
I am currently working on implementing support for this sensor.  
Any help / feedback / testing is appreciated: 
https://github.com/esphome/esphome/pull/8591

**Comment by B48D81EFCC** [comment]
The current WIP can be tested using external component:  

```
external_components:
  - source: github://pr#8631
    components: [ bh1900nux ]
```
```
sensor:
  - platform: bh1900nux
    name: "Living Room Temperature"
    address: 0x48
    update_interval: 10s
```
