### ISSUE TITLE
Add support for light control on Tormatic/Novoferm garage door drives

### ISSUE THREAD

**Issue by miguelangel-nubla** [esphome/feature-requests#3181]
Add support for light control on Tormatic/Novoferm garage door motor.

The Homematic IP addon for these motors (HmIP-MOD-TM) has separate control and is connected using the same USB port used in the current `tormatic` integration, so it should be doable.

**Comment by donkeylabs** [comment]
@MartB Hello, it would be great, if you could share a sample config if possible. I would like to test your component aswell.

Thank you for your work.

Regards
Alex

**Comment by MartB** [comment]
> [@MartB](https://github.com/MartB) Hello, it would be great, if you could share a sample config if possible. I would like to test your component aswell.
> 
> Thank you for your work.
> 
> Regards Alex

Im not sure which state is online at the moment, but the following should work.

```
novoferm:
    uart_id: uart_tormatic

cover:
  - platform: novoferm
    id: garage_door
    name: "Garage Door"
    open_duration: 15s
    close_duration: 22s
```

Where uart_id is your id of the uart.

**Comment by donkeylabs** [comment]
Hello @MartB, thank you for your quick response, but somehow it is not working for me. 

@miguelangel-nubla : could you be so kind and send me your ESPHome config for that part, I do not seem to get it running. 
Is there any special requirement when soldering the levelshifter. 
Thank you for your help.

**Comment by miguelangel-nubla** [comment]
Try to make it work with the original component first. https://esphome.io/components/cover/tormatic.html#setup
Here are some photos of the connections https://github.com/esphome/esphome/pull/5933#issuecomment-2684679501

Make sure you don't have a ground loop (the board is not connected to another power supply, etc)
I use a [POE powered ESP32-POE-ISO](https://www.olimex.com/Products/IoT/ESP32/ESP32-POE-ISO/open-source-hardware) and have had success with an ADUM1201 from amazon.

Also some users reported issues with cheap chinese level shifters, I have burned some myself. Don't know yet what is the culprit but make sure to always unplug the motor from AC before connecting the USB to reduce chances.

This is my current config with the version pinned in order to isolate variables. It has been running fine for weeks now with my [HW-800](https://de.elv.com/p/tormatic-funk-garagentorantrieb-hw-800-weiss-mit-2-funk-handsendern-und-homematic-ip-funkmodul-P250204/).

```
external_components:
  - components: [ novoferm ]
    source: github://MartB/esphome@b1c8b9d1d740d04e590fceb4ade04089689b13b6

uart:
  id: uart_tormatic
  rx_pin: GPIO36
  tx_pin: GPIO04
  baud_rate: 9600

novoferm:

light:
  - platform: novoferm
    name: garage door motor

cover:
  - platform: novoferm
    name: garage door
    device_class: garage
```

Make sure to enable debug logger to see if there is any raw communication at all.
