### ISSUE TITLE
Multiple wifis - no multiple domains

### ISSUE THREAD

**Issue by alve89** [esphome/feature-requests#3188]
**Describe the problem you have/What new integration you would like**
Hi all,

I actually expect a support of multiple domains when using multiple wifis. It's not uncommon that different networks use different domains.
```
wifi:
  networks:
    - ssid: !secret wifi_1_ssid
      password: !secret wifi_1_password
      # domain: ".domain1"
    - ssid: !secret wifi_2_ssid
      password: !secret wifi_2_password
      # domain: ".domain2"
```

Although I'm unsure if this is possible anyway because the hostname is set generally and not network specific...?

**Please describe your use case for this integration and alternatives you've tried:**
There's actually no alternative, I can't make it happen.

**Additional context**
