### ISSUE TITLE
SDS011 and Deep Sleep: No Data

### ISSUE THREAD

**Issue by tscs37** [esphome/feature-requests#322]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io + ESPHome Installation

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 (NodeMCU v2) but should affect other boards aswell

**Affected component:**

https://esphome.io/components/sensor/sds011.html

**Description of problem:**

When setting up the update interval of the SDS011, the documentation states this sets the operating interval in the sensor itself. When setting it to 1 minute it can be observed that the sensor operates at 1 minute intervals even if the ESP is in deep sleep (Node remains unavailable in the network).

The issue is that when setting higher deep sleep and update intervals for the ESP and component, it becomes difficult to "time" the operating time of both, resulting in the sensor and ESP drifting away after some time. In my case this causes the node to not report any new sensor values.

This issue occured both with MQTT and the native API.

However, the deep sleep is still something I want to save power, by my numbers a 30 minute deep sleep would extend the lifetime of the battery I use from 10 hours to a week.

I believe the query data mode would solve this [\[manual\]](https://cdn.sparkfun.com/assets/parts/1/2/2/7/5/Laser_Dust_Sensor_Control_Protocol_V1.3.pdf) and allow the ESP to retrieve data even when the sensor is not working.

At the moment, the SDS011.cpp code uses Active Reporting mode, which requires both the node and sensor to be online at the same time to work, from what I understand in the manual, so together with deep sleep, this makes it almost impossible to use the sensor for long-term unattended nodes.

```c++
// sds011.cpp:40
command_data[2] = SDS011_MODE_REPORT_ACTIVE;
```

**Problem-relevant YAML-configuration entries:**
```yaml
deep_sleep:
  run_duration: 90s
  sleep_duration: 30min

sensor:
  - platform: sds011
    pm_2_5:
      name: "PM25"
    pm_10_0:
      name. "PM100"
    update_interval: 30min
    id: sds011_sensor
# proposed solution
    sensor_mode: query
    #sensor_mode: active # default
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
