### ISSUE TITLE
Support for multiple i2c busses

### ISSUE THREAD

**Issue by tdamsma** [esphome/feature-requests#337]
**Describe the problem you have/What new integration you would like**
I would like to connect multiple sensors with a fixed I2C address

**Please describe your use case for this integration and alternatives you've tried:**
I have multiple bme280 that I want to connect to the same esp32. As there are plenty of pins capable of i2c I managed to do this with micropython by just setting up multiple i2c busses, no problem. With esphome there is no support for that

**Additional context**
Found a similar (misfiled) feature request here: https://github.com/esphome/issues/issues/473

**Comment by OttoWinter** [comment]
Already possible:

```yaml
i2c:
- sda: GPIO0
  scl: GPIO2
  id: i2c_bus1
- sda: GPIO3
  scl: GPIO4
  id: i2c_bus2

sensor:
- platform: bme280
  i2c_id: i2c_bus1
  # ...
```
