### ISSUE TITLE
Nextion: call "printf" for text sensors

### ISSUE THREAD

**Issue by romquenin** [esphome/feature-requests#356]
**Describe the problem you have/What new integration you would like**

Hello i have succesfully  linked buttons and sensors with "numeric" state from home assistant to my display but unfortunately "text" sensors wont work.

I'm completely stuck this time and and would like to know if you could help me with this issue.
Here is the code i have so far for text sensor:

`          it.set_component_text_printf("date","%",id(date_jour).state);`

I have tried to add "d", and "s" after the percent but "d" is retuning nothing an "s" makes the display become crazy.

Any help would be awsome.

Thank you.

Love your work and ESPHome,

**Comment by romquenin** [comment]
```
sensor:
  - platform: homeassistant   # Forecast precipitation
    id: uptime_hours
    entity_id: sensor.uptime     

text_sensor:
  - platform: homeassistant
    id: date_jour
    entity_id: weather.dark_sky
  - platform: version
    name: ESPHome Version
    id: version_test

            
binary_sensor:
  - platform: nextion
    page_id: 0
    component_id: 14
    id: reboot
    on_press:
      then:
        - homeassistant.service:
            service: script.hdmi_4

display:
  - platform: nextion
    id: teplomer
    update_interval: 5s
    lambda: |-
          it.set_component_text_printf("ligne","EN LIGNE DEPUIS %.2f MINUTES",id(uptime_hours).state);
          it.set_component_text_printf("date","%s",id(date_jour).state);
```
