### ISSUE TITLE
Several intervals

### ISSUE THREAD

**Issue by HFsi** [esphome/feature-requests#359]
**Describe the problem you have/What new integration you would like**

I need to define more than one interval, to do certain operations
**Please describe your use case for this integration and alternatives you've tried:**

I have for example an interval that blinks a led in N seconds depending on the state of one sensor, but I need another interval for switching a rele under certain periodic conditions
**Additional context**

**Comment by glmnet** [comment]
Hi,

You can have several intervals:

````yaml
# Example configuration entry
interval:
  - interval: 1min
    then:
      - switch.toggle: relay_1
  - interval: 42s
    then:
      - light.toggle: light_1
````
