### ISSUE TITLE
Possibility to fill a dark rectangle on a SSD1306 with a lux automation

### ISSUE THREAD

**Issue by Electronlibre2012** [esphome/feature-requests#366]
Hello, i would like to use a photoresistance attached to the A0 of a ESP8266 to measure lux (already published by @OttoWinter ) and then fill a rectangle (like black screen) on a ssd1360.
The light of a SSD1360 is too bright for a room in dark when you want to sleep...
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

I try this code but dont know what to do after the "then"...how to interact with the ```- platform: ssd1306_i2c``` component, because he is in the ```display:``` and not in ```sensor:``` :

```
- platform: adc
    pin: A0
    name: Illuminance
    id: luminanceC1
    unit_of_measurement: lux
    filters:
      - lambda: return ( x * 3.3 / 10000.0) * 2000000.0 
    on_value:
      if:
        condition:
          sensor.in_range:
            id: luminanceC1
            below: 10.0
        then:
          - script.execute: my_script 
```

**Additional context**

Thanks if someone can help
