### ISSUE TITLE
Nextion: Change picture by attribute

### ISSUE THREAD

**Issue by Andoramb** [esphome/feature-requests#374]
**Describe the problem you have/What new integration you would like**
For Nextion displays: it is possible to change a picture element to display a different image

For example in the Nextion debugger: 
```
p1.pic=80
or
p1.pic=p1.pic+1
```
Basically the same function is already implemented in _nextion.cpp_:

```
void Nextion::set_component_text(const char *component, const char *text) {
  this->send_command_printf("%s.txt=\"%s\"", component, text);
}
```
But it should work also with (or maybe not with char type as argument):
```
void Nextion::set_component_picture(const char *component, const char *text) {
  this->send_command_printf("%s.pic=\"%s\"", component, text);
}
```

**Please describe your use case for this integration and alternatives you've tried:**

This way it would be much easier ti display/change already positioned pictures.
A good use case is:

```
sensor:
  - platform: homeassistant   # Forecast icon
    id: today_icon
    entity_id: sensor.weather_symbol # 1,2,3,etc. imported from HA

#then 

display:
  - platform: nextion
    id: nextiondisplay
    ......
         #copied from above
          it.set_component_picture("weather","%i",id(today_icon).state);
```

This way the weather picture (or any other pic) can be updated automatically without messing aorund with XY coordinates and drawing one picture above another
![nextionPic](https://user-images.githubusercontent.com/3399628/63637226-85866d00-c67a-11e9-9ebf-7a43d72c2aaa.PNG)

**Additional context**
