### ISSUE TITLE
Support for output.ledc.set_frequency

### ISSUE THREAD

**Issue by DasBootU96** [esphome/feature-requests#380]
**Describe the problem you have/What new integration you would like**

Support for output.esp8266_pwm.set_frequency exists, but output.ledc.set_frequency on ESP32 does not. Can this be added?

**Please describe your use case for this integration and alternatives you've tried:**

I can get a single tone, but then tried this to get multiple tones, but since "set_frequency" is appears not implemented for ledc, I get error: Unable to find action with the name 'output.ledc.set_frequency'.

```yaml
output:
  - platform: ledc
    pin: GPIO19
    id: 'buzzer'

switch:
  - platform: template
    name: buzzzzzz
    turn_on_action:
      then:
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 800Hz
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 500ms
        - output.turn_off: buzzer
        - delay: 200ms
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 600Hz
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 500ms
        - output.turn_off: buzzer
```

**Additional context**

Want buzzer to generate a few Star Wars- The Imperial March tones.

**Comment by tdamsma** [comment]
I was about to file a feature request for exactly this, but see the work has already started. I am impressed once again, keep up the god work!

**Comment by martin3000** [comment]
what version of esphome do I ned to use set_frequency?

**Comment by glmnet** [comment]
> what version of esphome do I ned to use set_frequency?

Not available in 1.13. You need 1.14 beta or dev

**Comment by DasBootU96** [comment]
Tested with dev and It works quite well with a cheap passive buzzer, thanks a 1000000! 

```
script:
  - id: ImperialMarch
    then:
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 440
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 500ms
        - output.turn_off: buzzer
        - delay: 20ms
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 440
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 500ms
        - output.turn_off: buzzer
        - delay: 20ms
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 440
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 500ms
        - output.turn_off: buzzer
        - delay: 20ms        
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 349
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 350ms
        - output.turn_off: buzzer
        - delay: 20ms
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 523
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 150ms
        - output.turn_off: buzzer
        - delay: 20ms
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 440
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 500ms
        - output.turn_off: buzzer
        - delay: 20ms
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 349
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 350ms
        - output.turn_off: buzzer
        - delay: 20ms
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 523
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 150ms
        - output.turn_off: buzzer
        - delay: 20ms
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 440
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 650ms
        - output.turn_off: buzzer

  - id: SuperMario
    then:
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 660 
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 100ms
        - output.turn_off: buzzer
        - delay: 150ms
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 660 
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 100ms
        - output.turn_off: buzzer
        - delay: 300ms
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 660
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 100ms
        - output.turn_off: buzzer
        - delay: 300ms        
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 510
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 100ms
        - output.turn_off: buzzer
        - delay: 100ms
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 660
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 100ms
        - output.turn_off: buzzer
        - delay: 300ms
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 770
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 100ms
        - output.turn_off: buzzer
        - delay: 550ms
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 380
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 100ms
        - output.turn_off: buzzer


switch:
  - platform: template
    name: Buzz Imperial March
    icon: "mdi:bell-ring"
    turn_on_action:
      - if:
          condition:
            - script.is_running: ImperialMarch
          then:
            - script.stop: ImperialMarch
            - script.execute: ImperialMarch
          else:
            - script.execute: ImperialMarch    

  - platform: template
    name: Buzz Super Mario
    icon: "mdi:bell-ring"
    turn_on_action:
      - if:
          condition:
            - script.is_running: SuperMario
          then:
            - script.stop: SuperMario
            - script.execute: SuperMario
          else:
            - script.execute: SuperMario
```
