### ISSUE TITLE
[web server] No states on web server

### ISSUE THREAD

**Issue by froido** [esphome/feature-requests#385]
Hi,

there is a problem with showing the states on the web server. There are no states shown in the web frontend, even though they are updating in the serial console.

Config: Adafruit ESP32 Feather as standalone webserver

### YAML-File:
```
esphome:
  name: pump
  platform: ESP32
  board: featheresp32

web_server:
  port: 80

wifi:
  ap:
    ssid: "esp32-pump"
    password: "esp32-pump!"
  reboot_timeout: 0s
  
# Enable logging
logger:

sensor:
  - platform: esp32_hall
    name: "ESP32 Hall Sensor"
    update_interval: 2s
    id: bla

```

### Serial-Log:
[https://rwth-aachen.sciebo.de/s/Gt67D3o3YLqYnyR](https://rwth-aachen.sciebo.de/s/Gt67D3o3YLqYnyR)

### Web-Frontend:
[https://rwth-aachen.sciebo.de/s/heK4WbJeJ1jfJ2H](https://rwth-aachen.sciebo.de/s/heK4WbJeJ1jfJ2H)
