### ISSUE TITLE
Implement BLE temperature sensor - Inkbird 

### ISSUE THREAD

**Issue by danps1** [esphome/feature-requests#397]
**Describe the problem you have/What new integration you would like**

The Inkbird IBT-6X is a pretty popular BBQ thermometer that has 6 probes and transmits temperature data over BLE to a phone app. 

[https://www.amazon.com/stores/page/0546CE73-22C5-4AF8-AF34-01A3A4EF3F4D?ingress=0&visitId=939e9d41-b8b3-44d2-93f2-d58471c6bcfd&lp_slot=auto-sparkle-hsa-tetris&store_ref=SB_A0622099Z7RNH0U4IISR](url)

Both the device and the app are good, but it would be even better if we could use ESPHome to harvest this data into HA and then run automations etc!

I have captured the bluetooth packets, and decoded the frames, but lack the programming skills to implement this into ESPHome.

**Please describe your use case for this integration and alternatives you've tried:**

This is the capture of a typical packet...

![image](https://user-images.githubusercontent.com/36139437/64509047-43b82080-d322-11e9-8239-1d45ccd7c4ba.png)

The frame headers seem to be the same each time, with the part that changes being the value at the end. These 12 bytes seem to correspond to the temperature reading of the 6 probes in celsius. Each 2 byte pair appears to be swapped, and then converted to decimal gives the temperature (10x) in °C.

For example, in this capture, I have probes 1 and 3 connected, and probe 1 is at 4°C and probe 3 is at 194°C...
```
28 00 - Probe 1 - 0x0028 = 40 decimal = 4°C
f6 ff - Probe 2 - disconnected
94 07 - Probe 3 - 0x0794 = 1,940 decimal = 194°C
f6 ff - Probe 4 - disconnected
f6 ff - Probe 5 - disconnected
f6 ff - Probe 6 - disconnected
```

**Additional context**

I imagine the syntax in esphome then being similar to a xiaomi mijia...
```
esp32_ble_tracker:

sensor:
  - platform: inkbird
    mac_address: 7A:80:8E:19:36:BA
    probe1:
      name: "Inkbird Probe 1"
    probe2:
      name: "Inkbird Probe 2"
    probe3:
      name: "Inkbird Probe 3"
    probe4:
      name: "Inkbird Probe 4"
    probe5:
      name: "Inkbird Probe 5"
    probe6:
      name: "Inkbird Probe 6"
```
