### ISSUE TITLE
Hide build timestamp from text_sensor version

### ISSUE THREAD

**Issue by maartenpaauw** [esphome/feature-requests#398]
**Describe the problem you have/What new integration you would like**

I would like to be able to remove the version build timestamp from the `version text_sensor` component.

**Please describe your use case for this integration and alternatives you've tried:**

I didn't try anything yet. But it would be nice if something like this is possible.

```yaml
text_sensor:
  - platform: version
    name: version
    hide_build_timestamp: true
```

**Additional context**

https://community.home-assistant.io/t/version-sensor-without-build-date-and-time/135895
