### ISSUE TITLE
Improve configuration modularity with collecting enumeration for config

### ISSUE THREAD

**Issue by ng-galien** [esphome/feature-requests#402]
**Describe the problem you have/What new integration you would like**

When we integrate several devices with the same hardware, it's better to use a generic config.
When splitting the config between generic part and specific part an enum property is completely overridden.
Is it possible to collect the entries of the the same enum across files parsing instead of overriding it?

**CASE**  

It is the main config.
>config.yaml

```yaml
substitutions:
  device_id: "00"

  device_name: sonoff_t1
  #device_name: sonoff_light
  
  relay_icon: mdi:flash
  #relay_icon: mdi:lightbulb
  input_icon: mdi:gesture-tap
  timeout: 15min
  maintenance_ip: 10.0.1.49
  log_level: DEBUG

<<: !include 8266_base.yaml

## =====| SONOFF LIGHT CONFIG |===== ##
#<<: !include sonoff_basic_light.yaml
## =====| SONOFF SWITCH CONFIG |===== ##
#<<: !include sonoff_basic_switch.yaml
## =====|  SONOFF  T1 CONFIG   |===== ##
<<: !include sonoff_t1.yaml
```

The common config have a binary sensor (status) which should be shared across different devices.

> 8266_base.yaml

``` yaml
# COMMON PROPERTIES
esphome:
  name: ${device_name}_${device_id}
  platform: ESP8266
  board: esp01_1m
  on_boot:
    lambda: !lambda |-
      ESP.eraseConfig();

wifi:
  networks:
  - ssid: !secret wifi_1_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_maintenance_ssid
    password: !secret wifi_maintenance_password 

# The power save mode set to light causes connection troubles
#  power_save_mode: light
#  ap:
#    ssid: ${device_name}_${device_id}
#  ap:
#    ssid: ${device_name}_${device_id}
#  use_address: ${maintenance_ip}

api:
  reboot_timeout: ${timeout}

logger: 
  level: VERY_VERBOSE

ota:

# == WIFI == #
sensor:
  - platform: wifi_signal
    name: "${device_name}_${device_id}_wifi"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${device_name}_${device_id}_ip"
    ssid:
      name: "${device_name}${device_id}_ssid"
    bssid:
      name: "${device_name}_${device_id}_bssid"
binary_sensor:
  - platform: status
    name: "${device_name}_${device_id}_status" 
```

The others specific configs can have other binary sensors.

> sonoff_basic_ligh.yaml

```yaml
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${device_name}_${device_id}_button"
    on_press:
      - light.toggle: light_output
```

> sonoff_basic_ligh.yaml

```yaml
binary_sensor:
    # Button 1 templates
  - platform: template
    name: "${device_name}_${device_id}_virt_0_0"
    id: _virt_0_0
  - platform: template
    name: "${device_name}_${device_id}_virt_0_1"
    id: _virt_0_1
  - platform: template
    name: "${device_name}_${device_id}_virt_0_2"
    id: _virt_0_2
  - platform: template
    name: "${device_name}_${device_id}_virt_0_3"
    id: _virt_0_3
  - platform: gpio
    name: "${device_name}_${device_id}_button1"
    id: _btn_0
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_click: ...
```
The generated config loses the status binary sensor 

```yaml
binary_sensor:
- platform: template
  name: sonoff_t1_00_virt_0_0
  id: _virt_0_0
- platform: template
  name: sonoff_t1_00_virt_0_1
  id: _virt_0_1
- platform: template
  name: sonoff_t1_00_virt_0_2
  id: _virt_0_2
- platform: template
  name: sonoff_t1_00_virt_0_3
  id: _virt_0_3
- platform: gpio
  name: sonoff_t1_00_button1
  id: _btn_0
  pin:
    number: 0
    mode: INPUT_PULLUP
    inverted: true
  on_click:
  - then:
    - logger.log:
        format: _btn_0 short clicked
        args: []
        tag: main
        level: DEBUG
    - light.toggle:
        id: light_output_1
    - if:
        condition:
          binary_sensor.is_off:
            id: _virt_0_0
        then:
        - binary_sensor.template.publish:
            id: _virt_0_0
            state: true
        else:
        - if:
            condition:
              binary_sensor.is_off:
                id: _virt_0_1
            then:
            - binary_sensor.template.publish:
                id: _virt_0_1
                state: true
            else:
            - if:
                condition:
                  binary_sensor.is_off:
                    id: _virt_0_2
                then:
                - binary_sensor.template.publish:
                    id: _virt_0_2
                    state: true
                else:
                - if:
                    condition:
                      binary_sensor.is_off:
                        id: _virt_0_3
                    then:
                    - binary_sensor.template.publish:
                        id: _virt_0_3
                        state: true
    min_length: 50ms
    max_length: 350ms
  on_multi_click:
  - timing:
    - min_length: 1500ms
      state: true
    then:
    - logger.log:
        format: _btn_0 long clicked
        args: []
        tag: main
        level: DEBUG
    - if:
        condition:
          and:
          - binary_sensor.is_off:
              id: _virt_0_0
          - binary_sensor.is_off:
              id: _virt_0_1
          - binary_sensor.is_off:
              id: _virt_0_2
          - binary_sensor.is_off:
              id: _virt_0_3
        then:
        - logger.log:
            format: publish_on
            args: []
            tag: main
            level: DEBUG
        - binary_sensor.template.publish:
            id: _virt_0_0
            state: true
        - binary_sensor.template.publish:
            id: _virt_0_1
            state: true
        - binary_sensor.template.publish:
            id: _virt_0_2
            state: true
        - binary_sensor.template.publish:
            id: _virt_0_3
            state: true
        else:
        - logger.log:
            format: publish_off
            args: []
            tag: main
            level: DEBUG
        - binary_sensor.template.publish:
            id: _virt_0_0
            state: false
        - binary_sensor.template.publish:
            id: _virt_0_1
            state: false
        - binary_sensor.template.publish:
            id: _virt_0_2
            state: false
        - binary_sensor.template.publish:
            id: _virt_0_3
            state: false
    invalid_cooldown: 1s
- platform: template
  name: sonoff_t1_00_virt_1_0
  id: _virt_1_0
- platform: template
  name: sonoff_t1_00_virt_1_1
  id: _virt_1_1
- platform: template
  name: ssonoff_t1_00_virt_1_2
  id: _virt_1_2
- platform: template
  name: sonoff_t1_00_virt_1_3
  id: _virt_1_3
- platform: gpio
  name: sonoff_t1_00_button2
  id: _btn_1
  pin:
    number: 9
    mode: INPUT_PULLUP
    inverted: true
  on_click:
  - then:
    - logger.log:
        format: _btn_1 short clicked
        args: []
        tag: main
        level: DEBUG
    - light.toggle:
        id: light_output_2
    - if:
        condition:
          binary_sensor.is_off:
            id: _virt_1_0
        then:
        - binary_sensor.template.publish:
            id: _virt_1_0
            state: true
        else:
        - if:
            condition:
              binary_sensor.is_off:
                id: _virt_1_1
            then:
            - binary_sensor.template.publish:
                id: _virt_1_1
                state: true
            else:
            - if:
                condition:
                  binary_sensor.is_off:
                    id: _virt_1_2
                then:
                - binary_sensor.template.publish:
                    id: _virt_1_2
                    state: true
                else:
                - if:
                    condition:
                      binary_sensor.is_off:
                        id: _virt_1_3
                    then:
                    - binary_sensor.template.publish:
                        id: _virt_1_3
                        state: true
    min_length: 50ms
    max_length: 350ms
  on_multi_click:
  - timing:
    - min_length: 1500ms
      state: true
    then:
    - logger.log:
        format: _btn_1 long clicked
        args: []
        tag: main
        level: DEBUG
    - if:
        condition:
          and:
          - binary_sensor.is_off:
              id: _virt_1_0
          - binary_sensor.is_off:
              id: _virt_1_1
          - binary_sensor.is_off:
              id: _virt_1_2
          - binary_sensor.is_off:
              id: _virt_1_3
        then:
        - logger.log:
            format: publish_on
            args: []
            tag: main
            level: DEBUG
        - binary_sensor.template.publish:
            id: _virt_1_0
            state: true
        - binary_sensor.template.publish:
            id: _virt_1_1
            state: true
        - binary_sensor.template.publish:
            id: _virt_1_2
            state: true
        - binary_sensor.template.publish:
            id: _virt_1_3
            state: true
        else:
        - logger.log:
            format: publish_off
            args: []
            tag: main
            level: DEBUG
        - binary_sensor.template.publish:
            id: _virt_1_0
            state: false
        - binary_sensor.template.publish:
            id: _virt_1_1
            state: false
        - binary_sensor.template.publish:
            id: _virt_1_2
            state: false
        - binary_sensor.template.publish:
            id: _virt_1_3
            state: false
    invalid_cooldown: 1s
```

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

If the mechanism of appending is possible, it would be very useful for all others entries, to had or remove quickly a feature from the base config file.
Thanks
