### ISSUE TITLE
Use substitution in YAML !include directive

### ISSUE THREAD

**Issue by ng-galien** [esphome/feature-requests#403]
**Describe the problem you have/What new integration you would like**

It's not possible to use substitution in !include directive

**CASE**

>config.yaml

```yaml
substitutions:
  device_id: "00"
  device_name: sonoff_t1
<<: !include "${device_name}.yaml"
```

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**
