### ISSUE TITLE
Add wait action to wait until a script ends

### ISSUE THREAD

**Issue by vicfergar** [esphome/feature-requests#416]
**Describe the problem you have/What new integration you would like**

Some times when we call script.execute we need to "stop" execution until the script ends

**Please describe your use case for this integration and alternatives you've tried:**

It is possible to do this after script.execute to wait until the script ends:
```
 wait_until:
   condition:
     not: 
       script.is_running: script_id
```
It could be great to add an action like script.wait that reduce the necessary lines to wait until a certain script execution ends.
**Additional context**
