### ISSUE TITLE
Allow different manual_ip settings per ssid when configuring multiple wifi networks

### ISSUE THREAD

**Issue by davey** [esphome/feature-requests#434]
**Describe the problem you have/What new integration you would like**

Please add support for having separate, per-wifi static IP settings if using multiple wifi networks/SSIDs.

**Please describe your use case for this integration and alternatives you've tried:**

I configured multiple wifi networks to have connection redundancy, want to use manual IP settings instead of DHCP and have different IP settings / subnets in these different wifi networks. 
Currently, it seems not to be possible to have different manual_ip settings for these multiple wifi ssid settings in esphome.

This is what I have now, and it only works if connected to the main-wifi, because only there the IP settings fit:

```yaml
wifi:
  networks:
  - ssid: "main-wifi"
    password: "secret1"
  - ssid: "backup-wifi"
    password: "secret2"
  manual_ip:
    static_ip: 1.11.11.11
    gateway: 10.11.11.1
    subnet: 255.255.255.0
    dns1: 10.11.11.1
    dns2: 8.8.8.8
```

This is what I think would be desirable:

```yaml
wifi:
  networks:
  - ssid: "main-wifi"
    password: "secret1"
    manual_ip:
      static_ip: 10.11.11.11
      gateway: 10.11.11.1
      subnet: 255.255.255.0
      dns1: 10.11.11.1
      dns2: 8.8.8.8
  - ssid: "backup-wifi"
    password: "secret2"
    manual_ip:
      static_ip: 10.22.22.22
      gateway: 10.22.22.1
      subnet: 255.255.255.0
      dns1: 10.22.22.1
      dns2: 8.8.8.8
```

**Additional context**

I know that using DHCP would solve this, but in my case I need to have the static/manual IP settings for multiple reasons (e.g.: don't own the backup-wifi and no DHCP server there; need the fast connection setup; ...)

BTW: Thanks a lot for esphome - I'm LOVING it! :-)
