### ISSUE TITLE
IR gateway

### ISSUE THREAD

**Issue by escoand** [esphome/feature-requests#435]
I try to free my [WiFi-IR-gateway](https://blakadder.github.io/templates/auvisio_S06.html) from the cloud and so installed esphome but struggle to get it working correctly.

The goal ia to use my TV remote control to control my Logitech AV receiver to only have one remote control.

I tried two different options but both do not work. The receiving and the switch at is working without problems so IR is generally working.

```yaml
binary_sensor:
  # map volume_up from Samsung 0xE0E0E01F to NEC 0x10EF+0x58
A7
  - platform: remote_receiver
    id: samsung_volumeup
    samsung:
      data: 0xE0E0E01F
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0x10EF
          command: 0x58A7

  # map volume_down from Samsung 0xE0E0D02F to NEC 0x10EF+0x
708F
  - platform: remote_receiver
    id: samsung_volumedown
    samsung:
      data: 0xE0E0D02F
    on_press:
      - switch.turn_on: volume_down

switch:
  - platform: template
    id: volume_down
    name: Volume Down
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x10EF
          command: 0x708F
```
