### ISSUE TITLE
Support for Sensirion SPS30 Particulate Matter Sensors for air quality measurement

### ISSUE THREAD

**Issue by valordk** [esphome/feature-requests#442]
**Describe the problem you have/What new integration you would like**

Support for Sensirion SPS30 Particulate Matter (aka. air quality) sensor

**Please describe your use case for this integration and alternatives you've tried:**

I'm working on the implementation of this myself, so this is to ensure proper communication and see if others are willing to test it.

**Additional context**

**Comment by matthijsberg** [comment]
I have a couple, if you need someone to test it i'll be happy to.

**Comment by valordk** [comment]
Great. I'll create a pull-request this weekend.

**Comment by valordk** [comment]
> 
> 
> I have a couple, if you need someone to test it i'll be happy to.

I'm not done with the documentation part for the pull request yet... but the i2c implementation can allready be tested if you'd like to build from my feature branch:
`https://github.com/valordk/esphome/tree/dev-sps30-support`

I assume you already have the required JST ZHR-5 connector.
The YAML code snippet should countain the i2c configration and the sps30 platform configuration as follows:
```
i2c:
  sda: 21 <---change this to match your setup
  scl: 22 <---change this to match your setup
  scan: False
  frequency: 50kHz  <---not critical
sensor:
  - platform: sps30
    pm_1_0:
      name: "senntemp SPS30 0x69 PM <1µm Weight concentration"
      id: "senntemp_SPS30_0x69_PM_1_0"
      accuracy_decimals: 2
    pm_2_5:
      name: "senntemp SPS30 0x69 PM <2.5µm Weight concentration"
      id: "senntemp_SPS30_0x69_PM_2_5"
      accuracy_decimals: 2
    pm_4_0:
      name: "senntemp SPS30 0x69 PM <4µm Weight concentration"
      id: "senntemp_SPS30_0x69_PM_4_0"
      accuracy_decimals: 2
    pm_10_0:
      name: "senntemp SPS30 0x69 PM <10µm Weight concentration"
      id: "senntemp_SPS30_0x69_PM_10_0"
      accuracy_decimals: 2  
    pmc_0_5:
      name: "senntemp SPS30 0x69 PM <0.5µm Number concentration"
      id: "senntemp_SPS30_0x69_PMC_0_5"
      accuracy_decimals: 2
    pmc_1_0:
      name: "senntemp SPS30 0x69 PM <1µm Number concentration"
      id: "senntemp_SPS30_0x69_PMC_1_0"
      accuracy_decimals: 2
    pmc_2_5:
      name: "senntemp SPS30 0x69 PM <2.5µm Number concentration"
      id: "senntemp_SPS30_0x69_PMC_2_5"
      accuracy_decimals: 2
    pmc_4_0:
      name: "senntemp SPS30 0x69 PM <4µm Number concentration"
      id: "senntemp_SPS30_0x69_PMC_4_0"
      accuracy_decimals: 2
    pmc_10_0:
      name: "senntemp SPS30 0x69 PM <10µm Number concentration"
      id: "senntemp_SPS30_0x69_PMC_10_0"
      accuracy_decimals: 2  
    address: 0x69
    update_interval: 10s
```
The sensor data should look like this:
![2019-11-18 22_15_29-Home Assistant - Firefox Developer Edition](https://user-images.githubusercontent.com/15346053/69094616-01f9d380-0a51-11ea-8f52-1af149fe1295.png)

regards, 
Val
