### ISSUE TITLE
Support OEM-style Tuya dimmers (labelled QS-WiFi-D01-TRIAC)

### ISSUE THREAD

**Issue by tortfeaser** [esphome/feature-requests#456]
**Describe the problem you have/What new integration you would like**
I'd like it if ESPHome supported Tuya dimmer labelled QS-WiFi-D01-TRIAC

**Please describe your use case for this integration and alternatives you've tried:**
These are affordable, well packaged mosfet (not Triac) dimmers very suitable for home integration with ESPHome. While they work with Tasmota, the ESPHome API makes them a better option for control of these in Home Assistant.

**Additional context**
Tasmota's page for setting these up is at https://blakadder.github.io/templates/qs-wifi_D01_dimmer.html

**Comment by OttoWinter** [comment]
According to the website you linked, you can try something like this for your configuration (using a custom float output)

```cpp
// Save this file as qs_wifi_output.h in your config dir
#include "esphome.h"

class QSWiFiOutput : public FloatOutput, public UARTDevice {
 public:
  QSWiFiOutput(UARTComponent *parent) : UARTDevice(parent) {}

  void write_state(float state) override {
    write_byte(0xFF);
    write_byte(0x55);
    write_byte(uint8_t(state * 255));
    write_byte(0x05);
    write_byte(0xDC);
    write_byte(0x0A);
  }
};
```

```yaml
esphome:
  includes:
    - qs_wifi_output.h

logger:
  baud_rate: 0

uart:
  id: uart_bus
  tx_pin: GPIO1
  baud_rate: 9600

output:
- platform: custom
  type: float
  lambda: |-
    auto my_output = new QSWiFiOutput(id(uart_bus));
    return {my_custom};
  outputs:
    id: custom_float

light:
- platform: monochromatic
  output: custom_float
  name: QS WiFi Dimmer
```

**Comment by tortfeaser** [comment]
Thanks Otto. I'll give that a go and report back.

**Comment by tortfeaser** [comment]
Tried this, got the following compile result:
```
INFO Reading configuration /config/esphome/wifi_dimmer_2.yaml...
...
Compiling /data/wifi_dimmer_2/.pioenvs/wifi_dimmer_2/src/main.cpp.o
src/main.cpp: In lambda function:
src/main.cpp:153:15: error: 'my_custom' was not declared in this scope
       return {my_custom};
               ^
src/main.cpp:153:24: error: could not convert '{<expression error>}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::output::FloatOutput*>'
       return {my_custom};
                        ^
src/main.cpp:154:3: warning: control reaches end of non-void function [-Wreturn-type]
   });
   ^
*** [/data/wifi_dimmer_2/.pioenvs/wifi_dimmer_2/src/main.cpp.o] Error 1
========================= [FAILED] Took 41.91 seconds =========================
```
I think I found the bug though. Here's my attempt at a fix. This compiled:
```
esphome:
  name: wifi_dimmer_2
  platform: ESP8266
  board: esp01_1m
  includes:
    - qs_wifi_output.h

wifi:
  ssid: !secret wifi_SSID
  password: !secret wifi_password

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0

substitutions:
  hostname: "wifi_dimmer_2"

# Enable Home Assistant API
api:
  password: !secret default_password

ota:
  password: !secret default_password
  
# used just for testing, otherwise no need for it
web_server:
  port: 80

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

output:
- platform: custom
  type: float
  lambda: |-
    auto my_output = new QSWiFiOutput(id(uart_bus));
    return {my_output};
#    return {my_custom}; # I think this is wrong, and the line above is correct?
  outputs:
    id: custom_float

light:
- platform: monochromatic
  output: custom_float
  name: $hostname
```
This worked, I can dim and toggle the light from HA.

The remaining functionality available in Tasmota (and OEM) is for a momentary switch connected to GPIO13 counting AC pulses. I'm sure implementing this isn't trivial.

Thanks for your help and for your great product.
