### ISSUE TITLE
Add pzem004t total energy value (Energy field)

### ISSUE THREAD

**Issue by rradar** [esphome/feature-requests#457]
**Describe the problem you have/What new integration you would like**

It would be great (after pzem004t support arrived :rocket:) to also have support for the **total energy value** which is stored in the pzem004t and doesn't reset with a power cut.

This is a super useful value. It's included in all versions of the pzem004t (the old v1+2 and the new v3).

**Please describe your use case for this integration and alternatives you've tried:**

I use it to 'sync' my pzem004t to my mains energy meter :man_scientist: 

I tried to get the same information with the integration component. Problem is that I have my `update_interval:` set to `1s` for the pzem004t component to get real time information. When I add a `restore: true` to the `integration` component I'm worried it will wear out the flash from the esp really quick because it will write the value every second to the flash of the esp (if I understand the docs right).In general I also want avoid to store things on the esp flash.

Another good thing with the value stored inside the pzem004t is that a malfunction of the esp (hardware defect for example) or a communication failure (uart or wifi for example) can't stop it. The pzem004t will continue to measure power usage and stores it - no matter of the other failures. If things are fixed again the total energy consumption reported from the pzem004t will be the correct one. :confetti_ball: 

**Additional context**

https://github.com/esphome/feature-requests/issues/49

**Comment by rradar** [comment]
Actually I really tried to get this working with the integration

```
  - platform: integration
    name: "${upper_devicename} Energy Meter" 
    sensor: pzem_power
    time_unit: h
    restore: false #don't! pzem_power is updated every second!
    filters:
      # Multiplication factor from W to kW is 0.001
      # Energy Meter reads 2272kWh right now
      - lambda: return x * (0.001) + 2272;
    unit_of_measurement: kWh
    icon: mdi:counter
```

But the output isn't useful. Don't know why their is spikes and why it actually lowers the value again. :1234: 

![image](https://user-images.githubusercontent.com/34582688/67987626-cfb13f00-fc25-11e9-9e2d-07c07590c720.png)

My old setup with espurna (already replaced by esphome) was using the information directly from the pzem004t and reporting it via mqtt. It just goes one way :arrow_up: 

![image](https://user-images.githubusercontent.com/34582688/67987808-3e8e9800-fc26-11e9-9c45-c2ec4f052cfd.png)

**Comment by OttoWinter** [comment]
Thanks for creating a new feature request for this!

To answer some of the issues here:

> When I add a restore: true to the integration component I'm worried it will wear out the flash from the esp really quick because it will write the value every second to the flash of the esp

If this is an ESP8266 and you don't explicitly set `esp8266_restore_from_flash` to true in your config, it will be stored in RTC memory which does not have issues with wearing out the flash.

I don't know if the PZEM004T stores the accumulated value in a non-volatile area too (you can check by disconnecting+reconnecting to power). But if it does, it will have around the same write cycles as the ESP8266 because the technology is quite standard.

--------

As for the graphs you're seeing:

 - The first big jump appears to be adjusting the constant in the lambda.
 - The up/down thingies are concerning - but I would say that points more to a bug that can be fixed. My guess would be that it's in the PZEM data reading, could you attach a graph of the PZEM power value during that timeframe?

**Comment by rradar** [comment]
Thank's for your reply @OttoWinter ! Actually I just found out that I use still the custom component for the pzem004t v3 I'm using right now. I will get it running with latest esphome beta, test it again and report here. I also have a pzem004t v2 to help with testing!

**Comment by rradar** [comment]
Ok, I did upgraded my sensor yesterday to 1.14.0 using the pzemac component. Here are some graphs:

![image](https://user-images.githubusercontent.com/34582688/68085683-77ec2100-fe3b-11e9-8634-f5be412c2b9d.png)
![image](https://user-images.githubusercontent.com/34582688/68085744-2001ea00-fe3c-11e9-87dc-96fc3c9d7d1c.png)
![image](https://user-images.githubusercontent.com/34582688/68085761-4f185b80-fe3c-11e9-92a2-84c46eb51481.png)
![image](https://user-images.githubusercontent.com/34582688/68085752-3e67e580-fe3c-11e9-9fc0-b6b89a78a4fa.png)

and my yaml part:

```
sensor:
  - platform: pzemac
    frequency:
      name: "${upper_devicename} Frequency"
      unit_of_measurement: hz
    voltage:
      name: "${upper_devicename} Voltage"
    current:
      name: "${upper_devicename} Current"
    power_factor:
      name: "${upper_devicename} Powerfactor"
    power:
      name: "${upper_devicename} Power"
      id: pzem_power
    update_interval: 5s

  - platform: total_daily_energy
    name: "${upper_devicename} Total Daily Energy"
    power_id: pzem_power
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:counter

  - platform: integration
    name: "${upper_devicename} Energy Meter" 
    sensor: pzem_power
    time_unit: h
    filters:
     # Multiplication factor from W to kW is 0.001
      - lambda: return x * (0.001) + 2282;
    unit_of_measurement: kWh
    icon: mdi:counter
```

for me it looks good now. Still I think this feature would improve the accuracy dramatically. Because the pzem004t is not limited to a 5 second (or 1 second) read interval and I guess the total energy captured directly inside the pzem004t is therefor much more accurate.
