### ISSUE TITLE
L298 Dual H-Bridge DC Motor Controller

### ISSUE THREAD

**Issue by Qu3uk** [esphome/feature-requests#48]
**What new integration would you wish to have?**

L298 Dual H-Bridge DC Motor Controller
https://www.sparkfun.com/products/9670
**If possible, provide a link to an existing library for the integration:**
https://github.com/AndreaLombardo/L298N ?
**Is your feature request related to a problem? Please describe.**
This is what I have and rather not buy something else to convert an old project etc
**Additional context**

**Comment by workingmanrob** [comment]
Hi guys,

I think I am also interested in this integration.  I have recently purchased a few nodemcu motor shield boards and I'm pretty sure it's the same chip used.  Oh I have 293 instead but I assume it's quite similar. 

https://hackaday.io/project/8856-incubator-controller/log/29291-node-mcu-motor-shield

The shield is based on the L293D quadruple high-current half-H drivers typically used to drive motors.

This is supposed to support either a single stepper motor or two dc motors.  I'm just trying to use a single dc motor.  Seems to be a popular kit for making a wifi remote controlled car.

https://www.instructables.com/id/Motorize-IoT-With-ESP8266/

Will try that snippet from Otto and see if things move.

Thanks again!

Oh found this - http://drzzs.com/diy-window-shades-motorized-automated/

I really just want motorized curtain control..

**Comment by danpowpow** [comment]
Hi @OttoWinter ! 
I absolutely love esphome - well done on such a great piece of work :-)
has there been any development on this? i'm looking at using hbridges to give me dimming control of some polarity-reversing led string lights. I have code working on arduino, but am hoping to move to esphome for better hass integration.
the code i'm using uses three gpio from the arduino going to the L298N modulem, IN1 IN2 and PWM. i've repurposed code from here:
https://tronixlabs.com.au/news/tutorial-l298n-dual-motor-controller-module-2a-and-arduino/
thanks again for esphome!

**Comment by RIKWEBB** [comment]
Any integration planned for the L293D?
This would help create an easy solution for Shades / Blinds with these 
ARCELI L293D Wifi Motor Drive Expansion Board Shield Module For NodeMCU ESP-12E ESP8266
by QC EU
Learn more: https://www.amazon.co.uk/dp/B078CPZDW1/ref=cm_sw_em_r_mt_dp_U_OycyDbXBX2GX4

**Comment by OttoWinter** [comment]
@danpowpow See the response I posted above.

@RIKWEBB Looks like the L293D is essentially the same as the L298, so also look at said post.

**Comment by danpowpow** [comment]
thanks for the response @OttoWinter :-)
i'm not sure i completely follow you though. I understand ledc for pwm on the esp32, and have succeeded where that is concerned. the main issue i'm facing however is that in order to get my led festoon to light all the bulbs i have to keep switching the polarity very fast to the in1 and in2 pins of the L298N. not polarity reversing results in only 1/2 of the string working, as each led is wired up in reverse to that last one. the arduino code is dead easy:
  digitalWrite(in1, LOW);
  digitalWrite(in2, HIGH);  
  digitalWrite(in1, HIGH);
  digitalWrite(in2, LOW); 
but i can't quite see how to run this bit (or equivalent) in esphome. i've tried using the loop() iteration but it isn't fast enough.
Is esphome the right tool for this job?
thanks again,
dp

**Comment by cnctech** [comment]
I hope that I am asking this question in the right place. It's my first time using this.
I have HASSIO up and "somewhat" running, and have been looking into a good closed loop DC motor control. After experimenting with EspHome, I feel that this is one of the most advanced and flexible options to do much control. Has anyone tried using the L298 with a DC gear motor with encoder, and using the "Rotary Encoder" function in EspHome, along with "Cover" templates to set "Home" for position? I do not want to use stepper motors.

**Comment by glmnet** [comment]
> I hope that I am asking this question in the right place. It's my first time using this.
> I have HASSIO up and "somewhat" running, and have been looking into a good closed loop DC motor control. After experimenting with EspHome, I feel that this is one of the most advanced and flexible options to do much control. Has anyone tried using the L298 with a DC gear motor with encoder, and using the "Rotary Encoder" function in EspHome, along with "Cover" templates to set "Home" for position? I do not want to use stepper motors.

Certainly you can use ESPHome here, I haven't tried using the rotary encoder to control the position but that sounds clever, you'll have to implement the closed loop yourself as ESPHome does not provide any PID algorithm yet.

**Comment by shafr** [comment]
It took me 2 years to wrap my head around this thing (Mostly I was afraid to drill my window frame and was waiting for correct 3d model, PCB was ready and waiting).

```
# IN1 = 16
# IN2 = 12
# IN3 = 15
# IN4 = 01

stepper:
  - platform: uln2003
    id: my_stepper
    pin_a: 12 
    pin_b: 16
    pin_c: 01
    pin_d: 15
    max_speed: 250 steps/s
    sleep_when_done: true

    # Optional:
    acceleration: inf
    deceleration: inf

switch:
  - platform: gpio
    pin: 02
    id: red_pin
  
  - platform: template
    name: "Set position 250"
    turn_on_action:
      - stepper.set_target:
            id: my_stepper
            target: 250

  - platform: template
    name: "Set position -250"
    turn_on_action:
      - stepper.set_target:
            id: my_stepper
            target: -250     
```

1) First of all - pin order here is **in1,in3, in2,in4**. 
2) `sleep_when_done` is crucial! Or your motor will overheat.
3) Consumption - idle 0.09 A, with motor spinning - 0.3 A.
