### ISSUE TITLE
Non-integer font size

### ISSUE THREAD

**Issue by escoand** [esphome/feature-requests#501]
**Describe the problem you have/What new integration you would like**
I try to use [Tetris Blocks Font](https://www.dafont.com/tetris-blocks.font) to show on a display but I struggle with the font size. When using 3 some blocks are 1px too large and with 2 some are 1px too small. Using a font size in between is currently not possible. The limitation to integer numbers seem not to exist in the Pillow library itself.

**Please describe your use case for this integration and alternatives you've tried:**
Is there a way to define the glyphs by hand? Maybe like this to get the `L` block:
```yaml
font:
  - id: tetris
    glyphs:
      L:
        - [1, 0]
        - [1, 0]
        - [1, 1]
```

**Additional context**
