### ISSUE TITLE
More configurable stopping behaviour for time-based covers

### ISSUE THREAD

**Issue by lheckemann** [esphome/feature-requests#507]
**Describe the problem you have/What new integration you would like**
I have a cover which is controlled by a manufacturer remote where I've connected the GPIOs of an ESP32 to the buttons of the remote. It behaves as follows:

- Pressing the open button makes the cover start moving up
- Pressing the close button makes the cover start moving down
- Pressing the stop button makes the cover stop moving IF it's moving, otherwise it makes the cover move to a mostly-closed position then stop (this may be up or down).
- Releasing the buttons has no effect

I'd like to be able to prevent the stop button from having any effect when the cover is not moving, so that the actual state of the cover doesn't desynchronise with the assumed state in ESPHome.

**Please describe your use case for this integration and alternatives you've tried:**
Currently ESPHome will attempt to stop the cover when it is already stopped, causing it to _start_ moving. This desynchronises the state between the physical world and ESPHome.

The relevant part of my config currently looks like this:

<details>

```
cover:
  - platform: time_based
    name: "Office shades"
    open_action:
      - switch.turn_on: downswitch
      - delay: 300ms
      - switch.turn_off: downswitch
    open_duration: 16718ms
    close_action:
      - switch.turn_on: upswitch
      - delay: 300ms
      - switch.turn_off: upswitch
    close_duration: 16788ms
    stop_action:
      - switch.turn_on: stopswitch
      - delay: 300ms
      - switch.turn_off: stopswitch
    has_built_in_endstop: true

switch:
  - platform: gpio
    id: upswitch
    restore_mode: ALWAYS_OFF
    pin:
      inverted: true
      number: 13
      mode: OUTPUT_OPEN_DRAIN
  - platform: gpio
    id: stopswitch
    restore_mode: ALWAYS_OFF
    pin:
      inverted: true
      number: 12
      mode: OUTPUT_OPEN_DRAIN
  - platform: gpio
    id: downswitch
    restore_mode: ALWAYS_OFF
    pin:
      inverted: true
      number: 14
      mode: OUTPUT_OPEN_DRAIN

```
</details>

**Additional context**
