### ISSUE TITLE
xiaomi bluetooth kettle

### ISSUE THREAD

**Issue by ppanagiotis** [esphome/feature-requests#517]
**Describe the problem you have/What new integration you would like**

Use ble device to connect with xiaomi kettle

**Please describe your use case for this integration and alternatives you've tried:**

A nice try is described here
https://github.com/aprosvetova/xiaomi-kettle

**Additional context**

**Comment by n4ts** [comment]
This would be a nice feature-requests :)
If we would like to pull only the temperature then we can use the solution for Xiaomi LYWSDCGQ or Xiaomi CGG1 which works the same (they take the temperature based on BLE data).

Simple code is below:
https://github.com/able99/minik-ha-components/blob/master/kettle_mi/custom_components/sensor/kettle_mi.py

**Comment by jascdk** [comment]
Great - I have thought about the same:) It would be a cool integration:)

**Comment by Titanius** [comment]
**Additional context**

**Comment by andriej** [comment]
No further news?

**Comment by WildeRNS** [comment]
There is working custom [component](https://github.com/custom-components/ble_monitor)  that uses passive ble, maybe now it can be added to esphome?

**Comment by makefu** [comment]
I'd love to see this device being supported!

**Comment by n4ts** [comment]
For me, even getting temperature in the passive mode would be sufficient ;) maybe we can do this by getting advertise data?

**Comment by n4ts** [comment]
If someone needs to get only the temperature (in passive mode), below is my ready code to use:
`esp32_ble_tracker:
  scan_parameters:
    duration: 10s
    active: false
  on_ble_service_data_advertise:
    - mac_address: YOUR_MAC_HERE
      service_uuid: FE95
      then:
        - lambda: |-
            id(kettle_data).publish_state(float(x[16]));

sensor:
  - platform: template
    id: kettle_data
    name: "Kettle Temp"
    unit_of_measurement: '°C'
    accuracy_decimals: 0
    icon: "mdi:thermometer"`

Maybe it could be implemented in esphome as ready solution?

**Comment by Hilfarnal** [comment]
@n4ts Could you please upload all of your code? I'm new user and I'm geting syntax errors I can't fix.

**Comment by n4ts** [comment]
@Hilfarnal Below is the code and a small feature;)
```YAML
esp32_ble_tracker:
  scan_parameters:
    duration: 10s
    active: false
  on_ble_service_data_advertise:
    - mac_address: YOUR_MAC_HERE
      service_uuid: FE95
      then:
        - lambda: |-
            id(kettle_temp).publish_state(float(x[16]));
            if(x[15] == 01) {
              id(kettle_mode).publish_state(true);
            } else {
              id(kettle_mode).publish_state(false);
            }

sensor:
  - platform: template
    id: kettle_temp
    name: "Kettle Temp"
    unit_of_measurement: '°C'
    accuracy_decimals: 0
    icon: "mdi:thermometer"

binary_sensor:
  - platform: template
    id: kettle_mode
    name: "Kettle Mode"
```

I tried to decode the rest of the advertise data, but apart from the temperature, mode and MAC address, I wasn't able to decode the rest of the values. Even after using the information contained here https://github.com/aprosvetova/xiaomi-kettle
Please write if you have any fixes for my code.

**Comment by jascdk** [comment]
> @Hilfarnal Below is the code and a small feature;)
> 
> ```yaml
> esp32_ble_tracker:
>   scan_parameters:
>     duration: 10s
>     active: false
>   on_ble_service_data_advertise:
>     - mac_address: YOUR_MAC_HERE
>       service_uuid: FE95
>       then:
>         - lambda: |-
>             id(kettle_temp).publish_state(float(x[16]));
>             if(x[15] == 01) {
>               id(kettle_mode).publish_state(true);
>             } else {
>               id(kettle_mode).publish_state(false);
>             }
> 
> sensor:
>   - platform: template
>     id: kettle_temp
>     name: "Kettle Temp"
>     unit_of_measurement: '°C'
>     accuracy_decimals: 0
>     icon: "mdi:thermometer"
> 
> binary_sensor:
>   - platform: template
>     id: kettle_mode
>     name: "Kettle Mode"
> ```
> 
> I tried to decode the rest of the advertise data, but apart from the temperature, mode and MAC address, I wasn't able to decode the rest of the values. Even after using the information contained here https://github.com/aprosvetova/xiaomi-kettle
> Please write if you have any fixes for my code.
> 
> Example and description of received data below:
> 95fe712013010fzzzzzzzzzzzz09051002yyxx
> Where:
> xx - temp
> yy - mode
> zz - reverse mac address
> 95fe is service UUID

Wow this is great - works perfect:) Looking forward to se if anyone comes up with decoding of the rest of the values:)

By the way - how did you sniff the data-strings? Also with ESPHome ble tracker?

**Comment by Hilfarnal** [comment]
@n4ts @jascdk After a little bit of studying esphome web and learning proper syntax i got it working yesterday. Thanks for your contribution!

**Comment by jascdk** [comment]
@n4ts Hi :) A little bit off topic, but I as said I got your code to get working - great:) I have an Xiaomi BLE toothbrush (Oclean x), which could be fun have reporting some stuff to HA. When I search for it with an BLE scanner on my Iphone I get the following.
![IMG_5080](https://user-images.githubusercontent.com/35434108/106772121-fdaedb80-663f-11eb-8c20-c96fab46f317.PNG)
![IMG_5081](https://user-images.githubusercontent.com/35434108/106772135-00113580-6640-11eb-970b-5ca5d083d183.PNG)

Would it be possible to get the battery information with Lambda? And how should I do it - any help is appreciated :)

**Comment by koenvervloesem** [comment]
@jascdk Does your toothbrush also advertise its battery status when you're not connected? If it does, this should do the trick (I'm using this for another device):

```
esp32_ble_tracker:
  on_ble_service_data_advertise:
    - mac_address: AB:CD:EF:01:23:45
      service_uuid: 180F
      then:
        - lambda: 'id(battery_sensor).publish_state(x[0]);'

sensor:
  - platform: template
    name: "Battery Sensor"
    id: battery_sensor
    accuracy_decimals: 0
    unit_of_measurement: '%'
    icon: 'mdi:battery'
```
