### ISSUE TITLE
Allow effects for addressable LEDs to work on "groups" of N LEDs instead of single LEDs

### ISSUE THREAD

**Issue by Boggie** [esphome/feature-requests#554]
**Describe the problem you have/What new integration you would like**

I have just made some "Smart Nano leaf replicas" like these https://www.thingiverse.com/thing:3354082 and put three WS2811 LEDs in each corner. The project on thingiverse comes with some firmware, but I obviously wanted to use esphome instead :)

It was easy to get things to light up with a configuration like below:

```
light:
  - platform: fastled_clockless
    chipset: WS2811
    pin: D7
    num_leds: 9
    rgb_order: GRB
    name: "FastLED WS2811 Light"
    effects:
      - addressable_random_twinkle:
          name: Random Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 32ms
```

My problem is that when I use things like the twinkle effect, it twinkle the single LEDs instead of each corner, since each corner is 3 LEDs and not just one.

It would be perfect if I could specify a "group_leds: 3" or similar to make the effects work on corners instead of single LEDs.

**Please describe your use case for this integration and alternatives you've tried:**

It would look way cooler ..

**Additional context**

**Comment by brandond** [comment]
I am actually working on something like this and have it most of the way done.

My use case is a little different - I've hacked a bunch of LED strips together into a 30x30 pixel display panel (30 rows of 30 pixels). I want to address 3x3 pixel groups as a virtual lights in a 10x10 grid. To support this, I'm working on code to group multiple ranges of lights together into a single virtual light that's updated as a single entity.

I'd eventually like to support using it as an output for some of the drawing and printing primitives, like you can do with some of the other outputs, but that's waiting on some other core stuff like RGB display support.

**Comment by brandond** [comment]
I have a custom component you might try. If it works for you and @OttoWinter thinks it's not to terrible I'll try to get it added to core. I'm not settled on the name but for the moment I'm calling it an Addressable Panel since it groups light across multiple rows and columns.

1. Install esphome from [this branch](https://github.com/brandond/esphome/tree/addressable_custom) (needed for custom addressable lights)
2. Grab the component code from [this gist](https://gist.github.com/brandond/63dc9590465a095a478ae873780510d0#file-panel-h)
3. Configure the base addressable light. In my example, I'm using fastled_clockless as the base.
4. Configure the custom component. The AddressablePanel constructor arguments are height, width, rows, cols. For your purposes (simply grouping lights in a single row as opposed to across multiple rows) you probably want a height=1, width=3, rows=1, cols=**total number of light groups**
5. Check your setup. The base light `num_leds` should equal `height` x `width` x `rows` x `cols`.
 
```yaml
esphome:
  includes:
    - panel.h

light:
  - platform: fastled_clockless
    chipset: WS2812
    pin: GPIO23
    num_leds: 9
    rgb_order: BRG
    id: base_light
  - platform: custom
    lambda: |-
      auto panel = new esphome::panel::AddressablePanel(id(base_light), 1, 3, 1, 3);
      auto light = new esphome::panel::PanelLightOutput(*panel);
      App.register_component(light);
      return {light};
    lights:
      id: panel0
      name: "Panel Light"
```
