### ISSUE TITLE
Get cover position when triggered from Home Assistant front end

### ISSUE THREAD

**Issue by slarti42** [esphome/feature-requests#566]
**Describe the problem you have/What new integration you would like**

Drive a servo to a position that is requested by Home Assistant.

**Please describe your use case for this integration and alternatives you've tried:**

Hi. I'm new to esphome and Home Assistant but looking to move away from mysensors/domoticz/mqtt because using Wemos D1 minis is proving to be a headache with them. 

One thing I've always had is servo controlled mini-blinds. My problem is that I would like for the position (not just open/closed) be in sync with local control and the front end. I have almost accomplished this in Esphome but can't seem to get the final part right which is setting the position from Home Assistant.

I have a global variable and a script which drive the servo:

```
globals:
  - id: my_pos
    type: float
     
script:
  - id: move_servo
    then:
      - servo.write:
          id: my_servo
          level: !lambda "return id(my_pos);"
      - delay: 1s
      - servo.detach: my_servo
      - cover.template.publish:
          id: pub_pos
          position: !lambda "return id(my_pos) / 2 + 0.5;"
      - logger.log:
          format: "position: %.2f"
          args: ['id(my_pos)']
```

I also have a rotary encoder which I use to control the servo locally. This updates the global variable and calls the script on change (this works, and the position is updated in HA):

```
sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    id: knob
    pin_a: D8
    pin_b: D6
    min_value: -1
    max_value: 1
    on_value:
      then:
          - lambda: !lambda |-
                if (id(my_pos) > -0.9 && id(my_pos) < 0.9) {
                id(my_pos) += id(knob).state * 0.1;
                }
                else if (id(my_pos) <= -0.9 && id(knob).state == -1 && id(my_pos) > -1) {
                id(my_pos) = -1;
                }
                else if (id(my_pos) >= 0.9 && id(knob).state == 1 && id(my_pos) < 1) {
                id(my_pos) = 1;
                }
                else if (id(my_pos) == 1 && id(knob).state == -1) {
                id(my_pos) += id(knob).state * 0.1;
                }
                else if (id(my_pos) == -1 && id(knob).state == 1) {
                id(my_pos) += id(knob).state * 0.1;
                }            
          - script.execute: move_servo
          - sensor.rotary_encoder.set_value:
              id: knob
              value: 0
```

And in template cover component I have:

```
cover:
  - platform: template
    name: "Blinds"
    id: pub_pos

    open_action:
      - lambda: |-
          id(my_pos) = 1;
      - script.execute: move_servo

    close_action:    
      - lambda: |-
          id(my_pos) = -1;
      - script.execute: move_servo

    stop_action:
      - servo.detach: my_servo

    position_action:
      - logger.log:
          format: "position_action_position: %.2f"
          args: ['id(pub_pos).position']      
      - lambda: |-
          id(my_pos) = 2 * (id(pub_pos).position) - 1.0;
      - script.execute: move_servo
```      
This where it fails. **"id(my_pos) = 2 * (id(pub_pos).position) - 1.0;"**

id(pub_pos) isn't the new value from HA but the previous position and the servo doesn't budge. Is there any way to get that new position? The cover log reports it nicely (cover.cpp: line 80)

**Additional context**
