### ISSUE TITLE
D1 mini motor shield

### ISSUE THREAD

**Issue by accelle17** [esphome/feature-requests#567]
**Describe the problem you have/What new integration you would like**

D1 mini motor shield
[https://www.aliexpress.com/item/32891891983.html?spm=a2g0o.productlist.0.0.e78840feRKJzHN&algo_pvid=9c3c6d7e-7e32-4766-ae1e-a07e5d2b3416&algo_expid=9c3c6d7e-7e32-4766-ae1e-a07e5d2b3416-2&btsid=0f014cc3-6980-4cc5-9c8a-a5112e58ed95&ws_ab_test=searchweb0_0,searchweb201602_3,searchweb201603_53](url)

**Please describe your use case for this integration and alternatives you've tried:**

I’m trying to modify glade air freshener by attaching d1 mini on it.
However, it looks like I need to replace the original board (motor driver) with d1 mini
motor shield.

With esphome, how do you control this kind of motor driver? 

**Additional context**

I tried the following config but it doesn’t work:

```
output:
 - platform: gpio
   pin: D2
   id: direction_pin
 - platform: esp8266_pwm  # or ledc if on ESP32
   pin: D3
   id: speed_pin
switch:
  - platform: template
    name: "Kitchen Glade"
    turn_on_action:
     - output.turn_on: direction_pin
     - output.set_level:
        id: speed_pin
        level: 100%
     - delay: 1000ms
     - output.turn_off: speed_pin
     - output.turn_off: direction_pin
     - output.set_level:
        id: speed_pin
        level: 100%
     - delay: 1000ms
     - output.turn_off: speed_pin

```
