### ISSUE TITLE
Dictionaries and lists abbreviation

### ISSUE THREAD

**Issue by hwmland** [esphome/feature-requests#577]
**Describe the problem you have/What new integration you would like**

It would be nice if you support abreviated form of dictionaries/lists, it is part of YAML syntax I think.

**Please describe your use case for this integration and alternatives you've tried:**

It would improve code readibility e.g. in the case of logging.
`- logger.log: [ tag: "DEMO", level="INFO", format="This is example" ]`
instead of
```
- logger.log:
    tag: DEMO
    level: INFO
    format: This is example
```

**Additional context**

Thnigs like log or pin definition would benefit from shorter notation.
