### ISSUE TITLE
Individual acceleration setting for stepper

### ISSUE THREAD

**Issue by noxhirsch** [esphome/feature-requests#580]
**Describe the problem you have/What new integration you would like**
The stepper function only allows to set the acceleration/decceleration once in the initial config. It would be great to set individual acceleration/decceleration within a script:
```
- stepper.set_acceleration :
    id: my_stepper
    acceleration : 10000
```

**Please describe your use case for this integration and alternatives you've tried:**
I have a cover with a stepper. When the cover gets power, it has to home first. That happens in a loop with tiny steps until the endstop is reached. After that it opens/closes the cover in one go - there I use the acceleration. But because of the acceleration the homing gets ridiculously slow. It would be great if I could set the acceleration to infinite just for the homing.
I didn't find any alternative ways to solve this problem.

**Additional context**

**Comment by daned33** [comment]
How are you doing the homing for the stepper?

**Comment by daned33** [comment]
Has this worked for you?

https://github.com/esphome/feature-requests/issues/127#issuecomment-486769288

**Comment by noxhirsch** [comment]
> How are you doing the homing for the stepper? I am personally trying to work out how to do it in a smart way.

This is my homing-script:
```
script:
  - id: homing
    then:
      - logger.log: "Script Homing START"
      - stepper.set_speed:
          id: rollo_stepper
          speed: 2000 steps/s
      - while:
          condition:
            binary_sensor.is_off: endstop
          then:
            - stepper.set_target:
                id: rollo_stepper
                target: 20
            - delay: 1ms
            - stepper.report_position:
                id: rollo_stepper
                position: 0
      - lambda: 'id(calibrated) = 1;'
      - lambda: 'id(position) = 0;'
      - logger.log: "Script Homing END" 
```

> Has this worked for you? #127 (comment)
As you can see, I use it in my script above - and it's working perfectly fine. For normal open/close I have Home Assistant sensor with which I can control the speed from Home Assistant: 
Slow speed (and silent because of the low speed) for automatic open/close with alarm and sunrise/sunset. Fast speed if I'm using the buttons on my dashboard.
