### ISSUE TITLE
Prevent esp8266-restore-from-flash from wear-out flash

### ISSUE THREAD

**Issue by micw** [esphome/feature-requests#592]
**Describe the problem you have/What new integration you would like**
Currently enabling esp8266-restore-from-flash brings a high risk of wearing out the flash. This is caused by 2 facts:
- ~~state is always written to flash, regardless if it's changed or not (from what I've seen in preferences and light_state code, so correct me if I just did not see the code that avoids this)~~ edit: it's only written when changed, see below.
- state is written to with every state update which can be _very_ often

**Please describe your use case for this integration and alternatives you've tried:**
If state has not changes (e.g. variable is "updated" to the same value as before), flash should not be written at all (saving lots of write cycles).

In many use-cases, flash-persistence (across power outage) can easily tolerate the loss of several seconds or even minutes or hours. It would make sense to allow to set-up a "flash write interval" with the following logic:
- every write to flash is defered (e.g. stored to volatile rtc memory only)
- every `flash-write-interval` seconds, check if there are changes, write only to flash if there are any

**Additional context**
Tasmota does it in a similar way described here.

**Comment by OttoWinter** [comment]
> state is always written to flash, regardless if it's changed or not (f

That's not correct - if the state is the same, the ESPPreferenceObject class will filter out the write. (see esp8266_flash_dirty).

> state is written to with every state update which can be very often

For example when is it very often? I can only think of two cases, which are already handled:

 - Effects, but when effects are on saving to flash is disabled
 - Transitions, but only the "remote" values (which is the value it is fading *to*) is stored, so also not an issue.

**Comment by micw** [comment]
> > state is always written to flash, regardless if it's changed or not (f
> 
> That's not correct - if the state is the same, the ESPPreferenceObject class will filter out the write. (see esp8266_flash_dirty).

Ok found it: https://github.com/esphome/esphome/blob/7a6df38515fb4bdd48db1b25c8004d1d5d755872/esphome/core/preferences.cpp#L137
Thank you for clarification, I'll edit the issue accordingly.

> 
> > state is written to with every state update which can be very often
> 
> For example when is it very often? I can only think of two cases, which are already handled:
> 
>     * Effects, but when effects are on saving to flash is disabled
> 
>     * Transitions, but only the "remote" values (which is the value it is fading _to_) is stored, so also not an issue.

For example I have some monochromatic lights which should store their state across power loss. I dim it via button (while button hold, dim up/down). From my understanding every state change from within the "while" loop triggers the flashing process, this is ~10 writes/s while dimming:

```
    on_press:
      - then:
        # wait a second
        - delay: 1s
        # if button is still holding
        - if: 
            condition:
            - binary_sensor.is_on: btn1
            then:
            # dim while button is holding
            - while:
                condition:
                - binary_sensor.is_on: btn1
                then:
                - light.dim_relative:
                    id: light1
                    relative_brightness: !lambda |-
                      return id(dim_direction)*0.02;
                    transition_length: 0.01s
                - delay: 0.01s
            # switch dim direction
            - lambda: id(dim_direction)=-id(dim_direction);
```

Another case is with power meter which updates e.g. every second. If the cumulative value (kWh) is persisted to keep it after power loss, this can potentially be updated every second (#461).
