### ISSUE TITLE
Automation conditions for Cover Components (cover.is_moving)

### ISSUE THREAD

**Issue by Skaronator** [esphome/feature-requests#596]
**Describe the problem you have/What new integration you would like**
I've a timed based cover with 2 buttons to control it physically. I'd like to configure the buttons that when you press it while moving it should stop at the current level.

**Please describe your use case for this integration and alternatives you've tried:**
Easiest way to do that would be to modify the on_press events on these buttons with a simple `if cover.is_moving then cover.stop else cover.open`. Super easy but [according to the documentation](https://esphome.io/guides/automations.html#all-conditions) there are no conditions for covers! (What a shame)

```
binary_sensor:
  - platform: gpio
    pin: 5
    id: open_button
    on_press:
      - cover.open: tb_cover
  - platform: gpio
    pin: 13
    id: close_button
    on_press:
      - cover.close: tb_cover
```

**Additional context**
I think we need at least 3 conditions.
* cover.is_moving
* cover.is_moving_up
* cover.is_moving_down

Maybe it makes sense to have a cover.in_range similar to sensor.in_range but might be a bit overkill? I think you could use a template sensor?
