### ISSUE TITLE
Power supply manual switch

### ISSUE THREAD

**Issue by billdotjr** [esphome/feature-requests#598]
**Describe the problem you have/What new integration you would like**

Power supply component should have means of powering on manually

**Please describe your use case for this integration and alternatives you've tried:**

I have electronics lab, where I have 750W 12V power supply from an old server. I use it for powering LED strips in the lab, but I am using it as 12V sypply for projects as well. Currently I have configured a switch with power supply assigned to it, but this is eating up one pin on the ESP. I would like to have either:

1) A dummy switch, where I can assign power supply, but it would not require me to configure any pin.

or

2) Manually switchable power supply component.

**Additional context**

**Comment by glmnet** [comment]
> 1. A dummy switch, where I can assign power supply, but it would not require me to configure any pin.

try this

```` 
# Example configuration entry
output:
  - platform: gpio
    pin: 25 # A pin you are not using, or the pin of the PS 
    id: 'generic_out'
    power_supply: power_supply_id
switch:
  - platform: output
    name: "PS On"
    output: 'generic_out'

````
