### ISSUE TITLE
Prefix for all entities visible in HA.

### ISSUE THREAD

**Issue by freekode** [esphome/feature-requests#645]
**Describe the problem you have/What new integration you would like**
I want to have automatically added prefix for all entities which are visible in HA.

In esphome I have `sensor.temp`, `sensor.pressure`, in HA i want to have `sensor.myweatherstation_temp`, `sensor.myweatherstation_pressure` 

**Please describe your use case for this integration and alternatives you've tried:**
In esphome configuration I have sensors with names: temp, humidity, pressure.
These sensors transfers to HA with the same names: sensor.temp, sensor.humidity, etc. Which can produce name conflicts in HA.

**Additional context**

**Comment by brandond** [comment]
Why not just change the names in your esphome configuration? If that feels too verbose you can always use substitutions:

```yaml
substitutions:
  name: "myweatherstation"

sensor:
  - platform: wifi_signal
    name: "${name} wifi"
```
