### ISSUE TITLE
Add rate of change filter (or sensor)

### ISSUE THREAD

**Issue by petersandersen** [esphome/feature-requests#667]
**Describe the problem you have/What new integration you would like**

Ability to convert raw values to the rate of change over some window size. I.e. current value minus last value or an average of previous x values.

**Please describe your use case for this integration and alternatives you've tried:**

I've made a bed occupancy sensor using a load cell but there is a lot of drift even after calibration. Since I don't really need the exact weight I want to count the bed as occupied if either of these conditions have been met in the last 5 minutes: 1) Current weight is above the average weight in the last 24 hours or 2) the absolute value of the current value minus the last value is above 1kg. 

The automation rules can be handled in home assist but I need to be able to create a rate of change filter (or sensor? i.e. it could be a copy of an existing sensor with filters to facilitate multiple values) in esphome.

**Additional context**

Thanks again for creating esphome, its been an awesome piece of software to improve my home automation and tinker with electronics and components I'd never have otherwise played with.

**Comment by rudshep** [comment]
I'm looking for something similar but for energy monitoring. Detect if energy consumption increased by between 340 - 360 watts over 3 seconds which could be an indicator that a certain appliance has started up.

I don't know how to solve it either but let's exchange a few ideas...

- Use the sliding_window_moving_average to smooth out the absolute reading over 5 minutes.
- Set the delta filter to, say, 10kg to detect big changes. 1kg might be triggered by a dog or movement.

Thats still not your "Rate of Change Sensor" though. Home Assistant has a Trend integration but I don't think there is an equivalent in ESPHome. https://www.home-assistant.io/integrations/trend/

**Comment by petersandersen** [comment]
Thanks for the reply @rudshep, it looks like the existing lambda functionality can solve both our issues.

For my hx711 based bed presence sensor I'm now using the following code:
`sensor:
  - platform: hx711
    name: "Bed HX711 Value"
    id: bed_weight
    dout_pin: GPIO1
    clk_pin: GPIO3
    gain: 128
    update_interval: 1s
    filters:
      - lambda: |-
          static int last_value = 0;
          static int bed_change = 0;
          bed_change =  x - last_value;
          last_value = x;
          return abs(bed_change);
      - sliding_window_moving_average:
          window_size: 60
          send_every: 10
`
This returns the average absolute change in the raw sensor value over the last minute every 10 seconds. Due to sensor noise it sits around 140+/- 20 but is consistently above 1000 when I'm on the bed. Will report back if its working tomorrow. 

References used ( https://esphome.io/guides/automations.html & https://esphome.io/components/sensor/index.html ). 

Still doesn't solve the issue of creating copies of sensors that each have their own lambdas / filters for different indicators. Please report back how your implementation goes :)

**Comment by nebulous** [comment]
I've often wanted for something like the inverse of a median filter - where instead of removing outliers, outliers are detected. Would be useful for a couple things in my HA/ESP projects. I'm thinking the lambda filter idea above could solve that problem by having a median filter, then subtracting the current value from it. Thanks for the tip - maybe this comment will serve to trigger another new component or better idea :)

**Comment by rcxrbt** [comment]
> I've often wanted for something like the inverse of a median filter - where instead of removing outliers, outliers are detected. Would be useful for a couple things in my HA/ESP projects. I'm thinking the lambda filter idea above could solve that problem by having a median filter, then subtracting the current value from it. Thanks for the tip - maybe this comment will serve to trigger another new component or better idea :)

very interesting!
also me trying to find peaks on sensor output, can you share your code? :)
This is my case:
https://github.com/esphome/feature-requests/issues/1980

**Comment by nebulous** [comment]
I went ahead and tried this since this thread prompted it today. Here's a synopsis which may work for your case @rcxrbt - or might cause someone who actually knows what they're doing to be so annoyed they post TheRightWay® to handle this 😄 

There are four components:
- the actual signal sensor (in my test case this was a temperature sensor, but in yours would be particulate)
- a copy of said sensor with a long-term median filter applied which should approximate the steady state
- a delta sensor which returns the difference between the current value and the median
- a binary threshold sensor which turns on or off based on the delta sensor

```yaml
sensor:
  - platform: bme280
    temperature:
      name: "$name BME280 Temperature"
      id: bme280_temperature

  - platform: template
    name: "$name BME280 Temperature median"
    id: bme280_temperature_median
    lambda: |-
      return id(bme280_temperature).state;
    filters:
        - median:
            window_size: 7

  - platform: template
    name: "$name BME280 Temperature signal"
    id: bme280_temperature_signal
    lambda: |-
      float tempnow = id(bme280_temperature).state;
      float tempmed = id(bme280_temperature_median).state;
      return fabs(tempnow - tempmed);

binary_sensor:
  - platform: analog_threshold
    name: "$name rapid change"
    sensor_id: bme280_temperature_signal
    threshold: 1.5

```
