### ISSUE TITLE
ESPHome User-Defined HA service calls

### ISSUE THREAD

**Issue by OttoWinter** [esphome/feature-requests#67]
**Describe the problem you have/What new integration you would like**

With the native API, currently it's possible to transfer data from the ESP to HA with `homeassistant.service`. For the other direction you pretty much have to use template sensors in HA and transfer them to the ESP with homeassistant sensor platforms.

So I'd like to allow the same in the opposite direction too with User-Defined service calls. Example (ESPHome config)

```yaml
esphome:
  name: livingroom

api:
  on_message:
  - service: do_stuff_2
    then:
      - light.turn_on:
          brightness: 100%
  # With variables
  - service: do_stuff
    variables:
      stuff: int
      effect: string
    then:
      - light.turn_on:
          effect: !lambda 'return effect;'
      - lambda: 'stuff + 1;'
```

would give you a service call that you can then call from HA (prefixed with name for no collisions):

```yaml
service: esphome.livingroom_do_stuff
data_template:
  stuff: 0
  effect: >-
    {{ states.something.state }}
```

For this feature I'd like to go all-in on ease of use, so I want to provide the simplest config to make this possible - suggestions for even easier ones welcome!

At first, these message field types will be supported: `string`, `int`, `float`, `bool`. Maybe vectors of these can be added at some point later.

This approach shown here would be a lot of work but ultimately I think it will be worth it:

 - Core:

   - Convert all Triggers, Actions to take variadic templates
   - Create class that holds data of the types `std::string`, `int`, `bool`, `float` and works with variadics
   - This would need to be done with repeated embedded message fields in protobuf, so the proto parser needs to be extended to support that.
   - Find some place to transmit all user-defined services on connect, either in listentities or a new request.

- ESPHome:

  - Convert action registry to allow multiple named args for actions/conditions

- HA:

  - Update aioesphomeapi for changes
  - Register services on connect, unregister services that were removed
  - Store service definitions in storage, so that services are restored upon HA startup
