### ISSUE TITLE
Multiple ranges in on_value_range

### ISSUE THREAD

**Issue by QbaF** [esphome/feature-requests#690]
**Describe the problem you have/What new integration you would like**
For great working `on_value_range' function there is lack of multi ranges e.g.:
``` yaml
    on_value_range:
      above: 5
      below: 10
      then:
        - switch.turn_on: relay_1
    on_value_range:
      above: 25
      below: 30
      then:
        - switch.turn_on: relay_2
    on_value_range:
      above: 45
      below: 50
      then:
        - switch.turn_on: relay_3
```

**Please describe your use case for this integration and alternatives you've tried:**
Depending on voltages on pin A0 which give me the state of powerstrip buttons  I would like to switch its relays.

**Comment by QbaF** [comment]
My bad. It has solution:

```
    on_value_range:
      - above: 5
        below: 10
        then:
          - switch.turn_on: relay_1
      - above: 25
        below: 30
        then:
          - switch.turn_on: relay_2
      - above: 45
        below: 50
        then:
          - switch.turn_on: relay_3
```
