### ISSUE TITLE
Implement Auth support in http_request

### ISSUE THREAD

**Issue by danps1** [esphome/feature-requests#709]
**Describe the problem you have/What new integration you would like**

Please consider adding authentication support to the new http_request component - https://next.esphome.io/components/http_request.html

**Please describe your use case for this integration and alternatives you've tried:**

This would allow for authenticated ESP to ESP communication using the Rest API - https://esphome.io/web-api/index.html#rest-api
The Rest API is part of the http_server component, and currently has support for authentication.
Using http_server without auth would not be a great idea from a security perspective.
Adding auth to http_request would allow for security in node to node communication.

**Additional context**

One example of where this may be useful is for automations that could still work even if the Home Assistant server fails, such as 2 wall mounted light switches both controlling the same light, as commonly seen at the top and bottom of stairs. 
A button could be pressed on the downstairs ESP, which would then use the http_request component to send an authenticated request to the Rest API on the Smart Bulb ESP.

**Comment by brandond** [comment]
You can already do this, you just need to craft the auth header yourself. You can get the base64 string from `echo -n  "username:password" | base64` - if there are special characters in either you'll need to urlencode them first.

```yaml
on_...:
  - http_request.get:
      url: https://esphome.io
      headers:
        Content-Type: application/json
        Authentication: Basic dXNlcm5hbWU6cGFzc3dvcmQ=
      verify_ssl: false
```
