### ISSUE TITLE
Scroll function for MAX7219 7 seg display

### ISSUE THREAD

**Issue by rspaargaren** [esphome/feature-requests#730]
**Describe the problem you have/What new integration you would like**
The text display on the MAX7219 display is now static. More data can be shown when data scrolls (left).

**Please describe your use case for this integration and alternatives you've tried:**
More data can be displayed by scrolling text

**Additional context**
Same work is in progress for max7219 digit display.

**Comment by rspaargaren** [comment]
https://github.com/rspaargaren/esphome/tree/max7219-seg7-scroll
First try -> to be tested

**Comment by rradar** [comment]
> First try -> to be tested

tested:

```yaml
display:
  - platform: max7219
    cs_pin: D2
    num_chips: 1
    intensity: 3
    lambda: !lambda |-
      it.print("Hello it is me!");
      it.scroll_left();
```

and works :tada:
