### ISSUE TITLE
Time-based position calculation for Roller Shutter Blinds

### ISSUE THREAD

**Issue by santibur06** [esphome/feature-requests#739]
**Describe the problem you have/What new integration you would like**
I'm using the time-based cover component to control my window's Roller Shutter Blinds at.
It works perfectly with the exception of the position calculation which seems to be a bit more complex to calculate for roller shutter blinds.

So right now the component calculates position like this:

- Time 0s: Position 0%
- Time 50% of action duration : Position 50% 
- Time 100% of action duration: Position 100%

Pretty simple, at least that's how I understand it works.

So, position is also how far up the cover is from the bottom of the window, so 50% means my window is half covered.

That's where this component is not compatible with roller shutter blinds...
Say the cover is all the way down, motor has stopped rotating on its own cause it reached the bottom.
Now I issue the up command and it starts rotating, it is moving up, but segment by segment, and it takes it like 5 seconds (in my case) to actually start uncovering the window. So that's 5 seconds I lose but the component is calculating the position, so by the time my window is 50% uncovered, the component thinks the cover is at 70% or more.

So yeah, the actual position of the cover may be 70% but it is not covering 30% of my window, it's actually covering 50%.

I would really like to have a way tell the component how long it takes the cover from position 0% to actually start moving up and uncovering my window.

It would work something like this:

0% - Cover all the way down
10% - Cover has rolled up a bit and light can pass by it, but it still covering the entire window.
11% - Cover is **not** covering the entire window anymore, it actually started moving up.
50% - Cover is more or less covering 50% of my window.
100% - Cover is all the way up.

**Please describe your use case for this integration and alternatives you've tried:**
This could not only be useful for Roller Shutters but also for some garage covers that show the same behavior.

**Additional context**
I'm using Sonoff T1, 3 gang to control the shutters and aside from the issue mentioned above, it works excellent.

**Comment by santibur06** [comment]
yes, that would work.

so position would stay at 0% while the cover is going up during that roller_shutter_delay right?

what do you think about using 10% of movement for that shutter delay?

0-10%: Cover goes up, consuming the _roller_shutter_delay_.
11-100%: Cover goes up consuming the _(open_duration - roller shutter delay)_

That way you would still see position being updated whenever the cover is moving and you would also be able to set the cover to 10% and let some light come in while the window is still 100% covered.

Don't know if I'm explaining myself correctly..

**Comment by glmnet** [comment]
And what is the difference between that and what you already have?

**Comment by santibur06** [comment]
Right now if I set the position to 50% it will unroll (the delay) and then go up but since already consumed the delay it stops at around 30% kf the window

**Comment by santibur06** [comment]
What I'm saying is that while we unshutter it we update position but from 0 to 10% max so we can also control the unshuttering from HA. Right now it will say like 20% when it finishes unshuttering

**Comment by santibur06** [comment]
Hi @glmnet, just wondering if you had time to check this out.

Thanks!

**Comment by alexbarcelo** [comment]
Oh I am not the only one having those issues for roller covers!

Let me throw my idea here, just to see if it makes sense for this context:

ESPhome has a powerful system of filters. Right now, the code for filters is focused on sensors and using that outside the sensors seems to be hackish (I tried and half-succeeded with workarounds). However, it makes sense --in my head, at least-- to abstract those filter things into a C++ class that can be used from other components. I opened the #755 to discuss that specific refactoring, but the specifics of the consequences and potential for the cover component is more on-topic here.

To fix some ideas, let me put an example of how I would imagine my proposal. Let's start with the yaml definition:

```yaml
cover:
  - platform: time_based
    name: "My Fancy Cover"
    #(... open, close action and durations ...)
    open_filters: &common_filters
      - calibrate_polynomial:
          degree: 2
          datapoints:
            - 0.0 -> 0.0
            - 0.1 -> 0.15
            - 0.5 -> 0.75
            - 1.0 -> 1.0
    close_filters: *common_filters
    # conceivable case: open and close need different filters
```

Which would translate to: "when 10% of time has passed, the cover is opened 15%. When 50% time has passed, the cover is opened 75%".

Calibrate polynomial seems the most useful filter right now. I have an implementation of a `calibrate_spline` filter, which uses [spline](https://en.wikipedia.org/wiki/Spline_(mathematics)) fitting (piecewise polynomial functions). It seems to be working, I will deploy that in my ESP cover control and polish it.

At C++ level, I imagine reusing the same code geneartion that is instantiating filters but instead of instantiating them into the `filter_list_` attribute of the sensor component, instantiate a `FilterChain` instance which will have the `filter_list_` and its appropriate methods (`add_filters`, `set_filters`, a new `transform_value`, etc.). That `FilterChain` will be used also from time based covers that are using the `open_filters` and `close_filters` configuration entries.

Does it make sense? I know that it seems overkill, but note that `roller_shutter_delay` is not a silver-bullet as the linear speed is not constant: typically those motor have constant **rotation** speed, which means that the linear speed is greater when there is more cover rolled (because radius increases) and in my experiments it was quite noticeable.

**Comment by santibur06** [comment]
hey guys @glmnet @alexbarcelo, just wondering if you were able to take a look at this, I'm struggling with my shutters, position is totally off and the feature is useless in my setup. Do you guys know of any workaround I could put in place to fix this in the meantime? I'm sorry for asking but I would implement this code fix myself if I had any idea on where to start, it's been a while since I don't touch code other than yaml... thanks!

**Comment by muxa** [comment]
@alexbarcelo I like your idea of using filters to create a custom "curve" for time/position relation ship.
I'm in the same boat as @santibur06 - my blinds take a few seconds to start moving after issuing a command.
Have you been successful in implementing your idea?

I think being able to specify this filter for opening and closing independently would be useful. In my case the blinds are rotating to close there's a spot where they are kind of stuck for a second or so, and then rapidly move to the right position, so it would be great to be able to account for that.

**Comment by muxa** [comment]
Also to not depend on the refactoring required (#755) for implementing your idea, I was thinking to simply build the non-liner config into the `time_based` cover. e.g something like:

```yaml

cover:
  - platform: time_based
    name: "Balcony Louvres"

    open_action:
      - switch.turn_on: btn_open
    open_duration: 11s
    open_curve:
            - 0.0 -> 0.0
            - 0.4 -> 0.0
            - 0.9 -> 1.0
            - 1.0 -> 1.0

    close_action:
      - switch.turn_on: btn_close
    close_duration: 10s
    close_curve:
            - 0.0 -> 0.0
            - 0.1 -> 0.0
            - 0.3 -> 0.3
            - 0.4 -> 0.3
            - 0.42 -> 0.4
            - 0.8 -> 1.0
            - 1.0 -> 1.0

    stop_action:
      - switch.turn_on: btn_stop

```

Alternatively the curve can be configured using time (to make configuration more intuitive):

```yaml
    close_duration: 10s
    close_curve:
            # 0 -> 0.0 implied 
            - 1s -> 0.0
            - 3s -> 0.3
            - 4s -> 0.3
            - 4.2s -> 0.4
            - 8s -> 1.0
            # 10s -> 1.0 implied
```

@alexbarcelo what do you think?
