### ISSUE TITLE
Request: MQ135 Air Quality Sensor (PPM) support

### ISSUE THREAD

**Issue by micfogas** [esphome/feature-requests#757]
**Describe the problem you have/What new integration you would like**

I would like to request sensor integration for the MQ135 air quality gas sensor. This sensor provides 4 pins: 3.3v, GND, DOUT, AOUT. 

**Please describe your use case for this integration and alternatives you've tried:**

I have tried using custom sensor integrations, however I am still learning C++ and Arduino coding. I have found multiple libraries online (in .ino form and .h/.cpp form), and have tried multiple ways to impliment it into ESPHome, but I have been unsuccessful. Each library appears to use its own formula for calibration. The most accurate, from what I have heard, exists here: https://github.com/GeorgK/MQ135 however, additional libraries are:
https://platformio.org/lib/show/2537/TroykaMQ (comments in russian) and https://os.mbed.com/users/ngomez/code/MQ135/

**Additional context**

This is a gas/VOC sensor and should provide a reading output in PPM (particles per million). It appears the AOUT is used to provide the data to the NodeMCU/ESP8266.

**Comment by AlexBelfegor** [comment]
Here I changed the library for yaml format.
Outdoor calibration is required for adequate performance.
[https://github.com/AlexBelfegor/esphome-mq135](https://github.com/AlexBelfegor/esphome-mq135)

**Comment by micfogas** [comment]
thank you @AlexBelfegor !!

**Comment by hco** [comment]
@AlexBelfegor could you explain the calibration a little bit? 
If I put it on the street, which numbers do I need to read and where do I need to put them?

**Comment by AlexBelfegor** [comment]
> @AlexBelfegor could you explain the calibration a little bit?
> If I put it on the street, which numbers do I need to read and where do I need to put them?

You need to get CorrectedRZero on the street and enter this value into RZERO.

**Comment by dragonerix** [comment]
Hi @AlexBelfegor , can you help me with calibration... u must rewrite 2 index:

#Calibration resistance at atmospheric CO2 level. Outdoor calibration data
#Atmospheric CO2 level for calibration purposes. Outdoor CO2 level during calibration. Usually 450, but it's better to clarify.

True? Ok, i put sensro out door and get some data from (Corrected PPM CO2, PPM CO2, CorrectedRZero, RZero) Which i need use to write... Correcter or clasic? Thank you so much and sorry for my english.

**Comment by AlexBelfegor** [comment]
> Hi @AlexBelfegor , can you help me with calibration... i must rewrite 2 index:
> 
> #Calibration resistance at atmospheric CO2 level. Outdoor calibration data
> #Atmospheric CO2 level for calibration purposes. Outdoor CO2 level during calibration. Usually 450, but it's better to clarify.
> 
> True? Ok, i put sensro out door and get some data from (Corrected PPM CO2, PPM CO2, CorrectedRZero, RZero) Which i need use to write... Correcter or clasic? Thank you so much and sorry for my english.
> PS? C.RZero > RZero and C.CO2 > CO2?

I already answered earlier.
You need to get the CorrectedRZero readings on the street and write their globals RZERO (line 60 "initial_value: '35 .429 '").

"CorrectedRZero" and "RZERO" and "Corrected PPM CO2" and "PPM CO2" differ in that Corrected also takes into account temperature and humidity.

**Comment by Bojkas1985** [comment]
Hi, @AlexBelfegor , is it possible to use the DHT11 / 22 sensor instead of htu21d, or not use any?

Thank you

**Comment by AlexBelfegor** [comment]
> Hi, @AlexBelfegor , is it possible to use the DHT11 / 22 sensor instead of htu21d, or not use any?
> I changed all htu21d to dht
You can use any humidity and temperature sensor of your choice. But its resurrection is mandatory, because the formulas provide for the adjustment of temperature and humidity.

> But dht22 shows wrong temperature, at home 3,5°C and humidity 16%. I have 25°C and 55%. Any sugestion?
You may have a faulty sensor. The code has an adjustment for humidity, but the temperature is taken as is.

**Comment by Bojkas1985** [comment]
> You can use any humidity and temperature sensor of your choice. But its resurrection is mandatory, because the formulas provide for the adjustment of temperature and humidity.
> You may have a faulty sensor. The code has an adjustment for humidity, but the temperature is taken as is.

Can you please see if I'm all right? I only changed the temperature sensor to DHT.
```
esphome:
  name: co2_navstevnicky_pokoj
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: Internet home
  password: ""

  # Optional manual IP


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "co2_navstevnicky_pokoj"
    password: ""

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
   password: ""
   safe_mode: True
   
web_server:
  port: 80
  auth:
    username: admin
    password: ""

i2c:
  sda: 5
  scl: 4
  scan: False
  id: bus_a
  
globals:

#The load resistance on the board. Value in KiloOhms
  - id: RLOAD
    type: float
    restore_value: no
    initial_value: '1.025'

#Calibration resistance at atmospheric CO2 level. Outdoor calibration data
  - id: RZERO
    type: float
    restore_value: no
    initial_value: '5.175'

#Atmospheric CO2 level for calibration purposes. Outdoor CO2 level during calibration. Usually 450, but it's better to clarify.
  - id: ATMOCO2
    type: float
    restore_value: no
    initial_value: '450'

#Parameters for calculating ppm of CO2 from sensor resistance
#  Exponential regression:
#  GAS      | a      | b
#  CO       | 605.18 | -3.937  
#  Alcohol  | 77.255 | -3.18 
#  CO2      | 110.47 | -2.862
#  Tolueno  | 44.947 | -3.445
#  NH4      | 102.2  | -2.473
#  Acetona  | 34.668 | -3.369
  - id: PARA
    type: float
    restore_value: no
    initial_value: '110.47'
  - id: PARB
    type: float
    restore_value: no
    initial_value: '-2.862'

#Parameters to model temperature and humidity dependence
  - id: CORA
    type: float
    restore_value: no
    initial_value: '0.00035'
  - id: CORB
    type: float
    restore_value: no
    initial_value: '0.02718'
  - id: CORC
    type: float
    restore_value: no
    initial_value: '1.39538'
  - id: CORD
    type: float
    restore_value: no
    initial_value: '0.0018'
  - id: CORE
    type: float
    restore_value: no
    initial_value: '-0.003333333'
  - id: CORF
    type: float
    restore_value: no
    initial_value: '-0.001923077'
  - id: CORG
    type: float
    restore_value: no
    initial_value: '1.130128205'

# Here you need to indicate the supply voltage of the MQ135 sensor. It can be measured with a voltmeter. Please note that the rated power will not always be accurate.
  - id: volt_resolution
    type: float
    restore_value: no
    initial_value: '5.14'

# 1 for Exponential, 2 for Linear
  - id: regression_method
    type: int
    restore_value: no
    initial_value: '1'

sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "Temperature dht"
      id: dht_temperature
    humidity:
      name: "Humidity"
      id: dht_humidity
      filters:
      - lambda: if ((id(dht_temperature).state)>=0) {return (id(dht_humidity).raw_state + (25.0 - id(dht_temperature).state) * (-0.15));} else {return id(dht_humidity).raw_state;}
    update_interval: 30s

  - platform: adc
    pin: A0
    name: "Gas ADC"
    update_interval: 1s
    filters:
      - multiply: 3.3 # for NodeMcu ESP8266 v3 Lua
    accuracy_decimals: 0
    unit_of_measurement: V
    id: sensor_volt

  - platform: template
    #Linearization of the temperature dependency curve under and above 20 degree C
    #below 20degC: fact = a * t * t - b * t - (h - 33) * d
    #above 20degC: fact = a * t + b * h + c
    #this assumes a linear dependency on humidity
    #getCorrectionFactor
    name: "Correction Factor"
    lambda: |-
      if (id(dht_temperature).state<20) {
        return (id(CORA) * id(dht_temperature).state * id(dht_temperature).state - id(CORB) *
          id(dht_temperature).state + id(CORC) - (id(dht_humidity).state - 33.) * id(CORD));
      } else {
        return (id(CORE) * id(dht_temperature).state + id(CORF) * id(dht_humidity).state + id(CORG));
      }
    update_interval: 10s
    accuracy_decimals: 6
    id: correction_factor

  - platform: template
    #Get the resistance of the sensor, ie. the measurement value @return The sensor resistance in kOhm
    # RS = [(VC x RL) / VRL] - RL
    # RS_air = ((5.14*1.0)/sensor_volt)-1.0 Calculate RS in fresh air 
    #getResistance
    name: "Resistance"
    lambda: |-
      return ((id(volt_resolution)*id(RLOAD)/id(sensor_volt).state) - id(RLOAD));
    update_interval: 5s
    accuracy_decimals: 3
    unit_of_measurement: kOm
    id: resistance
    
  - platform: template
    # Get the resistance of the sensor, ie. the measurement value correctedfor temp/hum @return The corrected sensor resistance kOhm
    #getCorrectedResistance
    name: "Corrected Resistance"
    lambda: |-
      return (id(resistance).state / id(correction_factor).state);
    update_interval: 5s
    accuracy_decimals: 3
    unit_of_measurement: kOm
    id: corrected_resistance

  - platform: template
    # Get the ppm of CO2 sensed (assuming only CO2 in the air). The ppm of CO2 in the air
    #getPPM
    name: "PPM CO2"
    lambda: |-
      if (id(regression_method)==1) {
        return (id(PARA) * pow((id(resistance).state / id(RZERO)), id(PARB)));
      } else {
        return (pow(10, (log10(id(resistance).state / id(RZERO)) - id(PARB)) / id(PARA)));
      }
    update_interval: 5s
    unit_of_measurement: ppm
    id: ppm_co2

  - platform: template
    # Get the ppm of CO2 sensed (assuming only CO2 in the air), corrected  for temp. The ppm of CO2 in the air
    #getCorrectedPPM
    name: "Corrected PPM CO2"
    lambda: |-
      if (id(regression_method)==1) {
        return (id(PARA) * pow((id(corrected_resistance).state / id(RZERO)), id(PARB)));
      } else {
        return (pow(10, (log10(id(corrected_resistance).state / id(RZERO)) - id(PARB)) / id(PARA)));
      }
    update_interval: 5s
    unit_of_measurement: ppm
    id: corrected_ppm_co2

  - platform: template
    # Get the resistance RZero of the sensor for calibration purposes. The sensor resistance RZero in kOhm
    #getRZero
    name: "RZero"
    lambda: |-
      return (id(resistance).state / pow((id(ATMOCO2) / id(PARA)), (1./id(PARB))));
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 1
    update_interval: 5s
    accuracy_decimals: 3
    unit_of_measurement: kOm
    id: r_zero

  - platform: template
    # Get the corrected resistance RZero of the sensor for calibration purposes. The corrected sensor resistance RZERO in kOhm for ATMOCO2 level
    #getCorrectedRZero
    name: "CorrectedRZero"
    lambda: |-
      return (id(corrected_resistance).state / pow((id(ATMOCO2) / id(PARA)), (1./id(PARB))));
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 1
    update_interval: 5s
    accuracy_decimals: 3
    unit_of_measurement: kOm
    id: corrected_r_zero
```

I tried another sensor and the result is the same. :-/
Another problem I have is that I pulled the device out, left it there for about half an hour, pulled it out from Hassio CorrectedRZero, wrote to RZero in code, and reloaded into the device. For a while I had a value around 430, but now at home after about 4 hours there I have correcterd CO 60ppm.
