### ISSUE TITLE
Atlas Scientific EZO i2c sensors

### ISSUE THREAD

**Issue by Neukam** [esphome/feature-requests#766]
**Describe the problem you have/What new integration you would like**

I would like to see support for Atlas Scientific EZO sensors with i2c interface, specifically the ORP and PH sensors

**Please describe your use case for this integration and alternatives you've tried:**

 I want to be able to fully automate my pool with salt water generator. I'm currently using a Sonoff 4ch running Tasmota to control the pump, SWG and lights and read from a DS18B20 temperature sensor. I would like to be able to add the Atlas Scientific sensors and switch to ESPHome so that i can control the runtime of the SWG based on ORP, and also monitor PH.  These sensor modules could also be useful for a hydroponics system.

**Additional context**

There is a [library with examples](https://github.com/Atlas-Scientific/Ezo_I2c_lib).
There are datasheets and documentation on the product pages.
The following EZO devices are available
[ORP](https://www.atlas-scientific.com/circuits/ezo-orp-circuit/)
[PH](https://www.atlas-scientific.com/circuits/ezo-ph-circuit/)
[Dissolved Oxygen](https://www.atlas-scientific.com/circuits/ezo-dissolved-oxygen-circuit/)
[Electrical Conductivity](https://www.atlas-scientific.com/circuits/ezo-conductivity-circuit/)
[RTD Temperature](https://www.atlas-scientific.com/circuits/ezo-rtd-temperature-circuit/)
[Flow Meter Totalizer](https://www.atlas-scientific.com/circuits/ezo-embedded-flow-meter-totalizer/) This could be useful for tracking domestic water usage
[50 psi Pressure Sensor](https://www.atlas-scientific.com/probes/ezo-prs-embedded-pressure-sensor/)
[Peristaltic Dosing Pump](https://www.atlas-scientific.com/peristaltic/ezo-pmp-embedded-dosing-pump/)
[RGB Color Sensor](https://www.atlas-scientific.com/probes/ezo-rgb-embedded-color-sensor/)

Atlas Scientific also has a [Hydroponics Kit](https://www.atlas-scientific.com/kits/wi-fi-hydroponics-kit/) which has an ESP8266 mounted on a carrier board with PH, Electrical Conductivity, and RTD Temperature EZO boards with a provision to add one additional EZO board.  This could also be very useful for a pool controller.  Their code for the ESP is open source and [posted on their github](https://github.com/Atlas-Scientific/Ezo_I2c_lib/blob/master/Examples/hydroponics_kit/hydroponics_kit.ino).

**Comment by mrgoose2** [comment]
User ssieb has a custom component for these sensors. github com/ssieb/custom_components/tree/master/ezo

I have my sensors on a tentacle shield attached to an arduino mega, the scl and sda pins from the mega are attached to the D2 and D1 pins on a NodeMCU. 

I created a folder called "custom-components" under my esphome folder and placed ssieb's "ezo" folder in it. 

Here is the relevant part of my yaml file.
`i2c:
  sda: D2
  scl: D1
  scan: True
  id: bus_a

  #ezo platform from: https://github.com/ssieb/custom_components
sensor:
  - platform: ezo
    id: ph_ezo
    name: "pH"
    address: 99
    accuracy_decimals: 2
    unit_of_measurement: "pH"

      
  - platform: ezo
    id: rtd_ezo
    name: "RTD Temperature"
    address: 101
    accuracy_decimals: 2
    unit_of_measurement: "°C"

      
  - platform: ezo
    id: ec_ezo
    name: "EC CN"
    address: 100
    accuracy_decimals: 0
    unit_of_measurement: "CN"
`

I don't have much experience with esphome or arduino, but ssied's component made this easy.

**Comment by ssieb** [comment]
Ok, fine, I'll write up the docs and file a PR. :-)

**Comment by mrgoose2** [comment]
> Ok, fine, I'll write up the docs and file a PR. :-)

I was trying to get these sensors to work for the last couple days, stumbled across your repo and presto I was up and running. Thanks for putting it out there, I really appreciate it! So much that I had to share on this thread!

**Comment by Neukam** [comment]
Sweet!  You guys are awesome!  I'll be trying this out this weekend

**Comment by iHakia** [comment]
Hi guys, Thanks for the help implementing those sensors. 
I'm really trying to get this one working. for now, it seems that I have problem with the esphome folder structure or something. 
the files are located at \config(where my HA configuration yaml)\esphome\custom_components\ezo
this is my code 
```
esphome:
  name: nfatxxxxxlas
  platform: ESP8266
  board: esp01_1m
  includes:
    - ezo.h

i2c:
  sda: 4
  scl: 5
  scan: True
  id: bus_a

wifi:
  ssid: "xxxxxx"
  password: "xxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "xxxxFallback Hotspot"
    password: "LYoPZoHB4pdh"
    
sensor:
  - platform: ezo
    id: ph_ezo
    address: 99
    unit_of_measurement: "pH"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "xxxxxxxx"

ota:
  password: "xxxxxxxxxx"

```

Unfortunately I keep getting the message 
"platform not found. 'sensor. ezo'"
anyone have an idea? 
Help much appreciated 👍
