### ISSUE TITLE
Add CJMCU-8128 support

### ISSUE THREAD

**Issue by riochicken** [esphome/feature-requests#791]
Hi, 

It would be excellent to get CJMCU-8128 support to ESPhome, my new home will have a CO2 system installed and I would like to keep monitoring this constantly since new houses don't seem to have any natural ventilation systems anymore.

Thank you in advance!

Kind regards
Richard

**Comment by idavydov** [comment]
CJMCU-8128 is three different sensors on the same board:

- CCS881 (eCO2 & TVOc)
- BMP280 (temperature & pressure)
- Si7021 (temperature & humidity)

All of them are already supported by ESPHOME (amazing, I'm really impressed).

Here is the config which works for me:
```
sensor:
  - platform: bmp280
    temperature:
      name: "Temperature (BMP280)"
      id: bmp280_temperature
      oversampling: 16x
    pressure:
      name: "Pressure"
    address: 0x76
    update_interval: 60s
  - platform: htu21d
    temperature:
      name: "Temperature (Si7021)"
    humidity:
      name: "Humidity"
      id: si7021_humidity
    address: 0x40
    update_interval: 60s
  - platform: ccs811
    eco2:
      name: "CCS811 eCO2 Value"
    tvoc:
      name: "CCS811 Total Volatile Organic Compound"
    temperature: bmp280_temperature
    humidity: si7021_humidity
    address: 0x5A
    update_interval: 60s
```

Please note that:
- Temperature and humidity parameters for ccs811 are not necessary but are supposed to correct for changes in humidity and temperature.
- It [seems](https://mindeon.com/posts/coding-journal/cjmcu-8128-code-example/) that some versions of CJMCU-8128 have HDC1080, not Si7021. You need to change your settings accordingly. There might be also other differences, e.g., different addresses.
- You need to take special care calibrating the sensor. First, run it for 48 hours. Then you need to set the baseline (see [here](https://esphome.io/components/sensor/ccs811.html), ideally somewhere in the fresh air). Finally, they recommend a periodic baseline correction, which I am not sure is implemented in the esphome module for CCS881.
- I have an impression that CCS881 is not a very precise sensor; good CO2 sensors are expensive.
