### ISSUE TITLE
BLE Bridge

### ISSUE THREAD

**Issue by anthonyangel** [esphome/feature-requests#792]
**Describe the problem you have/What new integration you would like**
I'd like to be able to use devices controlled by esphome as BLE bridges (to connect BLE devices to a local network)

**Please describe your use case for this integration and alternatives you've tried:**
I currently use https://github.com/bendikwa/igrill to monitor a Weber iGrill (on a raspberry pi, I'd like to be able to use an esp instead to read from the sensors. This device would be read-only, but there are some which would benefit from read/write functionality (e.g. Anova Sous Vide machine)

**Additional context**

**Comment by xbmcnut** [comment]
+1

**Comment by anthonyangel** [comment]
With the new(ish) BLE Client Sensor component I've started poking this.

So far I can get the battery status with this config:
```
sensor:
  - platform: ble_client
    ble_client_id: igrill
    name: "iGrill battery level"
    service_uuid: '180f'
    characteristic_uuid: '2a19'
    icon: 'mdi:battery'
    unit_of_measurement: '%'
 ```
 
The debug logs show me that the device has 2 other services, which have 7 and 9 characteristics. I've tried taking the UUIDs from the logs (I don't know why but the logs showed malformed UUIDs and I had to move the dashes around), but this didn't give me any valid data.

From reading various python repos (like the one linked in the top post) it looks like the values are encrypted with a static key, so I'm going to try and experiment with a lambda to decrypt the values. So far I've tried the code for [raw data parsing](https://esphome.io/components/sensor/ble_client.html#raw-data-parsing-lambda), just to get the values, but it still errored.
