### ISSUE TITLE
PCF8574 custom characters

### ISSUE THREAD

**Issue by RichardDern** [esphome/feature-requests#818]
**Describe the problem you have/What new integration you would like**

I'd like to get an implementation of LiquidCrystal's method [createChar](https://www.arduino.cc/en/Reference/LiquidCrystalCreateChar).

**Please describe your use case for this integration and alternatives you've tried:**

I think it would be a nice addition to be able to define byte arrays for custom chars in display's definition. Maybe something like this:

```
- platform: lcd_pcf8574
  dimensions: 16x2
  address: 0x27
  custom_characters:
    - my_custom_char1: <character definition>
    - my_custom_char2: <...>
```

**Additional context**
