### ISSUE TITLE
Scripting : Lambda-less counted loops and infinite loops

### ISSUE THREAD

**Issue by AlexDanault** [esphome/feature-requests#827]
I hope I'm not alone thinking this, but scripting (automations) could benefit from two more structures usable with 100% YAML and 0% lambdas : counted loops ( `for (int i = 0; i < 5; i++) { ... } ` ) and infitine loops ( `while(true) { ... }` ).

Both can be done currently using a While action but rely on lambdas and even variables. I have a script that blinks a light (it is in a script so it can be started/stopped depending on events) and is a bit wordy  

```yaml
- while:
    condition:
      lambda: 'return 1;'
    then:
      - switch.turn_on: red
      - delay: 350ms
      - switch.turn_off: red
      - delay: 350ms
```

Counted loop need even mode lambda. Both could be simplified with a new Loop action:

```yaml
- loop:
    count: infinite    #or any positive integer for counted loops, or a lambda that returns an integer or null for infinite
    then:
      - switch.turn_on: red
      - delay: 350ms
      - switch.turn_off: red
      - delay: 350ms
```

Would this be a nice addition to EspHome ?
