### ISSUE TITLE
Allow non-string substitutions

### ISSUE THREAD

**Issue by lociii** [esphome/feature-requests#839]
**Describe the problem you have/What new integration you would like**

I'd like to be able to use non-string values in substitutions e.g. float

**Please describe your use case for this integration and alternatives you've tried:**

I have a shared template for all my Shelly RGBW2 devices. This template defines the outputs.

```yaml
output:
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    id: pwm_r

  - platform: esp8266_pwm
    pin: GPIO15
    frequency: 1000 Hz
    id: pwm_g

  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 1000 Hz
    id: pwm_b

  - platform: esp8266_pwm
    pin: GPIO4
    frequency: 1000 Hz
    id: pwm_w
```

As different devices derived from that template might need different max_power settings per channel, I'd like to be able to define them as substitutions. 

```yaml
output:
  - platform: esp8266_pwm
    pin: GPIO4
    frequency: 1000 Hz
    id: pwm_w
    max_power: ${max_power_w}
```

However I can neither use a float ```0.3``` substitution
```
Must be string, got <class 'esphome.yaml_util.ESPFloat'>. did you forget putting quotes around the value?.
max_power_w: 0.3 [source /config/esphome/my_device.yaml:9]
```
nor use a string ```"0.3"``` for the substitution

```
  File "/opt/esphome/esphome/config_validation.py", line 845, in possibly_negative_percentage
    if value > 1:
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Additional context**

None.
