### ISSUE TITLE
New Component - Timer

### ISSUE THREAD

**Issue by jchambers2012** [esphome/feature-requests#84]
**Describe the problem you have/What new integration you would like**
I would like a timer sensor.  This would be triggered by automation or Home Assistant and after the timer runs out, it would trigger an event on the ESP.  The timer would run on the ESP itself for internal automation and call back without the need to talk to Home Assistant. 

**Please describe your use case for this integration and alternatives you've tried:**
When a cabinet door is open; the ESP turn on an LED light strip. After the door is closed; the ESP turn off the LED strip. I am looking to have a fail safe to turn off the LEDs after X hours/minutes.  I want this timer to run on the ESP itself so it can still perform the "turn off" automation if the HA crashes or goes offline.

**Additional context**

Possible config:
```
time:
  - platform: timer
    seconds: <number>
    minutes: <number>
    hours: <number>
    self_reset TRUE(Default, Optional) <- would reset the counter after it expires
    self_stop TRUE(Default, Optional) <- if the self_reset is set to true, TRUE: set the timer to a stop state FALSE: time would keep running
    disable_switch: switch.myswitch (Default, Optional) <- switch exposed to Home Assistant for disabling the timer, could also be allowed to accept a GPIO or other binary components
    on_start:
        then: (actions) 
    on_stop: - Different then the counter going to 0
        then: (actions) 
    on_reset:
        then: (actions) 
    on_expire: - Counter going to 0
        then: (actions) 
        - light.turn_off: 
            id: dining_room_cabinet_inside_a
        - light.turn_off:
            id: dining_room_cabinet_inside_b
          - timer.reset_stop:
            id: my_timer
```
Automation functions:
-timer.start <-start the countdown counter
-timer.stop <- stop the countdown counter
-time.reset <- reset the countdown time to being full; counter would remain in a start or stop state
-timer.reset_start  <- reset the countdown time to being full; counter would go to start state
-timer.reset_stop  <- reset the countdown time to being full; counter would go to stop state
	
Real world example:
```
switch:
  - platform: template
    name: "Dining Room Cabinet Auto Light Turnoff"
    optimistic: true
    id: dining_room_cabinet_automation_autoturnoff

time:
  - platform: timer
    id: my_timer
    name: “Auto Lights turn off”
    disable_switch: switch.dining_room_cabinet_automation_autoturnoff
    hours: 2
    on_expire:
        then:
        - light.turn_off: 
            id: dining_room_cabinet_inside_a
        - light.turn_off:
            id: dining_room_cabinet_inside_b
        - timer.reset_stop: 
            id: my_timer

binary_sensor:
  - platform: gpio
    name: "Dining Room Cabinet Left Door"
    pin:
     number: D2
    device_class: door
    id: dining_room_cabinet_door_left
    on_release:
      then:
        - light.turn_off:
            id: dining_room_cabinet_inside_a
        - light.turn_off:
            id: dining_room_cabinet_inside_b
        -timer.stop: 
            id: my_timer
    on_press:
      then:
        - light.turn_on:
            id: dining_room_cabinet_inside_a
            brightness: 80%
        - light.turn_on:
            id: dining_room_cabinet_inside_b
            brightness: 80%
        -timer.reset_start: 
            id: my_timer
```

**Comment by OttoWinter** [comment]
I believe scripts can do exactly that.

```yaml
script:
  id: my_timer
  then:
  - # on_start
  - delay: 30min  # timer length
  - # on_end

# start/reset timer
- script.stop: my_timer
- script.execute: my_timer

# stop timer
- script.stop: my_timer
```

I definitely don't like the suggested config. It's way to complicated for normal setups, and feels a lot like the HA style of configs (with way too many options that thus confuse users).
