### ISSUE TITLE
Support tag scanning by introducing `homeassistant.tag`

### ISSUE THREAD

**Issue by balloob** [esphome/feature-requests#848]
**Describe the problem you have/What new integration you would like**

Home Assistant 0.115 is adding a new `tag` integration. The goal is to make it easier for users to use tags to automate things. 

Tags are passed to the tag integration by calling the [`async_scan_tag`](https://github.com/home-assistant/core/blob/3fc2bae49ef07cea270ffddbc24e7a758aade806/homeassistant/components/tag/__init__.py#L109) method on the tag integration (in Python). From here on the user will be guided via a yet-to-be-made UI to automate it. 

```python
await tag.async_scan_tag(
    hass,
    tag_id,     # tag that was scanned
    device_id,  # of ESPHome device that scanned tag
)
```

We will need ESPHome integration to be able to call this method with data send in from an ESPHome device.

To do so, I would like to propose a new script syntax to ESPHome `homeassistant.tag`. When invoked, it will scan a tag inside Home Assistant.

Example how it can be used with a pn532:

```yaml
pn532:
  cs_pin: D0
  update_interval: 1s
  on_tag:
    then:
    - homeassistant.tag:
        tag: !lambda 'return x;'
```

**Please describe your use case for this integration and alternatives you've tried:**

Currently it can be implemented using events, and then having a custom integration set up on the backend that converts events to calling the tag integration.

```yaml
pn532:
  cs_pin: D0
  update_interval: 1s
  on_tag:
    then:
    - homeassistant.event:
        event: esphome.rfid_read
        data_template: 
          message: !lambda 'return x;'

```

**Additional context**
