### ISSUE TITLE
Support for Adafruit_AMG8833 8X8 pixel Thermal Camera

### ISSUE THREAD

**Issue by IsaTTeN** [esphome/feature-requests#851]
**Describe the problem you have/What new integration you would like**
Adafruit AMG8833 Support. The AMG8833 is a Thermal Camera with a resolution of 8x8 pixel.
**Please describe your use case for this integration and alternatives you've tried:**
Since it measures temperature, It can detect a human from a distance of up to 7 meters (23 feet).
I made a custom component but I get errors (SPI stuff). This is my first try with a custom sensor. I can post here my custom component if you need it

**Additional context**

[https://github.com/adafruit/Adafruit_AMG88xx](url)
[https://www.adafruit.com/product/3538](url)

**Comment by DylanDonkersgoed** [comment]
I've actually been trying to do exactly what you are since last night, though I'm using a knockoff sensor. I'm guessing that like me you're trying to use the "Adafruit AMG88xx Library". I was able to resolve the SPI issue by including it under libraries, e.g.:

```
esphome:
  name: heatcam1
  platform: ESP32
  board: lolin32
  includes:
    - custom_amg8833.h
  libraries:
    - "Adafruit AMG88xx Library"
    - "SPI"
```

Perhaps it will work better for you.

Unfortunately I then ran into other issues that seem to be related to SD cards somehow. I think it's something to do with a dependency of some common library that Adafruit brings in. I elected to use the SparkFun library instead. It's not as popular but had the significant plus of actually compiling for my board. If the Adafruit library doesn't work for you either feel free to message me and I can send you what I've got so far, though it isn't really much.

**Comment by IsaTTeN** [comment]
Hello @DylanDonkersgoed !

Yes! I had the same SD issue! So, were you able to integrate into esphome?. Could you share your progress?

Thanks

**Comment by DylanDonkersgoed** [comment]
@IsaTTeN  It's not really integrated in any meaningful way yet but I *do* have it reading values from the sensor which I guess is the main thing. Here's what I've got, I'm sure you could adapt it to your use case:

```cplusplus
#include "esphome.h"
#include "SparkFun_GridEYE_Arduino_Library.h"

class AMG8833 : public PollingComponent, public Sensor {
 public:
  AMG8833() : PollingComponent(1000) {}

  float pixels[64];
  GridEYE grideye;

  void setup() override {
    ESP_LOGD("custom", "Starting up AMG8833 sensor");
    grideye.begin();
    delay(1000);
  }

  void update() override {
    for(unsigned char i = 0; i < 64; i++){
      pixels[i] = grideye.getPixelTemperature(i);      
    }

    for (unsigned char i = 0; i < 64; i++) {
      char buffer[8];
      ESP_LOGD("custom", dtostrf(pixels[i], 3, 2, buffer));
    }
  }

};
```

and of course you need the appropriate includes, i2c settings and sensor settings in your yaml file:
```yaml
esphome:
  name: heatcam1
  platform: ESP32
  board: lolin32
  includes:
    - custom_amg8833.h
  libraries:
    - "SparkFun GridEYE AMG88 Library"


i2c:
  # Change as per your preference
  sda: 19
  scl: 22
  scan: True

sensor:
  - platform: custom
    lambda: |-
      auto amg8833 = new AMG8833();
      App.register_component(amg8833);
      return {amg8833};

    sensors:
      name: "AMG8833"
```
