### ISSUE TITLE
Add support for ATC_MiThermometer

### ISSUE THREAD

**Issue by danielkucera** [esphome/feature-requests#877]
**Describe the problem you have/What new integration you would like**

I'd like to see ATC_MiThermometer supported in esphome.

**Please describe your use case for this integration and alternatives you've tried:**

The original firmware is supported but it requires complicated bind key generation and only sends the data once in 10 minutes.
The opensource firmware can be programmed to any interval.

**Additional context**

This has already been discussed a bit in closed issue #552 . I'm opening this one to not spoil the original issue.
All protocol info can be found here: https://github.com/atc1441/ATC_MiThermometer

**Comment by tubalainen** [comment]
This is GREAT! I would love not to go through the token/hash process to hijack the MI communication.

**Comment by Kuglikrug** [comment]
This would be amazing. Flashing atc1441's firmware works like a charm and integration with esphome would really help!!

**Comment by danielkucera** [comment]
BTW, this seems like a 2hour job, I  can try to implement it today.

**Comment by Calcu2006** [comment]
It was possible to implement ?

**Comment by ahpohl** [comment]
Initial support for the [ATC MiThermometer](https://github.com/atc1441/ATC_MiThermometer) custom firmware can be found here: [https://github.com/ahpohl/esphome/tree/atc_mithermometer](https://github.com/ahpohl/esphome/tree/atc_mithermometer). I have currently implemented temperature, humidity and battery level in %. The custom firmware also broadcasts battery level in mV, which is not collected yet.

Configuration is like this:
```
esphome:
  name: basement
  platform: ESP32
  board: nodemcu-32s 

wifi:
  ssid: "your ssid"
  password: "your wifi password"

api:

logger:
  #level: VERY_VERBOSE

ota:

esp32_ble_tracker:
  scan_parameters:
    window: 120ms

web_server:
  port: 80

mqtt:
  broker: 192.168.178.55

sensor:
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:4E:16:78"
    temperature:
      name: "ATC Temperature"
    humidity:
      name: "ATC Humidity"
    battery_level:
      name: "ATC Battery-Level"
```
Download and compile a new firmware:
```
git clone https://github.com/ahpohl/esphome.git
cd esphome
git checkout atc_mithermometer
python -m venv venv
source venv/bin/activate
python setup.py install
mkdir Testing; cd Testing
esphome atc_mithermeter.yaml run
```
