### ISSUE TITLE
Add uart_id and energy on Pzemdc

### ISSUE THREAD

**Issue by lucasimons** [esphome/feature-requests#880]
Now the pzemdc as, pzem 017, not support uart_id and energy meter, indeed the pzemac support all this two thinghs,
I would use two pzemdc to monitor the energy from the solar panel to battery, in the same board..
thanks for the support

 DO NOT DELETE ANY TEXT from this template! Otherwise the issue may be closed without a comment.
-->

**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by randybb** [comment]
Physical layer is UART, but on top of it it is MODBUS. That means if you want to attach it to a different UART, then it is done under _modbus:_ componet like this: 
```yaml
uart:
  - id: uart_2
    rx_pin: GPIO16
    tx_pin: GPIO17
    baud_rate: 9600
    stop_bits: 1
modbus:
  uart_id: uart_2
  id: modbus_2 # needed only for multiple buses

sensor:
  - platform: pzemdc
    modbus_id: modbus_2
    current:
      name: "PZEM-003 Current"
    voltage:
      name: "PZEM-003 Voltage"
    power:
      name: "PZEM-003 Power"
    update_interval: 60s
```
