### ISSUE TITLE
Add native API Home Assistant event fire action

### ISSUE THREAD

**Issue by OttoWinter** [esphome/feature-requests#89]
**Describe the problem you have/What new integration you would like**

ESPHome has triggers like on_click etc that can be used in automations - in HA terms these are events. Currently it's a bit hard to get these triggers into HA, you need to set up a `homeassistant.service` action:

```yaml
binary_sensor:
- platform: abc
  # ..
  on_press:
  - homeassistant.service:
      service: script.execute
      # ... etc
```

that is a whole bunch of yaml for something quite simple: getting events across these two systems.

So, let's add an `homeassistant.event` action like this

```yaml
binary_sensor:
- platform: abc
  # ..
  on_press:
  - homeassistant.event: esphome.my_gpio_triggered
```

So this will generate an event in the event bus in HA called `esphome.my_gpio_triggered` with no args.

```yaml
automation:
  trigger:
    platform: event
    event_type: esphome.my_gpio_triggered
```

Optionally, the user can also supply arguments:

```yaml
binary_sensor:
- platform: abc
  # ..
  on_press:
  - homeassistant.event: 
      event: esphome.my_gpio_triggered
      data:
        hello: world
        here: !lambda 'return "this";'
```
