### ISSUE TITLE
a way to fix Nextion Dual state button

### ISSUE THREAD

**Issue by AalianKhan** [esphome/feature-requests#91]
**Describe the problem you have/What new integration you would like**

set the binary sensor to have the correct state of the button
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

By default, you cannot send the value when it is pressed but there are workarounds. The one I tried is adding one line of code to the HMI file. Under each touch event, I wrote ``get bt0.val`` So whenever I touch it, it will send the correct value to the MCU. now whenever I touch it, I get 
``71 01 00 00 00 FF FF FF``
which translates to
71 = defining the message type. in this case numerical value
01 = the value
the rest is not useful.
So I was thinking that the Nextion binary sensor should have two types. One is ``normal`` and the other should be ``dual_state``

```YAML
binary_sensor:
  - platform: nextion
    page_id: 0
    component_id: 1
    type: dual_state
    nextion_id: display
    id: up
```
so that way esphome knows which type is being used and go accordingly. Then you can add the code to listen for the correct response. Love your work 😃
