### ISSUE TITLE
Use LEDC PWM for ST7789V's backlight_pin

### ISSUE THREAD

**Issue by GHF** [esphome/feature-requests#914]
**Describe the problem you have/What new integration you would like**

I'd like to use LEDC instead of GPIO output to control the `backlight_pin` of the ST7789V LCD on my TTGO T-Display project. 

So instead of:
```
display:
  - platform: st7789v
    backlight_pin: 4
    cs_pin: 5
    dc_pin: 16
    reset_pin: 23
```

I'd like to have:
```
output:
  - platform: ledc
    pin: 4
    id: ledc_display_backlight

display:
  - platform: st7789v
    backlight_pin: ledc_display_backlight
    cs_pin: 5
    dc_pin: 16
    reset_pin: 23
```

**Please describe your use case for this integration and alternatives you've tried:**

I don't really know the parser and schema well enough to hack together the above syntax, so what I've done is use an unused GPIO for the `backlight_pin` key then independently control the LEDC for GPIO4 independently of the ST7789V integration: https://github.com/GHF/iaq-node/commit/2642ecc1a425c1950ed78629615e030c20a13342

Per the [schematic](https://github.com/Xinyuan-LilyGO/TTGO-T-Display/blob/master/schematic/ESP32-TFT(6-26).pdf), GPIO4 controls the backlight LEDs through Q0 so it can be PWMed extremely fast and this works great, but I think PWMed backlight control should really be a part of the integration.

**Additional context**
