### ISSUE TITLE
Thermostat: Remember temperature when switching to/from away mode

### ISSUE THREAD

**Issue by Sebclem** [esphome/feature-requests#918]
**Describe the problem you have/What new integration you would like**

With the thermostat component: 
When to change the target temperature, switch to `away` mode and get back to `home` mode, the target temperature fall back to the `default_target_temperature_low` value. It will be interesting to remember the previous value and maybe add a setting to let the user choose if he want to fallback to default or remember the user changed value.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by wernight** [comment]
I actually noticed the same thing. Initially I implemented this myself using global variables that are stored and it worked, but now using the built-in thermostat it doesn't seem to recall any set value.

Here is my config for it:

```yaml
climate:
  - platform: thermostat
    id: my_thermostat
    name: "${devicename}"
    sensor: temperature
    default_target_temperature_low: 20 °C
    away_config:
      default_target_temperature_low: 5 °C
    heat_action:
      - switch.turn_on: floor_heating_switch
    idle_action:
      - switch.turn_off: floor_heating_switch
```

Once running, from Home Assistant:

 1. Set temperature to something else and wait a few seconds
 2. Change to Away mode for that thermostat
 3. Change back to Home mode for that thermostat

Expected: It restores the temperature set at step (1).
Actual: It restores the default temperature.

I'd expect that my device keeps a temperate set for home and one set for away. I get that some people might want to always go back to the hardcoded value in this scenario but that feel like the wrong behavior for most people. One point to back this up would be Nest Thermostats.
