### ISSUE TITLE
ESP8266 capacitive touch sensor using GPIO

### ISSUE THREAD

**Issue by redskinhu** [esphome/feature-requests#92]
**Describe the problem you have/What new integration you would like**
I would like create a capacitive touch switch using ESP8266 GPIO's.

**Please describe your use case for this integration and alternatives you've tried:**
I would like to use the ESP8266 GPIO's instead of using TTP223 or ESP32. I saw many of versions but they use the Arduino Capacitive Sensing Library. See: http://playground.arduino.cc/Main/CapacitiveSensor

Is it possible to integrate this feature or someone have / can create Custom Binary Sensor code for this problem? Or any other solution?

Thanks
T

**Comment by BananaPukeh** [comment]
I managed to implement this by toggling the ground of the switch when you touch is, so the button would be reset.

```
binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
    name: 'MCU 4 Button'
    id: 'button'
    on_press:
      then:
        - if: 
            condition:
              - switch.is_off: 'button_switch'
            then:
              - delay: 1s
              - if: 
                  condition:
                    - binary_sensor.is_on: 'button'
                  then:
                    - switch.turn_on: 'button_switch'
                    - delay: 200ms
                    - switch.turn_off: 'button_switch'
    
    
switch:
  - platform: gpio
    name: "button switch"
    id: button_switch
    pin: D2
    internal: true
```
