### ISSUE TITLE
cwww choose boot color temperature

### ISSUE THREAD

**Issue by pw-sys** [esphome/feature-requests#959]
**Describe the problem you have/What new integration you would like**
A cwww LED with the option restore_mode : ALWAYS_ON will always start in the cold white mode, it would be great to have an option to boot in warm white mode

**Please describe your use case for this integration and alternatives you've tried:**
This is for a lamp in the bathroom which is classically controlled via a power switch. It would be great to have the option to boot into warm white light.
I have tried on_boot - but it will allways start cold for a second and then change

**Additional context**

**Comment by ryanjohnsontv** [comment]
I find that defining an on_boot action solves this issue:
```
esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  on_boot:
    then:
      - light.turn_on:
          id: $devicename
          brightness: ${brightness}%
          color_temperature: ${colortemp}K
```
