### ISSUE TITLE
WLED sync for platform rgbww

### ISSUE THREAD

**Issue by pashdown** [esphome/feature-requests#966]
**Describe the problem you have/What new integration you would like**
Enable WLED sync effect for platform RGBWW and single RGB bulbs.

**Please describe your use case for this integration and alternatives you've tried:**
WLED doesn't support PWM for single RGB bulbs, and I'd rather use esphome anyway.  Although WLED is an effect for the neopixelbus, it would be nice to sync my esphome RGB bulbs to the WLED strips in the area.

**Additional context**
Example:
```
output:
  - platform: esp8266_pwm
    pin: GPIO14
    id: output_blue
  - platform: esp8266_pwm
    pin: GPIO12
    id: output_green
  - platform: esp8266_pwm
    pin: GPIO4
    id: output_red
  - platform: esp8266_pwm
    pin: GPIO5
    id: output_coldwhite
  - platform: esp8266_pwm
    pin: GPIO13
    id: output_warmwhite

light:
  - platform: rgbww
    name: ${friendly_name}
    id: ${device_name}
    default_transition_length: 1.5s
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_coldwhite
    warm_white: output_warmwhite
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    restore_mode: RESTORE_DEFAULT_OFF
    color_interlock: true
    effects:
      - wled:
         port: 21324

```
Result:
```
      Unable to find effect with the name 'wled'.
      wled:  [source /config/esphome/include/effects.yaml:269]
        port: 21324
```

**Comment by Sergey-SRG** [comment]
WLED support only the addressable led strings!

**Comment by pashdown** [comment]
Yes, I understand that.  Is there a reason that a single RGB bulb can't emulate a single LED of that string?

**Comment by mirko** [comment]
I'd also fancy this, there's a lot one could do with a simple RGB(W) strip to keep them in syc with the fully-addressable ones.

**Comment by oxan** [comment]
This is basically the same as #1107 (as in, a fix for either would most likely fix the other as well).

**Comment by mrand** [comment]
Did anyone (@oxan?) figure out how to use the partition functionality to implement WLED sync to a bulb?   #1107 even mentions that it should help, but I'm not seeing how...

**Comment by WeekendWarrior1** [comment]
> Did anyone (@oxan?) figure out how to use the partition functionality to implement WLED sync to a bulb? https://github.com/esphome/feature-requests/issues/1107 even mentions that it should help, but I'm not seeing how...

I think it's something like this:
```yaml
light:
  - platform: partition
    name: "Partition Light"
    segments:
      - single_light_id: light1
    effects:
      - wled:
         port: 21324
      
  - platform: rgbww
    name: "Light 1"
    id: light1
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_white_cold
    warm_white: output_white_warm
    cold_white_color_temperature: 5700 K
    warm_white_color_temperature: 3000 K
    restore_mode: RESTORE_DEFAULT_ON
    constant_brightness: true
    color_interlock: true
...
```

**Comment by Tuckie** [comment]
were you able to get this work, I still get an error `Unable to find effect with the name 'wled'.`

**Comment by mrand** [comment]
> were you able to get this work, I still get an error `Unable to find effect with the name 'wled'.`

Yes and no.  I got it to compile, but it doesn't sync.  Not sure where the fault lies, but I did open issue https://github.com/esphome/issues/issues/3296 on one error.

You're probably missing the "wled:"

```yaml
wled:

light:
  - platform: rgbw
    id: ${devicename}_light
    name: "RGBW 3"
    default_transition_length: 0s
    red: output_red
    green: output_green
    blue: output_blue
    white: cw

  - platform: partition
    name: "RGBW 3 Partition"
    segments:
      - single_light_id: ${devicename}_light
    effects:
      - wled:
```
