### ISSUE TITLE
Update Epaper on Action

### ISSUE THREAD

**Issue by deepc2020** [esphome/feature-requests#967]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**
With the epaper display new information are only shown when the display does a refresh.
When a new information is published, for example on an mqtt, it would be good, if this information can trigger a display/information refresh.
The update interval of the epaper display does a full refresh including full inverting, so if you chose a shorter interval you will get a "flickering" display.

**Additional context**

```
text_sensor:
  - platform: homeassistant
    name: "Outside Temp"
    entity_id: sensor.netatmo_one_balkon_temperature
    id: outside

display:
  - platform: waveshare_epaper
    cs_pin: D2
    dc_pin: D3
    busy_pin: D4
    reset_pin: D5
    model: 4.40in
    update_interval: 600 #The interval to re-draw the screen. Defaults to 10s.
    lambda: |-
     it.printf(0, 10, id(GoFont), "Outside Temp: %s °C", id(outside).state.c_str());
```

**Comment by m1ch** [comment]
This is already possible. 

Here is an working example to trigger the display refresh at exactly the change of the minute:
```yaml
on_time:
   - seconds: 0
     minutes: /1
     then:
        - component.update: eink

display:
  - platform: waveshare_epaper
    id: eink
    cs_pin: D2
    dc_pin: D3
    busy_pin: D4
    reset_pin: D5
    model: 4.40in
    update_interval: 6000000 #Set to one week or so
    lambda: |-
     it.printf(0, 10, id(GoFont), "Outside Temp: %s °C", id(outside).state.c_str());
```

I think this issue can be closed
