### ISSUE TITLE
Trigger for lights

### ISSUE THREAD

**Issue by redskinhu** [esphome/feature-requests#98]
Hello

**Describe the problem you have/What new integration you would like**
It would be useful if triggers are exist for lights too.

**Please describe your use case for this integration and alternatives you've tried:**
I needed to solve my problem with switches but they are light components anyway and i would like to use them like lights but the HA handled them like switches. Ok i can switch them on/off but the light's features are missing. And i can use HA automations too but what if the HA down....?

**Additional context**
Something like this: ` light.on_turn_on /  light.on_turn_off`

Thx
T

**Comment by phatpenguintn** [comment]
A specific use case for this is the Merkury color lights which have to be implemented as a 2 part light since the drivers are different for white and RGB

This is a current working Merkury yaml:
```
light:
  - platform: monochromatic
    name: 'Light1 White'
    output: pwm_w
    id: light1_white
  - platform: fastled_spi
    name: "Light1 Color"
    id: light1_color
    chipset: SM16716
    clock_pin: GPIO4
    data_pin: GPIO14
    power_supply: rgb_power
    num_leds: 8
    rgb_order: RGB
```

it would be great to be able to put something like this on the color light since you need the white light to turn off before you can see the color leds.
```
 on_turn_on:
   then:
     - light.turn_off: light1_white
```

Then you would not have to touch both lights to turn on the color.  

This method would also be great to control the light behavior in different circumstances.
For instance when someone steps onto the porch I want to turn on the white light and then once the pir stops turn off the white and let the color still be on, so I can handle the behavior differently for that light instead of the way I handle the accent lights for example where when white comes on I want to turn off the color.


BTW,
Thanks for all you do!
